import Foundation

struct AmharicHardExercisesData {
    static let allExercises: [Exercise] = [
        Exercise(
            id: UUID(),
            title: "AmharicHardExercisesData",
            instructions: "ጥያቄዎቹን በጥንቃቄ ይመልሱ።",
            section: .language,
            type: .multipleChoice,
            difficulty: .medium,
            items: [
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 1 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 2 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 3 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 4 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 5 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 6 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 7 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 8 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 9 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 10 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 11 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 12 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 13 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 14 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 15 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 16 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 17 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 18 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 19 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 20 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 21 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 22 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 23 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 24 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 25 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 26 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 27 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 28 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 29 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 30 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 31 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 32 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 33 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 34 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 35 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 36 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 37 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 38 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 39 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 40 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 41 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 42 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 43 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 44 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 45 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 46 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 47 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 48 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 49 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 50 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 51 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 52 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 53 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 54 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 55 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 56 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 57 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 58 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 59 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 60 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 61 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 62 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 63 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 64 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 65 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 66 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 67 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 68 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 69 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 70 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 71 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 72 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 73 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 74 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 75 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 76 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 77 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 78 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 79 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 80 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 81 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 82 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 83 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 84 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 85 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 86 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 87 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 88 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 89 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 90 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 91 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 92 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 93 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 94 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 95 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 96 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 97 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 98 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 99 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 100 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 101 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 102 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 103 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 104 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 105 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 106 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 107 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 108 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 109 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 110 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 111 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 112 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 113 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 114 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 115 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 116 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 117 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 118 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 119 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "ከባድ ጥያቄ 120 ፦ ትልቅ የሰውነት ክፍል የትኛው ነው?", options: ["ቆዳ", "ልብ", "ሳምባ", "ኩላሊት"], correctAnswer: "ቆዳ", explanation: ""),
            ]
        )
    ]
}
