import Foundation

struct EnglishNewExercisesData2 {

    static let allExercises: [Exercise] = [
        exercise1,
        exercise2,
        exercise3,
        exercise4,
        exercise5,
        exercise6,
        exercise7,
        exercise8,
        exercise9
    ]

    // MARK: - Exercise 1: Word to Definition
    private static let exercise1 = Exercise(
        title: "Word to Definition",
        instructions: "Choose the correct definition for the given word.",
        section: .language,
        type: .multipleChoice,
        trackedType: nil,
        difficulty: .medium,
        items: [
            ExerciseItem(prompt: "What does HIBERNATE mean?", options: ["Fly south for the winter", "Sleep through the winter", "Store food underground", "Shed fur in cold weather"], correctAnswer: "Sleep through the winter", explanation: "To hibernate means to sleep through the winter months."),
            ExerciseItem(prompt: "What does FRAGILE mean?", options: ["Very old", "Easily broken", "Very heavy", "Brightly colored"], correctAnswer: "Easily broken", explanation: "Fragile means easily broken or damaged."),
            ExerciseItem(prompt: "What does PHYSICIAN mean?", options: ["Lawyer", "Pharmacist", "Doctor", "Scientist"], correctAnswer: "Doctor", explanation: "A physician is a medical doctor."),
            ExerciseItem(prompt: "What does DONATE mean?", options: ["To borrow", "To sell", "To give freely", "To trade"], correctAnswer: "To give freely", explanation: "To donate means to give something freely without expecting anything in return."),
            ExerciseItem(prompt: "What does ANXIOUS mean?", options: ["Calm", "Angry", "Bored", "Worried"], correctAnswer: "Worried", explanation: "Anxious means feeling worried or nervous."),
            ExerciseItem(prompt: "What does TRANSPARENT mean?", options: ["Very heavy", "Clear enough to see through", "Completely hidden", "Brightly colored"], correctAnswer: "Clear enough to see through", explanation: "Transparent means clear enough that light passes through and objects behind can be seen."),
            ExerciseItem(prompt: "What does VACANT mean?", options: ["Full", "Broken", "Empty or unoccupied", "Locked"], correctAnswer: "Empty or unoccupied", explanation: "Vacant means empty or not in use."),
            ExerciseItem(prompt: "What does CHRONIC mean?", options: ["Short-lived", "Very painful", "Happening rarely", "Long-lasting or recurring"], correctAnswer: "Long-lasting or recurring", explanation: "Chronic describes a condition that persists for a long time or keeps coming back."),
            ExerciseItem(prompt: "What does FLEXIBLE mean?", options: ["Rigid and stiff", "Able to bend without breaking", "Very strong", "Extremely light"], correctAnswer: "Able to bend without breaking", explanation: "Flexible means able to bend easily without breaking."),
            ExerciseItem(prompt: "What does NUTRITION mean?", options: ["Physical exercise", "A type of medication", "The process of providing nourishment through food", "A cooking method"], correctAnswer: "The process of providing nourishment through food", explanation: "Nutrition refers to the process of taking in and using food for health and growth."),
            ExerciseItem(prompt: "What does CONTAGIOUS mean?", options: ["Very dangerous", "Spread from person to person", "Caused by allergies", "Requiring surgery"], correctAnswer: "Spread from person to person", explanation: "Contagious means able to be passed from one person to another."),
            ExerciseItem(prompt: "What does NAVIGATE mean?", options: ["To cook a meal", "To find your way or plan a route", "To argue with someone", "To build something"], correctAnswer: "To find your way or plan a route", explanation: "To navigate means to plan and follow a route to reach a destination."),
            ExerciseItem(prompt: "What does ENDURE mean?", options: ["To give up", "To enjoy greatly", "To put up with something difficult", "To forget"], correctAnswer: "To put up with something difficult", explanation: "To endure means to bear or put up with hardship over time."),
            ExerciseItem(prompt: "What does PRESCRIPTION mean?", options: ["A grocery list", "A written medical order for medication", "A list of symptoms", "A medical bill"], correctAnswer: "A written medical order for medication", explanation: "A prescription is a written order from a doctor authorizing a patient to receive medication."),
            ExerciseItem(prompt: "What does BUDGET mean?", options: ["A type of savings account", "A plan for how to spend money", "A kind of loan", "A financial penalty"], correctAnswer: "A plan for how to spend money", explanation: "A budget is a financial plan that outlines how money will be spent or saved."),
            ExerciseItem(prompt: "What does ALLERGIC mean?", options: ["Very tired", "Immune to illness", "Having a harmful reaction to a substance", "Highly contagious"], correctAnswer: "Having a harmful reaction to a substance", explanation: "Allergic means having an adverse physical reaction to a particular substance."),
            ExerciseItem(prompt: "What does RETIRE mean?", options: ["To take a short break", "To change careers", "To stop working permanently", "To move to a new city"], correctAnswer: "To stop working permanently", explanation: "To retire means to leave one's job and stop working, usually at an older age."),
            ExerciseItem(prompt: "What does SINCERE mean?", options: ["Clever and crafty", "Genuinely honest and heartfelt", "Shy and quiet", "Loud and confident"], correctAnswer: "Genuinely honest and heartfelt", explanation: "Sincere means genuinely honest and free from pretense."),
            ExerciseItem(prompt: "What does PEDESTRIAN mean?", options: ["A person riding a bicycle", "A person walking on foot", "A type of vehicle", "A crossing guard"], correctAnswer: "A person walking on foot", explanation: "A pedestrian is a person who is walking, especially in an area with traffic."),
            ExerciseItem(prompt: "What does DOSE mean?", options: ["A type of medicine", "A medical procedure", "The amount of medication taken at one time", "A doctor's appointment"], correctAnswer: "The amount of medication taken at one time", explanation: "A dose is the measured quantity of a medication to be taken at one time.")
        ]
    )

    // MARK: - Exercise 2: Verb Match
    private static let exercise2 = Exercise(
        title: "Verb Match",
        instructions: "Choose the action verb that best matches the person or situation.",
        section: .language,
        type: .multipleChoice,
        trackedType: nil,
        difficulty: .easy,
        items: [
            ExerciseItem(prompt: "A chef in a kitchen:", options: ["Drives", "Cooks", "Swims", "Files"], correctAnswer: "Cooks", explanation: "A chef's main job is to cook food."),
            ExerciseItem(prompt: "A surgeon in an operating room:", options: ["Plants", "Builds", "Operates", "Paints"], correctAnswer: "Operates", explanation: "A surgeon performs surgical operations."),
            ExerciseItem(prompt: "A teacher in a classroom:", options: ["Flies", "Fishes", "Teaches", "Bakes"], correctAnswer: "Teaches", explanation: "A teacher's job is to teach students."),
            ExerciseItem(prompt: "A mechanic in a garage:", options: ["Sings", "Repairs", "Sculpts", "Harvests"], correctAnswer: "Repairs", explanation: "A mechanic repairs vehicles and machinery."),
            ExerciseItem(prompt: "A librarian at work:", options: ["Welds", "Plants", "Organizes books", "Drives"], correctAnswer: "Organizes books", explanation: "A librarian organizes books and helps patrons find resources."),
            ExerciseItem(prompt: "A gardener in a backyard:", options: ["Operates", "Types", "Welds", "Plants"], correctAnswer: "Plants", explanation: "A gardener plants and tends to plants."),
            ExerciseItem(prompt: "A painter with a brush:", options: ["Paints", "Diagnoses", "Delivers", "Harvests"], correctAnswer: "Paints", explanation: "A painter uses a brush to paint."),
            ExerciseItem(prompt: "A mail carrier on a route:", options: ["Cooks", "Delivers", "Operates", "Teaches"], correctAnswer: "Delivers", explanation: "A mail carrier delivers letters and packages."),
            ExerciseItem(prompt: "A firefighter at a fire:", options: ["Bakes", "Sculpts", "Extinguishes", "Files"], correctAnswer: "Extinguishes", explanation: "A firefighter extinguishes fires."),
            ExerciseItem(prompt: "A nurse in a hospital:", options: ["Flies", "Cares for patients", "Harvests", "Welds"], correctAnswer: "Cares for patients", explanation: "A nurse's primary role is caring for patients."),
            ExerciseItem(prompt: "A pilot in a cockpit:", options: ["Diagnoses", "Paints", "Flies", "Plants"], correctAnswer: "Flies", explanation: "A pilot flies aircraft."),
            ExerciseItem(prompt: "A cashier at a store:", options: ["Welds", "Rings up purchases", "Operates", "Harvests"], correctAnswer: "Rings up purchases", explanation: "A cashier rings up and processes customer purchases."),
            ExerciseItem(prompt: "A farmer in a field:", options: ["Diagnoses", "Types", "Harvests", "Flies"], correctAnswer: "Harvests", explanation: "A farmer harvests crops from the field."),
            ExerciseItem(prompt: "A judge in a courtroom:", options: ["Bakes", "Rules", "Delivers", "Sculpts"], correctAnswer: "Rules", explanation: "A judge rules on legal matters in a courtroom."),
            ExerciseItem(prompt: "A baker in a bakery:", options: ["Welds", "Files", "Bakes", "Cares for patients"], correctAnswer: "Bakes", explanation: "A baker bakes bread, cakes, and other goods."),
            ExerciseItem(prompt: "A secretary at an office:", options: ["Operates", "Types and files", "Harvests", "Extinguishes"], correctAnswer: "Types and files", explanation: "A secretary types documents and files paperwork."),
            ExerciseItem(prompt: "A dentist in a clinic:", options: ["Delivers", "Flies", "Examines teeth", "Rings up purchases"], correctAnswer: "Examines teeth", explanation: "A dentist examines and treats teeth."),
            ExerciseItem(prompt: "A plumber under a sink:", options: ["Paints", "Repairs pipes", "Plants", "Rules"], correctAnswer: "Repairs pipes", explanation: "A plumber repairs pipes and plumbing systems."),
            ExerciseItem(prompt: "A lifeguard at a pool:", options: ["Bakes", "Diagnoses", "Watches and rescues", "Types"], correctAnswer: "Watches and rescues", explanation: "A lifeguard watches swimmers and performs rescues when needed."),
            ExerciseItem(prompt: "A waiter at a restaurant:", options: ["Welds", "Serves food", "Flies", "Rules"], correctAnswer: "Serves food", explanation: "A waiter serves food and drinks to restaurant customers.")
        ]
    )

    // MARK: - Exercise 3: Proverb Meaning
    private static let exercise3 = Exercise(
        title: "Proverb Meaning",
        instructions: "Choose the correct meaning of the common saying.",
        section: .cognition,
        type: .multipleChoice,
        trackedType: .completeTheSaying,
        difficulty: .medium,
        items: [
            ExerciseItem(prompt: "\"Don't cry over spilled milk.\"", options: ["Be careful with liquids", "Don't worry about things you can't change", "Clean up your messes right away", "Milk is expensive"], correctAnswer: "Don't worry about things you can't change", explanation: "This saying means there's no use being upset over something that has already happened and cannot be undone."),
            ExerciseItem(prompt: "\"A penny saved is a penny earned.\"", options: ["Pennies are very valuable", "Saving money is as good as making money", "Hard work always pays off", "Never spend coins"], correctAnswer: "Saving money is as good as making money", explanation: "Money you save has the same value as money you earn."),
            ExerciseItem(prompt: "\"The early bird catches the worm.\"", options: ["Birds wake up hungry", "Worms come out in the morning", "Starting early leads to success", "Sleep is overrated"], correctAnswer: "Starting early leads to success", explanation: "People who start early or act promptly have an advantage over others."),
            ExerciseItem(prompt: "\"Don't put all your eggs in one basket.\"", options: ["Be careful carrying groceries", "Eggs break easily", "Don't rely on just one plan or option", "Baskets are useful"], correctAnswer: "Don't rely on just one plan or option", explanation: "It is wise to spread your efforts or resources across multiple options."),
            ExerciseItem(prompt: "\"Actions speak louder than words.\"", options: ["People talk too much", "What you do matters more than what you say", "Loud people get more done", "Always keep your promises"], correctAnswer: "What you do matters more than what you say", explanation: "What a person actually does is more meaningful than what they claim or promise."),
            ExerciseItem(prompt: "\"You can't judge a book by its cover.\"", options: ["Books should have good covers", "Appearances can be deceiving", "Always read the whole book", "Covers protect books"], correctAnswer: "Appearances can be deceiving", explanation: "You cannot accurately judge something or someone based on outward appearance alone."),
            ExerciseItem(prompt: "\"The grass is always greener on the other side.\"", options: ["Other people's lawns are better maintained", "You should move to a new neighborhood", "People always think others have it better", "Gardening is satisfying"], correctAnswer: "People always think others have it better", explanation: "People tend to believe that other people's situations are better than their own."),
            ExerciseItem(prompt: "\"Two wrongs don't make a right.\"", options: ["Always do math carefully", "Retaliating for bad behavior is still wrong", "Two people can fix a mistake", "Wrongs should be forgotten"], correctAnswer: "Retaliating for bad behavior is still wrong", explanation: "Responding to wrongdoing with more wrongdoing does not make the situation right."),
            ExerciseItem(prompt: "\"Every cloud has a silver lining.\"", options: ["Clouds are made of water vapor", "Rain is good for plants", "There is something positive in every bad situation", "Silver is valuable"], correctAnswer: "There is something positive in every bad situation", explanation: "Even in difficult or negative situations, there is always some positive aspect."),
            ExerciseItem(prompt: "\"Don't bite the hand that feeds you.\"", options: ["Be careful around animals", "Don't hurt someone who helps you", "Always wash your hands before eating", "Feeding animals can be dangerous"], correctAnswer: "Don't hurt someone who helps you", explanation: "You should not harm or disrespect the person or thing that provides for you."),
            ExerciseItem(prompt: "\"Better late than never.\"", options: ["Arriving late is acceptable", "Doing something late is better than not doing it at all", "Punctuality is not important", "Good things come to those who wait"], correctAnswer: "Doing something late is better than not doing it at all", explanation: "It is preferable to do something after the expected time than to not do it at all."),
            ExerciseItem(prompt: "\"A watched pot never boils.\"", options: ["Old pots don't work well", "Stoves are unpredictable", "Waiting anxiously makes time feel slower", "You should always watch your cooking"], correctAnswer: "Waiting anxiously makes time feel slower", explanation: "When you are eagerly waiting for something, time seems to pass more slowly."),
            ExerciseItem(prompt: "\"Don't count your chickens before they hatch.\"", options: ["Chickens take a long time to grow", "Don't plan on something before it actually happens", "Farmers should keep track of their animals", "Eggs are unpredictable"], correctAnswer: "Don't plan on something before it actually happens", explanation: "Do not make plans based on outcomes that have not yet occurred."),
            ExerciseItem(prompt: "\"When in Rome, do as the Romans do.\"", options: ["Rome is a great city to visit", "Romans have strict rules", "Follow the local customs wherever you are", "Travel broadens the mind"], correctAnswer: "Follow the local customs wherever you are", explanation: "When you are in a new place, you should behave in the way that the people there do."),
            ExerciseItem(prompt: "\"If it ain't broke, don't fix it.\"", options: ["Repairs are expensive", "Don't change something that is working well", "Old things break easily", "Always hire a professional"], correctAnswer: "Don't change something that is working well", explanation: "There is no need to make changes to something that is already functioning properly."),
            ExerciseItem(prompt: "\"You reap what you sow.\"", options: ["Farming takes hard work", "Your actions and efforts determine your outcomes", "Seeds grow slowly", "Gardening is rewarding"], correctAnswer: "Your actions and efforts determine your outcomes", explanation: "The results you get in life correspond to the effort and choices you put in."),
            ExerciseItem(prompt: "\"Beggars can't be choosers.\"", options: ["Always be generous", "Money is hard to earn", "When you need help, you can't be too picky about what you get", "Never ask for charity"], correctAnswer: "When you need help, you can't be too picky about what you get", explanation: "Someone who is in need should accept what is offered rather than demanding something better."),
            ExerciseItem(prompt: "\"The pen is mightier than the sword.\"", options: ["Writing is a useful skill", "Pens are more practical than weapons", "Words and ideas can be more powerful than violence", "Books should not be banned"], correctAnswer: "Words and ideas can be more powerful than violence", explanation: "Communication, writing, and ideas have greater long-term power than physical force."),
            ExerciseItem(prompt: "\"Honesty is the best policy.\"", options: ["Doctors should be honest with patients", "Insurance policies are important", "It is always better to tell the truth", "Lying causes legal problems"], correctAnswer: "It is always better to tell the truth", explanation: "Being truthful is the wisest approach in all situations."),
            ExerciseItem(prompt: "\"Strike while the iron is hot.\"", options: ["Blacksmithing requires good timing", "Ironing clothes takes patience", "Take advantage of an opportunity when it is available", "Hot metal is dangerous"], correctAnswer: "Take advantage of an opportunity when it is available", explanation: "Act immediately when an opportunity presents itself, before it passes.")
        ]
    )

    // MARK: - Exercise 4: Absurdities
    private static let exercise4 = Exercise(
        title: "Absurdities",
        instructions: "Read the sentence and identify what is logically wrong with it.",
        section: .cognition,
        type: .multipleChoice,
        trackedType: .whatsWrongHere,
        difficulty: .medium,
        items: [
            ExerciseItem(prompt: "\"She wore her winter coat to stay cool in the snow.\" What is wrong?", options: ["She shouldn't go outside in the snow", "Winter coats keep you warm, not cool", "Snow is not cold", "Nothing is wrong"], correctAnswer: "Winter coats keep you warm, not cool", explanation: "Winter coats are designed to keep you warm, so wearing one to stay cool is backwards."),
            ExerciseItem(prompt: "\"He used a fork to drink his soup.\" What is wrong?", options: ["Soup is too hot to eat", "You use a spoon for soup, not a fork", "Forks are only for salad", "Nothing is wrong"], correctAnswer: "You use a spoon for soup, not a fork", explanation: "Soup is a liquid and requires a spoon; a fork's tines would let the soup drain through."),
            ExerciseItem(prompt: "\"The firefighter started a fire to put it out.\" What is wrong?", options: ["Firefighters don't work at night", "Firefighters put out fires — they don't start them", "Fire is always dangerous", "Nothing is wrong"], correctAnswer: "Firefighters put out fires — they don't start them", explanation: "A firefighter's job is to extinguish fires, not to start them."),
            ExerciseItem(prompt: "\"She went to the library to buy a new book.\" What is wrong?", options: ["Libraries are closed on weekends", "Libraries lend books for free — you don't buy them there", "Books are too expensive", "Nothing is wrong"], correctAnswer: "Libraries lend books for free — you don't buy them there", explanation: "Libraries allow you to borrow books for free; you buy books at a bookstore."),
            ExerciseItem(prompt: "\"He planted seeds in the middle of winter to enjoy a summer harvest.\" What is wrong?", options: ["Seeds are expensive in winter", "Seeds cannot germinate and grow in frozen ground", "Summer is too hot for a harvest", "Nothing is wrong"], correctAnswer: "Seeds cannot germinate and grow in frozen ground", explanation: "Frozen winter ground prevents seeds from germinating and growing."),
            ExerciseItem(prompt: "\"She put sunscreen on to protect herself from the rain.\" What is wrong?", options: ["Sunscreen is too expensive", "Sunscreen protects against UV rays, not rain", "Rain is not dangerous", "Nothing is wrong"], correctAnswer: "Sunscreen protects against UV rays, not rain", explanation: "Sunscreen blocks ultraviolet rays from the sun; an umbrella or raincoat protects from rain."),
            ExerciseItem(prompt: "\"He went to the dentist to get his eyes checked.\" What is wrong?", options: ["Dentists are hard to get appointments with", "Dentists treat teeth, not eyes — you see an eye doctor for that", "Eyes don't need to be checked", "Nothing is wrong"], correctAnswer: "Dentists treat teeth, not eyes — you see an eye doctor for that", explanation: "Dentists specialize in dental care; eyes are examined by an optometrist or ophthalmologist."),
            ExerciseItem(prompt: "\"She baked the cake in the refrigerator for 30 minutes.\" What is wrong?", options: ["30 minutes is too long to bake", "You bake in an oven, not a refrigerator", "Refrigerators are for keeping food cold only", "Nothing is wrong"], correctAnswer: "You bake in an oven, not a refrigerator", explanation: "Baking requires heat from an oven; a refrigerator keeps things cold and cannot bake."),
            ExerciseItem(prompt: "\"The fish climbed up the tree to escape from the cat.\" What is wrong?", options: ["Cats don't eat fish", "Fish cannot breathe air or climb trees", "Trees are not safe for animals", "Nothing is wrong"], correctAnswer: "Fish cannot breathe air or climb trees", explanation: "Fish breathe underwater using gills and have no limbs to climb with."),
            ExerciseItem(prompt: "\"He filled up his car with water so it would run better.\" What is wrong?", options: ["Water is too expensive", "Cars run on gasoline or electricity, not water", "Filling a car takes too long", "Nothing is wrong"], correctAnswer: "Cars run on gasoline or electricity, not water", explanation: "Engines require fuel such as gasoline or electricity; water would damage the engine."),
            ExerciseItem(prompt: "\"She wore her sunglasses to hear the concert better.\" What is wrong?", options: ["Sunglasses are not allowed at concerts", "Sunglasses affect vision, not hearing", "Concerts are too loud", "Nothing is wrong"], correctAnswer: "Sunglasses affect vision, not hearing", explanation: "Sunglasses are worn to protect and shade the eyes; they have no effect on hearing."),
            ExerciseItem(prompt: "\"He turned on the fan to warm up the room.\" What is wrong?", options: ["Fans use too much electricity", "Fans cool a room by circulating air — they do not produce heat", "Rooms don't need warming", "Nothing is wrong"], correctAnswer: "Fans cool a room by circulating air — they do not produce heat", explanation: "Fans move air to create a cooling effect; a heater is needed to warm a room."),
            ExerciseItem(prompt: "\"The baby drove herself to the hospital to be born.\" What is wrong?", options: ["Babies are born at home sometimes", "A newborn baby cannot drive", "Hospitals are far away", "Nothing is wrong"], correctAnswer: "A newborn baby cannot drive", explanation: "A baby about to be born cannot drive; the mother or another adult would do so."),
            ExerciseItem(prompt: "\"She used an umbrella to stay dry from the morning sunshine.\" What is wrong?", options: ["Umbrellas block wind, not sun", "Sunshine is not wet — you don't need an umbrella for it", "Morning is a bad time to be outside", "Nothing is wrong"], correctAnswer: "Sunshine is not wet — you don't need an umbrella for it", explanation: "Umbrellas protect against rain; sunshine produces light and warmth, not wetness."),
            ExerciseItem(prompt: "\"He called 911 to order a pizza.\" What is wrong?", options: ["Pizza delivery takes too long", "911 is for emergencies, not pizza orders", "Phone calls cost money", "Nothing is wrong"], correctAnswer: "911 is for emergencies, not pizza orders", explanation: "911 is an emergency services number; pizza orders are placed with a restaurant or delivery app."),
            ExerciseItem(prompt: "\"She mailed a letter by throwing it out the window.\" What is wrong?", options: ["Letters need stamps", "Letters need to be taken to a mailbox or post office, not thrown out a window", "Letters take too long to arrive", "Nothing is wrong"], correctAnswer: "Letters need to be taken to a mailbox or post office, not thrown out a window", explanation: "Mail must be deposited in a mailbox or post office to be delivered by postal carriers."),
            ExerciseItem(prompt: "\"He wore a life jacket to go skiing in the mountains.\" What is wrong?", options: ["Life jackets are too expensive", "Life jackets are for water safety, not skiing", "Mountain skiing is always dangerous", "Nothing is wrong"], correctAnswer: "Life jackets are for water safety, not skiing", explanation: "Life jackets are flotation devices for water activities; skiing requires different safety gear."),
            ExerciseItem(prompt: "\"She went to the grocery store to pick up her dry cleaning.\" What is wrong?", options: ["Grocery stores are too crowded", "Dry cleaning is picked up from a dry cleaner, not a grocery store", "Dry cleaning is too expensive", "Nothing is wrong"], correctAnswer: "Dry cleaning is picked up from a dry cleaner, not a grocery store", explanation: "Dry cleaning services are provided by dry cleaners, not grocery stores."),
            ExerciseItem(prompt: "\"He added ice cubes to his coffee to make it hotter.\" What is wrong?", options: ["Ice melts too quickly", "Ice cubes make drinks colder, not hotter", "Coffee doesn't need ice", "Nothing is wrong"], correctAnswer: "Ice cubes make drinks colder, not hotter", explanation: "Ice is frozen water that lowers the temperature of drinks; it cannot make something hotter."),
            ExerciseItem(prompt: "\"She turned off all the lights so she could read her book more easily.\" What is wrong?", options: ["Reading is bad for your eyes", "You need light to read — darkness makes it impossible", "Books should only be read in the daytime", "Nothing is wrong"], correctAnswer: "You need light to read — darkness makes it impossible", explanation: "Reading requires sufficient light to see the text; darkness makes reading impossible.")
        ]
    )

    // MARK: - Exercise 5: Memory: Repeat the List
    private static let exercise5 = Exercise(
        title: "Memory: Repeat the List",
        instructions: "Three words will be shown briefly. Remember them, then select the correct list.",
        section: .cognition,
        type: .multipleChoice,
        trackedType: nil,
        difficulty: .medium,
        items: [
            ExerciseItem(prompt: "Words shown: APPLE / CHAIR / BLUE\n\nWhich list did you see?", options: ["Apple, Table, Blue", "Apple, Chair, Green", "Apple, Chair, Blue", "Orange, Chair, Blue"], correctAnswer: "Apple, Chair, Blue", explanation: "The three words shown were Apple, Chair, and Blue."),
            ExerciseItem(prompt: "Words shown: DOCTOR / RIVER / HAT\n\nWhich list did you see?", options: ["Doctor, River, Cap", "Doctor, Lake, Hat", "Nurse, River, Hat", "Doctor, River, Hat"], correctAnswer: "Doctor, River, Hat", explanation: "The three words shown were Doctor, River, and Hat."),
            ExerciseItem(prompt: "Words shown: THURSDAY / LAMP / BREAD\n\nWhich list did you see?", options: ["Thursday, Lamp, Bread", "Friday, Lamp, Bread", "Thursday, Light, Bread", "Thursday, Lamp, Butter"], correctAnswer: "Thursday, Lamp, Bread", explanation: "The three words shown were Thursday, Lamp, and Bread."),
            ExerciseItem(prompt: "Words shown: PURPLE / SHOE / GARDEN\n\nWhich list did you see?", options: ["Purple, Boot, Garden", "Purple, Shoe, Garden", "Blue, Shoe, Garden", "Purple, Shoe, Park"], correctAnswer: "Purple, Shoe, Garden", explanation: "The three words shown were Purple, Shoe, and Garden."),
            ExerciseItem(prompt: "Words shown: CLOCK / RAIN / SISTER\n\nWhich list did you see?", options: ["Clock, Rain, Brother", "Watch, Rain, Sister", "Clock, Snow, Sister", "Clock, Rain, Sister"], correctAnswer: "Clock, Rain, Sister", explanation: "The three words shown were Clock, Rain, and Sister."),
            ExerciseItem(prompt: "Words shown: SEVEN / MIRROR / COAT\n\nWhich list did you see?", options: ["Seven, Mirror, Coat", "Seven, Window, Coat", "Eight, Mirror, Coat", "Seven, Mirror, Jacket"], correctAnswer: "Seven, Mirror, Coat", explanation: "The three words shown were Seven, Mirror, and Coat."),
            ExerciseItem(prompt: "Words shown: CANDLE / BICYCLE / MARCH\n\nWhich list did you see?", options: ["Candle, Bicycle, April", "Lamp, Bicycle, March", "Candle, Bicycle, March", "Candle, Tricycle, March"], correctAnswer: "Candle, Bicycle, March", explanation: "The three words shown were Candle, Bicycle, and March."),
            ExerciseItem(prompt: "Words shown: ELEPHANT / COFFEE / MONDAY\n\nWhich list did you see?", options: ["Elephant, Coffee, Tuesday", "Elephant, Coffee, Monday", "Giraffe, Coffee, Monday", "Elephant, Tea, Monday"], correctAnswer: "Elephant, Coffee, Monday", explanation: "The three words shown were Elephant, Coffee, and Monday."),
            ExerciseItem(prompt: "Words shown: LETTER / AUTUMN / SILVER\n\nWhich list did you see?", options: ["Letter, Autumn, Silver", "Letter, Summer, Silver", "Number, Autumn, Silver", "Letter, Autumn, Gold"], correctAnswer: "Letter, Autumn, Silver", explanation: "The three words shown were Letter, Autumn, and Silver."),
            ExerciseItem(prompt: "Words shown: PILLOW / TRAIN / DENTIST\n\nWhich list did you see?", options: ["Pillow, Bus, Dentist", "Blanket, Train, Dentist", "Pillow, Train, Dentist", "Pillow, Train, Doctor"], correctAnswer: "Pillow, Train, Dentist", explanation: "The three words shown were Pillow, Train, and Dentist."),
            ExerciseItem(prompt: "Words shown: ORANGE / HAMMER / SUNDAY\n\nWhich list did you see?", options: ["Orange, Hammer, Saturday", "Orange, Hammer, Sunday", "Lemon, Hammer, Sunday", "Orange, Wrench, Sunday"], correctAnswer: "Orange, Hammer, Sunday", explanation: "The three words shown were Orange, Hammer, and Sunday."),
            ExerciseItem(prompt: "Words shown: WINDOW / NURSE / FIFTY\n\nWhich list did you see?", options: ["Window, Doctor, Fifty", "Door, Nurse, Fifty", "Window, Nurse, Fifteen", "Window, Nurse, Fifty"], correctAnswer: "Window, Nurse, Fifty", explanation: "The three words shown were Window, Nurse, and Fifty."),
            ExerciseItem(prompt: "Words shown: BLANKET / APRIL / CAMERA\n\nWhich list did you see?", options: ["Blanket, April, Camera", "Blanket, March, Camera", "Pillow, April, Camera", "Blanket, April, Phone"], correctAnswer: "Blanket, April, Camera", explanation: "The three words shown were Blanket, April, and Camera."),
            ExerciseItem(prompt: "Words shown: TIGER / MUSIC / SPOON\n\nWhich list did you see?", options: ["Tiger, Music, Fork", "Lion, Music, Spoon", "Tiger, Music, Spoon", "Tiger, Radio, Spoon"], correctAnswer: "Tiger, Music, Spoon", explanation: "The three words shown were Tiger, Music, and Spoon."),
            ExerciseItem(prompt: "Words shown: WALLET / TUESDAY / GREEN\n\nWhich list did you see?", options: ["Wallet, Tuesday, Blue", "Wallet, Tuesday, Green", "Purse, Tuesday, Green", "Wallet, Wednesday, Green"], correctAnswer: "Wallet, Tuesday, Green", explanation: "The three words shown were Wallet, Tuesday, and Green."),
            ExerciseItem(prompt: "Words shown: BOTTLE / LIBRARY / YELLOW\n\nWhich list did you see?", options: ["Bottle, Library, Orange", "Jar, Library, Yellow", "Bottle, Library, Yellow", "Bottle, School, Yellow"], correctAnswer: "Bottle, Library, Yellow", explanation: "The three words shown were Bottle, Library, and Yellow."),
            ExerciseItem(prompt: "Words shown: PIANO / CLOUD / DINNER\n\nWhich list did you see?", options: ["Piano, Cloud, Dinner", "Guitar, Cloud, Dinner", "Piano, Rain, Dinner", "Piano, Cloud, Lunch"], correctAnswer: "Piano, Cloud, Dinner", explanation: "The three words shown were Piano, Cloud, and Dinner."),
            ExerciseItem(prompt: "Words shown: GARDEN / TWELVE / JACKET\n\nWhich list did you see?", options: ["Garden, Thirteen, Jacket", "Park, Twelve, Jacket", "Garden, Twelve, Coat", "Garden, Twelve, Jacket"], correctAnswer: "Garden, Twelve, Jacket", explanation: "The three words shown were Garden, Twelve, and Jacket."),
            ExerciseItem(prompt: "Words shown: OCEAN / PENCIL / FRIDAY\n\nWhich list did you see?", options: ["Ocean, Pencil, Saturday", "Ocean, Pencil, Friday", "River, Pencil, Friday", "Ocean, Pen, Friday"], correctAnswer: "Ocean, Pencil, Friday", explanation: "The three words shown were Ocean, Pencil, and Friday."),
            ExerciseItem(prompt: "Words shown: MIRROR / HOSPITAL / RED\n\nWhich list did you see?", options: ["Mirror, Hospital, Red", "Window, Hospital, Red", "Mirror, Clinic, Red", "Mirror, Hospital, Blue"], correctAnswer: "Mirror, Hospital, Red", explanation: "The three words shown were Mirror, Hospital, and Red.")
        ]
    )

    // MARK: - Exercise 6: Signs & Labels
    private static let exercise6 = Exercise(
        title: "Signs & Labels",
        instructions: "Read the sign or label and answer the question.",
        section: .functionalSkills,
        type: .multipleChoice,
        trackedType: nil,
        difficulty: .easy,
        items: [
            ExerciseItem(prompt: "A door sign says \"PUSH.\" What do you do to open it?", options: ["Pull", "Push", "Knock", "Wait for someone to open it"], correctAnswer: "Push", explanation: "The sign says PUSH, which means you apply forward pressure to open the door."),
            ExerciseItem(prompt: "A food label says \"Keep refrigerated.\" Where should you store it?", options: ["In the pantry", "In the freezer", "In the refrigerator", "On the counter"], correctAnswer: "In the refrigerator", explanation: "\"Keep refrigerated\" means it must be stored in the refrigerator to stay safe and fresh."),
            ExerciseItem(prompt: "A road sign says \"No right turn on red.\" When can you turn right?", options: ["Never at this intersection", "Only when the light is green", "Anytime", "Only between 8pm and 6am"], correctAnswer: "Only when the light is green", explanation: "The sign prohibits turning right on a red light; you must wait for the green light."),
            ExerciseItem(prompt: "A medication label says \"Take with food.\" When should you take it?", options: ["On an empty stomach", "With a meal or snack", "Before bed only", "After exercise"], correctAnswer: "With a meal or snack", explanation: "\"Take with food\" means you should eat something when you take the medication."),
            ExerciseItem(prompt: "A wet floor sign is placed in an aisle. What should you do?", options: ["Run across quickly", "Walk carefully or use another route", "Mop it up yourself", "Ignore it"], correctAnswer: "Walk carefully or use another route", explanation: "A wet floor sign warns of a slipping hazard; walk carefully or go around."),
            ExerciseItem(prompt: "A bottle of cleaning spray says \"Do not mix with bleach.\" What does this mean?", options: ["It doesn't work as well with bleach", "Mixing it with bleach creates a dangerous chemical reaction", "Bleach is more effective on its own", "The bottle is almost empty"], correctAnswer: "Mixing it with bleach creates a dangerous chemical reaction", explanation: "Certain cleaners react with bleach to produce toxic fumes, making it dangerous to mix them."),
            ExerciseItem(prompt: "A medication bottle says \"Take one tablet twice daily.\" How many tablets do you take in one day?", options: ["1", "2", "3", "4"], correctAnswer: "2", explanation: "One tablet twice a day means 1 + 1 = 2 tablets total per day."),
            ExerciseItem(prompt: "A food package says \"Best by June 15.\" What does this mean?", options: ["The food must be thrown away on June 15", "The food is best quality before June 15", "The food was made on June 15", "You must open it by June 15"], correctAnswer: "The food is best quality before June 15", explanation: "\"Best by\" is a quality date; the food is at its best flavor and quality before that date."),
            ExerciseItem(prompt: "A parking sign says \"2 Hour Parking, 8am–6pm.\" You arrive at 10am. When must you leave by?", options: ["11am", "12pm", "2pm", "6pm"], correctAnswer: "12pm", explanation: "Arriving at 10am with a 2-hour limit means you must leave by 12pm (noon)."),
            ExerciseItem(prompt: "A supplement bottle says \"Take 2 capsules with 8 oz. of water.\" What should you do?", options: ["Take 2 capsules with any liquid", "Take 2 capsules with a full glass of water", "Take 2 capsules on an empty stomach", "Take 2 capsules before bed"], correctAnswer: "Take 2 capsules with a full glass of water", explanation: "The label specifies taking the capsules with 8 ounces of water, which is a full glass."),
            ExerciseItem(prompt: "A door sign says \"EMPLOYEES ONLY.\" Who should go through this door?", options: ["Anyone", "Customers only", "Workers who are employed there", "No one"], correctAnswer: "Workers who are employed there", explanation: "\"Employees Only\" restricts access to staff members who work at that location."),
            ExerciseItem(prompt: "A food label says \"Contains: wheat, soy, milk.\" What does this mean?", options: ["The product is healthy", "The product lists its allergens", "The product is vegan", "The product is low in calories"], correctAnswer: "The product lists its allergens", explanation: "Allergen listings inform consumers with food allergies about ingredients that may cause reactions."),
            ExerciseItem(prompt: "A prescription label says \"Refills: 3.\" What does this mean?", options: ["The medication expires in 3 days", "You can get 3 more supplies of this medication", "You must take 3 pills at once", "The medication is very strong"], correctAnswer: "You can get 3 more supplies of this medication", explanation: "\"Refills: 3\" means your prescription can be refilled 3 more times at the pharmacy."),
            ExerciseItem(prompt: "A sign in a hospital says \"QUIET ZONE.\" What should you do?", options: ["Speak loudly so nurses can hear you", "Keep noise and talking to a minimum", "Leave the area immediately", "Turn off all electronics"], correctAnswer: "Keep noise and talking to a minimum", explanation: "A quiet zone asks everyone in the area to keep voices and noise levels low."),
            ExerciseItem(prompt: "A cleaning product says \"Wear gloves when using.\" Why?", options: ["Your hands will get dirty", "The product may irritate or harm skin", "Gloves keep your hands warm", "It makes the product work better"], correctAnswer: "The product may irritate or harm skin", explanation: "Gloves protect your skin from chemicals in the product that could cause irritation or burns."),
            ExerciseItem(prompt: "A gas pump sign says \"No smoking within 25 feet.\" Why?", options: ["Smoking smells bad near gas", "Gasoline fumes can ignite from a spark or flame", "It is a city ordinance", "The pump sensors are affected by smoke"], correctAnswer: "Gasoline fumes can ignite from a spark or flame", explanation: "Gasoline vapor is highly flammable and can be ignited by the heat or flame from a cigarette."),
            ExerciseItem(prompt: "A restaurant sign says \"Wait to be seated.\" What should you do when you arrive?", options: ["Find an empty table and sit down", "Wait near the entrance for a host or hostess", "Go directly to the bar", "Ask another customer for a seat"], correctAnswer: "Wait near the entrance for a host or hostess", explanation: "\"Wait to be seated\" means a staff member will show you to your table; do not seat yourself."),
            ExerciseItem(prompt: "A pill bottle says \"May cause drowsiness.\" What should you be careful about after taking it?", options: ["Eating too much", "Driving or operating heavy machinery", "Drinking water", "Going for a walk"], correctAnswer: "Driving or operating heavy machinery", explanation: "Drowsiness impairs alertness and reaction time, making driving or operating machinery dangerous."),
            ExerciseItem(prompt: "An elevator sign says \"Maximum Capacity: 10 persons.\" What does this mean?", options: ["The elevator is 10 years old", "No more than 10 people should ride at once", "The elevator goes up 10 floors", "Wait 10 minutes before entering"], correctAnswer: "No more than 10 people should ride at once", explanation: "Maximum capacity means the elevator is safe for up to 10 people at one time."),
            ExerciseItem(prompt: "A food label says \"Serving size: 1 cup. Servings per container: 4.\" If you eat the whole container, how many servings did you have?", options: ["1", "2", "3", "4"], correctAnswer: "4", explanation: "If the container holds 4 servings and you eat all of it, you have consumed 4 servings.")
        ]
    )

    // MARK: - Exercise 7: Which Aisle?
    private static let exercise7 = Exercise(
        title: "Which Aisle?",
        instructions: "Identify where in a store you would find the given item.",
        section: .functionalSkills,
        type: .multipleChoice,
        trackedType: nil,
        difficulty: .easy,
        items: [
            ExerciseItem(prompt: "Where would you find a loaf of bread?", options: ["Produce", "Dairy", "Bakery", "Frozen foods"], correctAnswer: "Bakery", explanation: "Bread is typically found in the bakery section of a grocery store."),
            ExerciseItem(prompt: "Where would you find aspirin?", options: ["Grocery aisle", "Bakery", "Pharmacy", "Produce"], correctAnswer: "Pharmacy", explanation: "Aspirin and other over-the-counter medications are found in the pharmacy section."),
            ExerciseItem(prompt: "Where would you find milk?", options: ["Bakery", "Snack aisle", "Dairy", "Deli"], correctAnswer: "Dairy", explanation: "Milk is a dairy product and is kept refrigerated in the dairy section."),
            ExerciseItem(prompt: "Where would you find frozen peas?", options: ["Produce", "Canned goods", "Dairy", "Frozen foods"], correctAnswer: "Frozen foods", explanation: "Frozen vegetables like peas are stored in the frozen foods section."),
            ExerciseItem(prompt: "Where would you find laundry detergent?", options: ["Pharmacy", "Household or cleaning aisle", "Bakery", "Produce"], correctAnswer: "Household or cleaning aisle", explanation: "Laundry detergent and other cleaning supplies are in the household or cleaning aisle."),
            ExerciseItem(prompt: "Where would you find fresh apples?", options: ["Frozen foods", "Canned goods", "Produce", "Bakery"], correctAnswer: "Produce", explanation: "Fresh fruits like apples are found in the produce section."),
            ExerciseItem(prompt: "Where would you find canned soup?", options: ["Frozen foods", "Canned goods", "Dairy", "Deli"], correctAnswer: "Canned goods", explanation: "Canned soups and other tinned items are in the canned goods aisle."),
            ExerciseItem(prompt: "Where would you find shampoo?", options: ["Produce", "Bakery", "Health and beauty", "Frozen foods"], correctAnswer: "Health and beauty", explanation: "Hair care products like shampoo are in the health and beauty section."),
            ExerciseItem(prompt: "Where would you find sliced turkey at a grocery store?", options: ["Frozen foods", "Bakery", "Produce", "Deli"], correctAnswer: "Deli", explanation: "Sliced meats like turkey are prepared and sold at the deli counter."),
            ExerciseItem(prompt: "Where would you find dog food?", options: ["Frozen foods", "Pet supplies", "Dairy", "Bakery"], correctAnswer: "Pet supplies", explanation: "Dog food and other pet products are found in the pet supplies aisle."),
            ExerciseItem(prompt: "Where would you find orange juice?", options: ["Produce", "Deli", "Beverage aisle or dairy", "Bakery"], correctAnswer: "Beverage aisle or dairy", explanation: "Orange juice is found in the beverage aisle (shelf-stable) or the dairy section (refrigerated)."),
            ExerciseItem(prompt: "Where would you find a birthday card?", options: ["Pharmacy", "Stationery or greeting card aisle", "Produce", "Bakery"], correctAnswer: "Stationery or greeting card aisle", explanation: "Greeting cards and stationery items are found in the stationery or card aisle."),
            ExerciseItem(prompt: "Where would you find cheddar cheese?", options: ["Canned goods", "Frozen foods", "Dairy", "Bakery"], correctAnswer: "Dairy", explanation: "Cheese is a dairy product kept refrigerated in the dairy section."),
            ExerciseItem(prompt: "Where would you find paper towels?", options: ["Health and beauty", "Household or paper goods aisle", "Produce", "Pharmacy"], correctAnswer: "Household or paper goods aisle", explanation: "Paper towels and other paper products are in the household or paper goods aisle."),
            ExerciseItem(prompt: "Where would you find a frozen pizza?", options: ["Bakery", "Deli", "Frozen foods", "Produce"], correctAnswer: "Frozen foods", explanation: "Frozen pizzas are kept in the frozen foods section."),
            ExerciseItem(prompt: "Where would you find peanut butter?", options: ["Frozen foods", "Dairy", "Condiments or spreads aisle", "Produce"], correctAnswer: "Condiments or spreads aisle", explanation: "Peanut butter is a spread and is typically found in the condiments or spreads aisle."),
            ExerciseItem(prompt: "Where would you find a toothbrush?", options: ["Produce", "Health and beauty", "Bakery", "Pet supplies"], correctAnswer: "Health and beauty", explanation: "Oral care products like toothbrushes are in the health and beauty section."),
            ExerciseItem(prompt: "Where would you find salsa?", options: ["Frozen foods", "Dairy", "Chips and condiments aisle", "Bakery"], correctAnswer: "Chips and condiments aisle", explanation: "Salsa is typically stocked in the chips and condiments aisle alongside tortilla chips."),
            ExerciseItem(prompt: "Where would you find butter?", options: ["Bakery", "Frozen foods", "Dairy", "Canned goods"], correctAnswer: "Dairy", explanation: "Butter is a dairy product kept refrigerated in the dairy section."),
            ExerciseItem(prompt: "Where would you find batteries?", options: ["Produce", "Bakery", "Household or electronics aisle", "Dairy"], correctAnswer: "Household or electronics aisle", explanation: "Batteries are sold in the household or electronics aisle of most stores.")
        ]
    )

    // MARK: - Exercise 8: Phone & Emergency Info
    private static let exercise8 = Exercise(
        title: "Phone & Emergency Info",
        instructions: "Answer the question about using a phone or responding to an emergency.",
        section: .functionalSkills,
        type: .multipleChoice,
        trackedType: nil,
        difficulty: .easy,
        items: [
            ExerciseItem(prompt: "What number do you call in an emergency?", options: ["411", "311", "911", "211"], correctAnswer: "911", explanation: "911 is the emergency services number in the United States for police, fire, and medical help."),
            ExerciseItem(prompt: "What does a busy signal sound like, and what does it mean?", options: ["A ringing tone — someone is calling you", "A repeated beeping — the line is in use", "Silence — no one is home", "A message saying the number is disconnected"], correctAnswer: "A repeated beeping — the line is in use", explanation: "A busy signal is a repeated beeping tone indicating the person you are calling is already on the phone."),
            ExerciseItem(prompt: "If you call someone and they don't answer, what can you do?", options: ["Call 911", "Leave a voicemail", "Give up", "Call the police"], correctAnswer: "Leave a voicemail", explanation: "When someone does not answer, you can leave a voicemail message for them to hear later."),
            ExerciseItem(prompt: "What is 411 used for?", options: ["Emergency services", "Directory assistance to find phone numbers", "Weather updates", "Poison control"], correctAnswer: "Directory assistance to find phone numbers", explanation: "411 is the number for directory assistance, which helps you find phone numbers for businesses or people."),
            ExerciseItem(prompt: "What should you say first when calling 911?", options: ["Your name and age", "Your location and what happened", "Your insurance information", "How long ago it happened"], correctAnswer: "Your location and what happened", explanation: "Giving your location first allows emergency responders to start heading to you while you describe the situation."),
            ExerciseItem(prompt: "What does it mean when your phone says \"No Service\"?", options: ["Your phone is broken", "Your phone cannot connect to a network to make or receive calls", "Someone has blocked your number", "Your battery is low"], correctAnswer: "Your phone cannot connect to a network to make or receive calls", explanation: "\"No Service\" means your phone cannot reach a cell tower to send or receive calls and texts."),
            ExerciseItem(prompt: "What is a voicemail?", options: ["A text message sent automatically", "A recorded message left when someone doesn't answer", "An email read aloud by your phone", "A video message"], correctAnswer: "A recorded message left when someone doesn't answer", explanation: "Voicemail is a system that records a spoken message when the person you called does not answer."),
            ExerciseItem(prompt: "What should you do if you accidentally call 911?", options: ["Hang up immediately and hope they don't call back", "Stay on the line and tell the operator it was a mistake", "Leave your phone off the hook", "Change your phone number"], correctAnswer: "Stay on the line and tell the operator it was a mistake", explanation: "Hanging up on 911 can cause dispatchers to send emergency services to your location. It is best to stay on and explain it was an accidental call."),
            ExerciseItem(prompt: "What is Poison Control's purpose?", options: ["To regulate pesticides sold in stores", "To provide immediate guidance when someone has been exposed to a poison", "To test food for contamination", "To identify dangerous plants"], correctAnswer: "To provide immediate guidance when someone has been exposed to a poison", explanation: "Poison Control specialists provide immediate advice when someone ingests, inhales, or is exposed to a toxic substance."),
            ExerciseItem(prompt: "If your landline phone has no dial tone, what is a likely reason?", options: ["Someone else is using a cell phone nearby", "There is a problem with your phone line or service", "You forgot to pay your electricity bill", "Your phone is too old"], correctAnswer: "There is a problem with your phone line or service", explanation: "No dial tone usually indicates an issue with the phone line, a loose connection, or a problem with your phone service."),
            ExerciseItem(prompt: "What does it mean when a call goes straight to voicemail?", options: ["The person has blocked you", "The person's phone may be off, out of range, or set to Do Not Disturb", "The call was dropped", "Your phone has a bad connection"], correctAnswer: "The person's phone may be off, out of range, or set to Do Not Disturb", explanation: "Calls going directly to voicemail often mean the person's phone is off, has no signal, or calls are being silenced."),
            ExerciseItem(prompt: "If you are in a car accident and need help, what should you do first?", options: ["Call your insurance company", "Call 911 to report the accident and request help", "Drive to the nearest hospital", "Take photos of the damage"], correctAnswer: "Call 911 to report the accident and request help", explanation: "Calling 911 ensures that police and emergency medical services are dispatched to assist."),
            ExerciseItem(prompt: "What does it mean if your smoke detector is beeping once every 30 to 60 seconds?", options: ["There is a fire nearby", "The battery is low and needs to be replaced", "The detector has been triggered by steam", "The detector is working correctly"], correctAnswer: "The battery is low and needs to be replaced", explanation: "A single chirp every 30 to 60 seconds is the standard low-battery warning signal for smoke detectors."),
            ExerciseItem(prompt: "What is the Poison Control hotline number in the US?", options: ["911", "811", "1-800-222-1222", "311"], correctAnswer: "1-800-222-1222", explanation: "The US Poison Control Center can be reached at 1-800-222-1222, available 24 hours a day."),
            ExerciseItem(prompt: "If you feel chest pain and shortness of breath, what should you do?", options: ["Wait and see if it gets better", "Call 911 or have someone drive you to the emergency room immediately", "Take an extra dose of your blood pressure medication", "Drink water and rest"], correctAnswer: "Call 911 or have someone drive you to the emergency room immediately", explanation: "Chest pain and shortness of breath can be signs of a heart attack or other serious emergency requiring immediate care."),
            ExerciseItem(prompt: "What should you do if you receive a call asking for your Social Security number?", options: ["Give it if they sound official", "Hang up and do not give it — this is likely a scam", "Give only the last four digits", "Ask them to send a letter instead"], correctAnswer: "Hang up and do not give it — this is likely a scam", explanation: "Legitimate organizations never call to ask for your Social Security number; unsolicited requests are almost always scams."),
            ExerciseItem(prompt: "What does 311 do in most US cities?", options: ["Emergency police response", "Connect you to non-emergency city services and information", "Provide medical advice", "Connect you to a local hospital"], correctAnswer: "Connect you to non-emergency city services and information", explanation: "311 is for non-emergency city services such as reporting potholes, noise complaints, or getting local government information."),
            ExerciseItem(prompt: "What is a text message?", options: ["A phone call recorded and saved", "A short written message sent from phone to phone", "An email sent to a phone number", "A photo sent between phones"], correctAnswer: "A short written message sent from phone to phone", explanation: "A text message (SMS) is a short written communication sent directly between mobile phones."),
            ExerciseItem(prompt: "If you call someone and get a recording saying \"the number you have dialed is not in service,\" what does this mean?", options: ["The person is not home", "The phone number is wrong, disconnected, or no longer active", "The call dropped", "You need to call back later"], correctAnswer: "The phone number is wrong, disconnected, or no longer active", explanation: "This recording means the number does not exist, has been disconnected, or is no longer assigned to anyone."),
            ExerciseItem(prompt: "What should you do if you witness someone collapse in a public place?", options: ["Wait to see if they get up on their own", "Call 911 immediately and stay with the person", "Ask bystanders to take a photo", "Drive them to the hospital yourself"], correctAnswer: "Call 911 immediately and stay with the person", explanation: "Calling 911 right away gets trained medical help on the way; staying with the person allows you to monitor their condition and assist the dispatcher.")
        ]
    )

    // MARK: - Exercise 9: Before or After?
    private static let exercise9 = Exercise(
        title: "Before or After?",
        instructions: "Identify which step comes first in the everyday task.",
        section: .functionalSkills,
        type: .multipleChoice,
        trackedType: nil,
        difficulty: .easy,
        items: [
            ExerciseItem(prompt: "When making coffee, do you add the water BEFORE or AFTER adding the coffee grounds?", options: ["Before — add water first, then grounds", "After — add grounds first, then water", "At the same time", "It doesn't matter"], correctAnswer: "Before — add water first, then grounds", explanation: "In most coffee makers, water is added to the reservoir before or alongside the grounds in the filter."),
            ExerciseItem(prompt: "When getting dressed, do you put on socks BEFORE or AFTER your shoes?", options: ["After — shoes first, then socks", "Before — socks first, then shoes", "At the same time", "It doesn't matter"], correctAnswer: "Before — socks first, then shoes", explanation: "Socks are worn next to the foot and must be put on before shoes."),
            ExerciseItem(prompt: "When washing your hands, what is the correct order?", options: ["Before — wet hands first, then soap", "After — soap first, then rinse", "Wet hands first, apply soap, then rinse", "It doesn't matter"], correctAnswer: "Wet hands first, apply soap, then rinse", explanation: "Proper handwashing means wetting your hands, applying soap and scrubbing, then rinsing off the soap."),
            ExerciseItem(prompt: "When mailing a letter, do you write the address BEFORE or AFTER sealing the envelope?", options: ["Before — write address, then seal", "After — seal first, then write address", "At the same time", "It doesn't matter"], correctAnswer: "Before — write address, then seal", explanation: "The address should be written on the envelope before sealing so it can be read by postal workers."),
            ExerciseItem(prompt: "When cooking pasta, do you add the pasta to the pot BEFORE or AFTER the water boils?", options: ["Before — pasta goes in with cold water", "After — wait for the water to boil first", "At the same time", "It doesn't matter"], correctAnswer: "After — wait for the water to boil first", explanation: "Adding pasta to already-boiling water ensures it cooks evenly and does not become mushy."),
            ExerciseItem(prompt: "When brushing your teeth, do you wet the toothbrush BEFORE or AFTER adding toothpaste?", options: ["Before — wet brush first, then add toothpaste", "After — toothpaste first, then wet", "At the same time", "It doesn't matter"], correctAnswer: "Before — wet brush first, then add toothpaste", explanation: "Wetting the brush first makes it more comfortable to use, and then toothpaste is applied on top."),
            ExerciseItem(prompt: "When making a sandwich, do you spread the condiments BEFORE or AFTER adding the fillings?", options: ["Before — spread on bread, then add fillings", "After — fillings first, then condiments on top", "At the same time", "It doesn't matter"], correctAnswer: "Before — spread on bread, then add fillings", explanation: "Condiments like mustard or mayonnaise are spread on the bread first, then fillings are layered on top."),
            ExerciseItem(prompt: "When taking a shower, do you turn on the water BEFORE or AFTER getting in?", options: ["Before — let water warm up first", "After — step in, then turn on water", "At the same time", "It doesn't matter"], correctAnswer: "Before — let water warm up first", explanation: "Turning on the water first allows you to adjust the temperature before stepping in."),
            ExerciseItem(prompt: "When refilling a prescription, should you call the pharmacy BEFORE or AFTER you run out completely?", options: ["After — wait until you are completely out", "Before — call a few days before you run out", "At the same time you take your last dose", "It doesn't matter"], correctAnswer: "Before — call a few days before you run out", explanation: "Calling ahead ensures there is no gap in your medication and allows time for the pharmacy to process the refill."),
            ExerciseItem(prompt: "When using an ATM, do you enter your PIN BEFORE or AFTER inserting your card?", options: ["Before — PIN first, then card", "After — insert card first, then enter PIN", "At the same time", "It doesn't matter"], correctAnswer: "After — insert card first, then enter PIN", explanation: "You must insert your card first so the ATM can read it; then it prompts you to enter your PIN."),
            ExerciseItem(prompt: "When boiling eggs, do you put the eggs in BEFORE or AFTER the water boils?", options: ["Before — eggs go in cold water, then heat", "After — wait for boil, then add eggs", "At the same time", "It doesn't matter"], correctAnswer: "Before — eggs go in cold water, then heat", explanation: "Starting eggs in cold water and bringing them to a boil together helps prevent cracking and gives more consistent results."),
            ExerciseItem(prompt: "When doing laundry, do you add detergent BEFORE or AFTER loading clothes?", options: ["Before — detergent first in some machines", "After — clothes first, then detergent on top", "At the same time", "It depends on the machine"], correctAnswer: "Before — detergent first in some machines", explanation: "In many top-load washers, detergent is added first so it dissolves before the clothes are loaded; always check your machine's instructions."),
            ExerciseItem(prompt: "When driving to a new place, should you check directions BEFORE or AFTER leaving home?", options: ["Before — plan your route first", "After — figure it out on the way", "At the same time", "It doesn't matter"], correctAnswer: "Before — plan your route first", explanation: "Checking directions before leaving helps you know the route and avoid getting lost or distracted while driving."),
            ExerciseItem(prompt: "When wrapping a gift, do you put the item in the box BEFORE or AFTER wrapping the paper?", options: ["Before — box the gift first, then wrap", "After — wrap first, then insert", "At the same time", "It doesn't matter"], correctAnswer: "Before — box the gift first, then wrap", explanation: "The gift goes into the box first, then the box is wrapped in paper."),
            ExerciseItem(prompt: "When going to a doctor's appointment, should you arrive BEFORE or AFTER your scheduled time?", options: ["Before — arrive a few minutes early", "After — it is okay to be a little late", "At the exact scheduled time", "It doesn't matter"], correctAnswer: "Before — arrive a few minutes early", explanation: "Arriving a few minutes early gives you time to check in, complete any paperwork, and be ready when the doctor is available."),
            ExerciseItem(prompt: "When unlocking a door with a key, do you insert the key BEFORE or AFTER turning the handle?", options: ["Before — insert and turn key, then open handle", "After — turn handle first, then key", "At the same time", "It doesn't matter"], correctAnswer: "Before — insert and turn key, then open handle", explanation: "The key must be inserted and turned to unlock the deadbolt before the handle can open the door."),
            ExerciseItem(prompt: "When making toast, do you slice bread BEFORE or AFTER toasting it?", options: ["Before — slice, then toast", "After — toast first, then slice", "At the same time", "It doesn't matter"], correctAnswer: "Before — slice, then toast", explanation: "Bread is sliced first so it fits in the toaster; toasting a whole loaf is not practical."),
            ExerciseItem(prompt: "When taking medicine \"with food,\" should you eat BEFORE or AFTER taking the pill?", options: ["Before or at the same time — take with food", "After — take pill first, then eat later", "At the same time", "It doesn't matter"], correctAnswer: "Before or at the same time — take with food", explanation: "\"Take with food\" means eating before or during the time you take the medication to protect your stomach."),
            ExerciseItem(prompt: "When signing a check, do you write the amount BEFORE or AFTER signing?", options: ["Before — fill in the check, then sign", "After — sign first, then fill in amount", "At the same time", "It doesn't matter"], correctAnswer: "Before — fill in the check, then sign", explanation: "The amount and payee should be filled in first; signing last confirms and authorizes the completed check."),
            ExerciseItem(prompt: "When checking out at a grocery store, do you place items on the belt BEFORE or AFTER the cashier scans them?", options: ["Before — place items on belt, cashier scans them", "After — cashier scans them directly from your cart", "At the same time", "It doesn't matter"], correctAnswer: "Before — place items on belt, cashier scans them", explanation: "You place items on the conveyor belt first, then the cashier picks them up to scan the barcodes.")
        ]
    )

}
