import Foundation

struct FrenchHardExercisesData {
    static let allExercises: [Exercise] = [
        Exercise(
            id: UUID(),
            title: "Easy Homonyms",
            instructions: "Choisissez le bon mot homophone.",
            section: .language,
            type: .homonym,
            difficulty: .easy,
            items: [
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte pour compléter la phrase : Il boit un ___ d'eau.", options: ["verre", "vert", "vers", "ver"], correctAnswer: "verre", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte pour compléter la phrase : Il boit un ___ d'eau.", options: ["verre", "vert", "vers", "ver"], correctAnswer: "verre", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte pour compléter la phrase : Il boit un ___ d'eau.", options: ["verre", "vert", "vers", "ver"], correctAnswer: "verre", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte pour compléter la phrase : Il boit un ___ d'eau.", options: ["verre", "vert", "vers", "ver"], correctAnswer: "verre", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte pour compléter la phrase : Il boit un ___ d'eau.", options: ["verre", "vert", "vers", "ver"], correctAnswer: "verre", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte pour compléter la phrase : Il boit un ___ d'eau.", options: ["verre", "vert", "vers", "ver"], correctAnswer: "verre", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte pour compléter la phrase : Il boit un ___ d'eau.", options: ["verre", "vert", "vers", "ver"], correctAnswer: "verre", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte pour compléter la phrase : Il boit un ___ d'eau.", options: ["verre", "vert", "vers", "ver"], correctAnswer: "verre", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte pour compléter la phrase : Il boit un ___ d'eau.", options: ["verre", "vert", "vers", "ver"], correctAnswer: "verre", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte pour compléter la phrase : Il boit un ___ d'eau.", options: ["verre", "vert", "vers", "ver"], correctAnswer: "verre", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte pour compléter la phrase : Il boit un ___ d'eau.", options: ["verre", "vert", "vers", "ver"], correctAnswer: "verre", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte pour compléter la phrase : Il boit un ___ d'eau.", options: ["verre", "vert", "vers", "ver"], correctAnswer: "verre", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte pour compléter la phrase : Il boit un ___ d'eau.", options: ["verre", "vert", "vers", "ver"], correctAnswer: "verre", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte pour compléter la phrase : Il boit un ___ d'eau.", options: ["verre", "vert", "vers", "ver"], correctAnswer: "verre", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte pour compléter la phrase : Il boit un ___ d'eau.", options: ["verre", "vert", "vers", "ver"], correctAnswer: "verre", explanation: ""),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Medium Homonyms",
            instructions: "Choisissez le bon mot homophone.",
            section: .language,
            type: .homonym,
            difficulty: .medium,
            items: [
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte : La ___ de la ville a pris une décision.", options: ["maire", "mer", "mère", "mât"], correctAnswer: "maire", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte : La ___ de la ville a pris une décision.", options: ["maire", "mer", "mère", "mât"], correctAnswer: "maire", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte : La ___ de la ville a pris une décision.", options: ["maire", "mer", "mère", "mât"], correctAnswer: "maire", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte : La ___ de la ville a pris une décision.", options: ["maire", "mer", "mère", "mât"], correctAnswer: "maire", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte : La ___ de la ville a pris une décision.", options: ["maire", "mer", "mère", "mât"], correctAnswer: "maire", explanation: ""),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Hard Homonyms",
            instructions: "Choisissez le bon mot homophone.",
            section: .language,
            type: .homonym,
            difficulty: .hard,
            items: [
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte : Ce comportement est tout à fait ___ (en bonne santé).", options: ["sain", "saint", "sein", "seing"], correctAnswer: "sain", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte : Ce comportement est tout à fait ___ (en bonne santé).", options: ["sain", "saint", "sein", "seing"], correctAnswer: "sain", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte : Ce comportement est tout à fait ___ (en bonne santé).", options: ["sain", "saint", "sein", "seing"], correctAnswer: "sain", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte : Ce comportement est tout à fait ___ (en bonne santé).", options: ["sain", "saint", "sein", "seing"], correctAnswer: "sain", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte : Ce comportement est tout à fait ___ (en bonne santé).", options: ["sain", "saint", "sein", "seing"], correctAnswer: "sain", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte : Ce comportement est tout à fait ___ (en bonne santé).", options: ["sain", "saint", "sein", "seing"], correctAnswer: "sain", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte : Ce comportement est tout à fait ___ (en bonne santé).", options: ["sain", "saint", "sein", "seing"], correctAnswer: "sain", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte : Ce comportement est tout à fait ___ (en bonne santé).", options: ["sain", "saint", "sein", "seing"], correctAnswer: "sain", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte : Ce comportement est tout à fait ___ (en bonne santé).", options: ["sain", "saint", "sein", "seing"], correctAnswer: "sain", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte : Ce comportement est tout à fait ___ (en bonne santé).", options: ["sain", "saint", "sein", "seing"], correctAnswer: "sain", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte : Ce comportement est tout à fait ___ (en bonne santé).", options: ["sain", "saint", "sein", "seing"], correctAnswer: "sain", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte : Ce comportement est tout à fait ___ (en bonne santé).", options: ["sain", "saint", "sein", "seing"], correctAnswer: "sain", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte : Ce comportement est tout à fait ___ (en bonne santé).", options: ["sain", "saint", "sein", "seing"], correctAnswer: "sain", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte : Ce comportement est tout à fait ___ (en bonne santé).", options: ["sain", "saint", "sein", "seing"], correctAnswer: "sain", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Choisissez l'orthographe correcte : Ce comportement est tout à fait ___ (en bonne santé).", options: ["sain", "saint", "sein", "seing"], correctAnswer: "sain", explanation: ""),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Easy Analogies",
            instructions: "Complétez la relation analogique.",
            section: .language,
            type: .analogyChoice,
            difficulty: .easy,
            items: [
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : Le chien aboie, le chat ___ ?", options: ["miaule", "rugit", "chante", "siffle"], correctAnswer: "miaule", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : Le chien aboie, le chat ___ ?", options: ["miaule", "rugit", "chante", "siffle"], correctAnswer: "miaule", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : Le chien aboie, le chat ___ ?", options: ["miaule", "rugit", "chante", "siffle"], correctAnswer: "miaule", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : Le chien aboie, le chat ___ ?", options: ["miaule", "rugit", "chante", "siffle"], correctAnswer: "miaule", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : Le chien aboie, le chat ___ ?", options: ["miaule", "rugit", "chante", "siffle"], correctAnswer: "miaule", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : Le chien aboie, le chat ___ ?", options: ["miaule", "rugit", "chante", "siffle"], correctAnswer: "miaule", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : Le chien aboie, le chat ___ ?", options: ["miaule", "rugit", "chante", "siffle"], correctAnswer: "miaule", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : Le chien aboie, le chat ___ ?", options: ["miaule", "rugit", "chante", "siffle"], correctAnswer: "miaule", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : Le chien aboie, le chat ___ ?", options: ["miaule", "rugit", "chante", "siffle"], correctAnswer: "miaule", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : Le chien aboie, le chat ___ ?", options: ["miaule", "rugit", "chante", "siffle"], correctAnswer: "miaule", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : Le chien aboie, le chat ___ ?", options: ["miaule", "rugit", "chante", "siffle"], correctAnswer: "miaule", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : Le chien aboie, le chat ___ ?", options: ["miaule", "rugit", "chante", "siffle"], correctAnswer: "miaule", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : Le chien aboie, le chat ___ ?", options: ["miaule", "rugit", "chante", "siffle"], correctAnswer: "miaule", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : Le chien aboie, le chat ___ ?", options: ["miaule", "rugit", "chante", "siffle"], correctAnswer: "miaule", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : Le chien aboie, le chat ___ ?", options: ["miaule", "rugit", "chante", "siffle"], correctAnswer: "miaule", explanation: ""),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Hard Analogies",
            instructions: "Complétez la relation analogique.",
            section: .language,
            type: .analogyChoice,
            difficulty: .hard,
            items: [
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : L'écrivain utilise des mots, le sculpteur utilise un ___ ?", options: ["ciseau", "pinceau", "stylo", "violon"], correctAnswer: "ciseau", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : L'écrivain utilise des mots, le sculpteur utilise un ___ ?", options: ["ciseau", "pinceau", "stylo", "violon"], correctAnswer: "ciseau", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : L'écrivain utilise des mots, le sculpteur utilise un ___ ?", options: ["ciseau", "pinceau", "stylo", "violon"], correctAnswer: "ciseau", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : L'écrivain utilise des mots, le sculpteur utilise un ___ ?", options: ["ciseau", "pinceau", "stylo", "violon"], correctAnswer: "ciseau", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : L'écrivain utilise des mots, le sculpteur utilise un ___ ?", options: ["ciseau", "pinceau", "stylo", "violon"], correctAnswer: "ciseau", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : L'écrivain utilise des mots, le sculpteur utilise un ___ ?", options: ["ciseau", "pinceau", "stylo", "violon"], correctAnswer: "ciseau", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : L'écrivain utilise des mots, le sculpteur utilise un ___ ?", options: ["ciseau", "pinceau", "stylo", "violon"], correctAnswer: "ciseau", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : L'écrivain utilise des mots, le sculpteur utilise un ___ ?", options: ["ciseau", "pinceau", "stylo", "violon"], correctAnswer: "ciseau", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : L'écrivain utilise des mots, le sculpteur utilise un ___ ?", options: ["ciseau", "pinceau", "stylo", "violon"], correctAnswer: "ciseau", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : L'écrivain utilise des mots, le sculpteur utilise un ___ ?", options: ["ciseau", "pinceau", "stylo", "violon"], correctAnswer: "ciseau", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : L'écrivain utilise des mots, le sculpteur utilise un ___ ?", options: ["ciseau", "pinceau", "stylo", "violon"], correctAnswer: "ciseau", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : L'écrivain utilise des mots, le sculpteur utilise un ___ ?", options: ["ciseau", "pinceau", "stylo", "violon"], correctAnswer: "ciseau", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : L'écrivain utilise des mots, le sculpteur utilise un ___ ?", options: ["ciseau", "pinceau", "stylo", "violon"], correctAnswer: "ciseau", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : L'écrivain utilise des mots, le sculpteur utilise un ___ ?", options: ["ciseau", "pinceau", "stylo", "violon"], correctAnswer: "ciseau", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez l'analogie : L'écrivain utilise des mots, le sculpteur utilise un ___ ?", options: ["ciseau", "pinceau", "stylo", "violon"], correctAnswer: "ciseau", explanation: ""),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Medium Word Association",
            instructions: "Choisissez le mot associé.",
            section: .language,
            type: .multipleChoice,
            difficulty: .medium,
            items: [
                ExerciseItem(id: UUID(), prompt: "Quel mot est le plus associé à : VIGNOBLE ?", options: ["raisin", "pomme", "livre", "voiture"], correctAnswer: "raisin", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quel mot est le plus associé à : VIGNOBLE ?", options: ["raisin", "pomme", "livre", "voiture"], correctAnswer: "raisin", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quel mot est le plus associé à : VIGNOBLE ?", options: ["raisin", "pomme", "livre", "voiture"], correctAnswer: "raisin", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quel mot est le plus associé à : VIGNOBLE ?", options: ["raisin", "pomme", "livre", "voiture"], correctAnswer: "raisin", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quel mot est le plus associé à : VIGNOBLE ?", options: ["raisin", "pomme", "livre", "voiture"], correctAnswer: "raisin", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quel mot est le plus associé à : VIGNOBLE ?", options: ["raisin", "pomme", "livre", "voiture"], correctAnswer: "raisin", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quel mot est le plus associé à : VIGNOBLE ?", options: ["raisin", "pomme", "livre", "voiture"], correctAnswer: "raisin", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quel mot est le plus associé à : VIGNOBLE ?", options: ["raisin", "pomme", "livre", "voiture"], correctAnswer: "raisin", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quel mot est le plus associé à : VIGNOBLE ?", options: ["raisin", "pomme", "livre", "voiture"], correctAnswer: "raisin", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quel mot est le plus associé à : VIGNOBLE ?", options: ["raisin", "pomme", "livre", "voiture"], correctAnswer: "raisin", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quel mot est le plus associé à : VIGNOBLE ?", options: ["raisin", "pomme", "livre", "voiture"], correctAnswer: "raisin", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quel mot est le plus associé à : VIGNOBLE ?", options: ["raisin", "pomme", "livre", "voiture"], correctAnswer: "raisin", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quel mot est le plus associé à : VIGNOBLE ?", options: ["raisin", "pomme", "livre", "voiture"], correctAnswer: "raisin", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quel mot est le plus associé à : VIGNOBLE ?", options: ["raisin", "pomme", "livre", "voiture"], correctAnswer: "raisin", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quel mot est le plus associé à : VIGNOBLE ?", options: ["raisin", "pomme", "livre", "voiture"], correctAnswer: "raisin", explanation: ""),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Easy Cause and Effect",
            instructions: "Déterminez la conséquence logique.",
            section: .cognition,
            type: .multipleChoice,
            difficulty: .easy,
            items: [
                ExerciseItem(id: UUID(), prompt: "Quelle est la conséquence logique : Le soleil brille intensément en été ?", options: ["Il fait chaud", "Il neige", "Le sol gèle", "Il fait nuit"], correctAnswer: "Il fait chaud", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quelle est la conséquence logique : Le soleil brille intensément en été ?", options: ["Il fait chaud", "Il neige", "Le sol gèle", "Il fait nuit"], correctAnswer: "Il fait chaud", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quelle est la conséquence logique : Le soleil brille intensément en été ?", options: ["Il fait chaud", "Il neige", "Le sol gèle", "Il fait nuit"], correctAnswer: "Il fait chaud", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quelle est la conséquence logique : Le soleil brille intensément en été ?", options: ["Il fait chaud", "Il neige", "Le sol gèle", "Il fait nuit"], correctAnswer: "Il fait chaud", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quelle est la conséquence logique : Le soleil brille intensément en été ?", options: ["Il fait chaud", "Il neige", "Le sol gèle", "Il fait nuit"], correctAnswer: "Il fait chaud", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quelle est la conséquence logique : Le soleil brille intensément en été ?", options: ["Il fait chaud", "Il neige", "Le sol gèle", "Il fait nuit"], correctAnswer: "Il fait chaud", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quelle est la conséquence logique : Le soleil brille intensément en été ?", options: ["Il fait chaud", "Il neige", "Le sol gèle", "Il fait nuit"], correctAnswer: "Il fait chaud", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quelle est la conséquence logique : Le soleil brille intensément en été ?", options: ["Il fait chaud", "Il neige", "Le sol gèle", "Il fait nuit"], correctAnswer: "Il fait chaud", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quelle est la conséquence logique : Le soleil brille intensément en été ?", options: ["Il fait chaud", "Il neige", "Le sol gèle", "Il fait nuit"], correctAnswer: "Il fait chaud", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quelle est la conséquence logique : Le soleil brille intensément en été ?", options: ["Il fait chaud", "Il neige", "Le sol gèle", "Il fait nuit"], correctAnswer: "Il fait chaud", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quelle est la conséquence logique : Le soleil brille intensément en été ?", options: ["Il fait chaud", "Il neige", "Le sol gèle", "Il fait nuit"], correctAnswer: "Il fait chaud", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quelle est la conséquence logique : Le soleil brille intensément en été ?", options: ["Il fait chaud", "Il neige", "Le sol gèle", "Il fait nuit"], correctAnswer: "Il fait chaud", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quelle est la conséquence logique : Le soleil brille intensément en été ?", options: ["Il fait chaud", "Il neige", "Le sol gèle", "Il fait nuit"], correctAnswer: "Il fait chaud", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quelle est la conséquence logique : Le soleil brille intensément en été ?", options: ["Il fait chaud", "Il neige", "Le sol gèle", "Il fait nuit"], correctAnswer: "Il fait chaud", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Quelle est la conséquence logique : Le soleil brille intensément en été ?", options: ["Il fait chaud", "Il neige", "Le sol gèle", "Il fait nuit"], correctAnswer: "Il fait chaud", explanation: ""),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Easy What's Wrong Here",
            instructions: "Identifiez l'incohérence logique.",
            section: .cognition,
            type: .multipleChoice,
            difficulty: .easy,
            items: [
                ExerciseItem(id: UUID(), prompt: "Trouvez l'erreur logique : Il pleut des cordes et Marie sort avec des lunettes de soleil et sans parapluie.", options: ["Sortir sans parapluie sous la pluie", "Le fait qu'il pleuve", "Le prénom de Marie", "Rien"], correctAnswer: "Sortir sans parapluie sous la pluie", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Trouvez l'erreur logique : Il pleut des cordes et Marie sort avec des lunettes de soleil et sans parapluie.", options: ["Sortir sans parapluie sous la pluie", "Le fait qu'il pleuve", "Le prénom de Marie", "Rien"], correctAnswer: "Sortir sans parapluie sous la pluie", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Trouvez l'erreur logique : Il pleut des cordes et Marie sort avec des lunettes de soleil et sans parapluie.", options: ["Sortir sans parapluie sous la pluie", "Le fait qu'il pleuve", "Le prénom de Marie", "Rien"], correctAnswer: "Sortir sans parapluie sous la pluie", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Trouvez l'erreur logique : Il pleut des cordes et Marie sort avec des lunettes de soleil et sans parapluie.", options: ["Sortir sans parapluie sous la pluie", "Le fait qu'il pleuve", "Le prénom de Marie", "Rien"], correctAnswer: "Sortir sans parapluie sous la pluie", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Trouvez l'erreur logique : Il pleut des cordes et Marie sort avec des lunettes de soleil et sans parapluie.", options: ["Sortir sans parapluie sous la pluie", "Le fait qu'il pleuve", "Le prénom de Marie", "Rien"], correctAnswer: "Sortir sans parapluie sous la pluie", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Trouvez l'erreur logique : Il pleut des cordes et Marie sort avec des lunettes de soleil et sans parapluie.", options: ["Sortir sans parapluie sous la pluie", "Le fait qu'il pleuve", "Le prénom de Marie", "Rien"], correctAnswer: "Sortir sans parapluie sous la pluie", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Trouvez l'erreur logique : Il pleut des cordes et Marie sort avec des lunettes de soleil et sans parapluie.", options: ["Sortir sans parapluie sous la pluie", "Le fait qu'il pleuve", "Le prénom de Marie", "Rien"], correctAnswer: "Sortir sans parapluie sous la pluie", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Trouvez l'erreur logique : Il pleut des cordes et Marie sort avec des lunettes de soleil et sans parapluie.", options: ["Sortir sans parapluie sous la pluie", "Le fait qu'il pleuve", "Le prénom de Marie", "Rien"], correctAnswer: "Sortir sans parapluie sous la pluie", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Trouvez l'erreur logique : Il pleut des cordes et Marie sort avec des lunettes de soleil et sans parapluie.", options: ["Sortir sans parapluie sous la pluie", "Le fait qu'il pleuve", "Le prénom de Marie", "Rien"], correctAnswer: "Sortir sans parapluie sous la pluie", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Trouvez l'erreur logique : Il pleut des cordes et Marie sort avec des lunettes de soleil et sans parapluie.", options: ["Sortir sans parapluie sous la pluie", "Le fait qu'il pleuve", "Le prénom de Marie", "Rien"], correctAnswer: "Sortir sans parapluie sous la pluie", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Trouvez l'erreur logique : Il pleut des cordes et Marie sort avec des lunettes de soleil et sans parapluie.", options: ["Sortir sans parapluie sous la pluie", "Le fait qu'il pleuve", "Le prénom de Marie", "Rien"], correctAnswer: "Sortir sans parapluie sous la pluie", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Trouvez l'erreur logique : Il pleut des cordes et Marie sort avec des lunettes de soleil et sans parapluie.", options: ["Sortir sans parapluie sous la pluie", "Le fait qu'il pleuve", "Le prénom de Marie", "Rien"], correctAnswer: "Sortir sans parapluie sous la pluie", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Trouvez l'erreur logique : Il pleut des cordes et Marie sort avec des lunettes de soleil et sans parapluie.", options: ["Sortir sans parapluie sous la pluie", "Le fait qu'il pleuve", "Le prénom de Marie", "Rien"], correctAnswer: "Sortir sans parapluie sous la pluie", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Trouvez l'erreur logique : Il pleut des cordes et Marie sort avec des lunettes de soleil et sans parapluie.", options: ["Sortir sans parapluie sous la pluie", "Le fait qu'il pleuve", "Le prénom de Marie", "Rien"], correctAnswer: "Sortir sans parapluie sous la pluie", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Trouvez l'erreur logique : Il pleut des cordes et Marie sort avec des lunettes de soleil et sans parapluie.", options: ["Sortir sans parapluie sous la pluie", "Le fait qu'il pleuve", "Le prénom de Marie", "Rien"], correctAnswer: "Sortir sans parapluie sous la pluie", explanation: ""),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Easy Sequencing",
            instructions: "Remettez dans le bon ordre.",
            section: .cognition,
            type: .sequencing,
            difficulty: .easy,
            items: [
                ExerciseItem(id: UUID(), prompt: "Remettez les étapes dans l'ordre chronologique :", options: ["Se coucher", "Dîner", "Se brosser les dents", "Regarder un film"], correctAnswer: "Dîner | Regarder un film | Se brosser les dents | Se coucher", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Remettez les étapes dans l'ordre chronologique :", options: ["Se coucher", "Dîner", "Se brosser les dents", "Regarder un film"], correctAnswer: "Dîner | Regarder un film | Se brosser les dents | Se coucher", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Remettez les étapes dans l'ordre chronologique :", options: ["Se coucher", "Dîner", "Se brosser les dents", "Regarder un film"], correctAnswer: "Dîner | Regarder un film | Se brosser les dents | Se coucher", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Remettez les étapes dans l'ordre chronologique :", options: ["Se coucher", "Dîner", "Se brosser les dents", "Regarder un film"], correctAnswer: "Dîner | Regarder un film | Se brosser les dents | Se coucher", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Remettez les étapes dans l'ordre chronologique :", options: ["Se coucher", "Dîner", "Se brosser les dents", "Regarder un film"], correctAnswer: "Dîner | Regarder un film | Se brosser les dents | Se coucher", explanation: ""),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Easy Complete the Saying",
            instructions: "Complétez le proverbe.",
            section: .language,
            type: .sentenceCompletion,
            difficulty: .easy,
            items: [
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe : Après la pluie, le beau ___.", options: ["temps", "vent", "jour", "ciel"], correctAnswer: "temps", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe : Après la pluie, le beau ___.", options: ["temps", "vent", "jour", "ciel"], correctAnswer: "temps", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe : Après la pluie, le beau ___.", options: ["temps", "vent", "jour", "ciel"], correctAnswer: "temps", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe : Après la pluie, le beau ___.", options: ["temps", "vent", "jour", "ciel"], correctAnswer: "temps", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe : Après la pluie, le beau ___.", options: ["temps", "vent", "jour", "ciel"], correctAnswer: "temps", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe : Après la pluie, le beau ___.", options: ["temps", "vent", "jour", "ciel"], correctAnswer: "temps", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe : Après la pluie, le beau ___.", options: ["temps", "vent", "jour", "ciel"], correctAnswer: "temps", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe : Après la pluie, le beau ___.", options: ["temps", "vent", "jour", "ciel"], correctAnswer: "temps", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe : Après la pluie, le beau ___.", options: ["temps", "vent", "jour", "ciel"], correctAnswer: "temps", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe : Après la pluie, le beau ___.", options: ["temps", "vent", "jour", "ciel"], correctAnswer: "temps", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe : Après la pluie, le beau ___.", options: ["temps", "vent", "jour", "ciel"], correctAnswer: "temps", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe : Après la pluie, le beau ___.", options: ["temps", "vent", "jour", "ciel"], correctAnswer: "temps", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe : Après la pluie, le beau ___.", options: ["temps", "vent", "jour", "ciel"], correctAnswer: "temps", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe : Après la pluie, le beau ___.", options: ["temps", "vent", "jour", "ciel"], correctAnswer: "temps", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe : Après la pluie, le beau ___.", options: ["temps", "vent", "jour", "ciel"], correctAnswer: "temps", explanation: ""),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Hard Complete the Saying",
            instructions: "Complétez le proverbe.",
            section: .language,
            type: .sentenceCompletion,
            difficulty: .hard,
            items: [
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe rare : Pierre qui roule n'amasse pas ___.", options: ["mousse", "terre", "or", "argent"], correctAnswer: "mousse", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe rare : Pierre qui roule n'amasse pas ___.", options: ["mousse", "terre", "or", "argent"], correctAnswer: "mousse", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe rare : Pierre qui roule n'amasse pas ___.", options: ["mousse", "terre", "or", "argent"], correctAnswer: "mousse", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe rare : Pierre qui roule n'amasse pas ___.", options: ["mousse", "terre", "or", "argent"], correctAnswer: "mousse", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe rare : Pierre qui roule n'amasse pas ___.", options: ["mousse", "terre", "or", "argent"], correctAnswer: "mousse", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe rare : Pierre qui roule n'amasse pas ___.", options: ["mousse", "terre", "or", "argent"], correctAnswer: "mousse", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe rare : Pierre qui roule n'amasse pas ___.", options: ["mousse", "terre", "or", "argent"], correctAnswer: "mousse", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe rare : Pierre qui roule n'amasse pas ___.", options: ["mousse", "terre", "or", "argent"], correctAnswer: "mousse", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe rare : Pierre qui roule n'amasse pas ___.", options: ["mousse", "terre", "or", "argent"], correctAnswer: "mousse", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe rare : Pierre qui roule n'amasse pas ___.", options: ["mousse", "terre", "or", "argent"], correctAnswer: "mousse", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe rare : Pierre qui roule n'amasse pas ___.", options: ["mousse", "terre", "or", "argent"], correctAnswer: "mousse", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe rare : Pierre qui roule n'amasse pas ___.", options: ["mousse", "terre", "or", "argent"], correctAnswer: "mousse", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe rare : Pierre qui roule n'amasse pas ___.", options: ["mousse", "terre", "or", "argent"], correctAnswer: "mousse", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe rare : Pierre qui roule n'amasse pas ___.", options: ["mousse", "terre", "or", "argent"], correctAnswer: "mousse", explanation: ""),
                ExerciseItem(id: UUID(), prompt: "Complétez le proverbe rare : Pierre qui roule n'amasse pas ___.", options: ["mousse", "terre", "or", "argent"], correctAnswer: "mousse", explanation: ""),
            ]
        )
    ]
}
