import Foundation


struct SpanishHardExercisesData {

    static let allExercises: [Exercise] = [
        exercise1,
        exercise2,
        exercise3,
        exercise4,
        exercise5,
        exercise6,
        exercise7,
        exercise8
    ]

    // MARK: - Exercise 1: Homónimos Avanzados
    private static let exercise1 = Exercise(
        title: "Homónimos Avanzados",
        instructions: "Elige la combinación correcta de homófonos para completar las oraciones.",
        section: .language,
        type: .homonym,
        trackedType: .homonym,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "[tubo / tuvo] El plomero cambió el ___ de metal. Ella ___ mucha paciencia.", options: ["tubo...tuvo", "tuvo...tubo", "tubo...tubo", "tuvo...tuvo"], correctAnswer: "tubo...tuvo", explanation: "'Tubo' es una pieza cilíndrica hueca; 'tuvo' es el pasado del verbo tener."),
            ExerciseItem(prompt: "[bello / vello] El paisaje de los Pirineos es ___. Él tiene ___ en los brazos.", options: ["bello...vello", "vello...bello", "bello...bello", "vello...vello"], correctAnswer: "bello...vello", explanation: "'Bello' significa hermoso; 'vello' es el pelo corto y suave en el cuerpo."),
            ExerciseItem(prompt: "[cocer / coser] Debemos ___ las papas para la cena. Ella va a ___ el botón roto.", options: ["cocer...coser", "coser...cocer", "cocer...cocer", "coser...coser"], correctAnswer: "cocer...coser", explanation: "'Cocer' es cocinar alimentos; 'coser' es unir tela con aguja e hilo."),
            ExerciseItem(prompt: "[echo / hecho] Siempre ___ la basura en su lugar. Él ha ___ toda la tarea.", options: ["echo...hecho", "hecho...echo", "echo...echo", "hecho...hecho"], correctAnswer: "echo...hecho", explanation: "'Echo' es del verbo echar (tirar); 'hecho' es del verbo hacer."),
            ExerciseItem(prompt: "[hola / ola] El niño dijo ___ al entrar. Una gran ___ golpeó la playa.", options: ["hola...ola", "ola...hola", "hola...hola", "ola...ola"], correctAnswer: "hola...ola", explanation: "'Hola' es un saludo; 'ola' es una onda en el agua del mar."),
            ExerciseItem(prompt: "[hulla / huya] La mina produce carbón de ___. Es mejor que él ___ del peligro.", options: ["hulla...huya", "huya...hulla", "hulla...hulla", "huya...huya"], correctAnswer: "hulla...huya", explanation: "'Hulla' es un tipo de carbón mineral; 'huya' es del verbo huir."),
            ExerciseItem(prompt: "[valla / vaya] El jardín tiene una ___ de madera. Espero que le ___ bien en la prueba.", options: ["valla...vaya", "vaya...valla", "valla...valla", "vaya...vaya"], correctAnswer: "valla...vaya", explanation: "'Valla' es una cerca; 'vaya' es del verbo ir."),
            ExerciseItem(prompt: "[basto / vasto] El terreno desértico es ___. Su comportamiento fue rudo y ___.", options: ["vasto...basto", "basto...vasto", "vasto...vasto", "basto...basto"], correctAnswer: "vasto...basto", explanation: "'Vasto' significa muy grande o extenso; 'basto' es algo tosco o grosero."),
            ExerciseItem(prompt: "[azar / asar] La carne se debe ___ en la parrilla. Dejaron el resultado al ___.", options: ["asar...azar", "azar...asar", "asar...asar", "azar...azar"], correctAnswer: "asar...azar", explanation: "'Asar' es cocinar con fuego; 'azar' es la suerte o casualidad."),
            ExerciseItem(prompt: "[hacia / hacía] El tren va ___ el sur. Ella ___ ejercicio todas las mañanas.", options: ["hacia...hacía", "hacía...hacia", "hacia...hacia", "hacía...hacía"], correctAnswer: "hacia...hacía", explanation: "'Hacia' es una preposición de dirección; 'hacía' es del verbo hacer."),
            ExerciseItem(prompt: "[graba / grava] El director ___ la escena. El camino tiene mucha ___.", options: ["graba...grava", "grava...graba", "graba...graba", "grava...grava"], correctAnswer: "graba...grava", explanation: "'Graba' es del verbo grabar; 'grava' son pequeñas piedras."),
            ExerciseItem(prompt: "[hierva / hierba] Arranca la mala ___ del huerto. Deja que el agua ___ primero.", options: ["hierba...hierva", "hierva...hierba", "hierba...hierba", "hierva...hierva"], correctAnswer: "hierba...hierva", explanation: "'Hierba' es una planta; 'hierva' es del verbo hervir."),
            ExerciseItem(prompt: "[abría / habría] Si pudiera, ___ venido antes. Él ___ la puerta lentamente.", options: ["habría...abría", "abría...habría", "abría...abría", "habría...habría"], correctAnswer: "habría...abría", explanation: "'Habría' es del verbo haber; 'abría' es del verbo abrir."),
            ExerciseItem(prompt: "[sabia / savia] La planta absorbe la ___ por el tallo. Ella es una mujer muy ___.", options: ["savia...sabia", "sabia...savia", "savia...savia", "sabia...sabia"], correctAnswer: "savia...sabia", explanation: "'Savia' es el líquido de las plantas; 'sabia' es una persona con sabiduría."),
            ExerciseItem(prompt: "[cabo / cavo] Soy el ___ de la policía. Yo ___ un pozo en la tierra.", options: ["cabo...cavo", "cavo...cabo", "cabo...cabo", "cavo...cavo"], correctAnswer: "cabo...cavo", explanation: "'Cabo' es un rango militar o extremo; 'cavo' es del verbo cavar (hacer pozos).")
        ]
    )

    // MARK: - Exercise 2: Analogías Avanzadas
    private static let exercise2 = Exercise(
        title: "Analogías Avanzadas",
        instructions: "Elige la palabra que mejor completa la analogía.",
        section: .language,
        type: .analogyChoice,
        trackedType: .analogyChoice,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "SOLILOCUIO es a ACTOR como SERMÓN es a ___", options: ["Feligrés", "Predicador", "Coro", "Templo"], correctAnswer: "Predicador", explanation: "Un soliloquio lo dice un actor, un sermón lo da un predicador."),
            ExerciseItem(prompt: "PÁGINA es a LIBRO como TECLA es a ___", options: ["Piano", "Música", "Sonido", "Papel"], correctAnswer: "Piano", explanation: "Una página es parte de un libro, una tecla es parte de un piano."),
            ExerciseItem(prompt: "PLUMA es a PÁJARO como ESCAMA es a ___", options: ["Pez", "Rana", "Pelo", "Agua"], correctAnswer: "Pez", explanation: "La pluma cubre al pájaro, la escama cubre al pez."),
            ExerciseItem(prompt: "CORAZÓN es a LATIDO como PULMÓN es a ___", options: ["Respiración", "Sangre", "Oxígeno", "Vena"], correctAnswer: "Respiración", explanation: "El corazón produce latidos, el pulmón produce la respiración."),
            ExerciseItem(prompt: "CEBOLLA es a LÁGRIMA como CHISTE es a ___", options: ["Risa", "Llanto", "Boca", "Gracia"], correctAnswer: "Risa", explanation: "La cebolla provoca lágrimas, el chiste provoca risa."),
            ExerciseItem(prompt: "VINO es a UVA como TEQUILA es a ___", options: ["Agave", "Caña", "Maíz", "Cactus"], correctAnswer: "Agave", explanation: "El vino se hace de uva, el tequila se hace de agave."),
            ExerciseItem(prompt: "TIMÓN es a BARCO como VOLANTE es a ___", options: ["Carro", "Rueda", "Camino", "Motor"], correctAnswer: "Carro", explanation: "El timón dirige al barco, el volante dirige al carro."),
            ExerciseItem(prompt: "MADERA es a CARPINTERO como ARCILLA es a ___", options: ["Alfarero", "Pintor", "Escultor", "Sastre"], correctAnswer: "Alfarero", explanation: "La madera es la materia prima del carpintero, la arcilla la del alfarero."),
            ExerciseItem(prompt: "FRÍO es a HIELO como CALOR es a ___", options: ["Fuego", "Agua", "Aire", "Tierra"], correctAnswer: "Fuego", explanation: "El hielo produce frío, el fuego produce calor."),
            ExerciseItem(prompt: "NOCHE es a LUNA como DÍA es a ___", options: ["Sol", "Cielo", "Nube", "Luz"], correctAnswer: "Sol", explanation: "La luna destaca en la noche, el sol destaca en el día."),
            ExerciseItem(prompt: "MÚSICA es a OÍDO como PINTURA es a ___", options: ["Vista", "Mano", "Ojo", "Pincel"], correctAnswer: "Vista", explanation: "La música se percibe por el oído, la pintura por la vista."),
            ExerciseItem(prompt: "CANTANTE es a MICRÓFONO como ESCRITOR es a ___", options: ["Pluma", "Libro", "Papel", "Letra"], correctAnswer: "Pluma", explanation: "El cantante usa el micrófono para trabajar, el escritor usa la pluma."),
            ExerciseItem(prompt: "PAN es a HARINA como TORTILLA es a ___", options: ["Maíz", "Trigo", "Sal", "Agua"], correctAnswer: "Maíz", explanation: "El pan se hace de harina, la tortilla tradicional mexicana se hace de maíz."),
            ExerciseItem(prompt: "ESTRELLA es a CONSTELACIÓN como ISLA es a ___", options: ["Archipiélago", "Mar", "Playa", "Arena"], correctAnswer: "Archipiélago", explanation: "Un grupo de estrellas forma una constelación, un grupo de islas forma un archipiélago."),
            ExerciseItem(prompt: "RELOJ es a TIEMPO como BRÚJULA es a ___", options: ["Dirección", "Viento", "Norte", "Mapa"], correctAnswer: "Dirección", explanation: "El reloj mide el tiempo, la brújula muestra la dirección.")
        ]
    )

    // MARK: - Exercise 3: Asociación de Palabras Avanzada
    private static let exercise3 = Exercise(
        title: "Asociación de Palabras Avanzada",
        instructions: "Elige la palabra más estrechamente asociada con la palabra dada.",
        section: .language,
        type: .multipleChoice,
        trackedType: .wordAssociation,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "ALTRUISMO", options: ["Generosidad", "Avaricia", "Egoísmo", "Orgullo"], correctAnswer: "Generosidad", explanation: "El altruismo está directamente relacionado con la generosidad y el dar sin esperar nada a cambio."),
            ExerciseItem(prompt: "SANGREGADO", options: ["Hacienda", "Rancho", "Café", "Trigo"], correctAnswer: "Hacienda", explanation: "La hacienda era la gran propiedad rural histórica en México."),
            ExerciseItem(prompt: "OFRENDA", options: ["Día de Muertos", "Navidad", "Boda", "Carnaval"], correctAnswer: "Día de Muertos", explanation: "La ofrenda es el altar tradicional del Día de Muertos en la cultura mexicana."),
            ExerciseItem(prompt: "CACAO", options: ["Chocolate", "Café", "Pan", "Tequila"], correctAnswer: "Chocolate", explanation: "El cacao es la base e ingrediente primordial para hacer chocolate."),
            ExerciseItem(prompt: "ALEBRIJE", options: ["Artesanía", "Comida", "Música", "Ropa"], correctAnswer: "Artesanía", explanation: "Los alebrijes son artesanías mexicanas de figuras fantásticas talladas o de cartón."),
            ExerciseItem(prompt: "MARIACHI", options: ["Trompeta", "Flauta", "Tambor", "Piano"], correctAnswer: "Trompeta", explanation: "La trompeta es un instrumento icónico e indispensable en un grupo de mariachi."),
            ExerciseItem(prompt: "MOLCAJETE", options: ["Salsa", "Sopa", "Postre", "Bebida"], correctAnswer: "Salsa", explanation: "El molcajete es el mortero de piedra usado tradicionalmente para moler salsas en México."),
            ExerciseItem(prompt: "CENOTE", options: ["Agua", "Fuego", "Bosque", "Desierto"], correctAnswer: "Agua", explanation: "Un cenote es un pozo de agua dulce subterráneo típico de la península de Yucatán."),
            ExerciseItem(prompt: "TAMAL", options: ["Hoja de maíz", "Trigo", "Papel", "Plástico"], correctAnswer: "Hoja de maíz", explanation: "Los tamales se envuelven tradicionalmente en hojas de maíz o de plátano."),
            ExerciseItem(prompt: "JACARANDA", options: ["Morado", "Amarillo", "Verde", "Rojo"], correctAnswer: "Morado", explanation: "Las jacarandas son árboles famosos en la Ciudad de México por sus hermosas flores de color morado en primavera."),
            ExerciseItem(prompt: "MOLINILLO", options: ["Chocolate caliente", "Salsa", "Café", "Agua"], correctAnswer: "Chocolate caliente", explanation: "El molinillo es un utensilio de madera para batir y hacer espuma al chocolate caliente."),
            ExerciseItem(prompt: "TACO", options: ["Tortilla", "Pan", "Arroz", "Fideo"], correctAnswer: "Tortilla", explanation: "La tortilla es la base esencial sobre la cual se sirve cualquier taco."),
            ExerciseItem(prompt: "GUACAMOLE", options: ["Aguacate", "Tomate", "Papa", "Zanahoria"], correctAnswer: "Aguacate", explanation: "El aguacate es el ingrediente principal del guacamole."),
            ExerciseItem(prompt: "AGAVE", options: ["Mezcal", "Cerveza", "Ron", "Sidra"], correctAnswer: "Mezcal", explanation: "El agave es la planta de la que se destilan el mezcal y el tequila."),
            ExerciseItem(prompt: "REBOZO", options: ["Prenda", "Comida", "Artesanía", "Música"], correctAnswer: "Prenda", explanation: "El rebozo es una prenda de vestir femenina tradicional de México tipo chal.")
        ]
    )

    // MARK: - Exercise 4: Completar Oraciones Avanzado
    private static let exercise4 = Exercise(
        title: "Completar Oraciones Avanzado",
        instructions: "Elige la palabra que mejor completa la oración.",
        section: .language,
        type: .sentenceCompletion,
        trackedType: .sentenceCompletion,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "El orador pronunció un discurso tan ___ que conmovió a toda la audiencia.", options: ["elocuente", "insípido", "aburrido", "breve"], correctAnswer: "elocuente", explanation: "Un discurso elocuente tiene la capacidad de conmover y persuadir a quienes lo escuchan."),
            ExerciseItem(prompt: "A pesar de las dificultades económicas, la familia mostró una ___ admirable.", options: ["resiliencia", "tristeza", "debilidad", "pobreza"], correctAnswer: "resiliencia", explanation: "Resiliencia es la capacidad de superar la adversidad y salir fortalecido de ella."),
            ExerciseItem(prompt: "El arqueólogo descubrió un jeroglífico ___ que nadie había visto antes.", options: ["inédito", "común", "moderno", "falso"], correctAnswer: "inédito", explanation: "'Inédito' significa que es completamente nuevo y no ha sido publicado o visto antes."),
            ExerciseItem(prompt: "El juez actuó con total ___ al evaluar las pruebas presentadas.", options: ["imparcialidad", "favoritismo", "rapidez", "duda"], correctAnswer: "imparcialidad", explanation: "Los jueces deben actuar con imparcialidad, es decir, sin prejuicios ni favoritismos."),
            ExerciseItem(prompt: "Su conocimiento de la historia prehispánica de México es verdaderamente ___.", options: ["vasto", "escaso", "reciente", "nulo"], correctAnswer: "vasto", explanation: "Un conocimiento 'vasto' significa que es muy amplio y profundo."),
            ExerciseItem(prompt: "El medicamento recetado ayudó a ___ los síntomas del resfriado.", options: ["mitigar", "aumentar", "provocar", "ignorar"], correctAnswer: "mitigar", explanation: "'Mitigar' significa moderar, aplacar o disminuir la intensidad de los síntomas."),
            ExerciseItem(prompt: "Las ruinas mayas de Palenque son un monumento ___ de la antigüedad.", options: ["vestigio", "edificio", "bosque", "dibujo"], correctAnswer: "vestigio", explanation: "Un vestigio es una señal, ruina o resto que queda de algo antiguo."),
            ExerciseItem(prompt: "El pintor utilizó colores ___ para reflejar la alegría de la fiesta mexicana.", options: ["vibrantes", "oscuros", "apagados", "grises"], correctAnswer: "vibrantes", explanation: "Los colores vibrantes y llamativos reflejan de forma natural la alegría de las fiestas mexicanas."),
            ExerciseItem(prompt: "La lluvia constante ayudó a ___ el calor del desierto de Sonora.", options: ["paliar", "subir", "continuar", "fomentar"], correctAnswer: "paliar", explanation: "'Paliar' significa mitigar, suavizar o atenuar una situación difícil como el calor extremo."),
            ExerciseItem(prompt: "El escritor redactó un prólogo ___ para resumir las ideas del libro.", options: ["sucinto", "eterno", "confuso", "largo"], correctAnswer: "sucinto", explanation: "'Sucinto' significa breve, conciso y preciso."),
            ExerciseItem(prompt: "Las tradiciones gastronómicas se transmiten de forma ___ entre generaciones.", options: ["generacional", "rápida", "secreta", "olvidada"], correctAnswer: "generacional", explanation: "Las tradiciones gastronómicas mexicanas se transmiten de generación en generación."),
            ExerciseItem(prompt: "El científico presentó una teoría ___ respaldada por abundantes experimentos.", options: ["sólida", "débil", "nueva", "falsa"], correctAnswer: "sólida", explanation: "Una teoría respaldada por experimentos es sólida y confiable."),
            ExerciseItem(prompt: "El diplomático logró un acuerdo ___ que benefició a ambos países fronterizos.", options: ["bilateral", "unilateral", "hostil", "secreto"], correctAnswer: "bilateral", explanation: "Un acuerdo bilateral involucra y beneficia a dos partes o países."),
            ExerciseItem(prompt: "Las artesanías de barro negro de Oaxaca son famosas por su acabado ___.", options: ["lustroso", "rugoso", "blando", "áspero"], correctAnswer: "lustroso", explanation: "El barro negro pulido o lustroso tiene un brillo negro metálico característico muy famoso."),
            ExerciseItem(prompt: "Su respuesta evasiva sembró la ___ entre los miembros del comité.", options: ["incertidumbre", "claridad", "paz", "confianza"], correctAnswer: "incertidumbre", explanation: "Una respuesta evasiva genera dudas, sospechas o incertidumbre.")
        ]
    )

    // MARK: - Exercise 5: Pasos de Actividades
    private static let exercise5 = Exercise(
        title: "Pasos de Actividades",
        instructions: "Ordena los pasos de la actividad de forma lógica.",
        section: .language,
        type: .sequencing,
        trackedType: .sequencing,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "Preparar tamales", options: ["Cocer al vapor en la vaporera", "Preparar la masa de maíz con manteca", "Untar la masa en las hojas de maíz remojadas", "Agregar el relleno de carne o guisado y doblar"], correctAnswer: "Preparar la masa de maíz con manteca | Untar la masa en las hojas de maíz remojadas | Agregar el relleno de carne o guisado y doblar | Cocer al vapor en la vaporera", explanation: "Se prepara la masa, se unta en las hojas, se rellena/dobla y finalmente se cose al vapor."),
            ExerciseItem(prompt: "Hacer guacamole casero", options: ["Machacar los aguacates en un tazón", "Agregar cebolla, cilantro y chile picados", "Extraer la pulpa de los aguacates", "Exprimir jugo de limón y sazonar con sal"], correctAnswer: "Extraer la pulpa de los aguacates | Machacar los aguacates en un tazón | Agregar cebolla, cilantro y chile picados | Exprimir jugo de limón y sazonar con sal", explanation: "Primero se saca la pulpa, se machaca, se agregan los picados y se sazona al final."),
            ExerciseItem(prompt: "Hacer café de olla", options: ["Colar y servir caliente", "Agregar café molido y apagar el fuego", "Poner agua a calentar en olla de barro con piloncillo y canela", "Dejar reposar tapado unos minutos"], correctAnswer: "Poner agua a calentar en olla de barro con piloncillo y canela | Agregar café molido y apagar el fuego | Dejar reposar tapado unos minutos | Colar y servir caliente", explanation: "Primero se calienta el agua con dulce/canela, se añade el café al apagar, se reposa y se cuela."),
            ExerciseItem(prompt: "Preparar agua de Jamaica", options: ["Hervir las flores de jamaica en agua", "Colar el líquido concentrado", "Añadir agua fría y azúcar al gusto", "Servir con hielo"], correctAnswer: "Hervir las flores de jamaica en agua | Colar el líquido concentrado | Añadir agua fría y azúcar al gusto | Servir con hielo", explanation: "Primero se hierven las flores, se cuela el concentrado, se endulza y se enfría con hielo."),
            ExerciseItem(prompt: "Hacer salsa verde asada", options: ["Licuar o moler en molcajete los ingredientes", "Retirar los tomates y chiles del fuego", "Asar tomates verdes, chiles, ajo y cebolla en un comal", "Agregar sal y cilantro picado"], correctAnswer: "Asar tomates verdes, chiles, ajo y cebolla en un comal | Retirar los tomates y chiles del fuego | Licuar o moler en molcajete los ingredientes | Agregar sal y cilantro picado", explanation: "Primero se asan los ingredientes, se retiran del fuego, se muelen y se sazona al final."),
            ExerciseItem(prompt: "Hacer tortillas de maíz a mano", options: ["Cocinar la tortilla en el comal caliente", "Hacer bolitas de masa (testales)", "Aplanar la bolita con la prensa de tortillas", "Preparar la masa de maíz nixtamalizado con agua"], correctAnswer: "Preparar la masa de maíz nixtamalizado con agua | Hacer bolitas de masa (testales) | Aplanar la bolita con la prensa de tortillas | Cocinar la tortilla en el comal caliente", explanation: "Se prepara la masa, se hacen las bolitas, se aplanan en la prensa y se cocinan en el comal."),
            ExerciseItem(prompt: "Preparar chilaquiles sencillos", options: ["Bañar los totopos con la salsa caliente", "Cortar tortillas en triángulos y freírlas para hacer totopos", "Decorar con crema, queso fresco y cebolla", "Preparar una salsa roja o verde licuada"], correctAnswer: "Cortar tortillas en triángulos y freírlas para hacer totopos | Preparar una salsa roja o verde licuada | Bañar los totopos con la salsa caliente | Decorar con crema, queso fresco y cebolla", explanation: "Se hacen los totopos, se hace la salsa, se bañan los totopos y se decoran al servir."),
            ExerciseItem(prompt: "Preparar frijoles refritos", options: ["Hervir frijoles con cebolla y sal", "Machacar los frijoles mientras se fríen", "Calentar aceite o manteca en una sartén", "Servir acompañados de queso fresco"], correctAnswer: "Hervir frijoles con cebolla y sal | Calentar aceite o manteca en una sartén | Machacar los frijoles mientras se fríen | Servir acompañados de queso fresco", explanation: "Se hierven los frijoles, se calienta grasa, se fríen y machacan, y se sirven con queso."),
            ExerciseItem(prompt: "Preparar una michelada", options: ["Servir cerveza fría lentamente", "Escarchar el borde del vaso con limón y chile en polvo", "Agregar hielo, jugo de limón y salsas sazonadoras", "Mezclar suavemente los ingredientes"], correctAnswer: "Escarchar el borde del vaso con limón y chile en polvo | Agregar hielo, jugo de limón y salsas sazonadoras | Servir cerveza fría lentamente | Mezclar suavemente los ingredientes", explanation: "Primero se escarcha el vaso, se añaden limones/salsas con hielo, se sirve la cerveza y se mezcla suavemente."),
            ExerciseItem(prompt: "Preparar mole poblano tradicional", options: ["Servir sobre pollo cocido y espolvorear ajonjolí", "Tostar chiles, semillas, chocolate y especias", "Moler los ingredientes hasta obtener una pasta fina", "Cocinar la pasta en caldo de pollo hasta espesar"], correctAnswer: "Tostar chiles, semillas, chocolate y especias | Moler los ingredientes hasta obtener una pasta fina | Cocinar la pasta en caldo de pollo hasta espesar | Servir sobre pollo cocido y espolvorear ajonjolí", explanation: "Se tuestan los ingredientes, se muelen en pasta, se cocinan con caldo y se sirve sobre el pollo."),
            ExerciseItem(prompt: "Cambiar una llanta ponchada", options: ["Aflojar las tuercas de la llanta", "Colocar el gato hidráulico y levantar el auto", "Quitar la llanta ponchada e instalar la de refacción", "Apretar las tuercas y bajar el auto"], correctAnswer: "Aflojar las tuercas de la llanta | Colocar el gato hidráulico y levantar el auto | Quitar la llanta ponchada e instalar la de refacción | Apretar las tuercas y bajar el auto", explanation: "Primero se aflojan las tuercas, se levanta el auto con el gato, se cambia la llanta y se aprietan las tuercas al bajar."),
            ExerciseItem(prompt: "Hacer arroz rojo mexicano", options: ["Agregar puré de tomate y caldo", "Freír el arroz en aceite hasta que esté dorado", "Tapar y cocinar a fuego bajo hasta secar", "Licuar tomates, ajo y cebolla para la salsa"], correctAnswer: "Licuar tomates, ajo y cebolla para la salsa | Freír el arroz en aceite hasta que esté dorado | Agregar puré de tomate y caldo | Tapar y cocinar a fuego bajo hasta secar", explanation: "Se hace el puré de tomate, se fríe el arroz hasta dorar, se agrega el puré/caldo y se cocina tapado."),
            ExerciseItem(prompt: "Hacer pico de gallo", options: ["Picar tomate, cebolla y chile serrano", "Mezclar los ingredientes en un tazón", "Agregar cilantro picado", "Añadir sal y jugo de limón al gusto"], correctAnswer: "Picar tomate, cebolla y chile serrano | Mezclar los ingredientes en un tazón | Agregar cilantro picado | Añadir sal y jugo de limón al gusto", explanation: "Se pican las verduras principales, se mezclan, se agrega cilantro y se sazona al final."),
            ExerciseItem(prompt: "Hacer flan casero", options: ["Verter la mezcla de leche y huevo en el molde", "Hornear a baño María", "Derretir azúcar para hacer caramelo en el molde", "Enfriar y desmoldar"], correctAnswer: "Derretir azúcar para hacer caramelo en el molde | Verter la mezcla de leche y huevo en el molde | Hornear a baño María | Enfriar y desmoldar", explanation: "Se hace el caramelo en el molde, se vierte la mezcla líquida, se hornea a baño María y se desmolda frío."),
            ExerciseItem(prompt: "Planchar una camisa de algodón", options: ["Ajustar la temperatura de la plancha", "Planchar primero el cuello y los puños", "Planchar las mangas y el cuerpo", "Colgar la camisa en un gancho de inmediato"], correctAnswer: "Ajustar la temperatura de la plancha | Planchar primero el cuello y los puños | Planchar las mangas y el cuerpo | Colgar la camisa en un gancho de inmediato", explanation: "Se ajusta la temperatura, se plancha el cuello/puños primero, luego el cuerpo/mangas y se cuelga.")
        ]
    )

    // MARK: - Exercise 6: Causa y Efecto Avanzado
    private static let exercise6 = Exercise(
        title: "Causa y Efecto Avanzado",
        instructions: "Elige la respuesta que muestra la causa o efecto más lógico.",
        section: .cognition,
        type: .multipleChoice,
        trackedType: .causeAndEffect,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "Causa: Hubo una sequía prolongada en la región norte de México.", options: ["Los precios de los cultivos básicos aumentaron debido a la escasez", "Los granjeros tuvieron cosechas récord este año", "Los ríos y lagos se desbordaron en la región", "Las tarifas de luz residencial disminuyeron"], correctAnswer: "Los precios de los cultivos básicos aumentaron debido a la escasez", explanation: "Una sequía disminuye la producción de alimentos, lo que eleva sus precios por escasez."),
            ExerciseItem(prompt: "Causa: La inflación aumentó aceleradamente en el último año.", options: ["El poder adquisitivo de los salarios disminuyó notablemente", "Las familias ahorraron más dinero que antes", "Los productos importados se abarataron", "Los bancos bajaron las tasas de interés"], correctAnswer: "El poder adquisitivo de los salarios disminuyó notablemente", explanation: "La inflación hace que el dinero rinda menos al comprar bienes y servicios cotidianos."),
            ExerciseItem(prompt: "Causa: Una fuerte tormenta tropical tocó tierra en la península de Yucatán.", options: ["Se suspendieron las clases y actividades turísticas de inmediato", "El clima se mantuvo soleado y templado", "Las playas registraron asistencia récord de bañistas", "Los vuelos comerciales operaron con total normalidad"], correctAnswer: "Se suspendieron las clases y actividades turísticas de inmediato", explanation: "Las tormentas tropicales representan un riesgo de seguridad que obliga a suspender clases y turismo."),
            ExerciseItem(prompt: "Efecto: El tráfico en la Ciudad de México estuvo completamente paralizado hoy.", options: ["Causa: Hubo una manifestación pacífica en el Paseo de la Reforma", "Causa: Las autopistas urbanas estaban vacías y sin autos", "Causa: Todos los semáforos de la ciudad funcionaron perfecto", "Causa: La gente decidió quedarse a trabajar en sus casas"], correctAnswer: "Causa: Hubo una manifestación pacífica en el Paseo de la Reforma", explanation: "Las manifestaciones en calles principales como Paseo de la Reforma causan graves embotellamientos viales."),
            ExerciseItem(prompt: "Efecto: La cosecha de aguacate en Michoacán cayó un 40% este ciclo.", options: ["Causa: Heladas tardías dañaron las plantaciones en invierno", "Causa: Los agricultores aumentaron el uso de fertilizantes orgánicos", "Causa: Hubo lluvias ideales durante toda la primavera", "Causa: La demanda internacional del producto disminuyó notablemente"], correctAnswer: "Causa: Heladas tardías dañaron las plantaciones en invierno", explanation: "Las heladas dañan los brotes de aguacate, disminuyendo la producción agrícola."),
            ExerciseItem(prompt: "Causa: Se construyó una nueva carretera directa entre Guadalajara y Puerto Vallarta.", options: ["El tiempo de viaje terrestre se redujo considerablemente", "El turismo en Puerto Vallarta disminuyó drásticamente", "Los costos de gasolina para el trayecto aumentaron al doble", "La carretera antigua se congestionó aún más"], correctAnswer: "El tiempo de viaje terrestre se redujo considerablemente", explanation: "Las autopistas directas disminuyen la distancia y tiempo de viaje entre ciudades."),
            ExerciseItem(prompt: "Causa: El gobierno local incrementó los impuestos a las bebidas azucaradas.", options: ["El consumo de refrescos y jugos procesados disminuyó ligeramente", "La producción de caña de azúcar aumentó de inmediato", "Los refrescos se volvieron más baratos en las tiendas", "La venta de agua embotellada se detuvo por completo"], correctAnswer: "El consumo de refrescos y jugos procesados disminuyó ligeramente", explanation: "Subir impuestos aumenta los precios, lo que desalienta el consumo de esos productos."),
            ExerciseItem(prompt: "Causa: Un sismo moderado activó la alerta sísmica en la capital.", options: ["La población evacuó rápidamente oficinas y escuelas de forma preventiva", "La gente ignoró la alarma y continuó durmiendo", "El sismo causó derrumbes masivos en toda la ciudad", "El servicio telefónico e internet aumentaron su velocidad"], correctAnswer: "La población evacuó rápidamente oficinas y escuelas de forma preventiva", explanation: "La alerta sísmica avisa con segundos de anticipación para realizar evacuaciones preventivas organizadas."),
            ExerciseItem(prompt: "Causa: Las remesas de dinero provenientes de Estados Unidos aumentaron un 15% este mes.", options: ["El consumo interno en las zonas rurales receptoras mejoró notablemente", "Las familias receptoras redujeron sus gastos básicos", "El peso mexicano se devaluó drásticamente frente al dólar", "Se redujo el volumen de llamadas de larga distancia internacional"], correctAnswer: "El consumo interno en las zonas rurales receptoras mejoró notablemente", explanation: "Un aumento de remesas incrementa el dinero disponible para gastar en las familias receptoras mexicanas."),
            ExerciseItem(prompt: "Causa: Se inauguró un gran centro comercial en una colonia residencial tranquila.", options: ["El tráfico vehicular y la actividad comercial de la zona aumentaron", "Los precios de las viviendas vecinas cayeron a la mitad", "Los residentes del vecindario tuvieron más privacidad que antes", "La delincuencia y el ruido desaparecieron por completo"], correctAnswer: "El tráfico vehicular y la actividad comercial de la zona aumentaron", explanation: "Los centros comerciales atraen un gran volumen de personas, autos y nuevos negocios."),
            ExerciseItem(prompt: "Efecto: El pozo de agua potable del pueblo se secó por completo en mayo.", options: ["Causa: El consumo excesivo para riego agrícola y la falta de lluvias invernales", "Causa: Las nevadas copiosas en las montañas vecinas", "Causa: El gobierno local redujo las tarifas de agua potable", "Causa: Se plantaron árboles de bajo consumo de agua en la plaza"], correctAnswer: "Causa: El consumo excesivo para riego agrícola y la falta de lluvias invernales", explanation: "La falta de recarga natural y la sobreexplotación vacían los acuíferos subterráneos de los pozos."),
            ExerciseItem(prompt: "Efecto: Se agotaron los boletos para el partido de fútbol de la selección en el Estadio Azteca.", options: ["Causa: El rival era el campeón del mundo y los boletos eran accesibles", "Causa: El partido fue cancelado por malas condiciones del clima", "Causa: El equipo local venía de perder cinco partidos seguidos", "Causa: Los precios de los boletos aumentaron al triple de su valor regular"], correctAnswer: "Causa: El rival era el campeón del mundo y los boletos eran accesibles", explanation: "Un rival de alto nivel y precios razonables genera gran interés y agota las entradas."),
            ExerciseItem(prompt: "Causa: Un frente frío invernal azotó la Sierra Tarahumara con temperaturas bajo cero.", options: ["Se habilitaron albergues temporales y se distribuyeron cobijas", "La población comenzó a usar ropa ligera de verano", "Las escuelas realizaron todas sus clases al aire libre", "El turismo de aventura en la sierra aumentó al doble"], correctAnswer: "Se habilitaron albergues temporales y se distribuyeron cobijas", explanation: "Las temperaturas congelantes obligan a proteger a la población vulnerable mediante albergues y calefacción."),
            ExerciseItem(prompt: "Efecto: El costo de los boletos de avión a Cancún subió drásticamente en diciembre.", options: ["Causa: Es temporada vacacional alta y la demanda turística aumenta muchísimo", "Causa: Las aerolíneas agregaron nuevos aviones vacíos a su flota", "Causa: Cancún reportó tormentas invernales récord ese mes", "Causa: El gobierno de Quintana Roo ofreció hospedajes gratis"], correctAnswer: "Causa: Es temporada vacacional alta y la demanda turística aumenta muchísimo", explanation: "La alta demanda turística por vacaciones decembrinas incrementa los precios de transporte de forma natural."),
            ExerciseItem(prompt: "Causa: El metro de la ciudad tuvo una falla de energía en plena hora pico.", options: ["Miles de pasajeros sufrieron retrasos severos para llegar a sus destinos", "Las estaciones se vaciaron de inmediato y de forma ordenada", "El tráfico en las calles de arriba disminuyó notablemente", "Los taxis comenzaron a dar servicio de manera gratuita"], correctAnswer: "Miles de pasajeros sufrieron retrasos severos para llegar a sus destinos", explanation: "La detención del transporte masivo en hora pico genera retrasos inmediatos a miles de trabajadores.")
        ]
    )

    // MARK: - Exercise 7: Absurdos Lógicos
    private static let exercise7 = Exercise(
        title: "Absurdos Lógicos",
        instructions: "Elige la respuesta que explica por qué la situación es imposible.",
        section: .cognition,
        type: .multipleChoice,
        trackedType: .whatsWrongHere,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "Juan asó los tomates y chiles en el comal apagado y frío para hacer una salsa picante caliente.", options: ["No se pueden asar ingredientes en un comal frío y apagado sin calor", "Las salsas picantes no llevan tomates verdes", "Los comales solo sirven para calentar tortillas", "Las salsas frías no se asan nunca"], correctAnswer: "No se pueden asar ingredientes en un comal frío y apagado sin calor", explanation: "Asar alimentos requiere calor de fuego; un comal apagado no tiene energía térmica para cocinar."),
            ExerciseItem(prompt: "María guardó el helado caliente de mango en la alacena abierta para que no se derritiera en el calor de Hermosillo.", options: ["El helado no es caliente y se derrite fuera del congelador", "El mango solo se come en invierno en México", "Las alacenas deben estar cerradas con llave siempre", "El helado caliente se conserva mejor en el refrigerador"], correctAnswer: "El helado no es caliente y se derrite fuera del congelador", explanation: "El helado debe mantenerse congelado; guardarlo a temperatura ambiente lo derrite de inmediato."),
            ExerciseItem(prompt: "El mariachi tocó una hermosa melodía silenciosa que hizo bailar alegremente a todos los invitados de la boda.", options: ["La música silenciosa no se puede escuchar ni bailar", "Los mariachis solo tocan en los funerales tradicionales", "Nadie baila en las bodas mexicanas modernas", "Las trompetas de mariachi no producen sonidos agudos"], correctAnswer: "La música silenciosa no se puede escuchar ni bailar", explanation: "La música requiere ondas sonoras audibles; una melodía silenciosa no transmite ritmo para bailar."),
            ExerciseItem(prompt: "Para refrescarse del sol ardiente de Mexicali, Pedro se puso una chamarra de lana gruesa y corrió 5 kilómetros.", options: ["La ropa pesada de lana calienta el cuerpo en lugar de refrescarlo", "No hace sol en Mexicali durante la tarde", "Pedro debió haber corrido en reversa para refrescarse", "Las chamarras de lana solo se usan en la playa"], correctAnswer: "La ropa pesada de lana calienta el cuerpo en lugar de refrescarlo", explanation: "La lana es un aislante térmico que atrapa el calor corporal; correr con ella bajo el sol provoca un golpe de calor."),
            ExerciseItem(prompt: "El panadero usó chiles habaneros picantes en vez de azúcar para endulzar el pan de muerto tradicional.", options: ["El chile habanero es picante y no sirve para endulzar panes", "El pan de muerto no se hornea en panaderías", "El chile habanero solo se usa en postres dulces de limón", "El pan de muerto lleva sal en lugar de azúcar siempre"], correctAnswer: "El chile habanero es picante y no sirve para endulzar panes", explanation: "El chile habanero contiene capsaicina que pica; no tiene compuestos dulces para endulzar repostería."),
            ExerciseItem(prompt: "El buzo nadó en el agua completamente seca del cenote subterráneo para explorar las cuevas profundas.", options: ["El agua de los cenotes no es seca, es un líquido húmedo", "Los cenotes no tienen cuevas en la península de Yucatán", "Los buzos solo nadan en el mar abierto", "El agua subterránea solo existe en forma gaseosa"], correctAnswer: "El agua de los cenotes no es seca, es un líquido húmedo", explanation: "Por definición física, el agua en estado líquido moja y no puede estar seca."),
            ExerciseItem(prompt: "Sofía encendió una vela de cera de chocolate para iluminar el patio oscuro de noche y poder leer un libro de corrido.", options: ["Una vela de chocolate se derretiría por el calor de la llama sin dar luz", "Las velas solo se encienden en el altar de muertos", "No se puede leer en un patio de noche con ninguna luz", "El chocolate solo se puede comer y nunca hacer cera"], correctAnswer: "Una vela de chocolate se derretiría por el calor de la llama sin dar luz", explanation: "El chocolate no es una cera combustible; se derretiría rápidamente con el fuego sin sostener una flama luminosa."),
            ExerciseItem(prompt: "El agricultor sembró semillas de maíz en una placa de concreto sólido y las regó diario para tener una cosecha excelente.", options: ["Las plantas no pueden crecer ni echar raíces en concreto sólido", "El maíz solo crece con agua salada del océano", "Las semillas de maíz se siembran únicamente en macetas", "El concreto necesita fertilizante líquido para germinar"], correctAnswer: "Las plantas no pueden crecer ni echar raíces en concreto sólido", explanation: "Las plantas necesitan tierra suave o sustrato húmedo para extender sus raíces; el concreto bloquea el crecimiento."),
            ExerciseItem(prompt: "La señora congeló el café de olla hirviendo para servirlo caliente a los invitados de la fiesta patria.", options: ["Congelar algo disminuye su temperatura, por lo que no se sirve caliente", "El café de olla no se toma en las fiestas patrias mexicanas", "El café caliente se sirve en vasos de plástico con popote siempre", "Las bebidas congeladas se evaporan de inmediato con el frío"], correctAnswer: "Congelar algo disminuye su temperatura, por lo que no se sirve caliente", explanation: "El proceso de congelación solidifica el líquido al retirar calor; es imposible servir caliente un café congelado."),
            ExerciseItem(prompt: "El mecánico quitó las cuatro llantas del camión y lo manejó por la autopista a Querétaro para probar la transmisión.", options: ["Un camión necesita llantas para rodar y desplazarse por el asfalto", "La autopista a Querétaro solo permite el paso de motocicletas", "Las transmisiones mecánicas no funcionan sin la batería del auto", "Quitar las llantas acelera el camión de manera peligrosa"], correctAnswer: "Un camión necesita llantas para rodar y desplazarse por el asfalto", explanation: "Sin neumáticos, el camión descansa directamente sobre los ejes de metal y no puede rodar por la carretera."),
            ExerciseItem(prompt: "Lucía tomó una fotografía nítida del altar de muertos en total oscuridad sin usar flash ni luces ambientales de apoyo.", options: ["La fotografía requiere luz para exponer la imagen en el sensor o película", "Los altares de muertos solo se fotografían de día", "El barro de las ofrendas absorbe la luz de la cámara", "El flash de la cámara solo funciona bajo el agua salada"], correctAnswer: "La fotografía requiere luz para exponer la imagen en el sensor o película", explanation: "La cámara capta luz reflejada; sin ninguna fuente de luz, la imagen obtenida es completamente negra."),
            ExerciseItem(prompt: "El carpintero usó una regla de plastilina flexible para medir con precisión milimétrica la tabla de madera del librero.", options: ["La plastilina es flexible y se deforma, perdiendo toda precisión para medir", "Las reglas solo se fabrican de metal pesado templado", "Los carpinteros no usan madera para hacer muebles modernos", "Las medidas milimétricas se hacen solo con hilos de coser"], correctAnswer: "La plastilina es flexible y se deforma, perdiendo toda precisión para medir", explanation: "Los instrumentos de medición lineal deben mantener una rigidez estructural para dar lecturas precisas."),
            ExerciseItem(prompt: "Para secar la ropa húmeda rápidamente en el departamento, Manuel la metió al fregadero lleno de agua fría.", options: ["Sumergir la ropa en agua fría la moja aún más en lugar de secarla", "El agua fría tiñe la ropa blanca de color azul de inmediato", "La ropa solo se seca en secadoras industriales de vapor", "El fregadero no tiene suficiente aire para secar telas"], correctAnswer: "Sumergir la ropa en agua fría la moja aún más en lugar de secarla", explanation: "El agua moja los tejidos textiles; secar la ropa requiere evaporación del agua por aire o calor."),
            ExerciseItem(prompt: "El constructor usó bloques de hielo sólido para edificar la casa de playa en las costas calientes de Acapulco.", options: ["El hielo se derretiría rápidamente con el clima cálido de Acapulco", "Las casas de playa solo se construyen con palmeras de coco", "Acapulco no tiene playas aptas para construir viviendas", "El hielo sólido no soporta el peso del techo de madera"], correctAnswer: "El hielo se derretiría rápidamente con el clima cálido de Acapulco", explanation: "Acapulco tiene un clima tropical cálido donde el hielo se funde a agua líquida en minutos."),
            ExerciseItem(prompt: "El conductor apagó el motor del carro para subir la empinada cuesta del Ajusco con más velocidad y fuerza.", options: ["Un motor apagado no produce energía mecánica para mover el auto hacia arriba", "Las montañas solo se pueden subir manejando en reversa", "El carro se desliza más rápido de subida con el freno de mano puesto", "Los motores se calientan más al estar apagados en el frío"], correctAnswer: "Un motor apagado no produce energía mecánica para mover el auto hacia arriba", explanation: "Subir pendientes requiere fuerza motriz proporcionada por el motor encendido en marcha.")
        ]
    )

    // MARK: - Exercise 8: Dichos y Refranes Populares
    private static let exercise8 = Exercise(
        title: "Dichos y Refranes Populares",
        instructions: "Elige la palabra que completa correctamente el refrán popular.",
        section: .language,
        type: .sentenceCompletion,
        trackedType: .completeTheSaying,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "Completa el refrán: Camarón que se duerme se lo lleva la ___.", options: ["corriente", "marea", "red", "ola"], correctAnswer: "corriente", explanation: "El refrán popular mexicano es 'Camarón que se duerme se lo lleva la corriente', indicando que quien se descuida sufre las consecuencias."),
            ExerciseItem(prompt: "Completa el refrán: De tal palo, tal ___.", options: ["astilla", "rama", "árbol", "hoja"], correctAnswer: "astilla", explanation: "El refrán es 'De tal palo, tal astilla', que indica que los hijos suelen parecerse a sus padres."),
            ExerciseItem(prompt: "Completa el refrán: Al mal tiempo, buena ___.", options: ["cara", "suerte", "actitud", "sonrisa"], correctAnswer: "cara", explanation: "El refrán es 'Al mal tiempo, buena cara', aconsejando mantener optimismo ante la adversidad."),
            ExerciseItem(prompt: "Completa el refrán: Más vale pájaro en mano que ciento ___.", options: ["volando", "en el aire", "en el nido", "corriendo"], correctAnswer: "volando", explanation: "El refrán es 'Más vale pájaro en mano que ciento volando', sugiriendo valorar lo seguro frente a lo incierto."),
            ExerciseItem(prompt: "Completa el refrán: No por mucho madrugar amanece más ___.", options: ["temprano", "rápido", "claro", "luz"], correctAnswer: "temprano", explanation: "El refrán es 'No por mucho madrugar amanece más temprano', indicando que las cosas llevan su tiempo natural."),
            ExerciseItem(prompt: "Completa el refrán: A caballo regalado no se le busca ___.", options: ["colmillo", "pelo", "silla", "ojo"], correctAnswer: "colmillo", explanation: "El refrán tradicional es 'A caballo regalado no se le busca colmillo' (o diente), indicando que no hay que criticar los obsequios recibidos."),
            ExerciseItem(prompt: "Completa el refrán: En boca cerrada no entran ___.", options: ["moscas", "palabras", "mentiras", "dudas"], correctAnswer: "moscas", explanation: "El refrán es 'En boca cerrada no entran moscas', advirtiendo que es mejor ser prudentes al hablar."),
            ExerciseItem(prompt: "Completa el refrán: Dime con quién andas y te diré quién ___.", options: ["eres", "serás", "vienes", "piensas"], correctAnswer: "eres", explanation: "El refrán es 'Dime con quién andas y te diré quién eres', señalando la influencia de las amistades."),
            ExerciseItem(prompt: "Completa el refrán: Perro que ladra no ___.", options: ["muerde", "corre", "come", "juega"], correctAnswer: "muerde", explanation: "El refrán es 'Perro que ladra no muerde', aplicable a quienes amenazan mucho pero no actúan."),
            ExerciseItem(prompt: "Completa el refrán: Ojos que no ven, corazón que no ___.", options: ["siente", "llora", "ama", "sufre"], correctAnswer: "siente", explanation: "El refrán es 'Ojos que no ven, corazón que no siente', refiriéndose a que no sufrimos por lo que ignoramos."),
            ExerciseItem(prompt: "Completa el refrán: El que con lobos anda, a ___ se enseña.", options: ["aullar", "comer", "correr", "cazar"], correctAnswer: "aullar", explanation: "El refrán es 'El que con lobos anda, a aullar se enseña', indicando que se adoptan las costumbres de quienes nos rodean."),
            ExerciseItem(prompt: "Completa el refrán: No todo lo que brilla es ___.", options: ["oro", "plata", "joya", "brillante"], correctAnswer: "oro", explanation: "El refrán es 'No todo lo que brilla es oro', advirtiendo sobre las apariencias engañosas."),
            ExerciseItem(prompt: "Completa el refrán: Árbol que nace torcido, jamás su tronco ___.", options: ["endereza", "crece", "rompe", "florece"], correctAnswer: "endereza", explanation: "El refrán es 'Árbol que nace torcido, jamás su tronco endereza', implicando que es difícil cambiar hábitos muy arraigados."),
            ExerciseItem(prompt: "Completa el refrán: Mucho ruido y pocas ___.", options: ["nueces", "hojas", "ramas", "palabras"], correctAnswer: "nueces", explanation: "El refrán es 'Mucho ruido y pocas nueces', para referirse a algo pomposo de poca sustancia real."),
            ExerciseItem(prompt: "Completa el refrán: El que busca ___.", options: ["encuentra", "pierde", "gana", "sabe"], correctAnswer: "encuentra", explanation: "El refrán es 'El que busca encuentra', alentando a la perseverancia en la investigación o acción.")
        ]
    )
}
