import Foundation


struct TagalogHardExercisesData {

    static let allExercises: [Exercise] = [
        exercise1,
        exercise2,
        exercise3,
        exercise4,
        exercise5,
        exercise6,
        exercise7,
        exercise8,
        easyHomonyms
    ]

    // MARK: - Exercise 1: Mga Salitang Magkapareho ang Baybay
    private static let exercise1 = Exercise(
        title: "Mga Salitang Magkapareho ang Baybay",
        instructions: "Piliin ang tamang pares ng salita na magkapareho ang baybay upang kumpletuhin ang mga pangungusap.",
        section: .language,
        type: .homonym,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "[baga / baga] Mainit pa ang mga ___ sa kalan. May sakit ang kanyang ___.", options: ["baga...baga", "baga...lungs", "lungs...baga", "baga...apoy"], correctAnswer: "baga...baga", explanation: "Ang unang 'baga' ay tumutukoy sa ningas ng apoy; ang pangalawang 'baga' ay organ sa katawan para sa paghinga (lungs)."),
            ExerciseItem(prompt: "[puno / puno] Ang ___ ng mangga ay malaki. ___ na ng tubig ang balde.", options: ["puno...puno", "puno...walang laman", "walang laman...puno", "puno...kahoy"], correctAnswer: "puno...puno", explanation: "Ang 'puno' ay maaaring tumukoy sa isang halaman (tree) o kalagayan na walang bakanteng espasyo (full)."),
            ExerciseItem(prompt: "[tuyo / tuyo] Kumain kami ng ___ na isda. ___ na ang mga sinampay sa labas.", options: ["tuyo...tuyo", "tuyo...basa", "basa...tuyo", "tuyo...sariwa"], correctAnswer: "tuyo...tuyo", explanation: "Ang unang 'tuyo' ay isang uri ng maalat na isda; ang pangalawa ay kalagayan na walang basa o halumigmig."),
            ExerciseItem(prompt: "[saya / saya] Maganda ang kanyang bagong ___. Puno ng ___ ang kanyang kaarawan.", options: ["saya...saya", "saya...lungkot", "lungkot...saya", "saya...damit"], correctAnswer: "saya...saya", explanation: "Ang unang 'saya' ay palda o damit ng babae; ang pangalawa ay kagalakan o ligaya (happiness)."),
            ExerciseItem(prompt: "[aso / aso] Tumatahol ang aming alagang ___. Makapal ang ___ na galing sa sunog.", options: ["aso...aso", "aso...pusa", "pusa...aso", "aso...singaw"], correctAnswer: "aso...aso", explanation: "Ang unang 'aso' ay hayop (dog); ang pangalawa ay usok na nagmumula sa apoy (smoke)."),
            ExerciseItem(prompt: "[suka / suka] Maasim ang ___ na gawa sa nipa. Ang ___ ng bata ay kulay dilaw.", options: ["suka...suka", "suka...dumi", "dumi...suka", "suka...asim"], correctAnswer: "suka...suka", explanation: "Ang unang 'suka' ay isang maasim na likido (vinegar); ang pangalawa ay ang iniluwa mula sa tiyan (vomit)."),
            ExerciseItem(prompt: "[bukas / bukas] ___ ang tindahan sa kanto. Babalik kami roon ___ ng umaga.", options: ["bukas...bukas", "bukas...sarado", "sarado...bukas", "bukas...ngayon"], correctAnswer: "bukas...bukas", explanation: "Ang unang 'bukas' ay nangangahulugang hindi sarado (open); ang pangalawa ay ang susunod na araw (tomorrow)."),
            ExerciseItem(prompt: "[gabi / gabi] Masarap ang nilagang ___ sa sinigang. Madilim na ang ___ nang kami ay umuwi.", options: ["gabi...gabi", "gabi...araw", "araw...gabi", "gabi...gulay"], correctAnswer: "gabi...gabi", explanation: "Ang unang 'gabi' ay isang uri ng halamang-ugat (taro); ang pangalawa ay ang bahagi ng araw pagkatapos lumubog ang araw (night)."),
            ExerciseItem(prompt: "[tubo / tubo] Gawa sa bakal ang ___ ng tubig. Matamis ang ___ na tanim sa Negros.", options: ["tubo...tubo", "tubo...ugat", "ugat...tubo", "tubo...bakal"], correctAnswer: "tubo...tubo", explanation: "Ang unang 'tubo' ay daanan ng likido (pipe); ang pangalawa ay halamang pinagkukunan ng asukal (sugarcane)."),
            ExerciseItem(prompt: "[lobo / lobo] Lumipad ang pulang ___ sa langit. Nakakatakot ang ungol ng ___ sa gubat.", options: ["lobo...lobo", "lobo...aso", "aso...lobo", "lobo...laruan"], correctAnswer: "lobo...lobo", explanation: "Ang unang 'lobo' ay laruang hinihipan ng hangin (balloon); ang pangalawa ay isang uri ng mabangis na hayop (wolf)."),
            ExerciseItem(prompt: "[pako / pako] Ginamit niya ang ___ sa paggawa ng upuan. Masarap igisa ang halamang ___.", options: ["pako...pako", "pako...kahoy", "kahoy...pako", "pako...metal"], correctAnswer: "pako...pako", explanation: "Ang unang 'pako' ay metal na ginagamit sa pagpupukpok (nail); ang pangalawa ay isang uri ng nakakain na halaman (fern)."),
            ExerciseItem(prompt: "[baba / baba] Mahaba ang ___ ng kanyang mukha. Pakisabi sa kanya na ___ na siya rito.", options: ["baba...baba", "baba...taas", "taas...baba", "baba...mukha"], correctAnswer: "baba...baba", explanation: "Ang unang 'baba' ay bahagi ng mukha sa ilalim ng bibig (chin); ang pangalawa ay kilos ng pagbaba (descend)."),
            ExerciseItem(prompt: "[kita / kita] Malaki ang ___ ng kanyang tindahan. Hindi ko ___ ang nakasulat sa pisara.", options: ["kita...kita", "kita...bulag", "bulag...kita", "kita...pera"], correctAnswer: "kita...kita", explanation: "Ang unang 'kita' ay ang perang kinita (income); ang pangalawa ay kakayahang makakita (visible)."),
            ExerciseItem(prompt: "[hapon / hapon] Natutulog siya tuwing ___. May bisita kaming galing sa bansa ng ___.", options: ["hapon...hapon", "hapon...umaga", "umaga...hapon", "hapon...tsina"], correctAnswer: "hapon...hapon", explanation: "Ang unang 'hapon' ay bahagi ng araw bago gabi (afternoon); ang pangalawa ay bansang Hapon (Japan/Japanese)."),
            ExerciseItem(prompt: "[bata / bata] Masayahin ang ___ na naglalaro. Dapat nating ___ ang hirap para sa pamilya.", options: ["bata...bata", "bata...matanda", "matanda...bata", "bata...tiis"], correctAnswer: "bata...bata", explanation: "Ang unang 'bata' ay taong maliit pa ang edad (child); ang pangalawa ay pagtitiis sa hirap o pasakit (endure).")
        ]
    )

    // MARK: - Exercise 2: Mga Analohiya
    private static let exercise2 = Exercise(
        title: "Mga Analohiya",
        instructions: "Piliin ang salita na pinakamahusay na kumukumpleto sa analohiya.",
        section: .language,
        type: .analogyChoice,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "SOLILOQUY ay sa AKTOR gaya ng SERMON ay sa ___", options: ["Pari", "Miyembro", "Koro", "Simbahan"], correctAnswer: "Pari", explanation: "Ang soliloquy ay sinasalita ng aktor, habang ang sermon naman ay binibigkas ng pari o pastor."),
            ExerciseItem(prompt: "PAHINA ay sa AKLAT gaya ng PIPINDUTIN ay sa ___", options: ["Pyano", "Musika", "Tunog", "Papel"], correctAnswer: "Pyano", explanation: "Ang pahina ay bahagi ng aklat, habang ang pipindutin o key ay bahagi ng pyano."),
            ExerciseItem(prompt: "PALAD ay sa TAO gaya ng PALAPAK ay sa ___", options: ["Manok", "Palaka", "Balahibo", "Tubig"], correctAnswer: "Manok", explanation: "Ang tao ay may palad, habang ang manok o ibon naman ay may palapak o paa na may sapot (webbed foot/foot structure)."),
            ExerciseItem(prompt: "PUSO ay sa TIBOK gaya ng BAGA ay sa ___", options: ["Paghinga", "Dugo", "Oksiheno", "Ugat"], correctAnswer: "Paghinga", explanation: "Ang puso ang gumagawa ng tibok, habang ang baga naman ang gumagawa ng paghinga."),
            ExerciseItem(prompt: "TIMON ay sa BARKO gaya ng MANIBELA ay sa ___", options: ["Kotse", "Kalsada", "Hangin", "Gulong"], correctAnswer: "Kotse", explanation: "Ang timon ang nagpapatakbo sa direksyon ng barko, habang ang manibela naman ang sa kotse."),
            ExerciseItem(prompt: "GINTO ay sa ALAHAS gaya ng KAHOY ay sa ___", options: ["Muwebles", "Gubat", "Puno", "Uling"], correctAnswer: "Muwebles", explanation: "Ang ginto ang ginagamit na materyales sa alahas, habang ang kahoy naman ay sa muwebles."),
            ExerciseItem(prompt: "ESTETOSKOP ay sa DOKTOR gaya ng TELESKOP ay sa ___", options: ["Astronomo", "Aklat", "Kompyuter", "Mapa"], correctAnswer: "Astronomo", explanation: "Ang estetoskop ang gamit ng doktor, habang ang teleskop naman ang gamit ng astronomo."),
            ExerciseItem(prompt: "GABI ay sa BUWAN gaya ng ARAW ay sa ___", options: ["Araw", "Bituin", "Ulap", "Hanging-amihan"], correctAnswer: "Araw", explanation: "Ang buwan ang nakikita sa gabi, habang ang araw naman ang nakikita sa umaga o tanghali (sun)."),
            ExerciseItem(prompt: "Pukyutan ay sa BAHAY-PUKYUTAN gaya ng GAGAMBA ay sa ___", options: ["Sapot", "Kuweba", "Lawa", "Puno"], correctAnswer: "Sapot", explanation: "Ang pukyutan ang gumagawa ng bahay-pukyutan, habang ang gagamba naman ang gumagawa ng sapot."),
            ExerciseItem(prompt: "MATA ay sa PANINGIN gaya ng TAINGA ay sa ___", options: ["Pandinig", "Tunog", "Musika", "Alingawngaw"], correctAnswer: "Pandinig", explanation: "Ang mata ang organ para sa paningin, habang ang tainga naman ang para sa pandinig."),
            ExerciseItem(prompt: "BAKAL ay sa PANDAY gaya ng PUTIK ay sa ___", options: ["Magsasayaw", "Magpapalayok", "Mananahi", "Magsasaka"], correctAnswer: "Magpapalayok", explanation: "Ang panday ang naghuhulma ng bakal, habang ang magpapalayok o potmaker naman ang naghuhulma ng putik/luwad."),
            ExerciseItem(prompt: "DAHON ay sa PUNO gaya ng PETALO ay sa ___", options: ["Bulaklak", "Tini", "Bunga", "Ugat"], correctAnswer: "Bulaklak", explanation: "Ang dahon ay bahagi ng puno, habang ang petalo naman ay bahagi ng bulaklak."),
            ExerciseItem(prompt: "PUTI ay sa ITIM gaya ng TAAS ay sa ___", options: ["Baba", "Kanan", "Kaliwa", "Loob"], correctAnswer: "Baba", explanation: "Ang puti at itim ay magkasalungat, gaya rin ng taas at baba."),
            ExerciseItem(prompt: "TERMOMETRO ay sa TEMPERATURA gaya ng BAROMETRO ay sa ___", options: ["Presyon ng hangin", "Oras", "Distansya", "Taas"], correctAnswer: "Presyon ng hangin", explanation: "Ang termometro ang sumusukat sa temperatura, habang ang barometro naman ay sa presyon ng hangin."),
            ExerciseItem(prompt: "LOTUS ay sa LAWA gaya ng ROSAS ay sa ___", options: ["Tini", "Bango", "Pula", "Petalo"], correctAnswer: "Tini", explanation: "Ang lotus ay tumutubo sa lawa o putikan, habang ang rosas naman ay tumutubo sa may mga tini (thorns).")
        ]
    )

    // MARK: - Exercise 3: Asosasyon ng mga Salita
    private static let exercise3 = Exercise(
        title: "Asosasyon ng mga Salita",
        instructions: "Piliin ang salita na may pinakamalapit na ugnayan sa ibinigay na salita.",
        section: .language,
        type: .multipleChoice,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "ALTRUISMO", options: ["Pagkakawanggawa", "Kaguluhan", "Galit", "Inggit"], correctAnswer: "Pagkakawanggawa", explanation: "Ang altruismo ay ang walang pag-iimbot na pagtulong o pagkakawanggawa sa iba."),
            ExerciseItem(prompt: "PASKO", options: ["Simbang Gabi", "Bibingka", "Kuneho", "Kabaong"], correctAnswer: "Simbang Gabi", explanation: "Ang Simbang Gabi ay isa sa pinakasikat na tradisyong Pilipino tuwing panahon ng Pasko."),
            ExerciseItem(prompt: "ADOBO", options: ["Toyo at Suka", "Gatas", "Keso", "Asukal"], correctAnswer: "Toyo at Suka", explanation: "Ang toyo at suka ang mga pangunahing sangkap sa pagluluto ng adobo."),
            ExerciseItem(prompt: "JEEPNEY", options: ["Hari ng Kalsada", "Dagat", "Eroplano", "Tren"], correctAnswer: "Hari ng Kalsada", explanation: "Ang jeepney ay kilala bilang 'Hari ng Kalsada' sa Pilipinas."),
            ExerciseItem(prompt: "BARONG TAGALOG", options: ["Pinya", "Seda", "Bulak", "Katad"], correctAnswer: "Pinya", explanation: "Ang tradisyonal na Barong Tagalog ay karaniwang hinahabi mula sa hibla ng pinya (piña cloth)."),
            ExerciseItem(prompt: "SAMPAGUITA", options: ["Pambansang Bulaklak", "Rosas", "Orkid", "Sunflower"], correctAnswer: "Pambansang Bulaklak", explanation: "Ang Sampaguita ang pambansang bulaklak ng Pilipinas."),
            ExerciseItem(prompt: "BALUT", options: ["Itlog ng Pato", "Manok", "Isda", "Baboy"], correctAnswer: "Itlog ng Pato", explanation: "Ang balut ay nilagang itlog ng pato na may nabubuong sisiw sa loob."),
            ExerciseItem(prompt: "BAYANIHAN", options: ["Pagtutulungan", "Kumpetisyon", "Away", "Sarili"], correctAnswer: "Pagtutulungan", explanation: "Ang bayanihan ay nagpapakita ng sama-samang pagtutulungan ng pamayanan nang walang hinihintay na kapalit."),
            ExerciseItem(prompt: "BARYA", options: ["Alkansya", "Bulsa", "Bag", "Kaha"], correctAnswer: "Alkansya", explanation: "Karaniwang iniipon ang mga barya sa loob ng alkansya."),
            ExerciseItem(prompt: "SINEGUElas", options: ["Tag-araw", "Tag-ulan", "Taglamig", "Bagyo"], correctAnswer: "Tag-araw", explanation: "Ang sineguelas ay isang prutas na sumisibol at sikat tuwing panahon ng tag-araw."),
            ExerciseItem(prompt: "LECHON", options: ["Mang Tomas", "Ketchup", "Toyo", "Suka"], correctAnswer: "Mang Tomas", explanation: "Ang sarsa ng Mang Tomas ang pinakasikat na kapareha ng lechon sa handaan."),
            ExerciseItem(prompt: "SINIGANG", options: ["Sampalok", "Mangga", "Kalamansi", "Kamias"], correctAnswer: "Sampalok", explanation: "Ang sampalok ang tradisyonal na pampaasim na ginagamit sa lutong sinigang."),
            ExerciseItem(prompt: "TINIKLING", options: ["Kawayan", "Tambo", "Kahoy", "Bakal"], correctAnswer: "Kawayan", explanation: "Ang tinikling ay sayaw na gumagamit ng dalawang mahahabang kawayan na pinupukpok sa sahig."),
            ExerciseItem(prompt: "KARIHAN", options: ["Turo-turo", "Restawran", "Hotel", "Kalsada"], correctAnswer: "Turo-turo", explanation: "Ang karihan o karinderya ay kilala rin sa tawag na turo-turo."),
            ExerciseItem(prompt: "MAYON", options: ["AlbAy", "Laguna", "Batangas", "Davao"], correctAnswer: "AlbAy", explanation: "Ang Bulkang Mayon na may perpektong hugis-kono ay matatagpuan sa Albay.")
        ]
    )

    // MARK: - Exercise 4: Pagsasanay sa Pagkumpleto ng Pangungusap
    private static let exercise4 = Exercise(
        title: "Pagsasanay sa Pagkumpleto ng Pangungusap",
        instructions: "Piliin ang pinakaangkop na salita upang kumpletuhin ang pangungusap.",
        section: .language,
        type: .sentenceCompletion,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "Nakatulong ang malakas na ulan upang ___ ang matinding tuyot sa lalawigan.", options: ["maibsan", "palalain", "panatilihin", "patagalin"], correctAnswer: "maibsan", explanation: "Ang ulan ay nagbibigay ng tubig na nakababawas o nakagagaan (nakapagpapaiibsan) sa tuyot o tagtuyot."),
            ExerciseItem(prompt: "Ang talumpati ng pangulo ay napaka-lohikal kaya ito ay nakakuha ng malawakang ___.", options: ["pagtanggap", "pagtatakwil", "pagdududa", "kalamigan"], correctAnswer: "pagtanggap", explanation: "Ang maayos at lohikal na talumpati ay karaniwang tinatanggap ng publiko nang may lugod."),
            ExerciseItem(prompt: "Sa kabila ng maraming pagsubok sa buhay, pinanatili niya ang isang ___ na espiritu.", options: ["matatag", "mahina", "takot", "nag-aalinlangan"], correctAnswer: "matatag", explanation: "Ang matatag na espiritu o kalooban ay nagpapakita ng hindi pagsuko sa mga pagsubok."),
            ExerciseItem(prompt: "Ang pinturang ito ay may napaka-harmonyang kulay at mahusay na tekniko, kaya ito ay isang ___.", options: ["obra-maestra", "masamang gawa", "simpleng kopya", "karaniwang guhit"], correctAnswer: "obra-maestra", explanation: "Ang isang napakahusay at natatanging likhang-sining ay tinatawag na obra-maestra."),
            ExerciseItem(prompt: "Sa pamamagitan ng pag-aaral sa mga lumang banga, muling ___ ng mga arkeologo ang kasaysayan.", options: ["nabuo", "nasira", "naitago", "nalimutan"], correctAnswer: "nabuo", explanation: "Ang pananaliksik sa mga sinaunang bagay ay tumutulong upang muling mabuo ang kasaysayan."),
            ExerciseItem(prompt: "Ang paggamit ng mga recycled na materyales ay nakatutulong sa mga industriya upang ___ ang gastos.", options: ["pababain", "pataasin", "panatilihin", "balewalain"], correctAnswer: "pababain", explanation: "Ang pag-recycled ay nakababawas o nakapagpapababa sa kabuuang gastos sa produksyon."),
            ExerciseItem(prompt: "Dahil sa maling desisyon ng pamunuan, ang kumpanya ay naharap sa matinding ___ sa pananalapi.", options: ["krisis", "kaunlaran", "paglago", "katatagan"], correctAnswer: "krisis", explanation: "Ang maling pamamahala ay maaaring magdulot ng krisis o matinding kakulangan sa pera."),
            ExerciseItem(prompt: "Ang panitikan ng manunulat na iyon ay kilala sa matalas na pagtuligsa sa mga ___ ng lipunan.", options: ["sakit", "tagumpay", "batas", "kabutihan"], correctAnswer: "sakit", explanation: "Ang mapanuring panitikan ay karaniwang naglalantad sa mga sakit o negatibong aspeto ng lipunan."),
            ExerciseItem(prompt: "Upang maibsan ang trapiko sa sentro ng lungsod, nagtayo ang pamahalaan ng daang ___.", options: ["pabilog", "sarado", "makipot", "pansamantala"], correctAnswer: "pabilog", explanation: "Ang daang pabilog o diversion road (bypass road) ay naglalayo ng trapiko sa sentro ng lungsod."),
            ExerciseItem(prompt: "Ang mga resulta ng pananaliksik na ito ay nagdulot ng ___ na tugon sa buong mundo.", options: ["malawak", "limitado", "negatibo", "panandalian"], correctAnswer: "malawak", explanation: "Ang mahahalagang pagtuklas ay nagdudulot ng malawak at positibong talakayan sa buong mundo."),
            ExerciseItem(prompt: "Nagkasundo ang dalawang kumpanya sa isang kasunduan sa ___ para sa parehong pakinabang.", options: ["pagtutulungan", "kumpetisyon", "pagsasanib", "pagtatalo"], correctAnswer: "pagtutulungan", explanation: "Ang kasunduan batay sa parehong pakinabang ay kasunduan sa pagtutulungan (partnership/cooperation)."),
            ExerciseItem(prompt: "Ang dokumentaryong ito ay nagpakita sa isang ___ na paraan ng buhay ng mga migratory bird.", options: ["makatotohanan", "kathang-isip", "nakasisira", "pinaganda"], correctAnswer: "makatotohanan", explanation: "Ang mga dokumentaryo ay nagpapakita ng buhay ng mga hayop sa makatotohanang paraan."),
            ExerciseItem(prompt: "Matapos ang ilang oras na pagsasaayos, ang linya ng komunikasyon ay bumalik na sa ___ na operasyon.", options: ["normal", "huli", "putol-putol", "blokeado"], correctAnswer: "normal", explanation: "Ang pagkumpuni ay nagbabalik sa linya sa normal o maayos na kalagayan."),
            ExerciseItem(prompt: "Ang Simbahan ng San Agustin ay isang makasaysayang gusali at itinuturing na ___ ng kulturang Pilipino.", options: ["simbolo", "dahilan", "kahinaan", "pabigat"], correctAnswer: "simbolo", explanation: "Ang mga makasaysayang istruktura ay nagsisilbing simbolo ng kultura at kasaysayan ng bansa."),
            ExerciseItem(prompt: "Siya ay napakahigpit sa kanyang trabaho at hindi tumatanggap ng anumang uri ng ___.", options: ["kapabayaan", "disiplina", "tiyaga", "pag-iingat"], correctAnswer: "kapabayaan", explanation: "Ang taong disiplinado at maayos magtrabaho ay hindi pinapayagan ang kapabayaan o kawalan ng kaayusan.")
        ]
    )

    // MARK: - Exercise 5: Pagkakasunod-sunod ng mga Hakbang
    private static let exercise5 = Exercise(
        title: "Pagkakasunod-sunod ng mga Hakbang",
        instructions: "Ayusin ang mga hakbang ng aktibidad sa isang lohikal na pagkakasunod-sunod.",
        section: .language,
        type: .sequencing,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "Paggawa ng kape gamit ang filter", options: ["Initin ang tubig ngunit huwag hayaang kumulo nang husto", "Ilagay ang giniling na kape sa salaan na may papel na filter", "Ibuhos ang mainit na tubig nang pabilog sa ibabaw ng kape", "Lagyan ng asukal o gatas at ihain sa tasa"], correctAnswer: "Initin ang tubig ngunit huwag hayaang kumulo nang husto | Ilagay ang giniling na kape sa salaan na may papel na filter | Ibuhos ang mainit na tubig nang pabilog sa ibabaw ng kape | Lagyan ng asukal o gatas at ihain sa tasa", explanation: "Paggawa ng kape: painitin ang tubig, ilagay ang kape sa filter, ibuhos ang tubig, at lagyan ng lasa bago ihain."),
            ExerciseItem(prompt: "Pagluluto ng adobo", options: ["I-marinate ang karne sa toyo, bawang, at paminta", "Igisa ang bawang at karne hanggang sa pumula", "Idagdag ang suka at hayaang kumulo nang hindi hinahalo", "Dagdagan ng kaunting tubig at hayaang lumapot ang sarsa"], correctAnswer: "I-marinate ang karne sa toyo, bawang, at paminta | Igisa ang bawang at karne hanggang sa pumula | Idagdag ang suka at hayaang kumulo nang hindi hinahalo | Dagdagan ng kaunting tubig at hayaang lumapot ang sarsa", explanation: "Pagluluto ng adobo: i-marinate, igisa ang karne, idagdag ang suka nang walang halo, at pakuluin hanggang lumapot ang sarsa."),
            ExerciseItem(prompt: "Pagtatapon ng basura sa tama", options: ["Ipunin ang mga basura sa loob ng bahay", "Ibukod ang nabubulok sa hindi nabubulok", "Ilagay ang mga ito sa kaukulang basurahan sa labas", "Hintayin ang trak ng basura para sa koleksyon"], correctAnswer: "Ipunin ang mga basura sa loob ng bahay | Ibukod ang nabubulok sa hindi nabubulok | Ilagay ang mga ito sa kaukulang basurahan sa labas | Hintayin ang trak ng basura para sa koleksyon", explanation: "Pagtatapon ng basura: ipunin, ibukod ang uri, ilabas sa tamang lalagyan, at ipasa sa kolektor."),
            ExerciseItem(prompt: "Wastong paghuhugas ng kamay", options: ["Basain ang mga kamay ng malinis na tubig", "Sabunin at kuskusin ang mga palad at daliri", "Banlawan ang sabon gamit ang tumutulong tubig", "Patuyuin ang kamay gamit ang malinis na tuwalya"], correctAnswer: "Basain ang mga kamay ng malinis na tubig | Sabunin at kuskusin ang mga palad at daliri | Banlawan ang sabon gamit ang tumutulong tubig | Patuyuin ang kamay gamit ang malinis na tuwalya", explanation: "Paghuhugas ng kamay: basain ang kamay, sabunin at kuskusin, banlawan, at patuyuin sa tuwalya."),
            ExerciseItem(prompt: "Pagsasaing ng kanin", options: ["Sukatin ang bigas at hugasan ito ng tubig", "Lagyan ng tamang dami ng tubig ang kaldero", "Punasan ang ilalim ng kaldero at isalang sa kalan", "Hintaying kumulo at matuyo ang tubig bago hinaan ang apoy"], correctAnswer: "Sukatin ang bigas at hugasan ito ng tubig | Lagyan ng tamang dami ng tubig ang kaldero | Punasan ang ilalim ng kaldero at isalang sa kalan | Hintaying kumulo at matuyo ang tubig bago hinaan ang apoy", explanation: "Pagsasaing: hugasan ang bigas, lagyan ng tubig, punasan ang ilalim ng kaldero at isalang, patuyuin sa mahinang apoy."),
            ExerciseItem(prompt: "Pamimili sa supermarket", options: ["Gumawa ng listahan ng mga bibilhin", "Kumuha ng cart at pumili ng mga produkto", "Pumila sa cashier at magbayad", "Ibalot ang mga binili at iuwi sa bahay"], correctAnswer: "Gumawa ng listahan ng mga bibilhin | Kumuha ng cart at pumili ng mga produkto | Pumila sa cashier at magbayad | Ibalot ang mga binili at iuwi sa bahay", explanation: "Pamimili: listahan, pumili sa cart, magbayad sa cashier, ibalot at iuwi."),
            ExerciseItem(prompt: "Pagbabayad ng kuryente online", options: ["Buksan ang mobile banking o e-wallet app", "Ilagay ang account number ng kuryente", "Suriin ang kabuuang halaga ng bill", "Ilagay ang OTP o PIN upang kumpirmahin"], correctAnswer: "Buksan ang mobile banking o e-wallet app | Ilagay ang account number ng kuryente | Suriin ang kabuuang halaga ng bill | Ilagay ang OTP o PIN upang kumpirmahin", explanation: "Pagbabayad: buksan ang app, ilagay ang account number, suriin ang bill, at kumpirmahin gamit ang PIN."),
            ExerciseItem(prompt: "Paglilinis ng kuwarto", options: ["Iligpit ang mga kalat at ibalik sa tamang lagayan", "Punasan ang alikabok sa mga lamesa at estante", "Walisin ang sahig gamit ang tingting o vacuum", "Lampasuhan o i-mop ang sahig gamit ang basang basahan"], correctAnswer: "Iligpit ang mga kalat at ibalik sa tamang lagayan | Punasan ang alikabok sa mga lamesa at estante | Walisin ang sahig gamit ang tingting o vacuum | Lampasuhan o i-mop ang sahig gamit ang basang basahan", explanation: "Paglilinis: iligpit ang kalat, punasan ang alikabok, walisin ang sahig, at lampasuhan."),
            ExerciseItem(prompt: "Pagpapadala ng package sa courier", options: ["Ibalot nang maayos ang ipapadala sa karton", "Isulat ang address ng sender at receiver sa kahon", "Dalhin sa sangay upang timbangin at kwentahin", "Bayaran ang shipping fee at kuhanin ang resibo"], correctAnswer: "Ibalot nang maayos ang ipapadala sa karton | Isulat ang address ng sender at receiver sa kahon | Dalhin sa sangay upang timbangin at kwentahin | Bayaran ang shipping fee at kuhanin ang resibo", explanation: "Pagpapadala: ibalot, isulat ang address, ipatimbang sa courier, bayaran at kuhanin ang resibo."),
            ExerciseItem(prompt: "Paggawa ng sunny-side up egg", options: ["Buksan ang kalan at maglagay ng mantika sa kawali", "Basagin ang itlog at dahan-dahang ilagay sa mainit na mantika", "Budburan ng kaunting asin at paminta", "Hanguin ang itlog gamit ang spatula at ilagay sa pinggan"], correctAnswer: "Buksan ang kalan at maglagay ng mantika sa kawali | Basagin ang itlog at dahan-dahang ilagay sa mainit na mantika | Budburan ng kaunting asin at paminta | Hanguin ang itlog gamit ang spatula at ilagay sa pinggan", explanation: "Sunny-side up: painitin ang mantika, basagin ang itlog sa kawali, lagyan ng asin/paminta, hanguin gamit ang spatula."),
            ExerciseItem(prompt: "Paghango ng pera sa ATM", options: ["Ipasok ang bank card at i-type ang PIN code", "Piliin ang Withdrawal at ilagay ang halaga", "Kunin ang pera at bilangin ito nang maayos", "Kunin ang card at itago ito sa pitaka"], correctAnswer: "Ipasok ang bank card at i-type ang PIN code | Piliin ang Withdrawal at ilagay ang halaga | Kunin ang pera at bilangin ito nang maayos | Kunin ang card at itago ito sa pitaka", explanation: "ATM: ipasok ang card at PIN, ilagay ang halaga ng withdrawal, kunin at bilangin ang pera, kunin ang card."),
            ExerciseItem(prompt: "Paglaba gamit ang washing machine", options: ["Ihiwalay ang mga damit ayon sa kulay at ilagay sa loob", "Maglagay ng sabong panlaba at softener sa lalagyan", "Piliin ang angkop na cycle at pindutin ang Start", "Isabit ang mga nilabhan sa sampayan upang matuyo"], correctAnswer: "Ihiwalay ang mga damit ayon sa kulay at ilagay sa loob | Maglagay ng sabong panlaba at softener sa lalagyan | Piliin ang angkop na cycle at pindutin ang Start | Isabit ang mga nilabhan sa sampayan upang matuyo", explanation: "Paglaba: ihiwalay ang damit sa loob, lagyan ng sabon, pindutin ang start, isabit sa sampayan."),
            ExerciseItem(prompt: "Pagpapatingin sa doktor sa ospital", options: ["Pumunta sa reception at kumuha ng queue number", "Makipagkita sa doktor upang magpaliwanag ng sakit", "Magbayad sa cashier at kuhanin ang reseta", "Dalhin ang reseta sa botika upang makuha ang gamot"], correctAnswer: "Pumunta sa reception at kumuha ng queue number | Makipagkita sa doktor upang magpaliwanag ng sakit | Magbayad sa cashier at kuhanin ang reseta | Dalhin ang reseta sa botika upang makuha ang gamot", explanation: "Pagpapatingin: queue sa reception, magpatingin sa doktor, magbayad sa cashier, kunin ang gamot sa botika."),
            ExerciseItem(prompt: "Pag-inom ng gamot", options: ["Suriin ang expiration date sa kahon ng gamot", "Kuhanin ang tamang dosis ng tabletas sa lalagyan", "Inumin ang gamot kasabay ng isang basong maligamgam na tubig", "Ibalik ang kahon ng gamot sa ligtas na taguan"], correctAnswer: "Suriin ang expiration date sa kahon ng gamot | Kuhanin ang tamang dosis ng tabletas sa lalagyan | Inumin ang gamot kasabay ng isang basong maligamgam na tubig | Ibalik ang kahon ng gamot sa ligtas na taguan", explanation: "Pag-inom ng gamot: suriin ang expiration, kuhanin ang tamang dosis, inumin kasabay ng tubig, ibalik sa taguan."),
            ExerciseItem(prompt: "Pag-charge ng cellphone", options: ["Hanapin ang charger at saksakan sa silid", "Isaksak ang charger sa saksakan sa dingding", "Ikonekta ang dulo ng cord sa saksakan ng cellphone", "Kapag puno na ang baterya, tanggalin ang cord sa cellphone"], correctAnswer: "Hanapin ang charger at saksakan sa silid | Isaksak ang charger sa saksakan sa dingding | Ikonekta ang dulo ng cord sa saksakan ng cellphone | Kapag puno na ang baterya, tanggalin ang cord sa cellphone", explanation: "Pag-charge: hanapin ang charger, isaksak sa dingding, ikonekta sa cellphone, tanggalin kapag puno na.")
        ]
    )

    // MARK: - Exercise 6: Pagsusuri ng Sanhi at Bunga
    private static let exercise6 = Exercise(
        title: "Pagsusuri ng Sanhi at Bunga",
        instructions: "Piliin ang pinaka-lohikal na sanhi o bunga para sa ibinigay na sitwasyon.",
        section: .cognition,
        type: .multipleChoice,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "Sanhi: Umabot sa higit 43 degrees Celsius ang temperatura nitong tag-araw.", options: ["Tumaas nang malaki ang konsumo sa kuryente dahil sa aircon", "Dumami ang mga taong namamasyal sa labas ng kalsada", "Tumaas ang benta ng makakapal na jacket sa mga tindahan", "Nag-anunsyo ang mga planta na bumaba ang konsumo sa kuryente"], correctAnswer: "Tumaas nang malaki ang konsumo sa kuryente dahil sa aircon", explanation: "Ang matinding init ay nagiging dahilan ng madalas na paggamit ng aircon, na nagpapataas sa konsumo ng kuryente."),
            ExerciseItem(prompt: "Sanhi: Binalewala ng drayber ang pulang ilaw at humarurot sa interseksyon.", options: ["Pinara siya ng pulis-trapiko at binigyan ng malaking multa", "Nakatanggap siya ng parangal bilang huwarang drayber", "Kusa at mabilis na tumabi ang ibang mga sasakyan", "Agad na nag-berde ang ilaw nang lumapit ang kanyang sasakyan"], correctAnswer: "Pinara siya ng pulis-trapiko at binigyan ng malaking multa", explanation: "Ang paglabag sa batas trapiko tulad ng paghabol sa pulang ilaw ay may katapat na multa at huli."),
            ExerciseItem(prompt: "Sanhi: Nabara ang drainage system ng lungsod dahil sa mga basura.", options: ["Bumaha nang malalim sa mga kalsada matapos ang malakas na ulan", "Mabilis at ligtas na umagos ang tubig-ulan patungo sa ilog", "Nanatiling tuyo at malinis ang mga kalsada sa buong lungsod", "Biglang tumaas ang presyo ng bottled mineral water sa merkado"], correctAnswer: "Bumaha nang malalim sa mga kalsada matapos ang malakas na ulan", explanation: "Ang baradong drainage ay nagdudulot ng pagkaantala ng daloy ng tubig-ulan na sanhi ng pagbaha."),
            ExerciseItem(prompt: "Bunga: Sobrang saya ni Juan at nagdiwang kasama ang pamilya matapos ang pagsusulit.", options: ["Sanhi: Nakakuha siya ng pinakamataas na marka sa board exam", "Sanhi: Hindi siya nakapagsulit dahil sa matinding sakit", "Sanhi: Iniwan niyang walang sagot ang kanyang sagutang papel", "Sanhi: Nag-anunsyo ang gobyerno na ipagpaliban ang pagsusulit"], correctAnswer: "Sanhi: Nakakuha siya ng pinakamataas na marka sa board exam", explanation: "Ang pagpasa nang may mataas na marka ang lohikal na dahilan ng kanyang labis na kagalakan."),
            ExerciseItem(prompt: "Bunga: Naging masagana ang ani ng mga magsasaka at tumaas ang kanilang kita.", options: ["Sanhi: Tamang-tama ang dami ng ulan at sikat ng araw ngayong taon", "Sanhi: Nagkaroon ng matinding tagtuyot sa buong lalawigan", "Sanhi: Gumamit ang mga magsasaka ng pekeng abono sa kanilang taniman", "Sanhi: Sinira ng mga ligaw na baboy-ramo ang malaking bahagi ng taniman"], correctAnswer: "Sanhi: Tamang-tama ang dami ng ulan at sikat ng araw ngayong taon", explanation: "Ang magandang panahon at sapat na ulan ay nagdudulot ng masaganang ani para sa mga pananim."),
            ExerciseItem(prompt: "Sanhi: Nagpuyat ang mga mag-aaral kagabi para magrebyu para sa pagsusulit.", options: ["Nahirapan silang gumising sa umaga dahil sa antok at pagod", "Maaga silang nagising na puno ng lakas at sigla", "Biglang ipinagpaliban ng paaralan ang pagsusulit sa araw na iyon", "Naging napakatalas at alerto ng kanilang isip sa oras ng pagsusulit"], correctAnswer: "Nahirapan silang gumising sa umaga dahil sa antok at pagod", explanation: "Ang puyat o kakulangan sa tulog ay nagdudulot ng labis na pagod at antok sa kinabukasan."),
            ExerciseItem(prompt: "Sanhi: Tumaas nang husto ang suplay ng sibuyas sa pamilihan.", options: ["Bumaba nang malaki ang presyo ng sibuyas sa palengke", "Wala nang makabili ng sibuyas sa lokal na tindahan", "Umakyat sa pinakamataas na tala ang presyo ng sibuyas", "Biglang tumaas ang presyo ng patatas kasabay ng suplay"], correctAnswer: "Bumaba nang malaki ang presyo ng sibuyas sa palengke", explanation: "Kapag marami ang suplay ng isang produkto tulad ng gulay, bumababa ang presyo nito sa merkado."),
            ExerciseItem(prompt: "Bunga: Nawalan ng kuryente ang buong subdibisyon at huminto ang mga elevator.", options: ["Sanhi: Sumabog ang pangunahing transformer ng kuryente sa lugar", "Sanhi: Tanghaling tapat at tirik na tirik ang sikat ng araw", "Sanhi: Gumamit ang mga residente ng LED bulb sa kanilang bahay", "Sanhi: Libre na ang monthly maintenance fee ng condo para sa buwan"], correctAnswer: "Sanhi: Sumabog ang pangunahing transformer ng kuryente sa lugar", explanation: "Ang pagkasira ng pangunahing transformer ang nagiging sanhi ng malawakang blackout sa isang komunidad."),
            ExerciseItem(prompt: "Sanhi: Nag-ehersisyo at nag-jogging araw-araw si Mang Pedro pagkatapos magretiro.", options: ["Bumuti nang husto ang kanyang pisikal at mental na kalusugan", "Naging mahina ang kanyang katawan at madaling magkasakit", "Biglang tumaas ng dalawampung kilo ang kanyang timbang sa isang buwan", "Nawalan siya ng kakayahang matulog nang maayos sa gabi"], correctAnswer: "Bumuti nang husto ang kanyang pisikal at mental na kalusugan", explanation: "Ang regular na ehersisyo ay nakatutulong upang mapabuti ang pangkalahatang kalusugan ng isang tao."),
            ExerciseItem(prompt: "Sanhi: Ipinatupad ng pamahalaan ang batas na nagbabawal sa single-use plastic bag.", options: ["Nasanay ang mga tao na magdala ng eco-bag at canvass bag sa pamimili", "Dumami ang mga basurang plastic sa mga kalsada at kanal", "Doble ang ginawang produksyon ng mga pabrika ng plastic bag", "Nagbigay ang mga tindera ng libreng plastic bag sa mga mamimili"], correctAnswer: "Nasanay ang mga tao na magdala ng eco-bag at canvass bag sa pamimili", explanation: "Ang plastic ban ay naghihikayat sa mga mamimili na gumamit ng mas eco-friendly na alternatibo tulad ng canvass bag."),
            ExerciseItem(prompt: "Bunga: Napanis at umasim ang sariwang gatas matapos iwan sa mesa ng isang araw.", options: ["Sanhi: Hindi ito inilagay sa refrigerator sa gitna ng mainit na panahon", "Sanhi: Maayos itong itinago sa loob ng refrigerator sa tamang lamig", "Sanhi: Naglagay ng isang kutsarang puting asukal sa baso ng gatas", "Sanhi: Bagong piga ang gatas mula sa farm kaninang umaga"], correctAnswer: "Sanhi: Hindi ito inilagay sa refrigerator sa gitna ng mainit na panahon", explanation: "Ang gatas ay madaling mapanis kapag naiwan sa mainit na temperatura ng kuwarto."),
            ExerciseItem(prompt: "Sanhi: Sinira ng malakas na bagyo ang mga taniman ng palay sa Gitnang Luzon.", options: ["Tumaas nang malaki ang presyo ng bigas sa mga pamilihan", "Sumobra ang suplay ng bigas kaya napilitang ibaba ang presyo", "Tumaas ang produksyon at kumita ang mga gilingan ng palay", "Tumigil sa pagbili ng bigas ang mga tao at puro instant noodles na lang"], correctAnswer: "Tumaas nang malaki ang presyo ng bigas sa mga pamilihan", explanation: "Ang pagkasira ng mga pananim ay nagdudulot ng kakulangan sa suplay ng bigas, na nagreresulta sa pagtaas ng presyo."),
            ExerciseItem(prompt: "Bunga: Biglang namatay ang screen ng cellphone at hindi na ito bumukas.", options: ["Sanhi: Nanood ng high-definition video ang gumagamit nang hindi naka-charge", "Sanhi: Naka-konekta ang cellphone sa charger sa buong gabi", "Sanhi: Naka-patay ang cellphone at nakatago sa loob ng drawer", "Sanhi: Sinara ng gumagamit ang mga background app at naka-battery saver"], correctAnswer: "Sanhi: Nanood ng high-definition video ang gumagamit nang hindi naka-charge", explanation: "Ang panonood ng HD video ay mabilis na nag-aalis ng charge sa baterya ng cellphone."),
            ExerciseItem(prompt: "Sanhi: Nahuli ng proctor ang mag-aaral na naghahanap ng sagot gamit ang kodigo.", options: ["Kinuha ang kanyang papel at pinatalsik siya sa silid-pagsusulit", "Itinalaga siyang kinatawan ng klase at binigyan ng scholarship", "Biniyayaan siya ng gantimpala ng paaralan dahil sa pagiging malikhain", "Nagpalakpakan ang lahat ng kanyang mga kaklase sa silid"], correctAnswer: "Kinuha ang kanyang papel at pinatalsik siya sa silid-pagsusulit", explanation: "Ang pangongodigo o pandaraya sa pagsusulit ay may parusang diskwalipikasyon."),
            ExerciseItem(prompt: "Bunga: Nagkabanggaan ang dalawang sasakyan na nagdulot ng malaking pinsala.", options: ["Sanhi: Makapal ang hamog sa umaga na nagpababa sa paningin ng drayber", "Sanhi: Parehong nakaparada nang maayos ang mga sasakyan sa garahe", "Sanhi: Maayos ang panahon at napakalinaw ng paningin sa kalsada", "Sanhi: Parehong sumunod sa speed limit ang mga drayber nang may pag-iingat"], correctAnswer: "Sanhi: Makapal ang hamog sa umaga na nagpababa sa paningin ng drayber", explanation: "Ang makapal na hamog o fog ay nagpapahirap sa mga drayber na makita ang kalsada, na nagdudulot ng aksidente.")
        ]
    )

    // MARK: - Exercise 7: Mga Hindi Lohikal na Sitwasyon
    private static let exercise7 = Exercise(
        title: "Mga Hindi Lohikal na Sitwasyon",
        instructions: "Piliin ang sagot na nagpapaliwanag kung bakit imposible o hindi lohikal ang sitwasyon.",
        section: .cognition,
        type: .multipleChoice,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "Nagluto si Juan ng mainit na tsaang gatas sa malamig na kaldero nang hindi binubuksan ang kalan.", options: ["Hindi makakapagluto o makakapagpakulo ng likido nang walang init", "Hindi dapat hinahaluan ng gatas ang tsaa", "Ang mainit na tsaa ay agad na nagiging yelo sa kuwarto", "Kailangang gumamit ng boteng plastic sa pagpapakulo ng tubig"], correctAnswer: "Hindi makakapagluto o makakapagpakulo ng likido nang walang init", explanation: "Ang pagpapakulo ay nangangailangan ng init; hindi ito mangyayari sa malamig na kalan."),
            ExerciseItem(prompt: "Matapos lumubog ang araw sa madilim na gabi, walang ilaw, namitas si Maria ng pulang rosas sa hardin.", options: ["Sa ganap na kadiliman, hindi kayang kilalanin ng mata ang mga kulay", "Ang pulang rosas ay kusa na nagiging puti sa dilim", "Kailangang gumamit ng gunting sa pamimitas ng rosas sa gabi", "Nawawala ang bango ng mga bulaklak kapag pinitas sa gabi"], correctAnswer: "Sa ganap na kadiliman, hindi kayang kilalanin ng mata ang mga kulay", explanation: "Ang paningin sa kulay ay nangangailangan ng repleksyon ng liwanag; imposible itong makita sa ganap na dilim."),
            ExerciseItem(prompt: "Gumamit ang magpapalayok ng tuyong buhangin upang gumawa ng banga at inilagay ito sa tubig upang matuyo.", options: ["Walang kakayahang dumikit ang buhangin at ang tubig ay hahadlang sa pagtuyo nito", "Ang mga palayok ay ginto lamang ang materyales", "Ang buhangin ay nagiging ginto kapag ibinabad sa tubig", "Kailangang gumamit ng microwave sa pagpapatuyo ng palayok"], correctAnswer: "Walang kakayahang dumikit ang buhangin at ang tubig ay hahadlang sa pagtuyo nito", explanation: "Ang buhangin ay walang lagkit gaya ng luwad; at ang tubig ay lalo lamang magpapabasa rito, hindi magpapatuyo."),
            ExerciseItem(prompt: "Sa gitna ng tag-araw na may 40 degrees init, nagsuot siya ng makapal na jacket at umupo sa yelo upang magpahinga.", options: ["Ang pagsusuot ng makapal na jacket at pag-upo sa yelo sa gitna ng init ay magkasalungat", "Hindi nalulusaw ang yelo sa ilalim ng matinding init ng kalsada", "Ang makapal na jacket ay ginagamit lamang sa paglangoy sa dagat", "Kailangang uminom ng tubig na may asin upang makaiwas sa init"], correctAnswer: "Ang pagsusuot ng makapal na jacket at pag-upo sa yelo sa gitna ng init ay magkasalungat", explanation: "Ang pagsusuot ng makapal na jacket ay nagkukulong ng init sa katawan, habang ang yelo naman ay nagpapababa ng temperatura sa hindi maayos na paraan."),
            ExerciseItem(prompt: "Nagkalat ng buto ng palay ang magsasaka sa aspalto ng highway at umasang makakaani ng marami sa taglagas.", options: ["Ang aspalto ay walang lupa at tubig na kailangan ng palay upang tumubo at mag-ugat", "Sa highway ay mansanas lamang ang pinapayagang itanim", "Ang pagtatanim ng palay ay ginagawa lamang sa ibabaw ng yelo", "Ang aspalto ay may natural na pataba na mas maganda sa lupa"], correctAnswer: "Ang aspalto ay walang lupa at tubig na kailangan ng palay upang tumubo at mag-ugat", explanation: "Ang mga pananim ay nangangailangan ng matabang lupa upang mag-ugat at kumuha ng sustansya; hindi ito tutubo sa aspalto."),
            ExerciseItem(prompt: "Tumalon ang isda palabas ng aquarium, tumakbo gamit ang mga paa patungo sa gubat at umakyat sa puno para magtago sa pusa.", options: ["Ang isda ay walang paa para tumakbo at hindi makakahinga sa labas ng tubig", "Natatakot ang pusa na umakyat sa mataas na puno sa gubat", "Ang mga isda ay lumilipad sa langit kasabay ng mga ibon", "Ang kaliskis ng isda ay nagdudulot ng apoy kapag nadikit sa damo"], correctAnswer: "Ang isda ay walang paa para tumakbo at hindi makakahinga sa labas ng tubig", explanation: "Ang isda ay gumagamit ng hasang upang huminga sa tubig; wala rin silang paa para tumakbo o umakyat sa puno."),
            ExerciseItem(prompt: "Pinatay ni Juan ang kanyang cellphone, at agad na tinawagan ang kanyang ina at nakipag-usap ng dalawang oras.", options: ["Ang patay na cellphone ay walang kuryente at signal upang makagawa ng tawag", "Ang pakikipag-usap sa ina ay nangangailangan ng landline lamang", "Nagpapadala ng SMS nang kusa ang cellphone kapag ito ay patay", "Hindi gagana ang tawag kapag walang nakakonektang headphone"], correctAnswer: "Ang patay na cellphone ay walang kuryente at signal upang makagawa ng tawag", explanation: "Kailangang bukas ang cellphone upang gumana ang transceiver nito at makakonekta sa network."),
            ExerciseItem(prompt: "Upang mas mabilis na matuyo ang mga basang damit, inilagay niya ang mga ito sa loob ng balde ng malamig na tubig.", options: ["Ang paglulubog sa tubig ay lalong magpapabasa sa damit at hahadlang sa pagtuyo nito", "Ang basang damit ay natutuyo lamang kapag inilagay sa saradong cabinet", "Sinisira ng malamig na tubig ang hibla ng polyester ng damit", "Kailangang gumamit ng nano powder na sumisipsip ng tubig upang matuyo"], correctAnswer: "Ang paglulubog sa tubig ay lalong magpapabasa sa damit at hahadlang sa pagtuyo nito", explanation: "Ang pagpapatuyo ay ang pag-aalis ng tubig; ang paglubog nito sa balde ay lalo lamang magpapabasa rito."),
            ExerciseItem(prompt: "Upang mapabilis ang takbo ng sasakyan sa pababang kalsada, tinapakan ng drayber ang preno nang pilit.", options: ["Ang preno ay nagpapabagal o nagpapahinto sa sasakyan, hindi nagpapabilis", "Bumabagal ang sasakyan kapag inikot ang manibela nang pakaliwa at pakanan", "Ang preno ng malalaking sasakyan ay nasa gilid lamang ng passenger seat", "Ang pagpreno nang husto ay nagiging sanhi ng pagkawala ng diesel sa tangke"], correctAnswer: "Ang preno ay nagpapabagal o nagpapahinto sa sasakyan, hindi nagpapabilis", explanation: "Ang preno ay ginagamit upang pabagalin ang sasakyan; ang gas pedal ang ginagamit sa pagpapabilis."),
            ExerciseItem(prompt: "Sumisid ang mga gansa sa ilalim ng dagat at gumawa ng pugad na gawa sa tuyong dahon upang mag-itlog.", options: ["Ang mga gansa ay humihinga sa hangin at ang pugad ay masisira ng agos ng tubig", "Ang mga gansa ay nag-iitlog lamang sa ibabaw ng mga ulap", "Ang tubig sa ilalim ng dagat ay palaging kumukulo sa higit 100 degrees", "Nasusunog ang balahibo ng ibon kapag nabasa ng tubig-alat"], correctAnswer: "Ang mga gansa ay humihinga sa hangin at ang pugad ay masisira ng agos ng tubig", explanation: "Ang gansa ay may baga at hindi makakahinga sa ilalim ng tubig; ang mga dahon at pugad ay matatangay din ng agos ng dagat."),
            ExerciseItem(prompt: "Tinikman niya ang kumukulong sabaw sa kalan at sinabing napakalamig nito na parang yelo.", options: ["Ang kumukulong sabaw ay may napakataas na temperatura at nakakapaso, hindi malamig", "Ang sabaw ay dapat kainin gamit ang kutsarang kahoy upang maramdaman ang tamang init", "Ang mainit na pagkain ay nagpapatulog sa dila ng tao", "Ang sabaw ay nagiging yelo agad kapag pinatay ang kalan"], correctAnswer: "Ang kumukulong sabaw ay may napakataas na temperatura at nakakapaso, hindi malamig", explanation: "Ang kumukulo ay may temperaturang malapit sa 100 degrees Celsius, kaya ito ay napakainit at nakakapaso."),
            ExerciseItem(prompt: "Upang ma-lock ang pinto ng bahay, itinapon ng ama ang susi sa labas ng bintana.", options: ["Ang pagla-lock ay nangangailangan ng pagpihit ng susi sa loob ng kandado, hindi ang pagtapon nito", "Ang maliit na butas ng pinto ay hindi papayag na dumaan ang susi", "Ang pintong kahoy ay dapat i-lock gamit ang trangka lamang", "Ang mga pintong bakal ay sa pamamagitan ng fingerprint lamang gumagana"], correctAnswer: "Ang pagla-lock ay nangangailangan ng pagpihit ng susi sa loob ng kandado, hindi ang pagtapon nito", explanation: "Kailangang gamitin ang susi sa mismong kandado upang mapihit ang mekanismo nito; hindi ito mai-lock kung itatapon ang susi."),
            ExerciseItem(prompt: "Tumingin ang isang bulag sa teleskopyo at inilarawan ang mga pulang bulaklak sa burol.", options: ["Ang bulag ay walang paningin kaya hindi magagamit ang teleskopyo", "Ang teleskopyo ay para lamang sa mga astronaut upang makita ang mga planeta", "Ang mga burol ay wala kundi mga cactus at tini ang tumutubo", "Ang teleskopyo ay walang kakayahang magpalaki ng larawan sa araw"], correctAnswer: "Ang bulag ay walang paningin kaya hindi magagamit ang teleskopyo", explanation: "Ang teleskopyo ay gumagamit ng mata upang makita ang pinalaking imahe; hindi ito magagamit ng bulag dahil sa kawalan ng paningin."),
            ExerciseItem(prompt: "Bumalik ang ikot ng kamay ng oras sa dingding, kaya bumalik din ang totoong oras sa kahapon.", options: ["Ang orasan ay tagasulat lamang ng oras at ang pag-ikot nito ay hindi nagbabago sa totoong oras", "Ang pag-ikot ng kamay sa likod ay nagpapasabog sa baterya ng orasan", "Ang oras ay tumatakbo nang mabilis kapag naglalakbay sa kalawakan", "Ang kamay ng orasan ay kontrolado ng electromagnetic wave na nagbabawal sa pag-ikot sa likod"], correctAnswer: "Ang orasan ay tagasulat lamang ng oras at ang pag-ikot nito ay hindi nagbabago sa totoong oras", explanation: "Ang oras ay isang dimensyon ng pisika na patuloy na tumatakbo pasulong; ang orasan ay nagpapakita lamang ng sukat nito."),
            ExerciseItem(prompt: "Sumulat siya gamit ang tuyong ballpen sa basang papel, at nakakuha ng napakalinis at maayos na sulat.", options: ["Ang basang papel ay madaling mapunit at ang tinta ay kakalat sa tubig", "Ang basang papel ay sa pamamagitan ng brush lamang sinusulatan sa ilalim ng tubig", "Ang ballpen ay sa ibabaw ng gintong papel lamang sumusulat", "Ang tubig sa papel ay mabilis na magwawala kapag nadikit ang dulo ng panulat"], correctAnswer: "Ang basang papel ay madaling mapunit at ang tinta ay kakalat sa tubig", explanation: "Ang tubig ay nagpapahina sa hibla ng papel kaya madali itong mapunit sa matalim na dulo ng ballpen; ang tinta ay kakalat din at magiging malabo.")
        ]
    )

    // MARK: - Exercise 8: Mga Salawikain at Kasabihan
    private static let exercise8 = Exercise(
        title: "Mga Salawikain at Kasabihan",
        instructions: "Piliin ang salita na tamang kumukumpleto sa salawikain o kasabihang Pilipino.",
        section: .language,
        type: .sentenceCompletion,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Ang hindi lumingon sa pinanggalingan ay hindi makararating sa ___.", options: ["paroroonan", "bahay", "kalsada", "bayan"], correctAnswer: "paroroonan", explanation: "Ang kilalang salawikain ay 'Ang hindi lumingon sa pinanggalingan ay hindi makararating sa paroroonan', na nagtuturo ng pagpapahalaga sa ating pinagmulan."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Pag may tiyaga, may ___.", options: ["nilaga", "pera", "pagkain", "tagumpay"], correctAnswer: "nilaga", explanation: "Ang kasabihan ay 'Pag may tiyaga, may nilaga', na nangangahulugang ang pagtitiyaga ay may katumbas na gantimpala."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Aanhin pa ang damo, kung patay na ang ___.", options: ["kabayo", "baka", "kambing", "kalabaw"], correctAnswer: "kabayo", explanation: "Ang salawikain ay 'Aanhin pa ang damo, kung patay na ang kabayo', na nangangahulugang balewala ang tulong kung huli na ang lahat."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Habang maikli ang kumot, matutong ___.", options: ["mamaluktot", "matulog", "bumili", "umiyak"], correctAnswer: "mamaluktot", explanation: "Ang salawikain ay 'Habang maikli ang kumot, matutong mamaluktot', na nagtuturo ng pagiging matipid o marunong makibagay sa sitwasyon."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Ang sakit ng kalingkingan, damdam ng buong ___.", options: ["katawan", "kamay", "ulo", "pamilya"], correctAnswer: "katawan", explanation: "Ang salawikain ay 'Ang sakit ng kalingkingan, damdam ng buong katawan', na nangangahulugang ang problema ng isa sa pamilya o grupo ay problema ng lahat."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Pag ang bulsa ay butas, madalas ___.", options: ["lumalabas", "nawawala", "walang laman", "butas"], correctAnswer: "walang laman", explanation: "Ang kasabihan ay 'Pag ang bulsa ay butas' (walang pera/naghihirap)."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Kung ano ang itinanim, siya ring ___.", options: ["aaiin", "kakainin", "tatanimin", "mawawala"], correctAnswer: "aaiin", explanation: "Ang salawikain ay 'Kung ano ang itinanim, siya ring aaiin', na nagtuturo ng batas ng karma o resulta ng ating mga gawa (aaniin)."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Walang matigas na tinapay sa mainit na ___.", options: ["kape", "gatas", "tubig", "tsaa"], correctAnswer: "kape", explanation: "Ang kasabihan ay 'Walang matigas na tinapay sa mainit na kape', na nangangahulugang walang matigas ang kalooban sa taong matiyaga o mabait."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Kung may isinuksok, may ___.", options: ["dudukutin", "kukunin", "mahihita", "mawiwili"], correctAnswer: "dudukutin", explanation: "Ang kasabihan ay 'Kung may isinuksok, may dudukutin', na nagtuturo ng kahalagahan ng pag-iipon."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Nasa tao ang gawa, nasa Diyos ang ___.", options: ["awa", "tulong", "pagpapala", "ganti"], correctAnswer: "awa", explanation: "Ang kasabihan ay 'Nasa tao ang gawa, nasa Diyos ang awa', na nagpapaalala na kailangan nating magsikap habang umaasa sa awa ng Maykapal."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Daig ng maagap ang ___.", options: ["masipag", "matalino", "malakas", "mayaman"], correctAnswer: "masipag", explanation: "Ang kasabihan ay 'Daig ng maagap ang masipag', na nagpapakita na ang taong handa o maaga ay may kalamangan."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Bago mo linisin ang dungis ng ibang tao, linisin mo muna ang sa sarili mong ___.", options: ["mukha", "kamay", "bahay", "salita"], correctAnswer: "mukha", explanation: "Ang kasabihan ay 'Bago mo linisin ang dungis ng ibang tao, linisin mo muna ang sa sarili mong mukha', na nagpapaalala na huwag mamuna ng iba kung may kapintasan din sarili."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Pagkahaba-haba man ng prusisyon, sa ___ din ang tuloy.", options: ["simbahan", "altar", "sementeryo", "kalsada"], correctAnswer: "simbahan", explanation: "Ang kasabihan ay 'Pagkahaba-haba man ng prusisyon, sa simbahan din ang tuloy', na nangangahulugang kahit gaano katagal ang paghihintay ay may patutunguhan pa rin ito sa huli."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Ang mabuting halimbawa ay higit na mabuti kaysa makapangyarihang ___.", options: ["aral", "salita", "utos", "gawain"], correctAnswer: "aral", explanation: "Ang kasabihan ay 'Ang mabuting halimbawa ay higit na mabuti kaysa makapangyarihang aral', na nagpapakita na mas epektibo ang aksyon kaysa sa salita lamang."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Ang lakas ay nanggagaling sa ___.", options: ["pagkakaisa", "sarili", "pera", "kapangyarihan"], correctAnswer: "pagkakaisa", explanation: "Ang kasabihan ay 'Ang lakas ay nanggagaling sa pagkakaisa', na katulad ng konseptong ang unyon ay lakas (unity is strength).")
        ]
    )

    // MARK: - Easy Homonyms
    private static let easyHomonyms = Exercise(
        title: "Mga Salitang Magkakapareho ang Tunog",
        instructions: "Piliin ang tamang salita upang kumpletuhin ang mga pangungusap.",
        section: .language,
        type: .homonym,
        difficulty: .easy,
        items: [
            ExerciseItem(prompt: "[saya / saya] Maganda ang kanyang bagong pulang ___. Puno ng ___ ang kanyang kaarawan.", options: ["saya...saya", "saya...lungkot", "lungkot...saya", "saya...damit"], correctAnswer: "saya...saya", explanation: "Ang unang 'saya' ay damit ng babae (skirt); ang pangalawang 'saya' ay kagalakan (happiness)."),
            ExerciseItem(prompt: "[aso / aso] Tumatahol ang alagang ___ ni Lola. Makapal ang puting ___ mula sa siga.", options: ["aso...aso", "aso...pusa", "pusa...aso", "aso...singaw"], correctAnswer: "aso...aso", explanation: "Ang unang 'aso' ay hayop (dog); ang pangalawang 'aso' ay usok na likha ng apoy (smoke)."),
            ExerciseItem(prompt: "[puno / puno] Ang ___ ng mangga ay matayog. ___ na ng tubig ang malaking balde.", options: ["puno...puno", "puno...walang laman", "walang laman...puno", "puno...kahoy"], correctAnswer: "puno...puno", explanation: "Ang unang 'puno' ay halaman (tree); ang pangalawang 'puno' ay walang bakanteng espasyo (full)."),
            ExerciseItem(prompt: "[gabi / gabi] Masarap ang halamang-ugat na ___ sa sinigang. Madilim na ang ___ nang umuwi si Tatay.", options: ["gabi...gabi", "gabi...araw", "araw...gabi", "gabi...gulay"], correctAnswer: "gabi...gabi", explanation: "Ang unang 'gabi' ay isang uri ng pananim (taro); ang pangalawang 'gabi' ay bahagi ng araw pagkatapos lumubog ang araw (night)."),
            ExerciseItem(prompt: "[bukas / bukas] ___ ang bintana kaya malamig ang hangin. Babalik si Ate dito ___ ng umaga.", options: ["bukas...bukas", "bukas...sarado", "sarado...bukas", "bukas...ngayon"], correctAnswer: "bukas...bukas", explanation: "Ang unang 'bukas' ay hindi nakasara (open); ang pangalawang 'bukas' ay susunod na araw (tomorrow)."),
            ExerciseItem(prompt: "[lobo / lobo] Lumipad ang makulay na ___ sa langit. Narinig namin ang alulong ng ___ sa gubat.", options: ["lobo...lobo", "lobo...aso", "aso...lobo", "lobo...laruan"], correctAnswer: "lobo...lobo", explanation: "Ang unang 'lobo' ay laruang lumilipad (balloon); ang pangalawang 'lobo' ay mabangis na hayop (wolf)."),
            ExerciseItem(prompt: "[suka / suka] Maasim ang ___ na gawa sa niyog. Ang ___ ng maysakit ay marami.", options: ["suka...suka", "suka...dumi", "dumi...suka", "suka...asim"], correctAnswer: "suka...suka", explanation: "Ang unang 'suka' ay maasim na sawsawan (vinegar); ang pangalawang 'suka' ay iniluwa ng tiyan (vomit)."),
            ExerciseItem(prompt: "[baba / baba] Mahaba ang ___ ng kanyang mukha. Pakisabi sa kanya na ___ na siya sa sala.", options: ["baba...baba", "baba...taas", "taas...baba", "baba...mukha"], correctAnswer: "baba...baba", explanation: "Ang unang 'baba' ay bahagi ng mukha (chin); ang pangalawang 'baba' ay kilos ng pagbaba (descend)."),
            ExerciseItem(prompt: "[tuyo / tuyo] Masarap almusal ang ___ na isda. ___ na ang mga sinampay na damit sa labas.", options: ["tuyo...tuyo", "tuyo...basa", "basa...tuyo", "tuyo...sariwa"], correctAnswer: "tuyo...tuyo", explanation: "Ang unang 'tuyo' ay maalat na isdang pinatuyo; ang pangalawang 'tuyo' ay walang basa o dry."),
            ExerciseItem(prompt: "[kita / kita] Malaki ang ___ ng aming sari-sari store. Hindi ko ___ ang ibon sa sanga.", options: ["kita...kita", "kita...bulag", "bulag...kita", "kita...pera"], correctAnswer: "kita...kita", explanation: "Ang unang 'kita' ay kinita o sahod (income); ang pangalawang 'kita' ay nakikita (visible)."),
            ExerciseItem(prompt: "[hapon / hapon] Masarap magmeryenda tuwing ___. May panauhin kaming galing sa bansang ___.", options: ["hapon...hapon", "hapon...umaga", "umaga...hapon", "hapon...tsina"], correctAnswer: "hapon...hapon", explanation: "Ang unang 'hapon' ay oras bago sumapit ang gabi (afternoon); ang pangalawang 'hapon' ay bansa o lahing Hapones (Japan/Japanese)."),
            ExerciseItem(prompt: "[pako / pako] Ginamit ng karpintero ang ___ sa kahoy. Masarap gisingin ang halamang ___.", options: ["pako...pako", "pako...kahoy", "kahoy...pako", "pako...metal"], correctAnswer: "pako...pako", explanation: "Ang unang 'pako' ay gawa sa bakal (nail); ang pangalawang 'pako' ay nakakain na gulay (fern)."),
            ExerciseItem(prompt: "[bata / bata] Masayahin ang ___ na naglalaro ng sipa. Kaya kong ___ ang hirap ng buhay.", options: ["bata...bata", "bata...matanda", "matanda...bata", "bata...tiis"], correctAnswer: "bata...bata", explanation: "Ang unang 'bata' ay may maliit na edad (child); ang pangalawang 'bata' ay pagtitiis sa pasakit (endure)."),
            ExerciseItem(prompt: "[tubo / tubo] Gawa sa plastik ang ___ ng gripo. Matamis ang ___ na ginagawang asukal.", options: ["tubo...tubo", "tubo...ugat", "ugat...tubo", "tubo...bakal"], correctAnswer: "tubo...tubo", explanation: "Ang unang 'tubo' ay daanan ng tubig (pipe); ang pangalawang 'tubo' ay halamang sugarcane."),
            ExerciseItem(prompt: "[lata / lata] Nilagay ang sardinas sa loob ng ___. Ang ___ ng kanyang tuhod ay dahil sa pagod.", options: ["lata...lata", "lata...baso", "baso...lata", "lata...lakas"], correctAnswer: "lata...lata", explanation: "Ang unang 'lata' ay sisidlang metal (tin can); ang pangalawang 'lata' ay panghihina ng katawan (weakness).")
        ]
    )
}
