import Foundation


struct TagalogHardExercisesData {

    static let allExercises: [Exercise] = [
        exercise1,
        exercise2,
        exercise3,
        exercise4,
        exercise5,
        exercise6,
        exercise7,
        exercise8,
        easyHomonyms,
        easyAnalogies,
        easyCauseEffect,
        easyWhatsWrong,
        easySequencing,
        mediumWordAssociation,
        mediumHomonyms,
        easyCompleteSaying,
        hardCompleteSaying
    ]

    // MARK: - Exercise 1: Mga Salitang Magkapareho ang Baybay
    private static let exercise1 = Exercise(
        title: "Mga Salitang Magkapareho ang Baybay",
        instructions: "Piliin ang tamang pares ng salita na magkapareho ang baybay upang kumpletuhin ang mga pangungusap.",
        section: .language,
        type: .homonym,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "[baga / baga] Mainit pa ang mga ___ sa kalan. May sakit ang kanyang ___.", options: ["baga...baga", "baga...lungs", "lungs...baga", "baga...apoy"], correctAnswer: "baga...baga", explanation: "Ang unang 'baga' ay tumutukoy sa ningas ng apoy; ang pangalawang 'baga' ay organ sa katawan para sa paghinga (lungs)."),
            ExerciseItem(prompt: "[puno / puno] Ang ___ ng mangga ay malaki. ___ na ng tubig ang balde.", options: ["puno...puno", "puno...walang laman", "walang laman...puno", "puno...kahoy"], correctAnswer: "puno...puno", explanation: "Ang 'puno' ay maaaring tumukoy sa isang halaman (tree) o kalagayan na walang bakanteng espasyo (full)."),
            ExerciseItem(prompt: "[tuyo / tuyo] Kumain kami ng ___ na isda. ___ na ang mga sinampay sa labas.", options: ["tuyo...tuyo", "tuyo...basa", "basa...tuyo", "tuyo...sariwa"], correctAnswer: "tuyo...tuyo", explanation: "Ang unang 'tuyo' ay isang uri ng maalat na isda; ang pangalawa ay kalagayan na walang basa o halumigmig."),
            ExerciseItem(prompt: "[saya / saya] Maganda ang kanyang bagong ___. Puno ng ___ ang kanyang kaarawan.", options: ["saya...saya", "saya...lungkot", "lungkot...saya", "saya...damit"], correctAnswer: "saya...saya", explanation: "Ang unang 'saya' ay palda o damit ng babae; ang pangalawa ay kagalakan o ligaya (happiness)."),
            ExerciseItem(prompt: "[aso / aso] Tumatahol ang aming alagang ___. Makapal ang ___ na galing sa sunog.", options: ["aso...aso", "aso...pusa", "pusa...aso", "aso...singaw"], correctAnswer: "aso...aso", explanation: "Ang unang 'aso' ay hayop (dog); ang pangalawa ay usok na nagmumula sa apoy (smoke)."),
            ExerciseItem(prompt: "[suka / suka] Maasim ang ___ na gawa sa nipa. Ang ___ ng bata ay kulay dilaw.", options: ["suka...suka", "suka...dumi", "dumi...suka", "suka...asim"], correctAnswer: "suka...suka", explanation: "Ang unang 'suka' ay isang maasim na likido (vinegar); ang pangalawa ay ang iniluwa mula sa tiyan (vomit)."),
            ExerciseItem(prompt: "[bukas / bukas] ___ ang tindahan sa kanto. Babalik kami roon ___ ng umaga.", options: ["bukas...bukas", "bukas...sarado", "sarado...bukas", "bukas...ngayon"], correctAnswer: "bukas...bukas", explanation: "Ang unang 'bukas' ay nangangahulugang hindi sarado (open); ang pangalawa ay ang susunod na araw (tomorrow)."),
            ExerciseItem(prompt: "[gabi / gabi] Masarap ang nilagang ___ sa sinigang. Madilim na ang ___ nang kami ay umuwi.", options: ["gabi...gabi", "gabi...araw", "araw...gabi", "gabi...gulay"], correctAnswer: "gabi...gabi", explanation: "Ang unang 'gabi' ay isang uri ng halamang-ugat (taro); ang pangalawa ay ang bahagi ng araw pagkatapos lumubog ang araw (night)."),
            ExerciseItem(prompt: "[tubo / tubo] Gawa sa bakal ang ___ ng tubig. Matamis ang ___ na tanim sa Negros.", options: ["tubo...tubo", "tubo...ugat", "ugat...tubo", "tubo...bakal"], correctAnswer: "tubo...tubo", explanation: "Ang unang 'tubo' ay daanan ng likido (pipe); ang pangalawa ay halamang pinagkukunan ng asukal (sugarcane)."),
            ExerciseItem(prompt: "[lobo / lobo] Lumipad ang pulang ___ sa langit. Nakakatakot ang ungol ng ___ sa gubat.", options: ["lobo...lobo", "lobo...aso", "aso...lobo", "lobo...laruan"], correctAnswer: "lobo...lobo", explanation: "Ang unang 'lobo' ay laruang hinihipan ng hangin (balloon); ang pangalawa ay isang uri ng mabangis na hayop (wolf)."),
            ExerciseItem(prompt: "[pako / pako] Ginamit niya ang ___ sa paggawa ng upuan. Masarap igisa ang halamang ___.", options: ["pako...pako", "pako...kahoy", "kahoy...pako", "pako...metal"], correctAnswer: "pako...pako", explanation: "Ang unang 'pako' ay metal na ginagamit sa pagpupukpok (nail); ang pangalawa ay isang uri ng nakakain na halaman (fern)."),
            ExerciseItem(prompt: "[baba / baba] Mahaba ang ___ ng kanyang mukha. Pakisabi sa kanya na ___ na siya rito.", options: ["baba...baba", "baba...taas", "taas...baba", "baba...mukha"], correctAnswer: "baba...baba", explanation: "Ang unang 'baba' ay bahagi ng mukha sa ilalim ng bibig (chin); ang pangalawa ay kilos ng pagbaba (descend)."),
            ExerciseItem(prompt: "[kita / kita] Malaki ang ___ ng kanyang tindahan. Hindi ko ___ ang nakasulat sa pisara.", options: ["kita...kita", "kita...bulag", "bulag...kita", "kita...pera"], correctAnswer: "kita...kita", explanation: "Ang unang 'kita' ay ang perang kinita (income); ang pangalawa ay kakayahang makakita (visible)."),
            ExerciseItem(prompt: "[hapon / hapon] Natutulog siya tuwing ___. May bisita kaming galing sa bansa ng ___.", options: ["hapon...hapon", "hapon...umaga", "umaga...hapon", "hapon...tsina"], correctAnswer: "hapon...hapon", explanation: "Ang unang 'hapon' ay bahagi ng araw bago gabi (afternoon); ang pangalawa ay bansang Hapon (Japan/Japanese)."),
            ExerciseItem(prompt: "[bata / bata] Masayahin ang ___ na naglalaro. Dapat nating ___ ang hirap para sa pamilya.", options: ["bata...bata", "bata...matanda", "matanda...bata", "bata...tiis"], correctAnswer: "bata...bata", explanation: "Ang unang 'bata' ay taong maliit pa ang edad (child); ang pangalawa ay pagtitiis sa hirap o pasakit (endure).")
        ]
    )

    // MARK: - Exercise 2: Mga Analohiya
    private static let exercise2 = Exercise(
        title: "Mga Analohiya",
        instructions: "Piliin ang salita na pinakamahusay na kumukumpleto sa analohiya.",
        section: .language,
        type: .analogyChoice,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "SOLILOQUY ay sa AKTOR gaya ng SERMON ay sa ___", options: ["Pari", "Miyembro", "Koro", "Simbahan"], correctAnswer: "Pari", explanation: "Ang soliloquy ay sinasalita ng aktor, habang ang sermon naman ay binibigkas ng pari o pastor."),
            ExerciseItem(prompt: "PAHINA ay sa AKLAT gaya ng PIPINDUTIN ay sa ___", options: ["Pyano", "Musika", "Tunog", "Papel"], correctAnswer: "Pyano", explanation: "Ang pahina ay bahagi ng aklat, habang ang pipindutin o key ay bahagi ng pyano."),
            ExerciseItem(prompt: "PALAD ay sa TAO gaya ng PALAPAK ay sa ___", options: ["Manok", "Palaka", "Balahibo", "Tubig"], correctAnswer: "Manok", explanation: "Ang tao ay may palad, habang ang manok o ibon naman ay may palapak o paa na may sapot (webbed foot/foot structure)."),
            ExerciseItem(prompt: "PUSO ay sa TIBOK gaya ng BAGA ay sa ___", options: ["Paghinga", "Dugo", "Oksiheno", "Ugat"], correctAnswer: "Paghinga", explanation: "Ang puso ang gumagawa ng tibok, habang ang baga naman ang gumagawa ng paghinga."),
            ExerciseItem(prompt: "TIMON ay sa BARKO gaya ng MANIBELA ay sa ___", options: ["Kotse", "Kalsada", "Hangin", "Gulong"], correctAnswer: "Kotse", explanation: "Ang timon ang nagpapatakbo sa direksyon ng barko, habang ang manibela naman ang sa kotse."),
            ExerciseItem(prompt: "GINTO ay sa ALAHAS gaya ng KAHOY ay sa ___", options: ["Muwebles", "Gubat", "Puno", "Uling"], correctAnswer: "Muwebles", explanation: "Ang ginto ang ginagamit na materyales sa alahas, habang ang kahoy naman ay sa muwebles."),
            ExerciseItem(prompt: "ESTETOSKOP ay sa DOKTOR gaya ng TELESKOP ay sa ___", options: ["Astronomo", "Aklat", "Kompyuter", "Mapa"], correctAnswer: "Astronomo", explanation: "Ang estetoskop ang gamit ng doktor, habang ang teleskop naman ang gamit ng astronomo."),
            ExerciseItem(prompt: "GABI ay sa BUWAN gaya ng ARAW ay sa ___", options: ["Araw", "Bituin", "Ulap", "Hanging-amihan"], correctAnswer: "Araw", explanation: "Ang buwan ang nakikita sa gabi, habang ang araw naman ang nakikita sa umaga o tanghali (sun)."),
            ExerciseItem(prompt: "Pukyutan ay sa BAHAY-PUKYUTAN gaya ng GAGAMBA ay sa ___", options: ["Sapot", "Kuweba", "Lawa", "Puno"], correctAnswer: "Sapot", explanation: "Ang pukyutan ang gumagawa ng bahay-pukyutan, habang ang gagamba naman ang gumagawa ng sapot."),
            ExerciseItem(prompt: "MATA ay sa PANINGIN gaya ng TAINGA ay sa ___", options: ["Pandinig", "Tunog", "Musika", "Alingawngaw"], correctAnswer: "Pandinig", explanation: "Ang mata ang organ para sa paningin, habang ang tainga naman ang para sa pandinig."),
            ExerciseItem(prompt: "BAKAL ay sa PANDAY gaya ng PUTIK ay sa ___", options: ["Magsasayaw", "Magpapalayok", "Mananahi", "Magsasaka"], correctAnswer: "Magpapalayok", explanation: "Ang panday ang naghuhulma ng bakal, habang ang magpapalayok o potmaker naman ang naghuhulma ng putik/luwad."),
            ExerciseItem(prompt: "DAHON ay sa PUNO gaya ng PETALO ay sa ___", options: ["Bulaklak", "Tini", "Bunga", "Ugat"], correctAnswer: "Bulaklak", explanation: "Ang dahon ay bahagi ng puno, habang ang petalo naman ay bahagi ng bulaklak."),
            ExerciseItem(prompt: "PUTI ay sa ITIM gaya ng TAAS ay sa ___", options: ["Baba", "Kanan", "Kaliwa", "Loob"], correctAnswer: "Baba", explanation: "Ang puti at itim ay magkasalungat, gaya rin ng taas at baba."),
            ExerciseItem(prompt: "TERMOMETRO ay sa TEMPERATURA gaya ng BAROMETRO ay sa ___", options: ["Presyon ng hangin", "Oras", "Distansya", "Taas"], correctAnswer: "Presyon ng hangin", explanation: "Ang termometro ang sumusukat sa temperatura, habang ang barometro naman ay sa presyon ng hangin."),
            ExerciseItem(prompt: "LOTUS ay sa LAWA gaya ng ROSAS ay sa ___", options: ["Tini", "Bango", "Pula", "Petalo"], correctAnswer: "Tini", explanation: "Ang lotus ay tumutubo sa lawa o putikan, habang ang rosas naman ay tumutubo sa may mga tini (thorns).")
        ]
    )

    // MARK: - Exercise 3: Asosasyon ng mga Salita
    private static let exercise3 = Exercise(
        title: "Asosasyon ng mga Salita",
        instructions: "Piliin ang salita na may pinakamalapit na ugnayan sa ibinigay na salita.",
        section: .language,
        type: .multipleChoice,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "ALTRUISMO", options: ["Pagkakawanggawa", "Kaguluhan", "Galit", "Inggit"], correctAnswer: "Pagkakawanggawa", explanation: "Ang altruismo ay ang walang pag-iimbot na pagtulong o pagkakawanggawa sa iba."),
            ExerciseItem(prompt: "PASKO", options: ["Simbang Gabi", "Bibingka", "Kuneho", "Kabaong"], correctAnswer: "Simbang Gabi", explanation: "Ang Simbang Gabi ay isa sa pinakasikat na tradisyong Pilipino tuwing panahon ng Pasko."),
            ExerciseItem(prompt: "ADOBO", options: ["Toyo at Suka", "Gatas", "Keso", "Asukal"], correctAnswer: "Toyo at Suka", explanation: "Ang toyo at suka ang mga pangunahing sangkap sa pagluluto ng adobo."),
            ExerciseItem(prompt: "JEEPNEY", options: ["Hari ng Kalsada", "Dagat", "Eroplano", "Tren"], correctAnswer: "Hari ng Kalsada", explanation: "Ang jeepney ay kilala bilang 'Hari ng Kalsada' sa Pilipinas."),
            ExerciseItem(prompt: "BARONG TAGALOG", options: ["Pinya", "Seda", "Bulak", "Katad"], correctAnswer: "Pinya", explanation: "Ang tradisyonal na Barong Tagalog ay karaniwang hinahabi mula sa hibla ng pinya (piña cloth)."),
            ExerciseItem(prompt: "SAMPAGUITA", options: ["Pambansang Bulaklak", "Rosas", "Orkid", "Sunflower"], correctAnswer: "Pambansang Bulaklak", explanation: "Ang Sampaguita ang pambansang bulaklak ng Pilipinas."),
            ExerciseItem(prompt: "BALUT", options: ["Itlog ng Pato", "Manok", "Isda", "Baboy"], correctAnswer: "Itlog ng Pato", explanation: "Ang balut ay nilagang itlog ng pato na may nabubuong sisiw sa loob."),
            ExerciseItem(prompt: "BAYANIHAN", options: ["Pagtutulungan", "Kumpetisyon", "Away", "Sarili"], correctAnswer: "Pagtutulungan", explanation: "Ang bayanihan ay nagpapakita ng sama-samang pagtutulungan ng pamayanan nang walang hinihintay na kapalit."),
            ExerciseItem(prompt: "BARYA", options: ["Alkansya", "Bulsa", "Bag", "Kaha"], correctAnswer: "Alkansya", explanation: "Karaniwang iniipon ang mga barya sa loob ng alkansya."),
            ExerciseItem(prompt: "SINEGUElas", options: ["Tag-araw", "Tag-ulan", "Taglamig", "Bagyo"], correctAnswer: "Tag-araw", explanation: "Ang sineguelas ay isang prutas na sumisibol at sikat tuwing panahon ng tag-araw."),
            ExerciseItem(prompt: "LECHON", options: ["Mang Tomas", "Ketchup", "Toyo", "Suka"], correctAnswer: "Mang Tomas", explanation: "Ang sarsa ng Mang Tomas ang pinakasikat na kapareha ng lechon sa handaan."),
            ExerciseItem(prompt: "SINIGANG", options: ["Sampalok", "Mangga", "Kalamansi", "Kamias"], correctAnswer: "Sampalok", explanation: "Ang sampalok ang tradisyonal na pampaasim na ginagamit sa lutong sinigang."),
            ExerciseItem(prompt: "TINIKLING", options: ["Kawayan", "Tambo", "Kahoy", "Bakal"], correctAnswer: "Kawayan", explanation: "Ang tinikling ay sayaw na gumagamit ng dalawang mahahabang kawayan na pinupukpok sa sahig."),
            ExerciseItem(prompt: "KARIHAN", options: ["Turo-turo", "Restawran", "Hotel", "Kalsada"], correctAnswer: "Turo-turo", explanation: "Ang karihan o karinderya ay kilala rin sa tawag na turo-turo."),
            ExerciseItem(prompt: "MAYON", options: ["AlbAy", "Laguna", "Batangas", "Davao"], correctAnswer: "AlbAy", explanation: "Ang Bulkang Mayon na may perpektong hugis-kono ay matatagpuan sa Albay.")
        ]
    )

    // MARK: - Exercise 4: Pagsasanay sa Pagkumpleto ng Pangungusap
    private static let exercise4 = Exercise(
        title: "Pagsasanay sa Pagkumpleto ng Pangungusap",
        instructions: "Piliin ang pinakaangkop na salita upang kumpletuhin ang pangungusap.",
        section: .language,
        type: .sentenceCompletion,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "Nakatulong ang malakas na ulan upang ___ ang matinding tuyot sa lalawigan.", options: ["maibsan", "palalain", "panatilihin", "patagalin"], correctAnswer: "maibsan", explanation: "Ang ulan ay nagbibigay ng tubig na nakababawas o nakagagaan (nakapagpapaiibsan) sa tuyot o tagtuyot."),
            ExerciseItem(prompt: "Ang talumpati ng pangulo ay napaka-lohikal kaya ito ay nakakuha ng malawakang ___.", options: ["pagtanggap", "pagtatakwil", "pagdududa", "kalamigan"], correctAnswer: "pagtanggap", explanation: "Ang maayos at lohikal na talumpati ay karaniwang tinatanggap ng publiko nang may lugod."),
            ExerciseItem(prompt: "Sa kabila ng maraming pagsubok sa buhay, pinanatili niya ang isang ___ na espiritu.", options: ["matatag", "mahina", "takot", "nag-aalinlangan"], correctAnswer: "matatag", explanation: "Ang matatag na espiritu o kalooban ay nagpapakita ng hindi pagsuko sa mga pagsubok."),
            ExerciseItem(prompt: "Ang pinturang ito ay may napaka-harmonyang kulay at mahusay na tekniko, kaya ito ay isang ___.", options: ["obra-maestra", "masamang gawa", "simpleng kopya", "karaniwang guhit"], correctAnswer: "obra-maestra", explanation: "Ang isang napakahusay at natatanging likhang-sining ay tinatawag na obra-maestra."),
            ExerciseItem(prompt: "Sa pamamagitan ng pag-aaral sa mga lumang banga, muling ___ ng mga arkeologo ang kasaysayan.", options: ["nabuo", "nasira", "naitago", "nalimutan"], correctAnswer: "nabuo", explanation: "Ang pananaliksik sa mga sinaunang bagay ay tumutulong upang muling mabuo ang kasaysayan."),
            ExerciseItem(prompt: "Ang paggamit ng mga recycled na materyales ay nakatutulong sa mga industriya upang ___ ang gastos.", options: ["pababain", "pataasin", "panatilihin", "balewalain"], correctAnswer: "pababain", explanation: "Ang pag-recycled ay nakababawas o nakapagpapababa sa kabuuang gastos sa produksyon."),
            ExerciseItem(prompt: "Dahil sa maling desisyon ng pamunuan, ang kumpanya ay naharap sa matinding ___ sa pananalapi.", options: ["krisis", "kaunlaran", "paglago", "katatagan"], correctAnswer: "krisis", explanation: "Ang maling pamamahala ay maaaring magdulot ng krisis o matinding kakulangan sa pera."),
            ExerciseItem(prompt: "Ang panitikan ng manunulat na iyon ay kilala sa matalas na pagtuligsa sa mga ___ ng lipunan.", options: ["sakit", "tagumpay", "batas", "kabutihan"], correctAnswer: "sakit", explanation: "Ang mapanuring panitikan ay karaniwang naglalantad sa mga sakit o negatibong aspeto ng lipunan."),
            ExerciseItem(prompt: "Upang maibsan ang trapiko sa sentro ng lungsod, nagtayo ang pamahalaan ng daang ___.", options: ["pabilog", "sarado", "makipot", "pansamantala"], correctAnswer: "pabilog", explanation: "Ang daang pabilog o diversion road (bypass road) ay naglalayo ng trapiko sa sentro ng lungsod."),
            ExerciseItem(prompt: "Ang mga resulta ng pananaliksik na ito ay nagdulot ng ___ na tugon sa buong mundo.", options: ["malawak", "limitado", "negatibo", "panandalian"], correctAnswer: "malawak", explanation: "Ang mahahalagang pagtuklas ay nagdudulot ng malawak at positibong talakayan sa buong mundo."),
            ExerciseItem(prompt: "Nagkasundo ang dalawang kumpanya sa isang kasunduan sa ___ para sa parehong pakinabang.", options: ["pagtutulungan", "kumpetisyon", "pagsasanib", "pagtatalo"], correctAnswer: "pagtutulungan", explanation: "Ang kasunduan batay sa parehong pakinabang ay kasunduan sa pagtutulungan (partnership/cooperation)."),
            ExerciseItem(prompt: "Ang dokumentaryong ito ay nagpakita sa isang ___ na paraan ng buhay ng mga migratory bird.", options: ["makatotohanan", "kathang-isip", "nakasisira", "pinaganda"], correctAnswer: "makatotohanan", explanation: "Ang mga dokumentaryo ay nagpapakita ng buhay ng mga hayop sa makatotohanang paraan."),
            ExerciseItem(prompt: "Matapos ang ilang oras na pagsasaayos, ang linya ng komunikasyon ay bumalik na sa ___ na operasyon.", options: ["normal", "huli", "putol-putol", "blokeado"], correctAnswer: "normal", explanation: "Ang pagkumpuni ay nagbabalik sa linya sa normal o maayos na kalagayan."),
            ExerciseItem(prompt: "Ang Simbahan ng San Agustin ay isang makasaysayang gusali at itinuturing na ___ ng kulturang Pilipino.", options: ["simbolo", "dahilan", "kahinaan", "pabigat"], correctAnswer: "simbolo", explanation: "Ang mga makasaysayang istruktura ay nagsisilbing simbolo ng kultura at kasaysayan ng bansa."),
            ExerciseItem(prompt: "Siya ay napakahigpit sa kanyang trabaho at hindi tumatanggap ng anumang uri ng ___.", options: ["kapabayaan", "disiplina", "tiyaga", "pag-iingat"], correctAnswer: "kapabayaan", explanation: "Ang taong disiplinado at maayos magtrabaho ay hindi pinapayagan ang kapabayaan o kawalan ng kaayusan.")
        ]
    )

    // MARK: - Exercise 5: Pagkakasunod-sunod ng mga Hakbang
    private static let exercise5 = Exercise(
        title: "Pagkakasunod-sunod ng mga Hakbang",
        instructions: "Ayusin ang mga hakbang ng aktibidad sa isang lohikal na pagkakasunod-sunod.",
        section: .language,
        type: .sequencing,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "Paggawa ng kape gamit ang filter", options: ["Initin ang tubig ngunit huwag hayaang kumulo nang husto", "Ilagay ang giniling na kape sa salaan na may papel na filter", "Ibuhos ang mainit na tubig nang pabilog sa ibabaw ng kape", "Lagyan ng asukal o gatas at ihain sa tasa"], correctAnswer: "Initin ang tubig ngunit huwag hayaang kumulo nang husto | Ilagay ang giniling na kape sa salaan na may papel na filter | Ibuhos ang mainit na tubig nang pabilog sa ibabaw ng kape | Lagyan ng asukal o gatas at ihain sa tasa", explanation: "Paggawa ng kape: painitin ang tubig, ilagay ang kape sa filter, ibuhos ang tubig, at lagyan ng lasa bago ihain."),
            ExerciseItem(prompt: "Pagluluto ng adobo", options: ["I-marinate ang karne sa toyo, bawang, at paminta", "Igisa ang bawang at karne hanggang sa pumula", "Idagdag ang suka at hayaang kumulo nang hindi hinahalo", "Dagdagan ng kaunting tubig at hayaang lumapot ang sarsa"], correctAnswer: "I-marinate ang karne sa toyo, bawang, at paminta | Igisa ang bawang at karne hanggang sa pumula | Idagdag ang suka at hayaang kumulo nang hindi hinahalo | Dagdagan ng kaunting tubig at hayaang lumapot ang sarsa", explanation: "Pagluluto ng adobo: i-marinate, igisa ang karne, idagdag ang suka nang walang halo, at pakuluin hanggang lumapot ang sarsa."),
            ExerciseItem(prompt: "Pagtatapon ng basura sa tama", options: ["Ipunin ang mga basura sa loob ng bahay", "Ibukod ang nabubulok sa hindi nabubulok", "Ilagay ang mga ito sa kaukulang basurahan sa labas", "Hintayin ang trak ng basura para sa koleksyon"], correctAnswer: "Ipunin ang mga basura sa loob ng bahay | Ibukod ang nabubulok sa hindi nabubulok | Ilagay ang mga ito sa kaukulang basurahan sa labas | Hintayin ang trak ng basura para sa koleksyon", explanation: "Pagtatapon ng basura: ipunin, ibukod ang uri, ilabas sa tamang lalagyan, at ipasa sa kolektor."),
            ExerciseItem(prompt: "Wastong paghuhugas ng kamay", options: ["Basain ang mga kamay ng malinis na tubig", "Sabunin at kuskusin ang mga palad at daliri", "Banlawan ang sabon gamit ang tumutulong tubig", "Patuyuin ang kamay gamit ang malinis na tuwalya"], correctAnswer: "Basain ang mga kamay ng malinis na tubig | Sabunin at kuskusin ang mga palad at daliri | Banlawan ang sabon gamit ang tumutulong tubig | Patuyuin ang kamay gamit ang malinis na tuwalya", explanation: "Paghuhugas ng kamay: basain ang kamay, sabunin at kuskusin, banlawan, at patuyuin sa tuwalya."),
            ExerciseItem(prompt: "Pagsasaing ng kanin", options: ["Sukatin ang bigas at hugasan ito ng tubig", "Lagyan ng tamang dami ng tubig ang kaldero", "Punasan ang ilalim ng kaldero at isalang sa kalan", "Hintaying kumulo at matuyo ang tubig bago hinaan ang apoy"], correctAnswer: "Sukatin ang bigas at hugasan ito ng tubig | Lagyan ng tamang dami ng tubig ang kaldero | Punasan ang ilalim ng kaldero at isalang sa kalan | Hintaying kumulo at matuyo ang tubig bago hinaan ang apoy", explanation: "Pagsasaing: hugasan ang bigas, lagyan ng tubig, punasan ang ilalim ng kaldero at isalang, patuyuin sa mahinang apoy."),
            ExerciseItem(prompt: "Pamimili sa supermarket", options: ["Gumawa ng listahan ng mga bibilhin", "Kumuha ng cart at pumili ng mga produkto", "Pumila sa cashier at magbayad", "Ibalot ang mga binili at iuwi sa bahay"], correctAnswer: "Gumawa ng listahan ng mga bibilhin | Kumuha ng cart at pumili ng mga produkto | Pumila sa cashier at magbayad | Ibalot ang mga binili at iuwi sa bahay", explanation: "Pamimili: listahan, pumili sa cart, magbayad sa cashier, ibalot at iuwi."),
            ExerciseItem(prompt: "Pagbabayad ng kuryente online", options: ["Buksan ang mobile banking o e-wallet app", "Ilagay ang account number ng kuryente", "Suriin ang kabuuang halaga ng bill", "Ilagay ang OTP o PIN upang kumpirmahin"], correctAnswer: "Buksan ang mobile banking o e-wallet app | Ilagay ang account number ng kuryente | Suriin ang kabuuang halaga ng bill | Ilagay ang OTP o PIN upang kumpirmahin", explanation: "Pagbabayad: buksan ang app, ilagay ang account number, suriin ang bill, at kumpirmahin gamit ang PIN."),
            ExerciseItem(prompt: "Paglilinis ng kuwarto", options: ["Iligpit ang mga kalat at ibalik sa tamang lagayan", "Punasan ang alikabok sa mga lamesa at estante", "Walisin ang sahig gamit ang tingting o vacuum", "Lampasuhan o i-mop ang sahig gamit ang basang basahan"], correctAnswer: "Iligpit ang mga kalat at ibalik sa tamang lagayan | Punasan ang alikabok sa mga lamesa at estante | Walisin ang sahig gamit ang tingting o vacuum | Lampasuhan o i-mop ang sahig gamit ang basang basahan", explanation: "Paglilinis: iligpit ang kalat, punasan ang alikabok, walisin ang sahig, at lampasuhan."),
            ExerciseItem(prompt: "Pagpapadala ng package sa courier", options: ["Ibalot nang maayos ang ipapadala sa karton", "Isulat ang address ng sender at receiver sa kahon", "Dalhin sa sangay upang timbangin at kwentahin", "Bayaran ang shipping fee at kuhanin ang resibo"], correctAnswer: "Ibalot nang maayos ang ipapadala sa karton | Isulat ang address ng sender at receiver sa kahon | Dalhin sa sangay upang timbangin at kwentahin | Bayaran ang shipping fee at kuhanin ang resibo", explanation: "Pagpapadala: ibalot, isulat ang address, ipatimbang sa courier, bayaran at kuhanin ang resibo."),
            ExerciseItem(prompt: "Paggawa ng sunny-side up egg", options: ["Buksan ang kalan at maglagay ng mantika sa kawali", "Basagin ang itlog at dahan-dahang ilagay sa mainit na mantika", "Budburan ng kaunting asin at paminta", "Hanguin ang itlog gamit ang spatula at ilagay sa pinggan"], correctAnswer: "Buksan ang kalan at maglagay ng mantika sa kawali | Basagin ang itlog at dahan-dahang ilagay sa mainit na mantika | Budburan ng kaunting asin at paminta | Hanguin ang itlog gamit ang spatula at ilagay sa pinggan", explanation: "Sunny-side up: painitin ang mantika, basagin ang itlog sa kawali, lagyan ng asin/paminta, hanguin gamit ang spatula."),
            ExerciseItem(prompt: "Paghango ng pera sa ATM", options: ["Ipasok ang bank card at i-type ang PIN code", "Piliin ang Withdrawal at ilagay ang halaga", "Kunin ang pera at bilangin ito nang maayos", "Kunin ang card at itago ito sa pitaka"], correctAnswer: "Ipasok ang bank card at i-type ang PIN code | Piliin ang Withdrawal at ilagay ang halaga | Kunin ang pera at bilangin ito nang maayos | Kunin ang card at itago ito sa pitaka", explanation: "ATM: ipasok ang card at PIN, ilagay ang halaga ng withdrawal, kunin at bilangin ang pera, kunin ang card."),
            ExerciseItem(prompt: "Paglaba gamit ang washing machine", options: ["Ihiwalay ang mga damit ayon sa kulay at ilagay sa loob", "Maglagay ng sabong panlaba at softener sa lalagyan", "Piliin ang angkop na cycle at pindutin ang Start", "Isabit ang mga nilabhan sa sampayan upang matuyo"], correctAnswer: "Ihiwalay ang mga damit ayon sa kulay at ilagay sa loob | Maglagay ng sabong panlaba at softener sa lalagyan | Piliin ang angkop na cycle at pindutin ang Start | Isabit ang mga nilabhan sa sampayan upang matuyo", explanation: "Paglaba: ihiwalay ang damit sa loob, lagyan ng sabon, pindutin ang start, isabit sa sampayan."),
            ExerciseItem(prompt: "Pagpapatingin sa doktor sa ospital", options: ["Pumunta sa reception at kumuha ng queue number", "Makipagkita sa doktor upang magpaliwanag ng sakit", "Magbayad sa cashier at kuhanin ang reseta", "Dalhin ang reseta sa botika upang makuha ang gamot"], correctAnswer: "Pumunta sa reception at kumuha ng queue number | Makipagkita sa doktor upang magpaliwanag ng sakit | Magbayad sa cashier at kuhanin ang reseta | Dalhin ang reseta sa botika upang makuha ang gamot", explanation: "Pagpapatingin: queue sa reception, magpatingin sa doktor, magbayad sa cashier, kunin ang gamot sa botika."),
            ExerciseItem(prompt: "Pag-inom ng gamot", options: ["Suriin ang expiration date sa kahon ng gamot", "Kuhanin ang tamang dosis ng tabletas sa lalagyan", "Inumin ang gamot kasabay ng isang basong maligamgam na tubig", "Ibalik ang kahon ng gamot sa ligtas na taguan"], correctAnswer: "Suriin ang expiration date sa kahon ng gamot | Kuhanin ang tamang dosis ng tabletas sa lalagyan | Inumin ang gamot kasabay ng isang basong maligamgam na tubig | Ibalik ang kahon ng gamot sa ligtas na taguan", explanation: "Pag-inom ng gamot: suriin ang expiration, kuhanin ang tamang dosis, inumin kasabay ng tubig, ibalik sa taguan."),
            ExerciseItem(prompt: "Pag-charge ng cellphone", options: ["Hanapin ang charger at saksakan sa silid", "Isaksak ang charger sa saksakan sa dingding", "Ikonekta ang dulo ng cord sa saksakan ng cellphone", "Kapag puno na ang baterya, tanggalin ang cord sa cellphone"], correctAnswer: "Hanapin ang charger at saksakan sa silid | Isaksak ang charger sa saksakan sa dingding | Ikonekta ang dulo ng cord sa saksakan ng cellphone | Kapag puno na ang baterya, tanggalin ang cord sa cellphone", explanation: "Pag-charge: hanapin ang charger, isaksak sa dingding, ikonekta sa cellphone, tanggalin kapag puno na.")
        ]
    )

    // MARK: - Exercise 6: Pagsusuri ng Sanhi at Bunga
    private static let exercise6 = Exercise(
        title: "Pagsusuri ng Sanhi at Bunga",
        instructions: "Piliin ang pinaka-lohikal na sanhi o bunga para sa ibinigay na sitwasyon.",
        section: .cognition,
        type: .multipleChoice,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "Sanhi: Umabot sa higit 43 degrees Celsius ang temperatura nitong tag-araw.", options: ["Tumaas nang malaki ang konsumo sa kuryente dahil sa aircon", "Dumami ang mga taong namamasyal sa labas ng kalsada", "Tumaas ang benta ng makakapal na jacket sa mga tindahan", "Nag-anunsyo ang mga planta na bumaba ang konsumo sa kuryente"], correctAnswer: "Tumaas nang malaki ang konsumo sa kuryente dahil sa aircon", explanation: "Ang matinding init ay nagiging dahilan ng madalas na paggamit ng aircon, na nagpapataas sa konsumo ng kuryente."),
            ExerciseItem(prompt: "Sanhi: Binalewala ng drayber ang pulang ilaw at humarurot sa interseksyon.", options: ["Pinara siya ng pulis-trapiko at binigyan ng malaking multa", "Nakatanggap siya ng parangal bilang huwarang drayber", "Kusa at mabilis na tumabi ang ibang mga sasakyan", "Agad na nag-berde ang ilaw nang lumapit ang kanyang sasakyan"], correctAnswer: "Pinara siya ng pulis-trapiko at binigyan ng malaking multa", explanation: "Ang paglabag sa batas trapiko tulad ng paghabol sa pulang ilaw ay may katapat na multa at huli."),
            ExerciseItem(prompt: "Sanhi: Nabara ang drainage system ng lungsod dahil sa mga basura.", options: ["Bumaha nang malalim sa mga kalsada matapos ang malakas na ulan", "Mabilis at ligtas na umagos ang tubig-ulan patungo sa ilog", "Nanatiling tuyo at malinis ang mga kalsada sa buong lungsod", "Biglang tumaas ang presyo ng bottled mineral water sa merkado"], correctAnswer: "Bumaha nang malalim sa mga kalsada matapos ang malakas na ulan", explanation: "Ang baradong drainage ay nagdudulot ng pagkaantala ng daloy ng tubig-ulan na sanhi ng pagbaha."),
            ExerciseItem(prompt: "Bunga: Sobrang saya ni Juan at nagdiwang kasama ang pamilya matapos ang pagsusulit.", options: ["Sanhi: Nakakuha siya ng pinakamataas na marka sa board exam", "Sanhi: Hindi siya nakapagsulit dahil sa matinding sakit", "Sanhi: Iniwan niyang walang sagot ang kanyang sagutang papel", "Sanhi: Nag-anunsyo ang gobyerno na ipagpaliban ang pagsusulit"], correctAnswer: "Sanhi: Nakakuha siya ng pinakamataas na marka sa board exam", explanation: "Ang pagpasa nang may mataas na marka ang lohikal na dahilan ng kanyang labis na kagalakan."),
            ExerciseItem(prompt: "Bunga: Naging masagana ang ani ng mga magsasaka at tumaas ang kanilang kita.", options: ["Sanhi: Tamang-tama ang dami ng ulan at sikat ng araw ngayong taon", "Sanhi: Nagkaroon ng matinding tagtuyot sa buong lalawigan", "Sanhi: Gumamit ang mga magsasaka ng pekeng abono sa kanilang taniman", "Sanhi: Sinira ng mga ligaw na baboy-ramo ang malaking bahagi ng taniman"], correctAnswer: "Sanhi: Tamang-tama ang dami ng ulan at sikat ng araw ngayong taon", explanation: "Ang magandang panahon at sapat na ulan ay nagdudulot ng masaganang ani para sa mga pananim."),
            ExerciseItem(prompt: "Sanhi: Nagpuyat ang mga mag-aaral kagabi para magrebyu para sa pagsusulit.", options: ["Nahirapan silang gumising sa umaga dahil sa antok at pagod", "Maaga silang nagising na puno ng lakas at sigla", "Biglang ipinagpaliban ng paaralan ang pagsusulit sa araw na iyon", "Naging napakatalas at alerto ng kanilang isip sa oras ng pagsusulit"], correctAnswer: "Nahirapan silang gumising sa umaga dahil sa antok at pagod", explanation: "Ang puyat o kakulangan sa tulog ay nagdudulot ng labis na pagod at antok sa kinabukasan."),
            ExerciseItem(prompt: "Sanhi: Tumaas nang husto ang suplay ng sibuyas sa pamilihan.", options: ["Bumaba nang malaki ang presyo ng sibuyas sa palengke", "Wala nang makabili ng sibuyas sa lokal na tindahan", "Umakyat sa pinakamataas na tala ang presyo ng sibuyas", "Biglang tumaas ang presyo ng patatas kasabay ng suplay"], correctAnswer: "Bumaba nang malaki ang presyo ng sibuyas sa palengke", explanation: "Kapag marami ang suplay ng isang produkto tulad ng gulay, bumababa ang presyo nito sa merkado."),
            ExerciseItem(prompt: "Bunga: Nawalan ng kuryente ang buong subdibisyon at huminto ang mga elevator.", options: ["Sanhi: Sumabog ang pangunahing transformer ng kuryente sa lugar", "Sanhi: Tanghaling tapat at tirik na tirik ang sikat ng araw", "Sanhi: Gumamit ang mga residente ng LED bulb sa kanilang bahay", "Sanhi: Libre na ang monthly maintenance fee ng condo para sa buwan"], correctAnswer: "Sanhi: Sumabog ang pangunahing transformer ng kuryente sa lugar", explanation: "Ang pagkasira ng pangunahing transformer ang nagiging sanhi ng malawakang blackout sa isang komunidad."),
            ExerciseItem(prompt: "Sanhi: Nag-ehersisyo at nag-jogging araw-araw si Mang Pedro pagkatapos magretiro.", options: ["Bumuti nang husto ang kanyang pisikal at mental na kalusugan", "Naging mahina ang kanyang katawan at madaling magkasakit", "Biglang tumaas ng dalawampung kilo ang kanyang timbang sa isang buwan", "Nawalan siya ng kakayahang matulog nang maayos sa gabi"], correctAnswer: "Bumuti nang husto ang kanyang pisikal at mental na kalusugan", explanation: "Ang regular na ehersisyo ay nakatutulong upang mapabuti ang pangkalahatang kalusugan ng isang tao."),
            ExerciseItem(prompt: "Sanhi: Ipinatupad ng pamahalaan ang batas na nagbabawal sa single-use plastic bag.", options: ["Nasanay ang mga tao na magdala ng eco-bag at canvass bag sa pamimili", "Dumami ang mga basurang plastic sa mga kalsada at kanal", "Doble ang ginawang produksyon ng mga pabrika ng plastic bag", "Nagbigay ang mga tindera ng libreng plastic bag sa mga mamimili"], correctAnswer: "Nasanay ang mga tao na magdala ng eco-bag at canvass bag sa pamimili", explanation: "Ang plastic ban ay naghihikayat sa mga mamimili na gumamit ng mas eco-friendly na alternatibo tulad ng canvass bag."),
            ExerciseItem(prompt: "Bunga: Napanis at umasim ang sariwang gatas matapos iwan sa mesa ng isang araw.", options: ["Sanhi: Hindi ito inilagay sa refrigerator sa gitna ng mainit na panahon", "Sanhi: Maayos itong itinago sa loob ng refrigerator sa tamang lamig", "Sanhi: Naglagay ng isang kutsarang puting asukal sa baso ng gatas", "Sanhi: Bagong piga ang gatas mula sa farm kaninang umaga"], correctAnswer: "Sanhi: Hindi ito inilagay sa refrigerator sa gitna ng mainit na panahon", explanation: "Ang gatas ay madaling mapanis kapag naiwan sa mainit na temperatura ng kuwarto."),
            ExerciseItem(prompt: "Sanhi: Sinira ng malakas na bagyo ang mga taniman ng palay sa Gitnang Luzon.", options: ["Tumaas nang malaki ang presyo ng bigas sa mga pamilihan", "Sumobra ang suplay ng bigas kaya napilitang ibaba ang presyo", "Tumaas ang produksyon at kumita ang mga gilingan ng palay", "Tumigil sa pagbili ng bigas ang mga tao at puro instant noodles na lang"], correctAnswer: "Tumaas nang malaki ang presyo ng bigas sa mga pamilihan", explanation: "Ang pagkasira ng mga pananim ay nagdudulot ng kakulangan sa suplay ng bigas, na nagreresulta sa pagtaas ng presyo."),
            ExerciseItem(prompt: "Bunga: Biglang namatay ang screen ng cellphone at hindi na ito bumukas.", options: ["Sanhi: Nanood ng high-definition video ang gumagamit nang hindi naka-charge", "Sanhi: Naka-konekta ang cellphone sa charger sa buong gabi", "Sanhi: Naka-patay ang cellphone at nakatago sa loob ng drawer", "Sanhi: Sinara ng gumagamit ang mga background app at naka-battery saver"], correctAnswer: "Sanhi: Nanood ng high-definition video ang gumagamit nang hindi naka-charge", explanation: "Ang panonood ng HD video ay mabilis na nag-aalis ng charge sa baterya ng cellphone."),
            ExerciseItem(prompt: "Sanhi: Nahuli ng proctor ang mag-aaral na naghahanap ng sagot gamit ang kodigo.", options: ["Kinuha ang kanyang papel at pinatalsik siya sa silid-pagsusulit", "Itinalaga siyang kinatawan ng klase at binigyan ng scholarship", "Biniyayaan siya ng gantimpala ng paaralan dahil sa pagiging malikhain", "Nagpalakpakan ang lahat ng kanyang mga kaklase sa silid"], correctAnswer: "Kinuha ang kanyang papel at pinatalsik siya sa silid-pagsusulit", explanation: "Ang pangongodigo o pandaraya sa pagsusulit ay may parusang diskwalipikasyon."),
            ExerciseItem(prompt: "Bunga: Nagkabanggaan ang dalawang sasakyan na nagdulot ng malaking pinsala.", options: ["Sanhi: Makapal ang hamog sa umaga na nagpababa sa paningin ng drayber", "Sanhi: Parehong nakaparada nang maayos ang mga sasakyan sa garahe", "Sanhi: Maayos ang panahon at napakalinaw ng paningin sa kalsada", "Sanhi: Parehong sumunod sa speed limit ang mga drayber nang may pag-iingat"], correctAnswer: "Sanhi: Makapal ang hamog sa umaga na nagpababa sa paningin ng drayber", explanation: "Ang makapal na hamog o fog ay nagpapahirap sa mga drayber na makita ang kalsada, na nagdudulot ng aksidente.")
        ]
    )

    // MARK: - Exercise 7: Mga Hindi Lohikal na Sitwasyon
    private static let exercise7 = Exercise(
        title: "Mga Hindi Lohikal na Sitwasyon",
        instructions: "Piliin ang sagot na nagpapaliwanag kung bakit imposible o hindi lohikal ang sitwasyon.",
        section: .cognition,
        type: .multipleChoice,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "Nagluto si Juan ng mainit na tsaang gatas sa malamig na kaldero nang hindi binubuksan ang kalan.", options: ["Hindi makakapagluto o makakapagpakulo ng likido nang walang init", "Hindi dapat hinahaluan ng gatas ang tsaa", "Ang mainit na tsaa ay agad na nagiging yelo sa kuwarto", "Kailangang gumamit ng boteng plastic sa pagpapakulo ng tubig"], correctAnswer: "Hindi makakapagluto o makakapagpakulo ng likido nang walang init", explanation: "Ang pagpapakulo ay nangangailangan ng init; hindi ito mangyayari sa malamig na kalan."),
            ExerciseItem(prompt: "Matapos lumubog ang araw sa madilim na gabi, walang ilaw, namitas si Maria ng pulang rosas sa hardin.", options: ["Sa ganap na kadiliman, hindi kayang kilalanin ng mata ang mga kulay", "Ang pulang rosas ay kusa na nagiging puti sa dilim", "Kailangang gumamit ng gunting sa pamimitas ng rosas sa gabi", "Nawawala ang bango ng mga bulaklak kapag pinitas sa gabi"], correctAnswer: "Sa ganap na kadiliman, hindi kayang kilalanin ng mata ang mga kulay", explanation: "Ang paningin sa kulay ay nangangailangan ng repleksyon ng liwanag; imposible itong makita sa ganap na dilim."),
            ExerciseItem(prompt: "Gumamit ang magpapalayok ng tuyong buhangin upang gumawa ng banga at inilagay ito sa tubig upang matuyo.", options: ["Walang kakayahang dumikit ang buhangin at ang tubig ay hahadlang sa pagtuyo nito", "Ang mga palayok ay ginto lamang ang materyales", "Ang buhangin ay nagiging ginto kapag ibinabad sa tubig", "Kailangang gumamit ng microwave sa pagpapatuyo ng palayok"], correctAnswer: "Walang kakayahang dumikit ang buhangin at ang tubig ay hahadlang sa pagtuyo nito", explanation: "Ang buhangin ay walang lagkit gaya ng luwad; at ang tubig ay lalo lamang magpapabasa rito, hindi magpapatuyo."),
            ExerciseItem(prompt: "Sa gitna ng tag-araw na may 40 degrees init, nagsuot siya ng makapal na jacket at umupo sa yelo upang magpahinga.", options: ["Ang pagsusuot ng makapal na jacket at pag-upo sa yelo sa gitna ng init ay magkasalungat", "Hindi nalulusaw ang yelo sa ilalim ng matinding init ng kalsada", "Ang makapal na jacket ay ginagamit lamang sa paglangoy sa dagat", "Kailangang uminom ng tubig na may asin upang makaiwas sa init"], correctAnswer: "Ang pagsusuot ng makapal na jacket at pag-upo sa yelo sa gitna ng init ay magkasalungat", explanation: "Ang pagsusuot ng makapal na jacket ay nagkukulong ng init sa katawan, habang ang yelo naman ay nagpapababa ng temperatura sa hindi maayos na paraan."),
            ExerciseItem(prompt: "Nagkalat ng buto ng palay ang magsasaka sa aspalto ng highway at umasang makakaani ng marami sa taglagas.", options: ["Ang aspalto ay walang lupa at tubig na kailangan ng palay upang tumubo at mag-ugat", "Sa highway ay mansanas lamang ang pinapayagang itanim", "Ang pagtatanim ng palay ay ginagawa lamang sa ibabaw ng yelo", "Ang aspalto ay may natural na pataba na mas maganda sa lupa"], correctAnswer: "Ang aspalto ay walang lupa at tubig na kailangan ng palay upang tumubo at mag-ugat", explanation: "Ang mga pananim ay nangangailangan ng matabang lupa upang mag-ugat at kumuha ng sustansya; hindi ito tutubo sa aspalto."),
            ExerciseItem(prompt: "Tumalon ang isda palabas ng aquarium, tumakbo gamit ang mga paa patungo sa gubat at umakyat sa puno para magtago sa pusa.", options: ["Ang isda ay walang paa para tumakbo at hindi makakahinga sa labas ng tubig", "Natatakot ang pusa na umakyat sa mataas na puno sa gubat", "Ang mga isda ay lumilipad sa langit kasabay ng mga ibon", "Ang kaliskis ng isda ay nagdudulot ng apoy kapag nadikit sa damo"], correctAnswer: "Ang isda ay walang paa para tumakbo at hindi makakahinga sa labas ng tubig", explanation: "Ang isda ay gumagamit ng hasang upang huminga sa tubig; wala rin silang paa para tumakbo o umakyat sa puno."),
            ExerciseItem(prompt: "Pinatay ni Juan ang kanyang cellphone, at agad na tinawagan ang kanyang ina at nakipag-usap ng dalawang oras.", options: ["Ang patay na cellphone ay walang kuryente at signal upang makagawa ng tawag", "Ang pakikipag-usap sa ina ay nangangailangan ng landline lamang", "Nagpapadala ng SMS nang kusa ang cellphone kapag ito ay patay", "Hindi gagana ang tawag kapag walang nakakonektang headphone"], correctAnswer: "Ang patay na cellphone ay walang kuryente at signal upang makagawa ng tawag", explanation: "Kailangang bukas ang cellphone upang gumana ang transceiver nito at makakonekta sa network."),
            ExerciseItem(prompt: "Upang mas mabilis na matuyo ang mga basang damit, inilagay niya ang mga ito sa loob ng balde ng malamig na tubig.", options: ["Ang paglulubog sa tubig ay lalong magpapabasa sa damit at hahadlang sa pagtuyo nito", "Ang basang damit ay natutuyo lamang kapag inilagay sa saradong cabinet", "Sinisira ng malamig na tubig ang hibla ng polyester ng damit", "Kailangang gumamit ng nano powder na sumisipsip ng tubig upang matuyo"], correctAnswer: "Ang paglulubog sa tubig ay lalong magpapabasa sa damit at hahadlang sa pagtuyo nito", explanation: "Ang pagpapatuyo ay ang pag-aalis ng tubig; ang paglubog nito sa balde ay lalo lamang magpapabasa rito."),
            ExerciseItem(prompt: "Upang mapabilis ang takbo ng sasakyan sa pababang kalsada, tinapakan ng drayber ang preno nang pilit.", options: ["Ang preno ay nagpapabagal o nagpapahinto sa sasakyan, hindi nagpapabilis", "Bumabagal ang sasakyan kapag inikot ang manibela nang pakaliwa at pakanan", "Ang preno ng malalaking sasakyan ay nasa gilid lamang ng passenger seat", "Ang pagpreno nang husto ay nagiging sanhi ng pagkawala ng diesel sa tangke"], correctAnswer: "Ang preno ay nagpapabagal o nagpapahinto sa sasakyan, hindi nagpapabilis", explanation: "Ang preno ay ginagamit upang pabagalin ang sasakyan; ang gas pedal ang ginagamit sa pagpapabilis."),
            ExerciseItem(prompt: "Sumisid ang mga gansa sa ilalim ng dagat at gumawa ng pugad na gawa sa tuyong dahon upang mag-itlog.", options: ["Ang mga gansa ay humihinga sa hangin at ang pugad ay masisira ng agos ng tubig", "Ang mga gansa ay nag-iitlog lamang sa ibabaw ng mga ulap", "Ang tubig sa ilalim ng dagat ay palaging kumukulo sa higit 100 degrees", "Nasusunog ang balahibo ng ibon kapag nabasa ng tubig-alat"], correctAnswer: "Ang mga gansa ay humihinga sa hangin at ang pugad ay masisira ng agos ng tubig", explanation: "Ang gansa ay may baga at hindi makakahinga sa ilalim ng tubig; ang mga dahon at pugad ay matatangay din ng agos ng dagat."),
            ExerciseItem(prompt: "Tinikman niya ang kumukulong sabaw sa kalan at sinabing napakalamig nito na parang yelo.", options: ["Ang kumukulong sabaw ay may napakataas na temperatura at nakakapaso, hindi malamig", "Ang sabaw ay dapat kainin gamit ang kutsarang kahoy upang maramdaman ang tamang init", "Ang mainit na pagkain ay nagpapatulog sa dila ng tao", "Ang sabaw ay nagiging yelo agad kapag pinatay ang kalan"], correctAnswer: "Ang kumukulong sabaw ay may napakataas na temperatura at nakakapaso, hindi malamig", explanation: "Ang kumukulo ay may temperaturang malapit sa 100 degrees Celsius, kaya ito ay napakainit at nakakapaso."),
            ExerciseItem(prompt: "Upang ma-lock ang pinto ng bahay, itinapon ng ama ang susi sa labas ng bintana.", options: ["Ang pagla-lock ay nangangailangan ng pagpihit ng susi sa loob ng kandado, hindi ang pagtapon nito", "Ang maliit na butas ng pinto ay hindi papayag na dumaan ang susi", "Ang pintong kahoy ay dapat i-lock gamit ang trangka lamang", "Ang mga pintong bakal ay sa pamamagitan ng fingerprint lamang gumagana"], correctAnswer: "Ang pagla-lock ay nangangailangan ng pagpihit ng susi sa loob ng kandado, hindi ang pagtapon nito", explanation: "Kailangang gamitin ang susi sa mismong kandado upang mapihit ang mekanismo nito; hindi ito mai-lock kung itatapon ang susi."),
            ExerciseItem(prompt: "Tumingin ang isang bulag sa teleskopyo at inilarawan ang mga pulang bulaklak sa burol.", options: ["Ang bulag ay walang paningin kaya hindi magagamit ang teleskopyo", "Ang teleskopyo ay para lamang sa mga astronaut upang makita ang mga planeta", "Ang mga burol ay wala kundi mga cactus at tini ang tumutubo", "Ang teleskopyo ay walang kakayahang magpalaki ng larawan sa araw"], correctAnswer: "Ang bulag ay walang paningin kaya hindi magagamit ang teleskopyo", explanation: "Ang teleskopyo ay gumagamit ng mata upang makita ang pinalaking imahe; hindi ito magagamit ng bulag dahil sa kawalan ng paningin."),
            ExerciseItem(prompt: "Bumalik ang ikot ng kamay ng oras sa dingding, kaya bumalik din ang totoong oras sa kahapon.", options: ["Ang orasan ay tagasulat lamang ng oras at ang pag-ikot nito ay hindi nagbabago sa totoong oras", "Ang pag-ikot ng kamay sa likod ay nagpapasabog sa baterya ng orasan", "Ang oras ay tumatakbo nang mabilis kapag naglalakbay sa kalawakan", "Ang kamay ng orasan ay kontrolado ng electromagnetic wave na nagbabawal sa pag-ikot sa likod"], correctAnswer: "Ang orasan ay tagasulat lamang ng oras at ang pag-ikot nito ay hindi nagbabago sa totoong oras", explanation: "Ang oras ay isang dimensyon ng pisika na patuloy na tumatakbo pasulong; ang orasan ay nagpapakita lamang ng sukat nito."),
            ExerciseItem(prompt: "Sumulat siya gamit ang tuyong ballpen sa basang papel, at nakakuha ng napakalinis at maayos na sulat.", options: ["Ang basang papel ay madaling mapunit at ang tinta ay kakalat sa tubig", "Ang basang papel ay sa pamamagitan ng brush lamang sinusulatan sa ilalim ng tubig", "Ang ballpen ay sa ibabaw ng gintong papel lamang sumusulat", "Ang tubig sa papel ay mabilis na magwawala kapag nadikit ang dulo ng panulat"], correctAnswer: "Ang basang papel ay madaling mapunit at ang tinta ay kakalat sa tubig", explanation: "Ang tubig ay nagpapahina sa hibla ng papel kaya madali itong mapunit sa matalim na dulo ng ballpen; ang tinta ay kakalat din at magiging malabo.")
        ]
    )

    // MARK: - Exercise 8: Mga Salawikain at Kasabihan
    private static let exercise8 = Exercise(
        title: "Mga Salawikain at Kasabihan",
        instructions: "Piliin ang salita na tamang kumukumpleto sa salawikain o kasabihang Pilipino.",
        section: .language,
        type: .sentenceCompletion,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Ang hindi lumingon sa pinanggalingan ay hindi makararating sa ___.", options: ["paroroonan", "bahay", "kalsada", "bayan"], correctAnswer: "paroroonan", explanation: "Ang kilalang salawikain ay 'Ang hindi lumingon sa pinanggalingan ay hindi makararating sa paroroonan', na nagtuturo ng pagpapahalaga sa ating pinagmulan."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Pag may tiyaga, may ___.", options: ["nilaga", "pera", "pagkain", "tagumpay"], correctAnswer: "nilaga", explanation: "Ang kasabihan ay 'Pag may tiyaga, may nilaga', na nangangahulugang ang pagtitiyaga ay may katumbas na gantimpala."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Aanhin pa ang damo, kung patay na ang ___.", options: ["kabayo", "baka", "kambing", "kalabaw"], correctAnswer: "kabayo", explanation: "Ang salawikain ay 'Aanhin pa ang damo, kung patay na ang kabayo', na nangangahulugang balewala ang tulong kung huli na ang lahat."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Habang maikli ang kumot, matutong ___.", options: ["mamaluktot", "matulog", "bumili", "umiyak"], correctAnswer: "mamaluktot", explanation: "Ang salawikain ay 'Habang maikli ang kumot, matutong mamaluktot', na nagtuturo ng pagiging matipid o marunong makibagay sa sitwasyon."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Ang sakit ng kalingkingan, damdam ng buong ___.", options: ["katawan", "kamay", "ulo", "pamilya"], correctAnswer: "katawan", explanation: "Ang salawikain ay 'Ang sakit ng kalingkingan, damdam ng buong katawan', na nangangahulugang ang problema ng isa sa pamilya o grupo ay problema ng lahat."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Pag ang bulsa ay butas, madalas ___.", options: ["lumalabas", "nawawala", "walang laman", "butas"], correctAnswer: "walang laman", explanation: "Ang kasabihan ay 'Pag ang bulsa ay butas' (walang pera/naghihirap)."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Kung ano ang itinanim, siya ring ___.", options: ["aaiin", "kakainin", "tatanimin", "mawawala"], correctAnswer: "aaiin", explanation: "Ang salawikain ay 'Kung ano ang itinanim, siya ring aaiin', na nagtuturo ng batas ng karma o resulta ng ating mga gawa (aaniin)."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Walang matigas na tinapay sa mainit na ___.", options: ["kape", "gatas", "tubig", "tsaa"], correctAnswer: "kape", explanation: "Ang kasabihan ay 'Walang matigas na tinapay sa mainit na kape', na nangangahulugang walang matigas ang kalooban sa taong matiyaga o mabait."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Kung may isinuksok, may ___.", options: ["dudukutin", "kukunin", "mahihita", "mawiwili"], correctAnswer: "dudukutin", explanation: "Ang kasabihan ay 'Kung may isinuksok, may dudukutin', na nagtuturo ng kahalagahan ng pag-iipon."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Nasa tao ang gawa, nasa Diyos ang ___.", options: ["awa", "tulong", "pagpapala", "ganti"], correctAnswer: "awa", explanation: "Ang kasabihan ay 'Nasa tao ang gawa, nasa Diyos ang awa', na nagpapaalala na kailangan nating magsikap habang umaasa sa awa ng Maykapal."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Daig ng maagap ang ___.", options: ["masipag", "matalino", "malakas", "mayaman"], correctAnswer: "masipag", explanation: "Ang kasabihan ay 'Daig ng maagap ang masipag', na nagpapakita na ang taong handa o maaga ay may kalamangan."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Bago mo linisin ang dungis ng ibang tao, linisin mo muna ang sa sarili mong ___.", options: ["mukha", "kamay", "bahay", "salita"], correctAnswer: "mukha", explanation: "Ang kasabihan ay 'Bago mo linisin ang dungis ng ibang tao, linisin mo muna ang sa sarili mong mukha', na nagpapaalala na huwag mamuna ng iba kung may kapintasan din sarili."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Pagkahaba-haba man ng prusisyon, sa ___ din ang tuloy.", options: ["simbahan", "altar", "sementeryo", "kalsada"], correctAnswer: "simbahan", explanation: "Ang kasabihan ay 'Pagkahaba-haba man ng prusisyon, sa simbahan din ang tuloy', na nangangahulugang kahit gaano katagal ang paghihintay ay may patutunguhan pa rin ito sa huli."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Ang mabuting halimbawa ay higit na mabuti kaysa makapangyarihang ___.", options: ["aral", "salita", "utos", "gawain"], correctAnswer: "aral", explanation: "Ang kasabihan ay 'Ang mabuting halimbawa ay higit na mabuti kaysa makapangyarihang aral', na nagpapakita na mas epektibo ang aksyon kaysa sa salita lamang."),
            ExerciseItem(prompt: "Kumpletuhin ang kasabihan: Ang lakas ay nanggagaling sa ___.", options: ["pagkakaisa", "sarili", "pera", "kapangyarihan"], correctAnswer: "pagkakaisa", explanation: "Ang kasabihan ay 'Ang lakas ay nanggagaling sa pagkakaisa', na katulad ng konseptong ang unyon ay lakas (unity is strength).")
        ]
    )

    // MARK: - Easy Homonyms
    private static let easyHomonyms = Exercise(
        title: "Mga Salitang Magkakapareho ang Tunog",
        instructions: "Piliin ang tamang salita upang kumpletuhin ang mga pangungusap.",
        section: .language,
        type: .homonym,
        difficulty: .easy,
        items: [
            ExerciseItem(prompt: "[saya / saya] Maganda ang kanyang bagong pulang ___. Puno ng ___ ang kanyang kaarawan.", options: ["saya...saya", "saya...lungkot", "lungkot...saya", "saya...damit"], correctAnswer: "saya...saya", explanation: "Ang unang 'saya' ay damit ng babae (skirt); ang pangalawang 'saya' ay kagalakan (happiness)."),
            ExerciseItem(prompt: "[aso / aso] Tumatahol ang alagang ___ ni Lola. Makapal ang puting ___ mula sa siga.", options: ["aso...aso", "aso...pusa", "pusa...aso", "aso...singaw"], correctAnswer: "aso...aso", explanation: "Ang unang 'aso' ay hayop (dog); ang pangalawang 'aso' ay usok na likha ng apoy (smoke)."),
            ExerciseItem(prompt: "[puno / puno] Ang ___ ng mangga ay matayog. ___ na ng tubig ang malaking balde.", options: ["puno...puno", "puno...walang laman", "walang laman...puno", "puno...kahoy"], correctAnswer: "puno...puno", explanation: "Ang unang 'puno' ay halaman (tree); ang pangalawang 'puno' ay walang bakanteng espasyo (full)."),
            ExerciseItem(prompt: "[gabi / gabi] Masarap ang halamang-ugat na ___ sa sinigang. Madilim na ang ___ nang umuwi si Tatay.", options: ["gabi...gabi", "gabi...araw", "araw...gabi", "gabi...gulay"], correctAnswer: "gabi...gabi", explanation: "Ang unang 'gabi' ay isang uri ng pananim (taro); ang pangalawang 'gabi' ay bahagi ng araw pagkatapos lumubog ang araw (night)."),
            ExerciseItem(prompt: "[bukas / bukas] ___ ang bintana kaya malamig ang hangin. Babalik si Ate dito ___ ng umaga.", options: ["bukas...bukas", "bukas...sarado", "sarado...bukas", "bukas...ngayon"], correctAnswer: "bukas...bukas", explanation: "Ang unang 'bukas' ay hindi nakasara (open); ang pangalawang 'bukas' ay susunod na araw (tomorrow)."),
            ExerciseItem(prompt: "[lobo / lobo] Lumipad ang makulay na ___ sa langit. Narinig namin ang alulong ng ___ sa gubat.", options: ["lobo...lobo", "lobo...aso", "aso...lobo", "lobo...laruan"], correctAnswer: "lobo...lobo", explanation: "Ang unang 'lobo' ay laruang lumilipad (balloon); ang pangalawang 'lobo' ay mabangis na hayop (wolf)."),
            ExerciseItem(prompt: "[suka / suka] Maasim ang ___ na gawa sa niyog. Ang ___ ng maysakit ay marami.", options: ["suka...suka", "suka...dumi", "dumi...suka", "suka...asim"], correctAnswer: "suka...suka", explanation: "Ang unang 'suka' ay maasim na sawsawan (vinegar); ang pangalawang 'suka' ay iniluwa ng tiyan (vomit)."),
            ExerciseItem(prompt: "[baba / baba] Mahaba ang ___ ng kanyang mukha. Pakisabi sa kanya na ___ na siya sa sala.", options: ["baba...baba", "baba...taas", "taas...baba", "baba...mukha"], correctAnswer: "baba...baba", explanation: "Ang unang 'baba' ay bahagi ng mukha (chin); ang pangalawang 'baba' ay kilos ng pagbaba (descend)."),
            ExerciseItem(prompt: "[tuyo / tuyo] Masarap almusal ang ___ na isda. ___ na ang mga sinampay na damit sa labas.", options: ["tuyo...tuyo", "tuyo...basa", "basa...tuyo", "tuyo...sariwa"], correctAnswer: "tuyo...tuyo", explanation: "Ang unang 'tuyo' ay maalat na isdang pinatuyo; ang pangalawang 'tuyo' ay walang basa o dry."),
            ExerciseItem(prompt: "[kita / kita] Malaki ang ___ ng aming sari-sari store. Hindi ko ___ ang ibon sa sanga.", options: ["kita...kita", "kita...bulag", "bulag...kita", "kita...pera"], correctAnswer: "kita...kita", explanation: "Ang unang 'kita' ay kinita o sahod (income); ang pangalawang 'kita' ay nakikita (visible)."),
            ExerciseItem(prompt: "[hapon / hapon] Masarap magmeryenda tuwing ___. May panauhin kaming galing sa bansang ___.", options: ["hapon...hapon", "hapon...umaga", "umaga...hapon", "hapon...tsina"], correctAnswer: "hapon...hapon", explanation: "Ang unang 'hapon' ay oras bago sumapit ang gabi (afternoon); ang pangalawang 'hapon' ay bansa o lahing Hapones (Japan/Japanese)."),
            ExerciseItem(prompt: "[pako / pako] Ginamit ng karpintero ang ___ sa kahoy. Masarap gisingin ang halamang ___.", options: ["pako...pako", "pako...kahoy", "kahoy...pako", "pako...metal"], correctAnswer: "pako...pako", explanation: "Ang unang 'pako' ay gawa sa bakal (nail); ang pangalawang 'pako' ay nakakain na gulay (fern)."),
            ExerciseItem(prompt: "[bata / bata] Masayahin ang ___ na naglalaro ng sipa. Kaya kong ___ ang hirap ng buhay.", options: ["bata...bata", "bata...matanda", "matanda...bata", "bata...tiis"], correctAnswer: "bata...bata", explanation: "Ang unang 'bata' ay may maliit na edad (child); ang pangalawang 'bata' ay pagtitiis sa pasakit (endure)."),
            ExerciseItem(prompt: "[tubo / tubo] Gawa sa plastik ang ___ ng gripo. Matamis ang ___ na ginagawang asukal.", options: ["tubo...tubo", "tubo...ugat", "ugat...tubo", "tubo...bakal"], correctAnswer: "tubo...tubo", explanation: "Ang unang 'tubo' ay daanan ng tubig (pipe); ang pangalawang 'tubo' ay halamang sugarcane."),
            ExerciseItem(prompt: "[lata / lata] Nilagay ang sardinas sa loob ng ___. Ang ___ ng kanyang tuhod ay dahil sa pagod.", options: ["lata...lata", "lata...baso", "baso...lata", "lata...lakas"], correctAnswer: "lata...lata", explanation: "Ang unang 'lata' ay sisidlang metal (tin can); ang pangalawang 'lata' ay panghihina ng katawan (weakness).")
        ]
    )

    // MARK: - Easy Analogies
    private static let easyAnalogies = Exercise(
        title: "Madaling Analhiya",
        instructions: "Piliin ang salita na pinakamahusay na nakakumpleto sa analhiya.",
        section: .language,
        type: .analogyChoice,
        difficulty: .easy,
        items: [
            ExerciseItem(prompt: "TAAS ay sa BABA tulad ng MAINIT ay sa MALAMIG", options: ["MALAMIG", "MALAMBING", "KUMUKULO", "BASA"], correctAnswer: "MALAMIG", explanation: "Ang taas at baba ay magkasalungat, tulad ng mainit at malamig."),
            ExerciseItem(prompt: "IBON ay sa LUMIPAD tulad ng ISDA ay sa LUMANGOY", options: ["LUMANGOY", "TUMAKBO", "LUMAKAD", "TUMALON"], correctAnswer: "LUMANGOY", explanation: "Ang ibon ay gumagalaw sa pamamagitan ng paglipad, at ang isda sa paglangoy."),
            ExerciseItem(prompt: "PUSA ay sa KUTING tulad ng ASO ay sa TUTA", options: ["TUTA", "KUTING", "BACA", "KABAYO"], correctAnswer: "TUTA", explanation: "Ang kuting ay anak ng pusa, at ang tuta ay anak ng aso."),
            ExerciseItem(prompt: "ARAW ay sa ARAW (SUN) tulad ng GABI ay sa BUWAN", options: ["BUWAN", "ULAN", "HANGIN", "ULAP"], correctAnswer: "BUWAN", explanation: "Ang araw ay nakikita sa umaga, at ang buwan sa gabi."),
            ExerciseItem(prompt: "YELO ay sa MALAMIG tulad ng APOY ay sa MAINIT", options: ["MAINIT", "BASA", "MADILIM", "MALAMBOT"], correctAnswer: "MAINIT", explanation: "Ang yelo ay malamig hawakan, habang ang apoy ay mainit."),
            ExerciseItem(prompt: "PANULAT ay sa MAGSULAT tulad ng GUNTING ay sa GUMUPIT", options: ["GUMUPIT", "MAGDIKIT", "GUMUHIT", "MAGKULAY"], correctAnswer: "GUMUPIT", explanation: "Ang panulat ay ginagamit sa pagsulat, at ang gunting sa paggupit."),
            ExerciseItem(prompt: "PUNO ay sa DAHON tulad ng BULAKLAK ay sa PETAL", options: ["PETAL", "TINIK", "UGAT", "TANGLAY"], correctAnswer: "PETAL", explanation: "Ang dahon ay bahagi ng puno, at ang petal ay bahagi ng bulaklak."),
            ExerciseItem(prompt: "KOTSE ay sa KALSADA tulad ng BANGKA ay sa TUBIG", options: ["TUBIG", "HIMPAPAWID", "LUPA", "Riles"], correctAnswer: "TUBIG", explanation: "Ang kotse ay tumatakbo sa kalsada, habang ang bangka sa tubig."),
            ExerciseItem(prompt: "MEDYAS ay sa PAA tulad ng GOWANTES ay sa KAMAY", options: ["KAMAY", "ULO", "LEEG", "BISIG"], correctAnswer: "KAMAY", explanation: "Ang medyas ay sinusuot sa paa, at ang guwantes sa kamay."),
            ExerciseItem(prompt: "GUTOM ay sa PAGKAIN tulad ng UHAW ay sa TUBIG", options: ["TUBIG", "TINAPAY", "PRUTAS", "ASIN"], correctAnswer: "TUBIG", explanation: "Kapag gutom ay kailangan ng pagkain, at kapag uhaw ay tubig."),
            ExerciseItem(prompt: "SAPATOS ay sa PAA tulad ng SUMBRERO ay sa ULO", options: ["ULO", "KAMAY", "Binti", "LEEG"], correctAnswer: "ULO", explanation: "Ang sapatos ay sinusuot sa paa, at ang sumbrero sa ulo."),
            ExerciseItem(prompt: "BAKA ay sa GATAS tulad ng LAYWAN ay sa PULOT", options: ["PULOT", "KANDILA", "BULAKLAK", "TUBIG"], correctAnswer: "PULOT", explanation: "Ang baka ay nagbibigay ng gatas, at ang laywan ay pulot-pukyutan."),
            ExerciseItem(prompt: "NGIPIN ay sa SIPILYO tulad ng BUHOK ay sa SUKLAY", options: ["SUKLAY", "HUGAS", "GUPIT", "TUYO"], correctAnswer: "SUKLAY", explanation: "Sinisipilyo ang ngipin para luminis, at sinusuklay ang buhok para maayos."),
            ExerciseItem(prompt: "ULAN ay sa BASA tulad ng ARAW ay sa TUYO", options: ["TUYO", "MALAMIG", "MADILIM", "MAHANGIN"], correctAnswer: "TUYO", explanation: "Ang ulan ay nagpapabasa ng mga bagay, habang ang araw ay nagpapatuyo.")
        ]
    )

    // MARK: - Easy Cause and Effect
    private static let easyCauseEffect = Exercise(
        title: "Madaling Sanhi at Bunga",
        instructions: "Piliin ang pinaka-lohikal na sanhi o bunga.",
        section: .cognition,
        type: .multipleChoice,
        difficulty: .easy,
        items: [
            ExerciseItem(prompt: "Sanhi: Nabitawan mo ang basong bubog sa semento.", options: ["Nabasag ang baso", "Lulutang ang baso", "Lalambot ang baso", "Magiging asul ang baso"], correctAnswer: "Nabasag ang baso", explanation: "Ang bubog ay madaling mabasag kapag bumagsak sa matigas na sahig."),
            ExerciseItem(prompt: "Sanhi: Nakalimutan mong diligan ang halaman nang isang linggo.", options: ["Nalanta at natuyo ito", "Tumubo ang mga bulaklak", "Naging kulay ube ito", "Namunga ito"], correctAnswer: "Nalanta at natuyo ito", explanation: "Kailangan ng halaman ng tubig; kung wala ito, ito ay malalanta at mamamatay."),
            ExerciseItem(prompt: "Sanhi: Iniwan mo ang yelo sa mesa ng kusina sa tag-init.", options: ["Natunaw ito at naging tubig", "Lumaki ito", "Naging kahoy ito", "Nanatiling matigas"], correctAnswer: "Natunaw ito at naging tubig", explanation: "Dahil sa init ng temperatura, ang yelo ay natutunaw at nagiging tubig."),
            ExerciseItem(prompt: "Sanhi: Hinipan mo ang lobo nang masyadong maraming hangin.", options: ["Pumutok ang lobo", "Naging yelo ito", "Kumanta ito", "Bumigat ito"], correctAnswer: "Pumutok ang lobo", explanation: "Ang labis na hangin ay lalampas sa kakayahan ng goma ng lobo kaya ito puputok."),
            ExerciseItem(prompt: "Sanhi: Pinindot mo ang switch ng ilaw sa dingding.", options: ["Sumindi ang ilaw", "Lumamig ang silid", "Nasusi ang pinto", "Huminto ang orasan"], correctAnswer: "Sumindi ang ilaw", explanation: "Ang pagpindot sa switch ay nagdurugtong sa kuryente kaya sumisindi ang ilaw."),
            ExerciseItem(prompt: "Sanhi: Hindi ka natulog buong magdamag.", options: ["Sobrang pagod mo kinabukasan", "Sobrang sigla mo", "Pumuti ang buhok mo", "Tangkad mo lalo"], correctAnswer: "Sobrang pagod mo kinabukasan", explanation: "Kailangan ng katawan ng pahinga; ang puyat ay nagdudulot ng matinding pagod."),
            ExerciseItem(prompt: "Sanhi: Tumayo ka sa malakas na ulan nang walang payong.", options: ["Nabasa ka", "Nanatili kang tuyo", "Lumipad ka sa hangin", "Nasunog ka"], correctAnswer: "Nabasa ka", explanation: "Ang ulan ay tubig mula sa langit; kung wala kang proteksyon ay mababasa ka."),
            ExerciseItem(prompt: "Sanhi: Naglagay ka ng tinapay sa toaster at binaba ang lever.", options: ["Naging tostado ang tinapay", "Naging harina ang tinapay", "Natunaw ang tinapay", "Nabasa ang tinapay"], correctAnswer: "Naging tostado ang tinapay", explanation: "Ang toaster ay nag-ainit upang gawing tostado at malutong ang tinapay."),
            ExerciseItem(prompt: "Sanhi: Iniwan mo ang gatas sa counter nang tatlong araw sa init.", options: ["Naasim at nasira ang gatas", "Tamis lalo ang gatas", "Naging yelo ito", "Naging pulot ito"], correctAnswer: "Naasim at nasira ang gatas", explanation: "Ang pag-iwan sa gatas sa init ay nagpaparami ng bakterya kaya ito nasisira."),
            ExerciseItem(prompt: "Sanhi: Hinipan mo nang malakas ang kandilang may apoy.", options: ["Namatay ang apoy", "Lumalaki ang apoy", "Natunaw agad ang kandila", "Naging asul ang kandila"], correctAnswer: "Namatay ang apoy", explanation: "Ang malakas na ihip ay nag-aalis ng init at hangin na kailangan ng apoy kaya ito namamatay."),
            ExerciseItem(prompt: "Sanhi: Naglagay ka ng kaldero ng tubig sa mainit na kalan.", options: ["Nag-umpisang kumulo ang tubig", "Naging yelo ang tubig", "Nawala agad ang tubig", "Lumaki ang kaldero"], correctAnswer: "Nag-umpisang kumulo ang tubig", explanation: "Ang init mula sa kalan ay nagpapataas ng temperatura ng tubig hanggang kumulo ito."),
            ExerciseItem(prompt: "Sanhi: Nakaapak ka ng matulis na pako nang nakayapak.", options: ["Nasugatan ang paa mo", "Nadumihan ang sapatos mo", "Tumalon ka nang mataas", "Naging berde ang paa mo"], correctAnswer: "Nasugatan ang paa mo", explanation: "Ang pag-apak sa matulis na bagay ay bumabaon sa balat at nagdudulot ng sugat."),
            ExerciseItem(prompt: "Sanhi: Naglagay ka ng asukal sa mapait na kape.", options: ["Tumatamis ang kape", "Lumalamig ang kape", "Nawawala ang kape", "Maalat ang kape"], correctAnswer: "Tumatamis ang kape", explanation: "Ang asukal ay nagbibigay ng tamis na nagtatakip sa pait ng kape."),
            ExerciseItem(prompt: "Sanhi: Nagtapon ka ng bola ng tennis sa pader.", options: ["Bumalik ang bola sa iyo", "Pumasok ang bola sa pader", "Nawasak ang pader", "Natunaw ang bola"], correctAnswer: "Bumalik ang bola sa iyo", explanation: "Dahil sa pagka-talbog ng bola ng tennis, babalik ito matapos tumama sa pader."),
            ExerciseItem(prompt: "Sanhi: Hindi ka nag-aral para sa mahalagang pagsusulit.", options: ["Mababa ang nakuha mong marka", "Perpekto ang nakuha mong marka", "Nagsara ang paaralan", "Nagtapos ka agad"], correctAnswer: "Mababa ang nakuha mong marka", explanation: "Kung walang paghahanda o pag-aaral, mahihirapan kang sumagot nang tama sa pagsusulit.")
        ]
    )

    // MARK: - Easy What's Wrong Here
    private static let easyWhatsWrong = Exercise(
        title: "Madaling Paghahanap ng Mali",
        instructions: "Tukuyin ang lohikal na mali o imposible sa pahayag.",
        section: .cognition,
        type: .multipleChoice,
        difficulty: .easy,
        items: [
            ExerciseItem(prompt: "Mali: Nagsuot si Juan ng sapatos bago ang kanyang medyas.", options: ["Dapat isuot ang medyas bago ang sapatos", "Dapat ilagay ang sapatos sa kamay", "Ang medyas ay sinusuot sa ulo", "Dapat kainin ang sapatos"], correctAnswer: "Dapat isuot ang medyas bago ang sapatos", explanation: "Ang medyas ay nasa loob ng sapatos, kaya ito ang unang sinusuot."),
            ExerciseItem(prompt: "Mali: Ginamit niya ang tinidor para higupin ang sabaw ng manok.", options: ["Ang sabaw ay likido at kailangan ng kutsara", "Dapat kamayin ang sabaw", "Ang tinidor ay ginagamit sa paghiwa ng karne", "Dapat lutuin ang sabaw sa baso"], correctAnswer: "Ang sabaw ay likido at kailangan ng kutsara", explanation: "Tutusok lang ang tinidor sa sabaw at tatagas ang sabaw; kutsara ang dapat gamitin."),
            ExerciseItem(prompt: "Mali: Umakyat ang isda sa puno para gumawa ng pugad.", options: ["Ang isda ay nakatira sa tubig at hindi umaakyat sa puno", "Walang sanga ang mga puno", "Ang isda ay gumagawa ng pugad sa bubong", "Lumilipad ang isda sa hangin"], correctAnswer: "Ang isda ay nakatira sa tubig at hindi umaakyat sa puno", explanation: "May hasang at palikpik ang isda`t hindi nabubuhay sa lupa o umaakyat sa puno."),
            ExerciseItem(prompt: "Mali: Nagsuot siya ng makapal na jacket para lumangoy sa pool.", options: ["Damit pampaligo ang ginagamit sa paglangoy, hindi makapal na jacket", "Nagpapabilis sa paglangoy ang makapal na jacket", "Dapat puno ng yelo ang pool", "Tuwing tag-init lang sinusuot ang makapal na jacket"], correctAnswer: "Damit pampaligo ang ginagamit sa paglangoy, hindi makapal na jacket", explanation: "Sumisipsip ng tubig ang jacket at bibigat kaya mahihirapan kang lumangoy."),
            ExerciseItem(prompt: "Mali: Niluto nila ang hilaw na itlog sa loob ng freezer.", options: ["Naglalamig ang freezer; kalan ang nagluluto", "Dapat hilaw lang kainin ang itlog", "Ang freezer ay ginagamit sa pagpapakulo ng tubig", "Mas madaling maluto ang itlog sa microwave"], correctAnswer: "Naglalamig ang freezer; kalan ang nagluluto", explanation: "Kailangan ng init para makapagluto; ang freezer ay para magpalamig."),
            ExerciseItem(prompt: "Mali: Binuksan ng aso ang libro at nagbasa nang malakas.", options: ["Hindi nakakapagsalita o nakakapagbasa ang aso", "Diyaryo lang ang binabasa ng aso", "Dapat tahimik lang magbasa", "Gusto ng aso na magsulat ng libro"], correctAnswer: "Hindi nakakapagsalita o nakakapagbasa ang aso", explanation: "Walang kakayahan ang hayop na magbasa o magsalita ng wika ng tao."),
            ExerciseItem(prompt: "Mali: Hinati niya ang cake gamit ang kutsara.", options: ["Kutsilyo ang ginagamit sa paghati ng cake, hindi kutsara", "Kamayin dapat ang cake", "Para sa sabaw lang ang kutsara", "Dapat gupitin ang cake ng gunting"], correctAnswer: "Kutsilyo ang ginagamit sa paghati ng cake, hindi kutsara", explanation: "May talim ang kutsilyo para makahati nang maayos; ang kutsara ay para sa paghigop."),
            ExerciseItem(prompt: "Mali: Ginamit niya ang lapis para mag-type sa kanyang cellphone.", options: ["Daliri o stylus ang ginagamit sa touchscreen ng cellphone", "Sa salamin lang ginagamit ang lapis", "Voice command lang ang tinatanggap ng cellphone", "Masyadong maikli ang lapis para magsulat"], correctAnswer: "Daliri o stylus ang ginagamit sa touchscreen ng cellphone", explanation: "Ang screen ng smartphone ay gumagana sa dampi ng daliri o stylus pen."),
            ExerciseItem(prompt: "Mali: Lumayag ang eroplano sa ibabaw ng malalim na dagat.", options: ["Lumilipad ang eroplano sa hangin; barko ang lumalayag sa dagat", "Berde palagi ang tubig sa dagat", "Sa lupa lang tumatakbo ang eroplano", "Lumilipad ang barko sa langit"], correctAnswer: "Lumilipad ang eroplano sa hangin; barko ang lumalayag sa dagat", explanation: "Ang eroplano ay para sa himpapawid; ang barko ang para sa dagat."),
            ExerciseItem(prompt: "Mali: Nagbukas siya ng payong sa loob ng tuyong sala.", options: ["Ang payong ay para sa ulan o araw sa labas", "Dapat may ulan sa loob ng sala", "Tuwing taglamig lang ginagamit ang payong", "Dapat magsuot siya ng jascket sa loob"], correctAnswer: "Ang payong ay para sa ulan o araw sa labas", explanation: "Proteksyon ang payong sa ulan sa labas; walang ulan sa loob ng tuyong bahay."),
            ExerciseItem(prompt: "Mali: Tiyak na tumahol ang pusa sa kartero.", options: ["Ngumiyaw ang pusa; tumahol ang aso", "Sa daga lang tumatahol ang pusa", "Takot ang kartero sa pusa", "Tuwing umaga lang tumatahol ang pusa"], correctAnswer: "Ngumiyaw ang pusa; tumahol ang aso", explanation: "Ang aso ang tumatahol; ngumiyaw naman ang tunog ng pusa."),
            ExerciseItem(prompt: "Mali: Naglagay siya ng gasolina sa kanyang bisikleta para pumunta sa tindahan.", options: ["Pedal at lakas ng tao ang nagpapatakbo sa bisikleta", "Diesel ang ginagamit sa bisikleta", "Baterya lang ang nagpapatakbo sa bisikleta", "Walang gulong ang bisikleta"], correctAnswer: "Pedal at lakas ng tao ang nagpapatakbo sa bisikleta", explanation: "Ang bisikleta ay walang makina; pedal ang nagpapandar nito gamit ang paa."),
            ExerciseItem(prompt: "Mali: Umulan ng yelo (snow) sa gitna ng mainit na tag-araw.", options: ["Sa malamig na taglamig lang umuulan ng yelo", "Madilim palagi ang tag-araw", "Tuwing Disyembre lang may tag-araw", "Mainit hawakan ang yelo (snow)"], correctAnswer: "Sa malamig na taglamig lang umuulan ng yelo", explanation: "Kailangan ng napakalamig na panahon para magka-yelo o snow."),
            ExerciseItem(prompt: "Mali: Hinugasan niya ang mga maruruming plato sa basurahan.", options: ["Sa sink hinuhugasan ang plato, hindi sa basurahan", "Para sa malilinis na damit ang basurahan", "Sa halamanan dapat hinuhugasan ang plato", "Puno ng malinis na tubig ang basurahan"], correctAnswer: "Sa sink hinuhugasan ang plato, hindi sa basurahan", explanation: "Tapunan ng dumi ang basurahan; sa lababo o sink hinuhugasan ang mga plato."),
            ExerciseItem(prompt: "Mali: Diniligan niya ang kanyang halaman ng isang balde ng buhangin.", options: ["Tubig ang kailangan ng halaman para lumaki, hindi buhangin", "Masyadong binabasa ng buhangin ang lupa", "Dapat puno ng bato ang halamanan", "Para sa pekeng halaman lang ang buhangin"], correctAnswer: "Tubig ang kailangan ng halaman para lumaki, hindi buhangin", explanation: "Tubig ang kailangan ng halaman para mabuhay; matutuyo ito sa buhangin.")
        ]
    )

    // MARK: - Easy Sequencing
    private static let easySequencing = Exercise(
        title: "Madaling Pagkakasunod-sunod",
        instructions: "Ayusin ang mga hakbang ng aktibidad sa tamang pagkakasunod-sunod.",
        section: .language,
        type: .sequencing,
        difficulty: .easy,
        items: [
            ExerciseItem(prompt: "Paggawa ng tinapay na tostado (toast)", options: ["Ilagay ang tinapay sa toaster", "Ibaon ang lever para mag-init", "Hintaying lumabas o tumalon ang tinapay", "Pahiran ng mantikilya ang tinapay"], correctAnswer: "Ilagay ang tinapay sa toaster | Ibaon ang lever para mag-init | Hintaying lumabas o tumalon ang tinapay | Pahiran ng mantikilya ang tinapay", explanation: "Ilagay ang tinapay, painitin, hintaying lumabas, saka pahiran ng mantikilya."),
            ExerciseItem(prompt: "Paghuhugas ng kamay", options: ["Basain ang mga kamay ng tubig", "Maglagay ng sabon at kuskusin ang mga palad", "Banlawan ang sabon ng tubig", "Patuyuin ang mga kamay gamit ang malinis na tuwalya"], correctAnswer: "Basain ang mga kamay ng tubig | Maglagay ng sabon at kuskusin ang mga palad | Banlawan ang sabon ng tubig | Patuyuin ang mga kamay gamit ang malinis na tuwalya", explanation: "Basain ang kamay, sabunin, banlawan, at patuyuin."),
            ExerciseItem(prompt: "Pagpapadala ng sulat", options: ["Isulat ang mensahe sa papel", "Ipasok ang sulat sa envelope", "Isulat ang address sa envelope", "Magdikit ng stamp at ihulog sa mailbox"], correctAnswer: "Isulat ang mensahe sa papel | Ipasok ang sulat sa envelope | Isulat ang address sa envelope | Magdikit ng stamp at ihulog sa mailbox", explanation: "Isulat ang sulat, ilagay sa sobre, isulat ang address, at padalhan ng selyo."),
            ExerciseItem(prompt: "Pagsisipilyo ng ngipin", options: ["Maglagay ng toothpaste sa sipilyo", "Sipilyuhin nang maayos ang mga ngipin", "Magmumog ng tubig", "Hugasan ang sipilyo at itabi ito"], correctAnswer: "Maglagay ng toothpaste sa sipilyo | Sipilyuhin nang maayos ang mga ngipin | Magmumog ng tubig | Hugasan ang sipilyo at itabi ito", explanation: "Maglagay ng toothpaste, sipilyuhin ang ngipin, magmumog, at linisin ang sipilyo."),
            ExerciseItem(prompt: "Paghahanda ng mainit na tsa (tea)", options: ["Magpakulo ng tubig sa takure", "Ilagay ang tea bag sa tasa", "Ibuhos ang mainit na tubig sa tasa", "Hayaang lumamig nang kaunti bago inumin"], correctAnswer: "Magpakulo ng tubig sa takure | Ilagay ang tea bag sa tasa | Ibuhos ang mainit na tubig sa tasa | Hayaang lumamig nang kaunti bago inumin", explanation: "Magpakulo ng tubig, ilagay ang tsa sa tasa, buhusan ng tubig, at inumin kapag sapat na ang lamig.")
        ]
    )

    // MARK: - Medium Word Association
    private static let mediumWordAssociation = Exercise(
        title: "Pag-uugnay ng Salita",
        instructions: "Piliin ang salita na may pinakamalapit na kaugnayan sa ibinigay na salita.",
        section: .language,
        type: .multipleChoice,
        difficulty: .medium,
        items: [
            ExerciseItem(prompt: "AKLATAN (LIBRARY)", options: ["Katahimikan", "Ingay", "Maraming Tao", "Laro"], correctAnswer: "Katahimikan", explanation: "Ang aklatan ay lugar ng pag-aaral kung saan kinakailangan ang katahimikan."),
            ExerciseItem(prompt: "OSPITAL", options: ["Paggaling", "Bakasyon", "Pamimili", "Pagluluto"], correctAnswer: "Paggaling", explanation: "Ang ospital ay pasilidad para gamutin ang mga may karamdaman upang gumaling."),
            ExerciseItem(prompt: "PALIPARAN (AIRPORT)", options: ["Pag-alis", "Pagtulog", "Paghahalaman", "Pinta"], correctAnswer: "Pag-alis", explanation: "Ang paliparan ay lugar para sa pag-alis o paglipad ng mga eroplano."),
            ExerciseItem(prompt: "DISYERTO", options: ["Tuyot", "Bagyo", "Gubat", "Dagat"], correctAnswer: "Tuyot", explanation: "Ang disyerto ay isang napakatuyong lugar dahil sa kawalan ng ulan."),
            ExerciseItem(prompt: "KASAL", options: ["Singsing", "Pagsusulit", "Opisina", "Susi"], correctAnswer: "Singsing", explanation: "Ang singsing ay tradisyonal na simbolo ng pag-iisang dibdib sa kasal."),
            ExerciseItem(prompt: "BUKID", options: ["Ani", "Lungsod", "Opisina", "Pabrika"], correctAnswer: "Ani", explanation: "Ang bukid ay lugar ng pagsasaka kung saan nakukuha ang ani."),
            ExerciseItem(prompt: "KUSINA", options: ["Resipe", "Kama", "Kotse", "Shower"], correctAnswer: "Resipe", explanation: "Ang pagluluto sa kusina ay karaniwang sumusunod sa resipe o hakbang."),
            ExerciseItem(prompt: "BUNDOK", options: ["Taluktok", "Silong", "Kalsada", "Disyerto"], correctAnswer: "Taluktok", explanation: "Ang taluktok o peak ang pinakamataas na bahagi ng bundok."),
            ExerciseItem(prompt: "HUKUMAN", options: ["Katarungan", "Teatro", "Kusina", "Pamilihan"], correctAnswer: "Katarungan", explanation: "Ang hukuman ay nagpapasya ayon sa batas para sa katarungan."),
            ExerciseItem(prompt: "OPISINA", options: ["Deadline", "Baybayin", "Kama", "Picnic"], correctAnswer: "Deadline", explanation: "Ang trabaho sa opisina ay nakatutok sa oras ng pagtatapos ng gawain (deadline)."),
            ExerciseItem(prompt: "TEATRO", options: ["Entablado", "Kusina", "Lansangan", "Gubat"], correctAnswer: "Entablado", explanation: "Ang entablado o stage ang lugar kung saan nagtatanghal ang mga aktor."),
            ExerciseItem(prompt: "GUBAT", options: ["Kalikasan", "Lungsod", "Disyerto", "Semento"], correctAnswer: "Kalikasan", explanation: "Ang gubat ay binubuo ng mga puno at mga hayop na bahagi ng kalikasan."),
            ExerciseItem(prompt: "LABORATORYO", options: ["Eksperimento", "Pagluluto", "Pagsayaw", "Pamimili"], correctAnswer: "Eksperimento", explanation: "Ang laboratoryo ay lugar para sa siyentipikong pag-aaral o eksperimento."),
            ExerciseItem(prompt: "MUSEO", options: ["Eksibisyon", "Pelikula", "Palakasan", "Pagluluto"], correctAnswer: "Eksibisyon", explanation: "Sa museo itinatanghal ang mga makasaysayang bagay sa pamamagitan ng eksibisyon."),
            ExerciseItem(prompt: "DENTISTA", options: ["Sira sa Ngipin", "Gupit", "Tiket", "Pagluluto"], correctAnswer: "Sira sa Ngipin", explanation: "Ang dentista ang nangangalaga sa ngipin tulad ng pagsasaayos ng sira o cavity.")
        ]
    )

    // MARK: - Medium Homonyms
    private static let mediumHomonyms = Exercise(
        title: "Katamtamang Homonimya",
        instructions: "Piliin ang tamang pares ng salita upang makumpleto ang mga pangungusap.",
        section: .language,
        type: .homonym,
        difficulty: .medium,
        items: [
            ExerciseItem(prompt: "[basa / basa] Ang basang papel ay mahirap sulatan. Ang ___ ng libro ay nakakatalino.", options: ["basa...basa", "basa...basa", "basa...basa", "basa...basa"], correctAnswer: "basa...basa", explanation: "Ang unang 'basa' ay may tubig (wet); ang ikalawang 'basa' ay pagbabasa (read)."),
            ExerciseItem(prompt: "[puno / puno] Ang malaking ___ ng mangga ay namumunga. Ang baso ay ___ ng tubig.", options: ["puno...puno", "puno...puno", "puno...puno", "puno...puno"], correctAnswer: "puno...puno", explanation: "Ang unang 'puno' ay halaman (tree); ang ikalawang 'puno' ay walang bakante (full)."),
            ExerciseItem(prompt: "[kita / kita] Magkano ang ___ mo sa trabaho ngayong araw? Doon ko ___ ang nawawalang aso.", options: ["kita...kita", "kita...kita", "kita...kita", "kita...kita"], correctAnswer: "kita...kita", explanation: "Ang unang 'kita' ay sahod o income; ang ikalawang 'kita' ay nakita (seen)."),
            ExerciseItem(prompt: "[tuyo / tuyo] Ang basang damit ay ___ na. Masarap kumain ng ___ na isda sa almusal.", options: ["tuyo...tuyo", "tuyo...tuyo", "tuyo...tuyo", "tuyo...tuyo"], correctAnswer: "tuyo...tuyo", explanation: "Ang unang 'tuyo' ay dry; ang ikalawang 'tuyo' ay ang uri ng isda (salted dried fish)."),
            ExerciseItem(prompt: "[gabi / gabi] Masarap ang ___ na hinalo sa sinigang. Madilim na kapag ___ na.", options: ["gabi...gabi", "gabi...gabi", "gabi...gabi", "gabi...gabi"], correctAnswer: "gabi...gabi", explanation: "Ang unang 'gabi' ay ang halamang-ugat (taro); ang ikalawang 'gabi' ay ang gabi pagkatapos ng hapon (night).")
        ]
    )

    // MARK: - Easy Complete the Saying
    private static let easyCompleteSaying = Exercise(
        title: "Madaling mga Salawikain",
        instructions: "Piliin ang salita na tamang nakakumpleto sa salawikain.",
        section: .language,
        type: .sentenceCompletion,
        difficulty: .easy,
        items: [
            ExerciseItem(prompt: "Aanhin pa ang damo, kung patay na ang ___", options: ["kabayo", "baka", "aso", "pusa"], correctAnswer: "kabayo", explanation: "Walang silbi ang tulong o ibinibigay kung huli na ang lahat."),
            ExerciseItem(prompt: "Habang maikli ang kumot, matutong ___", options: ["mamaluktot", "matulog", "bumangon", "umiyak"], correctAnswer: "mamaluktot", explanation: "Dapat mamuhay nang naaayon sa kakayahan habang kapos pa."),
            ExerciseItem(prompt: "Kung may tinanim, may ___", options: ["aanihin", "kakainin", "itatapon", "ibili"], correctAnswer: "aanihin", explanation: "Ang nagsisipag at naghahanda ay may makukuhang magandang bunga sa huli."),
            ExerciseItem(prompt: "Ang hindi lumingon sa pinanggalingan, hindi makakarating sa ___", options: ["paroroonan", "bahay", "paaralan", "trabaho"], correctAnswer: "paroroonan", explanation: "Dapat magpasalamat at tandaan ang mga taong tumulong sa atin upang magtagumpay."),
            ExerciseItem(prompt: "Pag habang may buhay, may ___", options: ["pag-asa", "pagsubok", "gawain", "hirap"], correctAnswer: "pag-asa", explanation: "Habang tayo ay nabubuhay, laging may pagkakataon na magbago o umayos ang sitwasyon."),
            ExerciseItem(prompt: "Nasa Diyos ang awa, nasa tao ang ___", options: ["gawa", "isip", "tiwala", "salita"], correctAnswer: "gawa", explanation: "Kailangang kumilos ng tao at huwag umasa lamang sa himala."),
            ExerciseItem(prompt: "Ang sakit ng kalingkingan, dama ng buong ___", options: ["katawan", "kamay", "pamilya", "bayan"], correctAnswer: "katawan", explanation: "Ang problema ng isang miyembro ay nararamdaman at nakakaapekto sa buong grupo."),
            ExerciseItem(prompt: "Daig ng maagap ang ___", options: ["masipag", "matalino", "mayaman", "malakas"], correctAnswer: "masipag", explanation: "Ang taong maagang kumilos ay nakalalamang sa kahit na sino."),
            ExerciseItem(prompt: "Bunsod ng katamaran, ang tao ay ___", options: ["nagugutom", "yumayaman", "sumasaya", "natututo"], correctAnswer: "nagugutom", explanation: "Ang hindi nagtatrabaho ay walang makakain."),
            ExerciseItem(prompt: "Kung ano ang puno, siya ang ___", options: ["bunga", "dahon", "sanga", "ugat"], correctAnswer: "bunga", explanation: "Ang katangian ng magulang ay makikita rin sa kanilang anak."),
            ExerciseItem(prompt: "Ang lalaking nagigipit, sa patalim ___", options: ["kumakapit", "tumatakbo", "lumalaban", "tumatalon"], correctAnswer: "kumakapit", explanation: "Ang taong desperado ay handang gumawa ng delikadong bagay."),
            ExerciseItem(prompt: "Walang matigas na tinapay sa mainit na ___", options: ["kape", "tubig", "tsokolate", "gatas"], correctAnswer: "kape", explanation: "Nalalamuyot ang matigas na puso sa pamamagitan ng mabuting pakikitungo."),
            ExerciseItem(prompt: "Walang lihim na hindi ___", options: ["nabubunyag", "nawawala", "sumasabog", "natatago"], correctAnswer: "nabubunyag", explanation: "Lahat ng sikreto ay nalalaman din pagdating ng tamang panahon."),
            ExerciseItem(prompt: "Ang taong walang kibo, nasa loob ang ___", options: ["kulo", "galit", "takot", "saya"], correctAnswer: "kulo", explanation: "Ang tahimik na tao ay may nakatagong matinding emosyon o plano."),
            ExerciseItem(prompt: "Magbiro ka na sa lasing, huwag lang sa bagong ___", options: ["gising", "tuyo", "salta", "kasal"], correctAnswer: "gising", explanation: "Madaling magalit ang taong bagong gising kaya huwag itong bibiruin.")
        ]
    )

    // MARK: - Hard Complete the Saying
    private static let hardCompleteSaying = Exercise(
        title: "Mahirap na mga Salawikain",
        instructions: "Piliin ang salita na tamang nakakumpleto sa salawikain.",
        section: .language,
        type: .sentenceCompletion,
        difficulty: .hard,
        items: [
            ExerciseItem(prompt: "Kapag ang ilog ay matahimik, asahan mong ito ay ___", options: ["malalim", "mababaw", "marumi", "tuyo"], correctAnswer: "malalim", explanation: "Ang taong tahimik ay malalim mag-isip at may malawak na kaalaman."),
            ExerciseItem(prompt: "Bago ka bumati sa matang may muta, pahirin mo muna ang iyong ___", options: ["mukha", "mata", "kamay", "luha"], correctAnswer: "mata", explanation: "Bago mo punahin ang pagkakamali ng iba, tingnan mo muna ang sarili mo."),
            ExerciseItem(prompt: "Walang humawak ng guryon na hindi ___", options: ["napasuko", "nasugatan", "natuwa", "nadala"], correctAnswer: "nasugatan", explanation: "Ang bawat pagsubok sa buhay o malaking ambisyon ay may kaakibat na sakripisyo."),
            ExerciseItem(prompt: "Ang bawat gubat ay may ___", options: ["ahas", "bato", "halaman", "ibon"], correctAnswer: "ahas", explanation: "Kahit saan ka pumunta ay may mga taong mapanlinlang kaya mag-ingat."),
            ExerciseItem(prompt: "Walang lumura sa langit na hindi sa mukha ___", options: ["tumatama", "pumapatak", "bumabagsak", "dumudura"], correctAnswer: "tumatama", explanation: "Ang paggawa ng masama sa kapwa o sa nakatataas ay babalik din sa iyo."),
            ExerciseItem(prompt: "Kung hindi ukol, hindi ___", options: ["bubukol", "darating", "mangyayari", "aabot"], correctAnswer: "bubukol", explanation: "Kung ang isang bagay ay hindi nakalaan sa iyo, hindi mo ito makukuha."),
            ExerciseItem(prompt: "Ang lumalakad nang matulin, kung matinik ay ___", options: ["malalim", "mababaw", "masakit", "madugo"], correctAnswer: "malalim", explanation: "Ang nagmamadali sa pagpapasya ay nakagagawa ng malubhang pagkakamali."),
            ExerciseItem(prompt: "Huwag mong bilangin ang sisu (chick) hangga't hindi ___", options: ["napipisa", "lumalabas", "lumalaki", "tumutubo"], correctAnswer: "napipisa", explanation: "Huwag munang umasa sa tagumpay hangga't hindi pa ito nangyayari."),
            ExerciseItem(prompt: "Ang pili nang pili, nauuwi sa ___", options: ["bungi", "wala", "tira", "mali"], correctAnswer: "bungi", explanation: "Ang taong napakapili ay madalas na nakakakuha ng pinakamasamang opsyon sa huli."),
            ExerciseItem(prompt: "Walang lumapit sa kalan na hindi ___", options: ["naulingan", "nainitan", "nasunog", "nabasa"], correctAnswer: "naulingan", explanation: "Ang taong sumasama sa masamang barkada ay tiyak na maiimpluwensyahan."),
            ExerciseItem(prompt: "Walang matiyagang alipin na hindi ___", options: ["nagtagumpay", "nakalaya", "naging panginoon", "yumaman"], correctAnswer: "nakalaya", explanation: "Ang pagtitiis at pagsisikap ay nagbubunga ng kalayaan o kaginhawaan."),
            ExerciseItem(prompt: "Magbiro ka na sa bagong gising, huwag lang sa gutom na ___", options: ["aso", "tao", "tigre", "lalaki"], correctAnswer: "aso", explanation: "Maging maingat sa pakikitungo sa mga taong nasa kritikal na kalagayan."),
            ExerciseItem(prompt: "Ang bawat palayok ay may katapat na ___", options: ["suklob", "pinggan", "kutsara", "takip"], correctAnswer: "suklob", explanation: "Lahat ng tao ay may katugma o kapareha na laan para sa kanya."),
            ExerciseItem(prompt: "Magsisi ka man at huli, wala nang ___", options: ["mangyayari", "saysay", "lunas", "gamot"], correctAnswer: "saysay", explanation: "Ang pagsisisi sa huli ay walang kapararakan o hindi na mababago ang nangyari.")
        ]
    )
}
