import Foundation

struct TagalogCognitionExerciseData {
    static let allExercises: [Exercise] = [
        storyRecall,
        numberSequences,
        causeAndEffect,
        emotions,
        whatsWrong,
    ]

    private static let storyRecall = Exercise(
        id: UUID(),
        title: "Paggunita sa Kwento",
        instructions: "Basahin ang maikling kuwento pagkatapos ay sagutin ang tanong tungkol dito.",
        section: .cognition,
        type: .multipleChoice,
        difficulty: .medium,
        items: [
            ExerciseItem(id: UUID(), prompt: "Pumunta si Maria sa Seafood City para bumili ng gatas at tinapay. Nakalimutan niya ang wallet niya sa kitchen counter. Ano ang iniwan ni Maria sa bahay?", options: ["Yung wallet niya", "Ang kanyang mga susi", "Ang shopping list niya", "Yung phone niya"], correctAnswer: "Yung wallet niya", explanation: "Ang kuwento ay nagsasaad na nakalimutan niya ang kanyang wallet sa counter ng kusina."),
            ExerciseItem(id: UUID(), prompt: "Maagang nagising si Jose noong Sabado para mangisda. Nakahuli siya ng isang malaking trout ngunit kinailangan itong itapon dahil napakaliit nito. Anong uri ng isda ang nahuli ni Jose?", options: ["Isang trout", "Isang salmon", "Isang bass", "Isang hito"], correctAnswer: "Isang trout", explanation: "Ang kuwento ay nagsasaad na nakahuli siya ng isang malaking trout."),
            ExerciseItem(id: UUID(), prompt: "Ipinarada ni Juan ang kanyang asul na kotse sa ilalim ng isang makulimlim na puno ng oak. Pagbalik niya, nakita niyang natatakpan na ng dilaw na dahon ang sasakyan. Ano ang kulay ng sasakyan ni Juan?", options: ["Asul", "Dilaw", "Pula", "Berde"], correctAnswer: "Asul", explanation: "Ang kuwento ay nagsasaad na ipinarada ni Juan ang kanyang asul na kotse."),
            ExerciseItem(id: UUID(), prompt: "Nagluto si Elena ng chocolate cake para sa birthday party ng kanyang anak. Naglagay siya ng sampung pulang kandila sa cake. Ilang kandila ang inilagay ni Elena sa cake?", options: ["Sampu", "lima", "Walo", "Labindalawa"], correctAnswer: "Sampu", explanation: "Nakasaad sa kuwento na naglagay siya ng sampung pulang kandila sa cake."),
            ExerciseItem(id: UUID(), prompt: "Pumunta si Juan sa post office para magpadala ng package sa kanyang kapatid sa Daly City. Sinabi sa kanya ng klerk na darating ito sa Martes. Saan nakatira ang kapatid ni Juan?", options: ["Daly City", "New York", "Boston", "Miami"], correctAnswer: "Daly City", explanation: "Ang kuwento ay nagsasaad na nagpadala siya ng isang pakete sa kanyang kapatid sa Daly City."),
            ExerciseItem(id: UUID(), prompt: "Bumili si Elena ng bagong pares ng running shoes kahapon. Ang mga ito ay maliwanag na berde na may mga puting guhit. Anong kulay ang bagong running shoes ni Elena?", options: ["Matingkad na berde", "Asul", "Pula", "Itim"], correctAnswer: "Matingkad na berde", explanation: "Ang kuwento ay nagsasabi na ang sapatos ay maliwanag na berde na may puting guhit."),
            ExerciseItem(id: UUID(), prompt: "Naglalakad si Jose sa parke nang umulan. Binuksan niya ang kanyang dilaw na payong para manatiling tuyo. Anong kulay ang ginamit na payong ni Jose?", options: ["Dilaw", "Pula", "Asul", "Itim"], correctAnswer: "Dilaw", explanation: "Ang sabi sa kuwento ay binuksan niya ang kanyang dilaw na payong."),
            ExerciseItem(id: UUID(), prompt: "Ang lokal na panaderya ay sarado noong Lunes para sa pagkukumpuni. Nagplano silang magbukas muli noong Martes ng umaga sa alas-sais. Anong araw sarado ang panaderya?", options: ["Lunes", "Martes", "Miyerkules", "Linggo"], correctAnswer: "Lunes", explanation: "Ang kuwento ay nagsabi na ang panaderya ay sarado noong Lunes."),
            ExerciseItem(id: UUID(), prompt: "Tumawag si Maria ng tubero dahil tumutulo ang kanyang lababo sa kusina. Dumating ang tubero sa loob ng isang oras at inayos ang tubo. Bakit tumawag si Maria ng tubero?", options: ["Tumutulo ang lababo niya", "Nasira ang kanyang kalan", "Patay ang ilaw niya", "Naka-lock ang pinto niya"], correctAnswer: "Tumutulo ang lababo niya", explanation: "Ang sabi sa kuwento ay tumawag siya ng tubero dahil tumutulo ang kanyang lababo sa kusina."),
            ExerciseItem(id: UUID(), prompt: "Inilibot ni Juan ang kanyang aso, si Max, sa paligid ng bloke. Nakita ni Max ang isang ardilya at tumahol ito ng malakas. Ano ang pangalan ng aso ni Juan?", options: ["Max", "Buddy", "Charlie", "Rocky"], correctAnswer: "Max", explanation: "Ang kuwento ay nagsasaad na nilakad ni Juan ang kanyang aso, si Max."),
            ExerciseItem(id: UUID(), prompt: "Si Elena ay nagluluto ng gulay na sopas para sa hapunan. Napagtanto niya na wala na siyang karot, kaya patatas na lang ang ginamit niya. Anong sangkap ang naubos ni Elena?", options: ["Mga karot", "Patatas", "Mga sibuyas", "Kintsay"], correctAnswer: "Mga karot", explanation: "Ang kuwento ay nagsasaad na napagtanto niya na wala na siya sa mga karot."),
            ExerciseItem(id: UUID(), prompt: "Umorder si Jose ng pepperoni pizza at isang bote ng soda para sa tanghalian. Ang kabuuang halaga ay labinlimang dolyar. Magkano ang baon ni Jose?", options: ["Labinlimang dolyar", "Sampung dolyar", "Dalawampung dolyares", "Labindalawang dolyar"], correctAnswer: "Labinlimang dolyar", explanation: "Ang kuwento ay nagsasaad na ang kabuuang halaga ay labinlimang dolyar."),
            ExerciseItem(id: UUID(), prompt: "Pumunta si Maria sa silid-aklatan para manghiram ng libro tungkol sa paghahalaman. Nanghiram din siya ng DVD tungkol sa kasaysayan. Ano ang paksa ng aklat na hiniram ni Maria?", options: ["Paghahalaman", "Kasaysayan", "Pagluluto", "Paglalakbay"], correctAnswer: "Paghahalaman", explanation: "Nakasaad sa kuwento na humiram siya ng libro tungkol sa paghahalaman."),
            ExerciseItem(id: UUID(), prompt: "Sumakay si Juan ng tren sa umaga patungo sa lungsod para sa isang pakikipanayam sa trabaho. Ang kanyang tren ay naantala ng labinlimang minuto dahil sa pagpapanatili ng track. Bakit naantala ang tren?", options: ["Pagpapanatili ng track", "Isang malakas na bagyo", "Isang pagkawala ng kuryente", "Isang nawawalang tauhan"], correctAnswer: "Pagpapanatili ng track", explanation: "Ang kuwento ay nagsasaad na ang tren ay naantala dahil sa pagpapanatili ng track."),
            ExerciseItem(id: UUID(), prompt: "Pumunta si Elena sa garden center para bumili ng pulang rosas. Naubos na ang mga ito, kaya bumili na lang siya ng pink na carnation. Anong bulaklak ang nabili ni Elena?", options: ["Mga kulay rosas na carnation", "Mga pulang rosas", "Dilaw na tulips", "Mga puting liryo"], correctAnswer: "Mga kulay rosas na carnation", explanation: "Ang kuwento ay nagsasaad na binili niya ang mga pink na carnation sa halip.")
        ]
    )

    private static let numberSequences = Exercise(
        id: UUID(),
        title: "Mga Pagkakasunod-sunod ng Numero",
        instructions: "Anong numero ang susunod sa sequence?",
        section: .cognition,
        type: .multipleChoice,
        difficulty: .medium,
        items: [
            ExerciseItem(id: UUID(), prompt: "2, 4, 6, 8, ___", options: ["9", "10", "11", "12"], correctAnswer: "10", explanation: "Ang sequence ay tumataas sa pamamagitan ng pagdaragdag ng 2 sa bawat oras."),
            ExerciseItem(id: UUID(), prompt: "5, 10, 15, 20, ___", options: ["21", "22", "25", "30"], correctAnswer: "25", explanation: "Tumataas ang pagkakasunod-sunod sa pamamagitan ng pagdaragdag ng 5 sa bawat oras."),
            ExerciseItem(id: UUID(), prompt: "10, 20, 30, 40, ___", options: ["45", "50", "60", "70"], correctAnswer: "50", explanation: "Tumataas ang pagkakasunod-sunod sa pamamagitan ng pagdaragdag ng 10 sa bawat pagkakataon."),
            ExerciseItem(id: UUID(), prompt: "3, 6, 9, 12, ___", options: ["13", "14", "15", "16"], correctAnswer: "15", explanation: "Ang pagkakasunod-sunod ay tumataas sa pamamagitan ng pagdaragdag ng 3 sa bawat oras."),
            ExerciseItem(id: UUID(), prompt: "9, 8, 7, 6, ___", options: ["4", "5", "7", "8"], correctAnswer: "5", explanation: "Bumababa ang pagkakasunod-sunod sa pamamagitan ng pagbabawas ng 1 sa bawat pagkakataon."),
            ExerciseItem(id: UUID(), prompt: "20, 18, 16, 14, ___", options: ["12", "13", "10", "15"], correctAnswer: "12", explanation: "Bumababa ang pagkakasunod-sunod sa pamamagitan ng pagbabawas ng 2 sa bawat oras."),
            ExerciseItem(id: UUID(), prompt: "1, 3, 5, 7, ___", options: ["8", "9", "10", "11"], correctAnswer: "9", explanation: "Ang pagkakasunud-sunod ng mga kakaibang numero ay tumataas sa pamamagitan ng pagdaragdag ng 2 sa bawat oras."),
            ExerciseItem(id: UUID(), prompt: "4, 8, 12, 16, ___", options: ["18", "20", "22", "24"], correctAnswer: "20", explanation: "Ang sequence ay tumataas sa pamamagitan ng pagdaragdag ng 4 sa bawat oras."),
            ExerciseItem(id: UUID(), prompt: "50, 45, 40, 35, ___", options: ["25", "28", "30", "32"], correctAnswer: "30", explanation: "Ang pagkakasunod-sunod ay bumababa sa pamamagitan ng pagbabawas ng 5 sa bawat oras."),
            ExerciseItem(id: UUID(), prompt: "100, 90, 80, 70, ___", options: ["50", "60", "65", "75"], correctAnswer: "60", explanation: "Ang pagkakasunod-sunod ay bumababa sa pamamagitan ng pagbabawas ng 10 sa bawat oras."),
            ExerciseItem(id: UUID(), prompt: "11, 22, 33, 44, ___", options: ["50", "53", "55", "66"], correctAnswer: "55", explanation: "Tumataas ang pagkakasunod-sunod sa pamamagitan ng pagdaragdag ng 11 sa bawat oras."),
            ExerciseItem(id: UUID(), prompt: "8, 10, 12, 14, ___", options: ["15", "16", "17", "18"], correctAnswer: "16", explanation: "Ang sequence ay tumataas sa pamamagitan ng pagdaragdag ng 2 sa bawat oras."),
            ExerciseItem(id: UUID(), prompt: "12, 15, 18, 21, ___", options: ["22", "23", "24", "25"], correctAnswer: "24", explanation: "Ang pagkakasunod-sunod ay tumataas sa pamamagitan ng pagdaragdag ng 3 sa bawat oras."),
            ExerciseItem(id: UUID(), prompt: "30, 27, 24, 21, ___", options: ["18", "19", "20", "17"], correctAnswer: "18", explanation: "Ang pagkakasunod-sunod ay bumababa sa pamamagitan ng pagbabawas ng 3 sa bawat oras."),
            ExerciseItem(id: UUID(), prompt: "7, 14, 21, 28, ___", options: ["30", "32", "35", "42"], correctAnswer: "35", explanation: "Tumataas ang pagkakasunod-sunod sa pamamagitan ng pagdaragdag ng 7 sa bawat oras."),
            ExerciseItem(id: UUID(), prompt: "40, 36, 32, 28, ___", options: ["20", "24", "26", "27"], correctAnswer: "24", explanation: "Ang pagkakasunod-sunod ay bumababa sa pamamagitan ng pagbabawas ng 4 sa bawat oras."),
            ExerciseItem(id: UUID(), prompt: "6, 12, 18, 24, ___", options: ["26", "28", "30", "32"], correctAnswer: "30", explanation: "Tumataas ang pagkakasunod-sunod sa pamamagitan ng pagdaragdag ng 6 sa bawat oras."),
            ExerciseItem(id: UUID(), prompt: "15, 20, 25, 30, ___", options: ["31", "32", "35", "40"], correctAnswer: "35", explanation: "Tumataas ang pagkakasunod-sunod sa pamamagitan ng pagdaragdag ng 5 sa bawat oras."),
            ExerciseItem(id: UUID(), prompt: "90, 80, 70, 60, ___", options: ["40", "50", "55", "45"], correctAnswer: "50", explanation: "Ang pagkakasunod-sunod ay bumababa sa pamamagitan ng pagbabawas ng 10 sa bawat oras."),
            ExerciseItem(id: UUID(), prompt: "13, 15, 17, 19, ___", options: ["20", "21", "22", "23"], correctAnswer: "21", explanation: "Ang sequence ay tumataas sa pamamagitan ng pagdaragdag ng 2 sa bawat oras.")
        ]
    )

    private static let causeAndEffect = Exercise(
        id: UUID(),
        title: "Sanhi at Bunga",
        instructions: "Piliin ang pinaka-malamang na resulta ng sitwasyong inilarawan.",
        section: .cognition,
        type: .multipleChoice,
        difficulty: .medium,
        items: [
            ExerciseItem(id: UUID(), prompt: "Mag-iwan ka ng ice cream sa counter ng kusina sa loob ng dalawang oras sa isang mainit na araw. Ano ang mangyayari?", options: ["Ito ay nagiging mas mahirap", "Natutunaw ito", "Nagbabago ito ng kulay", "Naglalaho ito"], correctAnswer: "Natutunaw ito", explanation: "Ang init ay nagdudulot ng pagkatunaw ng frozen ice cream."),
            ExerciseItem(id: UUID(), prompt: "Nakalimutan mong diligan ang iyong halaman sa loob ng tatlong linggo. Ano ang malamang na resulta?", options: ["Tumutubo ito ng mga bulaklak", "Ito ay nananatiling berde", "Ito ay nalalanta at natutuyo", "Nagiging asul ito"], correctAnswer: "Ito ay nalalanta at natutuyo", explanation: "Ang mga halaman ay nangangailangan ng tubig upang mabuhay; kung wala ito, sila ay nalalanta at natutuyo."),
            ExerciseItem(id: UUID(), prompt: "Isang madilim na ulap ng bagyo ang humaharang sa araw, at dumadagundong ang kulog. Ano ang posibleng susunod na mangyayari?", options: ["Uulan", "Lalong mag-iinit", "Babagsak agad ang snow", "Lalabas ang mga bituin"], correctAnswer: "Uulan", explanation: "Ang mga ulap ng bagyo at kulog ay mga tagapagpahiwatig ng paparating na pag-ulan."),
            ExerciseItem(id: UUID(), prompt: "Ibinabagsak mo ang isang mangkok na salamin sa isang matigas na sahig na baldosa. Ano ang malamang na resulta?", options: ["Tumatalbog ito pabalik", "Nagbabago ito ng kulay", "Naputol ito", "Ito ay nagiging tubig"], correctAnswer: "Naputol ito", explanation: "Ang salamin ay marupok at nababasag kapag nalaglag sa matitigas na ibabaw."),
            ExerciseItem(id: UUID(), prompt: "Maglagay ka ng isang slice ng tinapay sa toaster at iwanan ito sa pinakamataas na setting. Ano ang mangyayari?", options: ["Ito ay nagiging basa", "Nasusunog ito at nagiging itim", "Ito ay nananatiling malambot at puti", "Naglalaho ito"], correctAnswer: "Nasusunog ito at nagiging itim", explanation: "Ang sobrang init sa isang toaster ay masusunog ang tinapay."),
            ExerciseItem(id: UUID(), prompt: "Iiwan mong bukas ang mga headlight ng kotse sa magdamag. Ano ang mangyayari sa umaga?", options: ["Mas mabilis ang takbo ng sasakyan", "Mamamatay ang baterya", "Magbabago ang kulay ng sasakyan", "Agad na magsisimula ang makina"], correctAnswer: "Mamamatay ang baterya", explanation: "Ang pag-iwan sa mga ilaw na nakabukas ay nakakaubos ng lakas ng baterya."),
            ExerciseItem(id: UUID(), prompt: "Isang malakas na snowstorm ang bumagsak sa buong gabi, na nagdedeposito ng anim na pulgada ng snow. Ano ang nangyayari sa mga kalsada?", options: ["Nanatili silang tuyo", "Sila ay nagiging madulas at nababalot ng niyebe", "Nagiging berde sila", "Sila ay sumingaw"], correctAnswer: "Sila ay nagiging madulas at nababalot ng niyebe", explanation: "Naiipon ang bumabagsak na snow sa mga kalsada, na ginagawang mapanganib ang pagmamaneho."),
            ExerciseItem(id: UUID(), prompt: "Maglagay ka ng tray na puno ng tubig sa freezer. Ano ang mangyayari pagkatapos ng ilang oras?", options: ["Kumukulo ang tubig", "Ang tubig ay nagiging yelo", "Ang tubig ay sumingaw", "Nagbabago ang kulay ng tubig"], correctAnswer: "Ang tubig ay nagiging yelo", explanation: "Ang nagyeyelong temperatura ay ginagawang solidong yelo ang likidong tubig."),
            ExerciseItem(id: UUID(), prompt: "Nagsusuot ka ng isang pares ng makapal na lana na medyas at mabibigat na bota sa isang mainit na araw ng tag-araw. Ano ang nangyayari sa iyong mga paa?", options: ["Nakaramdam sila ng lamig", "Nanatili silang tuyo", "Nagiinit sila at pinagpapawisan", "Nagiging asul sila"], correctAnswer: "Nagiinit sila at pinagpapawisan", explanation: "Ang mga makapal na layer ay nagpapanatili ng init, na nagiging sanhi ng pagpapawis sa mainit na panahon."),
            ExerciseItem(id: UUID(), prompt: "Ang isang tao ay hindi natutulog nang 24 oras nang diretso. Ano ang malamang na mararamdaman nila?", options: ["Napaka-energetic", "Pagod at inaantok", "Gutom", "Sobrang saya"], correctAnswer: "Pagod at inaantok", explanation: "Ang kakulangan sa tulog ay nagreresulta sa pagkapagod at pagkaantok."),
            ExerciseItem(id: UUID(), prompt: "Nagdagdag ka ng asukal sa isang tasa ng mainit na tsaa at ihalo ito. Ano ang mangyayari sa asukal?", options: ["Ito ay nagiging yelo", "Nawala ito sa tasa", "Natutunaw ito sa tsaa", "Nasusunog ito"], correctAnswer: "Natutunaw ito sa tsaa", explanation: "Ang paghalo ng asukal sa mainit na likido ay nagiging sanhi ng pagkatunaw nito."),
            ExerciseItem(id: UUID(), prompt: "Lumabas ka sa isang malakas na ulan na walang payong o kapote. Ano ang resulta?", options: ["Manatiling tuyo ka", "Basang basa ang damit mo", "Nagiging asul ka", "Mas mainit ang pakiramdam mo"], correctAnswer: "Basang basa ang damit mo", explanation: "Ang tubig-ulan ay direktang bumagsak sa iyo, na nagpapabasa sa iyong mga damit."),
            ExerciseItem(id: UUID(), prompt: "Nag-ihip ka ng hangin sa isang lobo hanggang sa mapuno ito. Ano ang mangyayari?", options: ["Lumilipad ito sa buwan", "Ito pops", "Ito ay nagiging isang ibon", "Lumiliit ito"], correctAnswer: "Ito pops", explanation: "Ang sobrang presyon ng hangin ay lumampas sa kapasidad ng lobo, na nagiging sanhi ng pag-pop nito."),
            ExerciseItem(id: UUID(), prompt: "Pinapatay mo ang lahat ng ilaw sa isang silid na walang bintana sa gabi. Ano ang mangyayari?", options: ["Ang silid ay nagiging mas maliwanag", "Nagiging ganap na madilim ang silid", "Nagiging berde ang kwarto", "Napuno ng liwanag ang silid"], correctAnswer: "Nagiging ganap na madilim ang silid", explanation: "Walang pinagmumulan ng liwanag ang nagreresulta sa kabuuang kadiliman."),
            ExerciseItem(id: UUID(), prompt: "Hindi ka nag-aaral o naghahanda para sa isang mahirap na pagsusulit. Ano ang malamang na resulta?", options: ["Makakakuha ka ng perpektong marka", "Mahina ang performance mo", "Nakalimutan mo ang iyong pangalan", "Kinansela ang pagsusulit"], correctAnswer: "Mahina ang performance mo", explanation: "Dahil sa kakulangan sa paghahanda, hindi malamang na makapasa sa mahihirap na pagsubok.")
        ]
    )

    private static let emotions = Exercise(
        id: UUID(),
        title: "Anong Emosyon Ito?",
        instructions: "Basahin ang sitwasyon at piliin ang emosyon na malamang na nararamdaman ng tao.",
        section: .cognition,
        type: .multipleChoice,
        difficulty: .easy,
        items: [
            ExerciseItem(id: UUID(), prompt: "Nalaman na lang ni Elena na nanalo siya sa unang pwesto sa isang kompetisyon. Ano ang nararamdaman niya?", options: ["Malungkot", "Galit", "Masaya", "Natatakot"], correctAnswer: "Masaya", explanation: "Ang pagkapanalo sa isang kompetisyon ay isang kapana-panabik at masayang kaganapan."),
            ExerciseItem(id: UUID(), prompt: "Nakarinig si Juan ng kakaiba at malakas na ingay sa ibaba ng hatinggabi. Ano ang nararamdaman niya?", options: ["Masaya", "Natatakot", "Nababagot", "Excited"], correctAnswer: "Natatakot", explanation: "Ang mga hindi inaasahang ingay sa dilim ay nagdudulot ng takot o pangamba."),
            ExerciseItem(id: UUID(), prompt: "Ang matalik na kaibigan ni Mary ay lumipat sa ibang estado na malayo. Ano ang pakiramdam ni Mary?", options: ["Malungkot", "Galit", "Excited", "Nagseselos"], correctAnswer: "Malungkot", explanation: "Ang pagpaalam sa malalapit na kaibigan ay nagdudulot ng kalungkutan."),
            ExerciseItem(id: UUID(), prompt: "May pumutol sa harap ni John sa mahabang pila sa tindahan. Ano ang pakiramdam ni John?", options: ["Masaya", "Natatakot", "Inis", "Nahihiya"], correctAnswer: "Inis", explanation: "Ang bastos na pag-uugali mula sa iba ay karaniwang nagdudulot ng inis o pagkabigo."),
            ExerciseItem(id: UUID(), prompt: "Magsasalita na si Emily sa harap ng napakaraming audience. Ano ang nararamdaman niya?", options: ["Kinakabahan", "Nababagot", "Malungkot", "Galit"], correctAnswer: "Kinakabahan", explanation: "Ang pagsasalita sa publiko ay karaniwang nagdudulot ng nerbiyos o pagkabalisa."),
            ExerciseItem(id: UUID(), prompt: "Kinansela ang flight ni Juan, naantala ang kanyang bakasyon ng dalawang araw. Ano ang nararamdaman niya?", options: ["Frustrated", "Masaya", "Natatakot", "Proud"], correctAnswer: "Frustrated", explanation: "Ang mga pagkansela na nakakagambala sa mga plano ay humahantong sa pagkabigo."),
            ExerciseItem(id: UUID(), prompt: "Ang anak ni Lisa ay nagtapos sa unibersidad na may pinakamataas na karangalan. Ano ang nararamdaman ni Lisa?", options: ["Proud", "Nagseselos", "Malungkot", "Natatakot"], correctAnswer: "Proud", explanation: "Ang makitang nagtagumpay ang mga miyembro ng pamilya ay nakadarama ng pagmamalaki."),
            ExerciseItem(id: UUID(), prompt: "Ang isang klerk ay nagpapaliwanag ng isang kumplikadong anyo sa ikaapat na pagkakataon, ngunit hindi pa rin maintindihan ni Juan. Ano ang pakiramdam ni Juan?", options: ["Nalilito", "Masaya", "Excited", "Proud"], correctAnswer: "Nalilito", explanation: "Ang kawalan ng kakayahang maunawaan ang impormasyon ay humahantong sa pagkalito."),
            ExerciseItem(id: UUID(), prompt: "Mahigit dalawang oras nang naghihintay si Jose sa isang tahimik na waiting room na walang nababasa. Ano ang nararamdaman niya?", options: ["Nababagot", "Natatakot", "Galit", "Masaya"], correctAnswer: "Nababagot", explanation: "Ang mahabang paghihintay na walang pampasigla ay nagdudulot ng pagkabagot."),
            ExerciseItem(id: UUID(), prompt: "Ang pamilya ni Ellen ay nagbigay sa kanya ng isang sorpresang birthday party kasama ang lahat ng kanyang mga kaibigan. Ano ang nararamdaman niya?", options: ["Nagulat", "Galit", "Malungkot", "Natatakot"], correctAnswer: "Nagulat", explanation: "Ang hindi inaasahang pagdiriwang ay humahantong sa pagkagulat."),
            ExerciseItem(id: UUID(), prompt: "Isang ligaw na aso ang sumugod at agresibong tumahol kay Karen habang naglalakad. Ano ang nararamdaman niya?", options: ["Natatakot", "Masaya", "Nababagot", "Proud"], correctAnswer: "Natatakot", explanation: "Ang mga agresibong hayop ay nagdudulot ng takot o sindak."),
            ExerciseItem(id: UUID(), prompt: "Nawala ni William ang kanyang singsing sa kasal habang naghahalaman. Ano ang nararamdaman niya?", options: ["Galit", "Excited", "Nababagot", "Kalmado"], correctAnswer: "Galit", explanation: "Ang pagkawala ng isang sentimental na bagay ay nakababahala at nagpapagalit sa isa."),
            ExerciseItem(id: UUID(), prompt: "Nakatanggap si Patricia ng magandang card at bulaklak mula sa kanyang mga apo. Ano ang nararamdaman niya?", options: ["Minahal", "Galit", "Natatakot", "Nalilito"], correctAnswer: "Minahal", explanation: "Ang mabait na kilos ng pamilya ay nagpapadama sa isang tao na minamahal at pinahahalagahan."),
            ExerciseItem(id: UUID(), prompt: "Ang Seafood City ay wala sa partikular na tinapay na gusto ni Jose, kaya kailangan niyang bumili ng isa pang brand. Ano ang nararamdaman niya?", options: ["Bahagyang nadismaya", "Takot na takot", "Galit na galit", "Tuwang-tuwa"], correctAnswer: "Bahagyang nadismaya", explanation: "Ang hindi pagkuha ng isang maliit na kagustuhan ay humahantong sa banayad na pagkabigo."),
            ExerciseItem(id: UUID(), prompt: "Buong hapon si Juan sa paggawa ng isang bookshelf, at ito ay naging perpekto. Ano ang nararamdaman niya?", options: ["Nasiyahan", "Malungkot", "Natatakot", "Nababagot"], correctAnswer: "Nasiyahan", explanation: "Ang matagumpay na pagkumpleto ng isang gawain ay humahantong sa kasiyahan."),
            ExerciseItem(id: UUID(), prompt: "Aksidenteng nalaglag ni Elena ang isang tray ng inumin sa isang tahimik na restaurant. Ano ang nararamdaman niya?", options: ["Nahihiya", "Masaya", "Galit", "Nababagot"], correctAnswer: "Nahihiya", explanation: "Ang pagkuha ng negatibong atensyon ng publiko sa isang pagkakamali ay nagdudulot ng kahihiyan."),
            ExerciseItem(id: UUID(), prompt: "Si Jose ay pupunta sa kanyang unang paglalakbay sa Hawaii bukas ng umaga. Ano ang nararamdaman niya?", options: ["Excited", "Malungkot", "Galit", "Nababagot"], correctAnswer: "Excited", explanation: "Ang pag-asam ng isang masayang bakasyon ay nagdudulot ng kaguluhan."),
            ExerciseItem(id: UUID(), prompt: "Nakauwi nang ligtas ang pusa ni Susan matapos mawala ng tatlong araw. Ano ang nararamdaman niya?", options: ["Nakakagaan ng loob", "Galit", "Natatakot", "Nalilito"], correctAnswer: "Nakakagaan ng loob", explanation: "Ang isang positibong resolusyon sa isang nakababahalang sitwasyon ay nagdudulot ng kaginhawahan."),
            ExerciseItem(id: UUID(), prompt: "Ang koneksyon sa internet ay patuloy na bumababa bawat limang minuto habang sinusubukan ni Juan na magtrabaho. Ano ang nararamdaman niya?", options: ["Naiirita", "Natatakot", "Masaya", "Nababagot"], correctAnswer: "Naiirita", explanation: "Ang paulit-ulit na maliliit na abala ay nagdudulot ng pangangati."),
            ExerciseItem(id: UUID(), prompt: "Si Elena ay naligo ng mahaba at mainit-init pagkatapos ng nakakapagod na araw. Ano ang nararamdaman niya?", options: ["Nakakarelax", "Galit", "Natatakot", "Kinakabahan"], correctAnswer: "Nakakarelax", explanation: "Ang mga maiinit na paliguan at downtime ay nakakatulong sa isang tao na maging relaxed.")
        ]
    )

    private static let whatsWrong = Exercise(
        id: UUID(),
        title: "Ano ang Mali Dito?",
        instructions: "Piliin kung ano ang mali o imposible sa pangungusap.",
        section: .cognition,
        type: .multipleChoice,
        difficulty: .medium,
        items: [
            ExerciseItem(id: UUID(), prompt: "Si John ay kumain ng almusal sa hatinggabi bago matulog.", options: ["Ang mga tao ay hindi kumakain ng pagkain", "Ang almusal ay pagkain sa umaga, hindi hatinggabi", "Hindi dapat matulog si John", "Ang hatinggabi ay sa hapon"], correctAnswer: "Ang almusal ay pagkain sa umaga, hindi hatinggabi", explanation: "Ang almusal ay ayon sa kahulugan ng pagkain sa umaga na pumuputol sa magdamag na pag-aayuno."),
            ExerciseItem(id: UUID(), prompt: "Tinahol ng aso ang kartero at pagkatapos ay lumipad sa bubong para manghuli ng ibon.", options: ["Ang mga aso ay hindi tumatahol", "Hindi makakalipad ang mga aso", "Ang mga mailmen ay hindi naghahatid ng mail", "Hindi lumilipad ang mga ibon"], correctAnswer: "Hindi makakalipad ang mga aso", explanation: "Ang mga aso ay walang pakpak at hindi makakalipad."),
            ExerciseItem(id: UUID(), prompt: "Isinuot ni Elena ang kanyang mainit na winter coat at guwantes para lumangoy sa outdoor pool noong Hulyo.", options: ["Ang mga tao ay hindi lumangoy sa Hulyo", "Hindi ka nagsusuot ng winter coat at guwantes para lumangoy", "Walang mga panlabas na pool", "Ang mga coat ay isinusuot sa tag-araw"], correctAnswer: "Hindi ka nagsusuot ng winter coat at guwantes para lumangoy", explanation: "Ang paglangoy ay nangangailangan ng kasuotang panlangoy, at ang kagamitan sa taglamig ay hindi angkop para sa maligamgam na tubig."),
            ExerciseItem(id: UUID(), prompt: "Umabot sa labintatlo ang orasan sa dingding, kaya alam ni Juan na oras na para sa kanyang kape sa umaga.", options: ["Ang mga orasan ay hindi napupunta sa mga dingding", "Ang mga karaniwang orasan ay umabot lamang sa labindalawang oras", "Ang kape ay hindi inumin sa umaga", "Hindi umiinom ng kape si Juan"], correctAnswer: "Ang mga karaniwang orasan ay umabot lamang sa labindalawang oras", explanation: "Ang mga tradisyunal na orasan ay nagpapakita ng mga oras mula isa hanggang alas-dose."),
            ExerciseItem(id: UUID(), prompt: "Sumakay si Paul sa kanyang bisikleta sa malalim na lawa para bisitahin ang kanyang kaibigan.", options: ["Ang mga bisikleta ay hindi maaaring sumakay sa tubig", "Ang mga lawa ay walang isda", "Hindi bumibisita ang magkakaibigan", "Ang mga bisikleta ay walang pedal"], correctAnswer: "Ang mga bisikleta ay hindi maaaring sumakay sa tubig", explanation: "Ang mga bisikleta ay mga sasakyang panlupa at lumulubog sa tubig."),
            ExerciseItem(id: UUID(), prompt: "Nagpakulo si Elena ng ice cubes sa isang kaldero para gawing malamig na tubig na maiinom.", options: ["Ang mga ice cube ay wala", "Ang kumukulong ice cubes ay ginagawa silang mainit na tubig, hindi malamig", "Ang mga kaldero ay hindi maaaring maglaman ng yelo", "Ang pag-inom ng tubig ay hindi malusog"], correctAnswer: "Ang kumukulong ice cubes ay ginagawa silang mainit na tubig, hindi malamig", explanation: "Ang kumukulo ay nagpapainit ng likido, na nagpapainit sa halip na malamig."),
            ExerciseItem(id: UUID(), prompt: "Umakyat ang isda sa puno upang makatakas sa gutom na pusa.", options: ["Ang mga isda ay hindi maaaring umakyat sa mga puno", "Ang mga pusa ay hindi kumakain ng isda", "Ang mga puno ay hindi tumutubo ng mga dahon", "Ang mga isda ay nakatira sa mga puno"], correctAnswer: "Ang mga isda ay hindi maaaring umakyat sa mga puno", explanation: "Ang mga isda ay nabubuhay sa tubig at walang mga paa upang umakyat sa mga puno."),
            ExerciseItem(id: UUID(), prompt: "Gumamit si Juan ng tinidor para inumin ang kanyang chicken noodle soup.", options: ["Ang mga tinidor ay hindi maaaring maglaman ng likidong sopas", "Ang sopas ay hindi gawa sa manok", "Dapat gumamit si Juan ng kutsilyo", "Ang sopas ay hindi kinakain kasama ng mga kagamitan"], correctAnswer: "Ang mga tinidor ay hindi maaaring maglaman ng likidong sopas", explanation: "Ang mga tinidor ay may mga tines na nagpapalabas ng mga likido; ang sopas ay nangangailangan ng isang kutsara."),
            ExerciseItem(id: UUID(), prompt: "Dahil malakas ang ulan, isinabit ni Elena ang basang damit sa sampayan sa labas upang matuyo.", options: ["Hindi nababasa ng ulan ang mga bagay", "Hindi matutuyo ang mga damit sa labas sa ulan", "Ang mga damit ay ginagamit lamang sa loob ng bahay", "Hindi nagsusuot ng damit si Elena"], correctAnswer: "Hindi matutuyo ang mga damit sa labas sa ulan", explanation: "Pinipigilan ng ulan na basa ang mga damit, na pinipigilan itong matuyo."),
            ExerciseItem(id: UUID(), prompt: "Ligtas na lumapag ang eroplano sa paliparan, at lahat ng pasahero ay lumabas sa riles ng tren.", options: ["Ang mga eroplano ay hindi dumarating sa mga paliparan", "Ang mga pasahero ay hindi bumibiyahe sa mga eroplano", "Ang mga paliparan ay walang riles ng tren sa mga landing gate", "Ang mga tren ay hindi tumatakbo sa mga riles"], correctAnswer: "Ang mga paliparan ay walang riles ng tren sa mga landing gate", explanation: "Ang mga eroplano ay dumarating sa mga runway at gate, hindi sa mga riles ng tren."),
            ExerciseItem(id: UUID(), prompt: "Binuksan ni Elena ang aircon para mas uminit ang sala.", options: ["Ang mga air conditioner ay nagpapalamig sa mga silid, hindi nila pinainit ang mga ito", "Walang dingding ang mga sala", "Walang sariling bahay si Elena", "Ang mga air conditioner ay hindi gumagamit ng kuryente"], correctAnswer: "Ang mga air conditioner ay nagpapalamig sa mga silid, hindi nila pinainit ang mga ito", explanation: "Ang mga air conditioner ay idinisenyo upang babaan ang temperatura, hindi itaas ang mga ito."),
            ExerciseItem(id: UUID(), prompt: "Hinabol ng kuneho ang malaking kulay abong lobo sa kagubatan.", options: ["Ang mga kuneho ay hindi nakatira sa kagubatan", "Ang mga lobo ay hindi tumatakbo", "Ang mga kuneho ay hindi humahabol sa mga lobo", "Ang mga lobo ay hindi kulay abo"], correctAnswer: "Ang mga kuneho ay hindi humahabol sa mga lobo", explanation: "Ang mga lobo ay mga mandaragit at ang mga kuneho ay biktima; ang mga kuneho ay tumakas mula sa mga lobo."),
            ExerciseItem(id: UUID(), prompt: "Bumili si Jose ng isang pares ng leather na sapatos para sa kanyang mga kamay upang panatilihing mainit ang mga ito sa taglamig.", options: ["Ang mga sapatos ay isinusuot sa paa, hindi kamay", "Ang balat ay hindi ginagamit para sa sapatos", "Hindi nilalamig ang mga kamay", "Hindi malamig ang taglamig"], correctAnswer: "Ang mga sapatos ay isinusuot sa paa, hindi kamay", explanation: "Ang mga guwantes o guwantes ay isinusuot sa mga kamay; ang sapatos ay para sa paa."),
            ExerciseItem(id: UUID(), prompt: "Ang araw ay sumisikat sa hatinggabi, na nagbibigay liwanag sa kalangitan ng umaga.", options: ["Ang araw ay sumisikat sa umaga, hindi hatinggabi", "Ang hatinggabi ay sa hapon", "Hindi maliwanag ang araw", "Madilim ang umaga"], correctAnswer: "Ang araw ay sumisikat sa umaga, hindi hatinggabi", explanation: "Ang hatinggabi ay ang kalagitnaan ng gabi kung kailan hindi nakikita ang araw."),
            ExerciseItem(id: UUID(), prompt: "Binuksan ni Maria ang telebisyon para makinig sa paborito niyang istasyon ng radyo.", options: ["Ang mga telebisyon ay nagpapakita ng video, hindi sila mga radyo", "Ang mga radyo ay hindi nagpapatugtog ng musika", "Hindi gusto ni Maria ang musika", "Ang mga telebisyon ay walang mga speaker"], correctAnswer: "Ang mga telebisyon ay nagpapakita ng video, hindi sila mga radyo", explanation: "Ang telebisyon ay isang display device; ang mga istasyon ng radyo ay ibinobrodkast sa mga radyo.")
        ]
    )

}
