import Foundation

struct UkrainianLanguageExerciseData {
    static let allExercises: [Exercise] = [
        Exercise(
            id: UUID(),
            title: "Викресліть зайве (легке)",
            instructions: "Торкніться слова, яке НЕ підходить до групи.",
            section: .language,
            type: .categoryCrossOut,
            trackedType: nil,
            difficulty: .easy,
            items: [
                ExerciseItem(id: UUID(), prompt: "ЯБЛУКО, ГРУША, МОРКВА, СЛИВА", options: ["ЯБЛУКО", "ГРУША", "МОРКВА", "СЛИВА"], correctAnswer: "МОРКВА", explanation: "Морква — це овоч, а решта — фрукти."),
                ExerciseItem(id: UUID(), prompt: "МАШИНА, АВТОБУС, ЛОЖКА, ВАНТАЖІВКА", options: ["МАШИНА", "АВТОБУС", "ЛОЖКА", "ВАНТАЖІВКА"], correctAnswer: "ЛОЖКА", explanation: "Ложка — не транспортний засіб, а столовий прилад."),
                ExerciseItem(id: UUID(), prompt: "ЗОЛОТО, КІТ, ПЕС, ПТАХ", options: ["ЗОЛОТО", "КІТ", "ПЕС", "ПТАХ"], correctAnswer: "ЗОЛОТО", explanation: "Золото — метал, а решта — тварини."),
                ExerciseItem(id: UUID(), prompt: "СОРОЧКА, ШТАНИ, ВИДЕЛКА, КАПЕЛЮХ", options: ["СОРОЧКА", "ШТАНИ", "ВИДЕЛКА", "КАПЕЛЮХ"], correctAnswer: "ВИДЕЛКА", explanation: "Виделка — столовий прилад, а не одяг."),
                ExerciseItem(id: UUID(), prompt: "СТІЛЕЦЬ, СТІЛ, ЯБЛУКО, ЛІЖКО", options: ["СТІЛЕЦЬ", "СТІЛ", "ЯБЛУКО", "ЛІЖКО"], correctAnswer: "ЯБЛУКО", explanation: "Яблуко — це їжа, а решта — меблі."),
                ExerciseItem(id: UUID(), prompt: "МОЛОТОК, КЛЮЧ, ПОДУШКА, ДРИЛЬ", options: ["МОЛОТОК", "КЛЮЧ", "ПОДУШКА", "ДРИЛЬ"], correctAnswer: "ПОДУШКА", explanation: "Подушка — не інструмент, а річ для сну."),
                ExerciseItem(id: UUID(), prompt: "СІЧЕНЬ, БЕРЕЗЕНЬ, П'ЯТНИЦЯ, ТРАВЕНЬ", options: ["СІЧЕНЬ", "БЕРЕЗЕНЬ", "П'ЯТНИЦЯ", "ТРАВЕНЬ"], correctAnswer: "П'ЯТНИЦЯ", explanation: "П'ятниця — день тижня, а решта — місяці."),
                ExerciseItem(id: UUID(), prompt: "ПАРИЖ, ЛОНДОН, ЮПІТЕР, РИМ", options: ["ПАРИЖ", "ЛОНДОН", "ЮПІТЕР", "РИМ"], correctAnswer: "ЮПІТЕР", explanation: "Юпітер — планета, а решта — міста."),
                ExerciseItem(id: UUID(), prompt: "ПЕС, КІТ, ДЕРЕВО, МИША", options: ["ПЕС", "КІТ", "ДЕРЕВО", "МИША"], correctAnswer: "ДЕРЕВО", explanation: "Дерево — рослина, а решта — тварини."),
                ExerciseItem(id: UUID(), prompt: "ОКО, НІС, МАШИНА, ВУХО", options: ["ОКО", "НІС", "МАШИНА", "ВУХО"], correctAnswer: "МАШИНА", explanation: "Машина — не частина тіла."),
                ExerciseItem(id: UUID(), prompt: "МОЛОКО, СІК, ХЛІБ, ВОДА", options: ["МОЛОКО", "СІК", "ХЛІБ", "ВОДА"], correctAnswer: "ХЛІБ", explanation: "Хліб — їжа, а решта — напої."),
                ExerciseItem(id: UUID(), prompt: "ДИВАН, ЛІЖКО, ПЛИТА, КРІСЛО", options: ["ДИВАН", "ЛІЖКО", "ПЛИТА", "КРІСЛО"], correctAnswer: "ПЛИТА", explanation: "Плита — кухонний прилад, а решта — меблі для сидіння чи сну."),
                ExerciseItem(id: UUID(), prompt: "ТРОЯНДА, ТЮЛЬПАН, РОМАШКА, МАШИНА", options: ["ТРОЯНДА", "ТЮЛЬПАН", "РОМАШКА", "МАШИНА"], correctAnswer: "МАШИНА", explanation: "Машина — не квітка."),
                ExerciseItem(id: UUID(), prompt: "РУЧКА, ОЛІВЕЦЬ, КРЕЙДА, ВИДЕЛКА", options: ["РУЧКА", "ОЛІВЕЦЬ", "КРЕЙДА", "ВИДЕЛКА"], correctAnswer: "ВИДЕЛКА", explanation: "Виделка — не те, чим пишуть."),
                ExerciseItem(id: UUID(), prompt: "ДИВАН, КИЛИМ, ЛАМПА, КУРКА", options: ["ДИВАН", "КИЛИМ", "ЛАМПА", "КУРКА"], correctAnswer: "КУРКА", explanation: "Курка — жива істота, а не предмет домашнього вжитку."),
                ExerciseItem(id: UUID(), prompt: "СОНЦЕ, ДОЩ, ВІТЕР, СОРОЧКА", options: ["СОНЦЕ", "ДОЩ", "ВІТЕР", "СОРОЧКА"], correctAnswer: "СОРОЧКА", explanation: "Сорочка — одяг, а не погодне явище."),
                ExerciseItem(id: UUID(), prompt: "ТАРІЛКА, МИСКА, ЧАШКА, МАШИНА", options: ["ТАРІЛКА", "МИСКА", "ЧАШКА", "МАШИНА"], correctAnswer: "МАШИНА", explanation: "Машина — не посуд."),
                ExerciseItem(id: UUID(), prompt: "АВТОБУС, ПОТЯГ, ЧОВЕН, КІТ", options: ["АВТОБУС", "ПОТЯГ", "ЧОВЕН", "КІТ"], correctAnswer: "КІТ", explanation: "Кіт — тварина, а не транспорт."),
                ExerciseItem(id: UUID(), prompt: "КАПЕЛЮХ, ШКАРПЕТКИ, ВЗУТТЯ, КАСТРУЛЯ", options: ["КАПЕЛЮХ", "ШКАРПЕТКИ", "ВЗУТТЯ", "КАСТРУЛЯ"], correctAnswer: "КАСТРУЛЯ", explanation: "Каструля — кухонний посуд, а не одяг."),
                ExerciseItem(id: UUID(), prompt: "КІТ, ПЕС, ПТАХ, ВАНТАЖІВКА", options: ["КІТ", "ПЕС", "ПТАХ", "ВАНТАЖІВКА"], correctAnswer: "ВАНТАЖІВКА", explanation: "Вантажівка — транспорт, а не тварина."),
                ExerciseItem(id: UUID(), prompt: "БЕРЕЗЕНЬ, КВІТЕНЬ, ВІВТОРОК, ЧЕРВЕНЬ", options: ["БЕРЕЗЕНЬ", "КВІТЕНЬ", "ВІВТОРОК", "ЧЕРВЕНЬ"], correctAnswer: "ВІВТОРОК", explanation: "Вівторок — день тижня, а решта — місяці."),
                ExerciseItem(id: UUID(), prompt: "ЧЕРВОНИЙ, СИНІЙ, СТІЛ, ЗЕЛЕНИЙ", options: ["ЧЕРВОНИЙ", "СИНІЙ", "СТІЛ", "ЗЕЛЕНИЙ"], correctAnswer: "СТІЛ", explanation: "Стіл — предмет, а не колір."),
                ExerciseItem(id: UUID(), prompt: "НІЖ, ВИДЕЛКА, ЛОЖКА, ЛІЖКО", options: ["НІЖ", "ВИДЕЛКА", "ЛОЖКА", "ЛІЖКО"], correctAnswer: "ЛІЖКО", explanation: "Ліжко — меблі, а решта — столові прилади."),
                ExerciseItem(id: UUID(), prompt: "ОРЕЛ, ЯСТРУБ, СОВА, РИБА", options: ["ОРЕЛ", "ЯСТРУБ", "СОВА", "РИБА"], correctAnswer: "РИБА", explanation: "Риба — не птах."),
                ExerciseItem(id: UUID(), prompt: "ПЕНІ, НІКЕЛЬ, ДАЙМ, КУРТКА", options: ["ПЕНІ", "НІКЕЛЬ", "ДАЙМ", "КУРТКА"], correctAnswer: "КУРТКА", explanation: "Куртка — одяг, а решта — американські монети."),
                ExerciseItem(id: UUID(), prompt: "ЛЕВ, ВЕДМІДЬ, ТИГР, ПІЦА", options: ["ЛЕВ", "ВЕДМІДЬ", "ТИГР", "ПІЦА"], correctAnswer: "ПІЦА", explanation: "Піца — їжа, а не тварина."),
                ExerciseItem(id: UUID(), prompt: "ЯБЛУКО, БАНАН, МОРКВА, ВИНОГРАД", options: ["ЯБЛУКО", "БАНАН", "МОРКВА", "ВИНОГРАД"], correctAnswer: "МОРКВА", explanation: "Морква — овоч, а решта — фрукти."),
                ExerciseItem(id: UUID(), prompt: "СТІЛЕЦЬ, СТІЛ, ПИСЬМОВИЙ СТІЛ, ДЕЛЬФІН", options: ["СТІЛЕЦЬ", "СТІЛ", "ПИСЬМОВИЙ СТІЛ", "ДЕЛЬФІН"], correctAnswer: "ДЕЛЬФІН", explanation: "Дельфін — морська тварина, а не меблі."),
                ExerciseItem(id: UUID(), prompt: "СОЛОВЕЙ, ОРЕЛ, ЛОСОСЬ, ПАПУГА", options: ["СОЛОВЕЙ", "ОРЕЛ", "ЛОСОСЬ", "ПАПУГА"], correctAnswer: "ЛОСОСЬ", explanation: "Лосось — риба, а решта — птахи."),
                ExerciseItem(id: UUID(), prompt: "БЕЙСБОЛ, ТЕНІС, ШАХИ, ФУТБОЛ", options: ["БЕЙСБОЛ", "ТЕНІС", "ШАХИ", "ФУТБОЛ"], correctAnswer: "ШАХИ", explanation: "Шахи — настільна гра, а решта — спортивні ігри з фізичним навантаженням."),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Викресліть зайве (складне)",
            instructions: "Торкніться слова, яке НЕ підходить до групи.",
            section: .language,
            type: .categoryCrossOut,
            trackedType: nil,
            difficulty: .hard,
            items: [
                ExerciseItem(id: UUID(), prompt: "ПОРІВНЯННЯ, МЕТАФОРА, ГІПЕРБОЛА, АБЗАЦ", options: ["ПОРІВНЯННЯ", "МЕТАФОРА", "ГІПЕРБОЛА", "АБЗАЦ"], correctAnswer: "АБЗАЦ", explanation: "Абзац — частина структури тексту, а не художній прийом."),
                ExerciseItem(id: UUID(), prompt: "СТЕГНОВА, ВЕЛИКОГОМІЛКОВА, ПРОМЕНЕВА, РОГІВКА", options: ["СТЕГНОВА", "ВЕЛИКОГОМІЛКОВА", "ПРОМЕНЕВА", "РОГІВКА"], correctAnswer: "РОГІВКА", explanation: "Рогівка — частина ока, а решта — кістки."),
                ExerciseItem(id: UUID(), prompt: "БЕТГОВЕН, МОЦАРТ, ПІКАССО, ШОПЕН", options: ["БЕТГОВЕН", "МОЦАРТ", "ПІКАССО", "ШОПЕН"], correctAnswer: "ПІКАССО", explanation: "Пікассо — художник, а решта — композитори."),
                ExerciseItem(id: UUID(), prompt: "КАРДИГАН, ПІДЖАК, ВОДОЛАЗКА, ТУФЛІ", options: ["КАРДИГАН", "ПІДЖАК", "ВОДОЛАЗКА", "ТУФЛІ"], correctAnswer: "ТУФЛІ", explanation: "Туфлі — взуття, а решта — одяг для верхньої частини тіла."),
                ExerciseItem(id: UUID(), prompt: "ТЕМЗА, НІЛ, АМАЗОНКА, ЕВЕРЕСТ", options: ["ТЕМЗА", "НІЛ", "АМАЗОНКА", "ЕВЕРЕСТ"], correctAnswer: "ЕВЕРЕСТ", explanation: "Еверест — гора, а решта — річки."),
                ExerciseItem(id: UUID(), prompt: "МЕМУАРИ, БІОГРАФІЯ, АВТОБІОГРАФІЯ, СОНЕТ", options: ["МЕМУАРИ", "БІОГРАФІЯ", "АВТОБІОГРАФІЯ", "СОНЕТ"], correctAnswer: "СОНЕТ", explanation: "Сонет — вірш, а решта — розповіді про життя людини."),
                ExerciseItem(id: UUID(), prompt: "ІНСУЛІН, АДРЕНАЛІН, ЕСТРОГЕН, ІБУПРОФЕН", options: ["ІНСУЛІН", "АДРЕНАЛІН", "ЕСТРОГЕН", "ІБУПРОФЕН"], correctAnswer: "ІБУПРОФЕН", explanation: "Ібупрофен — синтетичний препарат, а решта — гормони, які виробляє організм."),
                ExerciseItem(id: UUID(), prompt: "ЦЕЛЬСІЙ, ФАРЕНГЕЙТ, КЕЛЬВІН, ДЕЦИБЕЛ", options: ["ЦЕЛЬСІЙ", "ФАРЕНГЕЙТ", "КЕЛЬВІН", "ДЕЦИБЕЛ"], correctAnswer: "ДЕЦИБЕЛ", explanation: "Децибел вимірює гучність звуку, а не температуру."),
                ExerciseItem(id: UUID(), prompt: "ПРИСЯЖНІ, СУДДЯ, ПРИСТАВ, ПОЗИВАЧ", options: ["ПРИСЯЖНІ", "СУДДЯ", "ПРИСТАВ", "ПОЗИВАЧ"], correctAnswer: "ПОЗИВАЧ", explanation: "Позивач — сторона у справі, а решта — працівники й учасники судового складу."),
                ExerciseItem(id: UUID(), prompt: "СОНЕТ, ХАЙКУ, БАЛАДА, ПРОЗА", options: ["СОНЕТ", "ХАЙКУ", "БАЛАДА", "ПРОЗА"], correctAnswer: "ПРОЗА", explanation: "Проза — не поезія, а решта — поетичні форми."),
                ExerciseItem(id: UUID(), prompt: "СОПРАНО, АЛЬТ, ТЕНОР, ДИРИГЕНТ", options: ["СОПРАНО", "АЛЬТ", "ТЕНОР", "ДИРИГЕНТ"], correctAnswer: "ДИРИГЕНТ", explanation: "Диригент керує оркестром, а решта — види співочих голосів."),
                ExerciseItem(id: UUID(), prompt: "ІМПРЕСІОНІЗМ, СЮРРЕАЛІЗМ, КУБІЗМ, ДЖАЗ", options: ["ІМПРЕСІОНІЗМ", "СЮРРЕАЛІЗМ", "КУБІЗМ", "ДЖАЗ"], correctAnswer: "ДЖАЗ", explanation: "Джаз — музичний жанр, а решта — напрями в образотворчому мистецтві."),
                ExerciseItem(id: UUID(), prompt: "СТОКГОЛЬМ, ОСЛО, КОПЕНГАГЕН, БРЮССЕЛЬ", options: ["СТОКГОЛЬМ", "ОСЛО", "КОПЕНГАГЕН", "БРЮССЕЛЬ"], correctAnswer: "БРЮССЕЛЬ", explanation: "Брюссель — столиця Бельгії, а решта — скандинавські столиці."),
                ExerciseItem(id: UUID(), prompt: "РУБІН, САПФІР, СМАРАГД, ГРАНІТ", options: ["РУБІН", "САПФІР", "СМАРАГД", "ГРАНІТ"], correctAnswer: "ГРАНІТ", explanation: "Граніт — гірська порода, а решта — дорогоцінне каміння."),
                ExerciseItem(id: UUID(), prompt: "АПЕНДИКС, ЖОВЧНИЙ МІХУР, ПІДШЛУНКОВА ЗАЛОЗА, СТЕГНОВА КІСТКА", options: ["АПЕНДИКС", "ЖОВЧНИЙ МІХУР", "ПІДШЛУНКОВА ЗАЛОЗА", "СТЕГНОВА КІСТКА"], correctAnswer: "СТЕГНОВА КІСТКА", explanation: "Стегнова кістка — частина скелета, а решта — внутрішні органи."),
                ExerciseItem(id: UUID(), prompt: "ВІОЛОНЧЕЛЬ, СКРИПКА, АРФА, ГОБОЙ", options: ["ВІОЛОНЧЕЛЬ", "СКРИПКА", "АРФА", "ГОБОЙ"], correctAnswer: "ГОБОЙ", explanation: "Гобой — духовий інструмент, а решта — струнні."),
                ExerciseItem(id: UUID(), prompt: "ФРЕСКА, МОЗАЇКА, ЛІТОГРАФІЯ, СОНАТА", options: ["ФРЕСКА", "МОЗАЇКА", "ЛІТОГРАФІЯ", "СОНАТА"], correctAnswer: "СОНАТА", explanation: "Соната — музичний твір, а решта — види образотворчого мистецтва."),
                ExerciseItem(id: UUID(), prompt: "АРХІПЕЛАГ, ФЬОРД, ПЛАТО, ДІАЛЕКТ", options: ["АРХІПЕЛАГ", "ФЬОРД", "ПЛАТО", "ДІАЛЕКТ"], correctAnswer: "ДІАЛЕКТ", explanation: "Діалект — різновид мови, а решта — географічні утворення."),
                ExerciseItem(id: UUID(), prompt: "МАГНІЙ, КАЛЬЦІЙ, КАЛІЙ, НАФТА", options: ["МАГНІЙ", "КАЛЬЦІЙ", "КАЛІЙ", "НАФТА"], correctAnswer: "НАФТА", explanation: "Нафта — викопне паливо, а решта — хімічні елементи, потрібні організму."),
                ExerciseItem(id: UUID(), prompt: "ФЛАМЕНКО, ТАНГО, ВАЛЬС, ОПЕРА", options: ["ФЛАМЕНКО", "ТАНГО", "ВАЛЬС", "ОПЕРА"], correctAnswer: "ОПЕРА", explanation: "Опера — вокальний сценічний жанр, а решта — танці."),
                ExerciseItem(id: UUID(), prompt: "АРТЕРІЯ, ВЕНА, КАПІЛЯР, СУХОЖИЛЛЯ", options: ["АРТЕРІЯ", "ВЕНА", "КАПІЛЯР", "СУХОЖИЛЛЯ"], correctAnswer: "СУХОЖИЛЛЯ", explanation: "Сухожилля з'єднує м'яз із кісткою, а решта — кровоносні судини."),
                ExerciseItem(id: UUID(), prompt: "ТУНДРА, ТАЙГА, САВАНА, ДЕЛЬТА", options: ["ТУНДРА", "ТАЙГА", "САВАНА", "ДЕЛЬТА"], correctAnswer: "ДЕЛЬТА", explanation: "Дельта — форма рельєфу в гирлі річки, а решта — природні зони."),
                ExerciseItem(id: UUID(), prompt: "ТАЙФУН, ЦИКЛОН, МУСОН, ЗЕМЛЕТРУС", options: ["ТАЙФУН", "ЦИКЛОН", "МУСОН", "ЗЕМЛЕТРУС"], correctAnswer: "ЗЕМЛЕТРУС", explanation: "Землетрус — рух земної кори, а решта — погодні явища."),
                ExerciseItem(id: UUID(), prompt: "ХРЯЩ, ЗВ'ЯЗКА, СУХОЖИЛЛЯ, НЕЙРОН", options: ["ХРЯЩ", "ЗВ'ЯЗКА", "СУХОЖИЛЛЯ", "НЕЙРОН"], correctAnswer: "НЕЙРОН", explanation: "Нейрон — нервова клітина, а решта — сполучні тканини."),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Закінчіть вислів",
            instructions: "Оберіть слово, яке правильно завершує відомий вислів чи прислів'я.",
            section: .language,
            type: .multipleChoice,
            trackedType: .completeTheSaying,
            difficulty: .hard,
            items: [
                ExerciseItem(id: UUID(), prompt: "Без труда нема ___", options: ["плода", "гриба", "хліба", "меду"], correctAnswer: "плода", explanation: "Прислів'я «Без труда нема плода» означає, що без праці не буде результату."),
                ExerciseItem(id: UUID(), prompt: "Не все те золото, що ___", options: ["блищить", "горить", "тяжіє", "цінне"], correctAnswer: "блищить", explanation: "Прислів'я «Не все те золото, що блищить» застерігає, що гарний вигляд не завжди свідчить про справжню цінність."),
                ExerciseItem(id: UUID(), prompt: "Тихіше їдеш — ___ будеш", options: ["далі", "швидше", "вище", "ближче"], correctAnswer: "далі", explanation: "Прислів'я каже, що обережність і спокій допомагають дістатися мети надійніше."),
                ExerciseItem(id: UUID(), prompt: "Сім разів відміряй, один раз ___", options: ["відріж", "скажи", "зашей", "заплати"], correctAnswer: "відріж", explanation: "Прислів'я порівнює з кравцем: спочатку треба все ретельно обміркувати, а потім діяти."),
                ExerciseItem(id: UUID(), prompt: "Хто рано встає, тому Бог ___", options: ["дає", "шле", "править", "несе"], correctAnswer: "дає", explanation: "Прислів'я хвалить тих, хто рано починає день і працьовитий."),
                ExerciseItem(id: UUID(), prompt: "Де тонко, там і ___", options: ["рветься", "ламається", "тріскає", "в'яне"], correctAnswer: "рветься", explanation: "Прислів'я означає, що найслабше місце підводить першим, як тонка нитка."),
                ExerciseItem(id: UUID(), prompt: "Краще пізно, ніж ___", options: ["ніколи", "зарано", "ніяк", "потім"], correctAnswer: "ніколи", explanation: "Прислів'я означає, що зробити щось із запізненням краще, ніж не зробити взагалі."),
                ExerciseItem(id: UUID(), prompt: "Не май сто рублів, а май сто ___", options: ["друзів", "коней", "хат", "гривень"], correctAnswer: "друзів", explanation: "Прислів'я вчить, що справжні друзі цінніші за гроші."),
                ExerciseItem(id: UUID(), prompt: "Яблуко від яблуні недалеко ___", options: ["падає", "росте", "висить", "цвіте"], correctAnswer: "падає", explanation: "Прислів'я означає, що діти зазвичай схожі на своїх батьків."),
                ExerciseItem(id: UUID(), prompt: "Нема диму без ___", options: ["вогню", "води", "вітру", "хмар"], correctAnswer: "вогню", explanation: "Прислів'я означає, що чутки зазвичай мають якусь підставу."),
                ExerciseItem(id: UUID(), prompt: "Що посієш, те й ___", options: ["пожнеш", "з'їси", "знайдеш", "купиш"], correctAnswer: "пожнеш", explanation: "Прислів'я означає, що результат залежить від того, що ти сам зробив."),
                ExerciseItem(id: UUID(), prompt: "Одна ластівка весни не ___", options: ["робить", "дає", "несе", "чекає"], correctAnswer: "робить", explanation: "Прислів'я означає, що один випадок ще не доводить закономірності."),
                ExerciseItem(id: UUID(), prompt: "Лежачого не ___", options: ["б'ють", "будять", "піднімають", "лякають"], correctAnswer: "б'ють", explanation: "Прислів'я закликає не добивати того, хто вже беззахисний або впав."),
                ExerciseItem(id: UUID(), prompt: "Слово — срібло, а мовчання — ___", options: ["золото", "залізо", "мідь", "скло"], correctAnswer: "золото", explanation: "Прислів'я каже, що вміння вчасно промовчати цінується ще дужче, ніж слово."),
                ExerciseItem(id: UUID(), prompt: "В гостях добре, а вдома ___", options: ["найкраще", "гірше", "тихо", "сумно"], correctAnswer: "найкраще", explanation: "Прислів'я означає, що рідна оселя дорожча за будь-яке гостювання."),
                ExerciseItem(id: UUID(), prompt: "Око за око, зуб за ___", options: ["зуб", "ніс", "вухо", "руку"], correctAnswer: "зуб", explanation: "Вислів означає помсту у відповідь рівною мірою."),
                ExerciseItem(id: UUID(), prompt: "Бідний, як церковна ___", options: ["миша", "свічка", "лавка", "дзвіниця"], correctAnswer: "миша", explanation: "Порівняння виникло з думки, що в церкві немає їжі, тож миші там нічого їсти. Воно означає надзвичайну бідність."),
                ExerciseItem(id: UUID(), prompt: "Впертий, як ___", options: ["баран", "кіт", "заєць", "горобець"], correctAnswer: "баран", explanation: "Баран у народних порівняннях уособлює впертість."),
                ExerciseItem(id: UUID(), prompt: "Хитрий, як ___", options: ["лис", "баран", "ведмідь", "кабан"], correctAnswer: "лис", explanation: "У народних казках і приказках лис славиться хитрістю."),
                ExerciseItem(id: UUID(), prompt: "Чекати, як манни ___", options: ["небесної", "золотої", "лісової", "морської"], correctAnswer: "небесної", explanation: "Вислів іде від біблійної манни, що падала з неба. Він означає дуже сильно чекати чогось."),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Синоніми (легкі)",
            instructions: "Оберіть слово, яке означає те саме, що й дане слово.",
            section: .language,
            type: .multipleChoice,
            trackedType: nil,
            difficulty: .easy,
            items: [
                ExerciseItem(id: UUID(), prompt: "Слово: ЗЛИЙ", options: ["щасливий", "розлючений", "спокійний", "сумний"], correctAnswer: "розлючений", explanation: "Розлючений — дуже злий, тобто близьке за значенням, але сильніше слово."),
                ExerciseItem(id: UUID(), prompt: "Слово: ХОЛОДНИЙ", options: ["теплий", "крижаний", "гарячий", "лагідний"], correctAnswer: "крижаний", explanation: "Крижаний — дуже холодний, як лід."),
                ExerciseItem(id: UUID(), prompt: "Слово: ВЕЛИКИЙ", options: ["крихітний", "чималий", "низький", "тонкий"], correctAnswer: "чималий", explanation: "Чималий означає досить великий за розміром."),
                ExerciseItem(id: UUID(), prompt: "Слово: ВТОМЛЕНИЙ", options: ["бадьорий", "пильний", "виснажений", "відпочилий"], correctAnswer: "виснажений", explanation: "Виснажений — дуже втомлений, без сил."),
                ExerciseItem(id: UUID(), prompt: "Слово: НАЛЯКАНИЙ", options: ["сміливий", "переляканий", "спокійний", "відважний"], correctAnswer: "переляканий", explanation: "Переляканий означає охоплений страхом, так само як і наляканий."),
                ExerciseItem(id: UUID(), prompt: "Слово: ДОБРИЙ", options: ["злий", "жорстокий", "лагідний", "грубий"], correctAnswer: "лагідний", explanation: "Лагідний — м'який, ніжний і доброзичливий."),
                ExerciseItem(id: UUID(), prompt: "Слово: ШВИДКИЙ", options: ["повільний", "бистрий", "ледачий", "млявий"], correctAnswer: "бистрий", explanation: "Бистрий означає такий, що рухається з великою швидкістю."),
                ExerciseItem(id: UUID(), prompt: "Слово: СТАРИЙ", options: ["молодий", "давній", "новий", "свіжий"], correctAnswer: "давній", explanation: "Давній означає такий, що існує з далеких часів, тобто старий."),
                ExerciseItem(id: UUID(), prompt: "Слово: БРУДНИЙ", options: ["чистий", "замурзаний", "охайний", "акуратний"], correctAnswer: "замурзаний", explanation: "Замурзаний — геть брудний, укритий брудом."),
                ExerciseItem(id: UUID(), prompt: "Слово: СВІТЛИЙ", options: ["тьмяний", "темний", "сяючий", "похмурий"], correctAnswer: "сяючий", explanation: "Сяючий — повний світла, а отже, дуже світлий."),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Синоніми (складні)",
            instructions: "Оберіть слово, яке означає те саме, що й дане слово.",
            section: .language,
            type: .multipleChoice,
            trackedType: nil,
            difficulty: .hard,
            items: [
                ExerciseItem(id: UUID(), prompt: "Слово: МЕЛАНХОЛІЙНИЙ", options: ["радісний", "скорботний", "збуджений", "задоволений"], correctAnswer: "скорботний", explanation: "Обидва слова описують глибокий сум і журбу."),
                ExerciseItem(id: UUID(), prompt: "Слово: СПОКІЙНИЙ", options: ["галасливий", "схвильований", "умиротворений", "метушливий"], correctAnswer: "умиротворений", explanation: "Умиротворений означає тихий, без тривоги, тобто спокійний."),
                ExerciseItem(id: UUID(), prompt: "Слово: МУЖНІЙ", options: ["боязкий", "полохливий", "відважний", "несміливий"], correctAnswer: "відважний", explanation: "Відважний — той, хто не боїться небезпеки, як і мужній."),
                ExerciseItem(id: UUID(), prompt: "Слово: НЕЗВИЧАЙНИЙ", options: ["звичайний", "дивний", "нормальний", "типовий"], correctAnswer: "дивний", explanation: "Дивний — такий, що вирізняється з-поміж звичайного, тобто незвичайний."),
                ExerciseItem(id: UUID(), prompt: "Слово: ОБИЛЬНИЙ", options: ["мізерний", "рясний", "рідкісний", "обмежений"], correctAnswer: "рясний", explanation: "Рясний означає такий, якого багато, тобто обильний."),
                ExerciseItem(id: UUID(), prompt: "Слово: НЕМІЧНИЙ", options: ["сильний", "могутній", "слабкий", "міцний"], correctAnswer: "слабкий", explanation: "Немічний — той, хто не має сил, тобто слабкий."),
                ExerciseItem(id: UUID(), prompt: "Слово: ЯСКРАВИЙ", options: ["тьмяний", "блякий", "барвистий", "блідий"], correctAnswer: "барвистий", explanation: "Барвистий — повний насичених кольорів, тобто яскравий."),
                ExerciseItem(id: UUID(), prompt: "Слово: ЗАОЩАДЛИВИЙ", options: ["марнотратний", "економний", "розкішний", "щедрий"], correctAnswer: "економний", explanation: "Обидва слова описують людину, яка ощадливо витрачає гроші й ресурси."),
                ExerciseItem(id: UUID(), prompt: "Слово: КРАСНОМОВНИЙ", options: ["мовчазний", "нерозбірливий", "промовистий", "незграбний"], correctAnswer: "промовистий", explanation: "Красномовний і промовистий описують того, хто вміє виразно й переконливо говорити."),
                ExerciseItem(id: UUID(), prompt: "Слово: НАПОЛЕГЛИВИЙ", options: ["слабкий", "завзятий", "гнучкий", "полохливий"], correctAnswer: "завзятий", explanation: "Завзятий — той, хто уперто йде до мети попри труднощі, тобто наполегливий."),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Антоніми (легкі)",
            instructions: "Оберіть слово, яке означає ПРОТИЛЕЖНЕ до даного слова.",
            section: .language,
            type: .multipleChoice,
            trackedType: nil,
            difficulty: .easy,
            items: [
                ExerciseItem(id: UUID(), prompt: "Слово: ГАРЯЧИЙ", options: ["теплий", "холодний", "прохолодний", "літеплий"], correctAnswer: "холодний", explanation: "Холодний — протилежна крайність температури щодо гарячого."),
                ExerciseItem(id: UUID(), prompt: "Слово: ЩАСЛИВИЙ", options: ["радісний", "веселий", "сумний", "задоволений"], correctAnswer: "сумний", explanation: "Сумний — протилежний за настроєм до щасливого."),
                ExerciseItem(id: UUID(), prompt: "Слово: ВЕЛИКИЙ", options: ["величезний", "чималий", "малий", "високий"], correctAnswer: "малий", explanation: "Малий — протилежний за розміром до великого."),
                ExerciseItem(id: UUID(), prompt: "Слово: ШВИДКИЙ", options: ["бистрий", "повільний", "моторний", "хуткий"], correctAnswer: "повільний", explanation: "Повільний рухається з малою швидкістю, а швидкий — з великою."),
                ExerciseItem(id: UUID(), prompt: "Слово: ЧИСТИЙ", options: ["охайний", "акуратний", "брудний", "свіжий"], correctAnswer: "брудний", explanation: "Брудний — це той, що не чистий."),
                ExerciseItem(id: UUID(), prompt: "Слово: БАДЬОРИЙ", options: ["пильний", "уважний", "млявий", "активний"], correctAnswer: "млявий", explanation: "Млявий — без енергії, а бадьорий — повний сил."),
                ExerciseItem(id: UUID(), prompt: "Слово: ГУЧНИЙ", options: ["галасливий", "тихий", "вибуховий", "сильний"], correctAnswer: "тихий", explanation: "Тихий — це той, що майже не видає звуку, на відміну від гучного."),
                ExerciseItem(id: UUID(), prompt: "Слово: ВІДЧИНЕНИЙ", options: ["широкий", "зачинений", "вільний", "чистий"], correctAnswer: "зачинений", explanation: "Зачинений — протилежний стан дверей чи вікна щодо відчиненого."),
                ExerciseItem(id: UUID(), prompt: "Слово: ПОВНИЙ", options: ["набитий", "порожній", "завантажений", "цілий"], correctAnswer: "порожній", explanation: "Порожній — у ньому нічого немає, на відміну від повного."),
                ExerciseItem(id: UUID(), prompt: "Слово: ЛЮБИТИ", options: ["обожнювати", "цінувати", "ненавидіти", "піклуватися"], correctAnswer: "ненавидіти", explanation: "Ненавидіти — це найсильніше почуття, протилежне любові."),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Закінчіть речення (легке)",
            instructions: "Оберіть слово, яке найкраще завершує речення.",
            section: .language,
            type: .sentenceCompletion,
            trackedType: .sentenceCompletion,
            difficulty: .easy,
            items: [
                ExerciseItem(id: UUID(), prompt: "Вона полила ___.", options: ["квіти", "кити", "віти"], correctAnswer: "квіти", explanation: "Поливають рослини, а кити живуть у морі. Віти — гілки, їх не поливають."),
                ExerciseItem(id: UUID(), prompt: "Він одягнув ___.", options: ["пальто", "пальма", "паляниця"], correctAnswer: "пальто", explanation: "Пальто — це одяг, його можна одягнути. Пальма й паляниця — не одяг."),
                ExerciseItem(id: UUID(), prompt: "Мені потрібна склянка ___.", options: ["води", "вози", "види"], correctAnswer: "води", explanation: "Склянку наповнюють водою. Слова «вози» та «види» тут не мають змісту."),
                ExerciseItem(id: UUID(), prompt: "Мама спекла ___.", options: ["пиріг", "пирій", "пир"], correctAnswer: "пиріг", explanation: "Печуть пиріг. Пирій — бур'ян, а пир — бенкет."),
                ExerciseItem(id: UUID(), prompt: "Собака виляв ___.", options: ["хвостом", "мостом", "постом"], correctAnswer: "хвостом", explanation: "Собаки виляють хвостом, а міст і піст так не роблять."),
                ExerciseItem(id: UUID(), prompt: "Він вимкнув ___.", options: ["світло", "світанок", "світ"], correctAnswer: "світло", explanation: "Вимикають світло в кімнаті. Світанок і світ вимкнути неможливо."),
                ExerciseItem(id: UUID(), prompt: "Птах звив ___.", options: ["гніздо", "гвіздок", "гніт"], correctAnswer: "гніздо", explanation: "Птахи звивають гнізда. Гвіздок і гніт до цього не стосуються."),
                ExerciseItem(id: UUID(), prompt: "Діти гралися в ___.", options: ["парку", "парті", "паркані"], correctAnswer: "парку", explanation: "У парку діти граються. Грати «в парті» чи «в паркані» не говорять."),
                ExerciseItem(id: UUID(), prompt: "Він читав ___.", options: ["газету", "газон", "гази"], correctAnswer: "газету", explanation: "Читають газету. Газон — трава, а гази не читають."),
                ExerciseItem(id: UUID(), prompt: "Він полагодив ___.", options: ["кран", "баран", "тиран"], correctAnswer: "кран", explanation: "Кран ремонтують. Баран — тварина, а тиран — жорстокий правитель."),
                ExerciseItem(id: UUID(), prompt: "Суп був занадто ___.", options: ["гарячий", "гарний", "гарбузовий"], correctAnswer: "гарячий", explanation: "Про суп, який неможливо їсти одразу, кажуть «занадто гарячий»."),
                ExerciseItem(id: UUID(), prompt: "Вона розкрила ___.", options: ["парасольку", "каструльку", "гільзу"], correctAnswer: "парасольку", explanation: "Розкривають парасольку від дощу."),
                ExerciseItem(id: UUID(), prompt: "Він заплатив ___.", options: ["рахунок", "район", "розтин"], correctAnswer: "рахунок", explanation: "Платять рахунок у ресторані чи в крамниці."),
                ExerciseItem(id: UUID(), prompt: "Кіт спав на ___.", options: ["килимку", "кульку", "кілку"], correctAnswer: "килимку", explanation: "Коти люблять спати на м'якому килимку."),
                ExerciseItem(id: UUID(), prompt: "Вона одягла теплий ___.", options: ["светр", "сектор", "сервер"], correctAnswer: "светр", explanation: "Светр — теплий одяг. Сектор і сервер одягнути неможливо."),
                ExerciseItem(id: UUID(), prompt: "Вона посадила в городі ___.", options: ["картоплю", "каплю", "картку"], correctAnswer: "картоплю", explanation: "У городі садять картоплю."),
                ExerciseItem(id: UUID(), prompt: "Вона писала у ___.", options: ["щоденнику", "щоку", "щіттю"], correctAnswer: "щоденнику", explanation: "Записи роблять у щоденнику."),
                ExerciseItem(id: UUID(), prompt: "Вона замкнула ___.", options: ["двері", "звірі", "дірі"], correctAnswer: "двері", explanation: "Замикають двері на ключ."),
                ExerciseItem(id: UUID(), prompt: "Дитина міцно ___.", options: ["спить", "сипить", "скипить"], correctAnswer: "спить", explanation: "Мала дитина міцно спить. Інші слова не пасують до цього речення."),
                ExerciseItem(id: UUID(), prompt: "Сестра купила ___.", options: ["хліб", "хлів", "хлоп"], correctAnswer: "хліб", explanation: "Хліб купують у крамниці, а хлів — будівля для худоби."),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Будова слова",
            instructions: "Оберіть правильно утворене слово, щоб завершити речення.",
            section: .language,
            type: .sentenceCompletion,
            trackedType: nil,
            difficulty: .medium,
            items: [
                ExerciseItem(id: UUID(), prompt: "Діти бігли ___.", options: ["швидкий", "швидко", "швидкість"], correctAnswer: "швидко", explanation: "Біжать як? — швидко: до дієслова потрібен прислівник."),
                ExerciseItem(id: UUID(), prompt: "Вона — ___ учениця в класі.", options: ["розумна", "розумніша", "найрозумніша"], correctAnswer: "найрозумніша", explanation: "Коли йдеться про порівняння з усіма в класі, вживають найвищий ступінь: найрозумніша."),
                ExerciseItem(id: UUID(), prompt: "Йому потрібно ___ твір, бо там багато помилок.", options: ["переписати", "розписати", "підписати"], correctAnswer: "переписати", explanation: "Префікс пере- означає зробити заново, тож «переписати» — написати ще раз."),
                ExerciseItem(id: UUID(), prompt: "Після довгого походу вона була ___.", options: ["втомлена", "втомити", "втома"], correctAnswer: "втомлена", explanation: "Йдеться про стан людини після походу, тому потрібен прикметник: втомлена."),
                ExerciseItem(id: UUID(), prompt: "Двері були ___.", options: ["замкнені", "замикати", "замикаючи"], correctAnswer: "замкнені", explanation: "Опис стану дверей — це пасивний дієприкметник «замкнені»."),
                ExerciseItem(id: UUID(), prompt: "Він поводився по-___.", options: ["дитячому", "дитячий", "дитинство"], correctAnswer: "дитячому", explanation: "Прислівник із префіксом по- утворюється від прикметника: по-дитячому."),
                ExerciseItem(id: UUID(), prompt: "У неї двоє ___.", options: ["дитин", "дітей", "дитям"], correctAnswer: "дітей", explanation: "Після «двоє» потрібен родовий відмінок множини; для слова «дитина» це «дітей»."),
                ExerciseItem(id: UUID(), prompt: "Він ___ говорив про аварію.", options: ["обережний", "обережно", "обережність"], correctAnswer: "обережно", explanation: "Говорити як? — обережно: потрібен прислівник."),
                ExerciseItem(id: UUID(), prompt: "Торт був ___ шоколадом.", options: ["покритий", "покривати", "покриття"], correctAnswer: "покритий", explanation: "Опис торта вимагає дієприкметника: покритий."),
                ExerciseItem(id: UUID(), prompt: "Вона ___ за брата.", options: ["висока", "вища", "найвища"], correctAnswer: "вища", explanation: "Слово «за» вказує на порівняння двох осіб, тому потрібен вищий ступінь: вища."),
                ExerciseItem(id: UUID(), prompt: "Я знову ___ свої ключі.", options: ["загубив", "губити", "загубити"], correctAnswer: "загубив", explanation: "Дія вже відбулася, тому потрібна форма минулого часу: загубив."),
                ExerciseItem(id: UUID(), prompt: "Інструкція була ___.", options: ["незрозуміла", "антизрозуміла", "передзрозуміла"], correctAnswer: "незрозуміла", explanation: "Префікс не- заперечує значення: не зрозуміла."),
                ExerciseItem(id: UUID(), prompt: "Учора він ___ вікно.", options: ["розбив", "розбити", "розбиває"], correctAnswer: "розбив", explanation: "Слово «учора» вимагає минулого часу: розбив."),
                ExerciseItem(id: UUID(), prompt: "Вона дуже ___ людина.", options: ["привітна", "привітання", "вітати"], correctAnswer: "привітна", explanation: "Слово «людина» — іменник, тому потрібен узгоджений прикметник: привітна."),
                ExerciseItem(id: UUID(), prompt: "Фільм був ___.", options: ["нудний", "нудити", "нудьга"], correctAnswer: "нудний", explanation: "Опис фільму — прикметник: нудний."),
                ExerciseItem(id: UUID(), prompt: "У нього три ___.", options: ["дружина", "дружини", "дружин"], correctAnswer: "дружини", explanation: "Після числівника «три» іменник жіночого роду стоїть у називному множини: дружини."),
                ExerciseItem(id: UUID(), prompt: "Вона заспівала ___.", options: ["гарний", "гарно", "гарність"], correctAnswer: "гарно", explanation: "Заспівала як? — гарно: потрібен прислівник."),
                ExerciseItem(id: UUID(), prompt: "Марія була ___ погодою.", options: ["незадоволена", "передоволена", "антидоволена"], correctAnswer: "незадоволена", explanation: "Префікс не- вказує на протилежне значення: не задоволена."),
                ExerciseItem(id: UUID(), prompt: "Треба ___ морозилку.", options: ["розморозити", "заморозити", "доморозити"], correctAnswer: "розморозити", explanation: "Префікс роз- означає зворотну дію, тож розморозити — зробити так, щоб лід розтанув."),
                ExerciseItem(id: UUID(), prompt: "Посилка прибула ___.", options: ["пошкодженою", "пошкодження", "пошкодити"], correctAnswer: "пошкодженою", explanation: "Опис стану посилки — дієприкметник у орудному відмінку: пошкодженою."),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Схожі слова (легке)",
            instructions: "Над реченнями показано пару слів. Оберіть варіант, який правильно заповнює ОБИДВІ пропуски по порядку.",
            section: .language,
            type: .homonym,
            trackedType: .homonym,
            difficulty: .medium,
            items: [
                ExerciseItem(id: UUID(), prompt: "[одягти / надіти] Мама хоче ___ дитину. Дитина хоче ___ капелюх.", options: ["одягти…одягти", "надіти…надіти", "одягти…надіти", "надіти…одягти"], correctAnswer: "одягти…надіти", explanation: "Одягають КОГО (дитину), а надівають ЩО (капелюх)."),
                ExerciseItem(id: UUID(), prompt: "[ефективний / ефектний] Це ___ засіб від болю. Це ___ костюм.", options: ["ефективний…ефективний", "ефектний…ефектний", "ефективний…ефектний", "ефектний…ефективний"], correctAnswer: "ефективний…ефектний", explanation: "Ефективний — той, що дає результат (засіб), а ефектний — той, що справляє враження (костюм)."),
                ExerciseItem(id: UUID(), prompt: "[абонемент / абонент] У мене є ___ до басейну. Телефонний ___ не відповідає.", options: ["абонемент…абонемент", "абонент…абонент", "абонемент…абонент", "абонент…абонемент"], correctAnswer: "абонемент…абонент", explanation: "Абонемент — документ на послугу, а абонент — користувач зв'язку."),
                ExerciseItem(id: UUID(), prompt: "[економно / економічно] Він живе ___. Це рішення ___ вигідне.", options: ["економно…економно", "економічно…економічно", "економно…економічно", "економічно…економно"], correctAnswer: "економно…економічно", explanation: "Економно означає ощадливо, а економічно вигідне — вигідне з погляду економіки."),
                ExerciseItem(id: UUID(), prompt: "[перевезти / перевести] Треба ___ меблі на нову квартиру. Треба ___ бабусю через дорогу.", options: ["перевезти…перевезти", "перевести…перевести", "перевезти…перевести", "перевести…перевезти"], correctAnswer: "перевезти…перевести", explanation: "Перевозять вантаж транспортом, а переводять людину пішки."),
                ExerciseItem(id: UUID(), prompt: "[лікувати / лічити] Лікар повинен ___ хворого. Касир повинен ___ гроші.", options: ["лікувати…лікувати", "лічити…лічити", "лікувати…лічити", "лічити…лікувати"], correctAnswer: "лікувати…лічити", explanation: "Лікувати — відновлювати здоров'я, а лічити — рахувати."),
                ExerciseItem(id: UUID(), prompt: "[кіт / кит] У хаті живе ___. В океані плаває ___.", options: ["кіт…кіт", "кит…кит", "кіт…кит", "кит…кіт"], correctAnswer: "кіт…кит", explanation: "Кіт — домашня тварина, а кит — морський ссавець."),
                ExerciseItem(id: UUID(), prompt: "[коза / коса] На лузі пасеться ___. У дівчинки довга ___.", options: ["коза…коза", "коса…коса", "коза…коса", "коса…коза"], correctAnswer: "коза…коса", explanation: "Коза пасеться на луці, а коса — заплетене волосся."),
                ExerciseItem(id: UUID(), prompt: "[дим / дім] З комина йде ___. Це наш новий ___.", options: ["дим…дим", "дім…дім", "дим…дім", "дім…дим"], correctAnswer: "дим…дім", explanation: "З комина іде дим, а дім — це оселя."),
                ExerciseItem(id: UUID(), prompt: "[мир / мур] Після війни настав ___. Навколо саду стоїть високий ___.", options: ["мир…мир", "мур…мур", "мир…мур", "мур…мир"], correctAnswer: "мир…мур", explanation: "Мир настає після війни, а мур — кам'яна огорожа."),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Аналогії",
            instructions: "Оберіть слово, яке найкраще завершує аналогію.",
            section: .language,
            type: .analogyChoice,
            trackedType: .analogyChoice,
            difficulty: .medium,
            items: [
                ExerciseItem(id: UUID(), prompt: "ЦУЦЕНЯ до ПСА, як КОШЕНЯ до ___", options: ["кота", "пса", "птаха", "риби"], correctAnswer: "кота", explanation: "Цуценя — малюк пса, а кошеня — малюк кота."),
                ExerciseItem(id: UUID(), prompt: "ХОЛОД до ЗИМИ, як СПЕКА до ___", options: ["весни", "осені", "літа", "дощу"], correctAnswer: "літа", explanation: "Холод типовий для зими, а спека — для літа."),
                ExerciseItem(id: UUID(), prompt: "ОКО потрібне, щоб БАЧИТИ, а ВУХО — щоб ___", options: ["торкатися", "чути", "нюхати", "куштувати"], correctAnswer: "чути", explanation: "Кожен орган чуття виконує свою функцію: вухо слугує для слуху."),
                ExerciseItem(id: UUID(), prompt: "КУХАР до КУХНІ, як ЛІКАР до ___", options: ["бібліотеки", "лікарні", "школи", "крамниці"], correctAnswer: "лікарні", explanation: "Кухар працює на кухні, а лікар — у лікарні."),
                ExerciseItem(id: UUID(), prompt: "РУКАВИЧКА до РУКИ, як ШКАРПЕТКА до ___", options: ["руки", "коліна", "ноги", "голови"], correctAnswer: "ноги", explanation: "Рукавичку носять на руці, а шкарпетку — на нозі."),
                ExerciseItem(id: UUID(), prompt: "ЩАСЛИВИЙ сміється, а СУМНИЙ ___", options: ["усміхається", "спить", "плаче", "біжить"], correctAnswer: "плаче", explanation: "Сміх виражає радість, а сльози — сум."),
                ExerciseItem(id: UUID(), prompt: "ПТАХ до ГНІЗДА, як ВЕДМІДЬ до ___", options: ["дерева", "барлогу", "океану", "поля"], correctAnswer: "барлогу", explanation: "Птах живе в гнізді, а ведмідь — у барлозі."),
                ExerciseItem(id: UUID(), prompt: "ОЛІВЕЦЬ потрібен, щоб ПИСАТИ, а ПЕНЗЛИК — щоб ___", options: ["різати", "малювати", "підмітати", "мішати"], correctAnswer: "малювати", explanation: "Пензлем наносять фарбу, тобто малюють."),
                ExerciseItem(id: UUID(), prompt: "ДЕНЬ до НОЧІ, як ЧОРНИЙ до ___", options: ["темного", "сірого", "білого", "синього"], correctAnswer: "білого", explanation: "День і ніч — протилежності, так само чорний і білий."),
                ExerciseItem(id: UUID(), prompt: "СОЛДАТ до АРМІЇ, як МОРЯК до ___", options: ["авіації", "піхоти", "флоту", "гвардії"], correctAnswer: "флоту", explanation: "Солдат служить в армії, а моряк — у флоті."),
                ExerciseItem(id: UUID(), prompt: "КОЛЕСО до МАШИНИ, як КРИЛО до ___", options: ["човна", "літака", "потяга", "автобуса"], correctAnswer: "літака", explanation: "Колесо — частина машини, а крило — частина літака."),
                ExerciseItem(id: UUID(), prompt: "ВЧИТЕЛЬ до ШКОЛИ, як СУДДЯ до ___", options: ["офісу", "лікарні", "залу суду", "крамниці"], correctAnswer: "залу суду", explanation: "Вчитель працює в школі, а суддя — у залі суду."),
                ExerciseItem(id: UUID(), prompt: "ГУСЕНИЦЯ до МЕТЕЛИКА, як ГОЛОВАСТИК до ___", options: ["риби", "черепахи", "жаби", "ящірки"], correctAnswer: "жаби", explanation: "Гусениця перетворюється на метелика, а головастик — на жабу."),
                ExerciseItem(id: UUID(), prompt: "ЇЖА втамовує ГОЛОД, а ВОДА — ___", options: ["вологість", "спрагу", "холод", "нудьгу"], correctAnswer: "спрагу", explanation: "Їжа усуває голод, а вода — спрагу."),
                ExerciseItem(id: UUID(), prompt: "ВОВНА від ВІВЦІ, як ШОВК від ___", options: ["мухи", "шовкопряда", "бавовни", "льону"], correctAnswer: "шовкопряда", explanation: "Вовну дає вівця, а шовк — гусениця шовкопряда."),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Факт чи думка",
            instructions: "Визначте: це твердження — ФАКТ чи ДУМКА?",
            section: .language,
            type: .factOrOpinion,
            trackedType: nil,
            difficulty: .easy,
            items: [
                ExerciseItem(id: UUID(), prompt: "У тижні 7 днів.", options: ["Fact", "Opinion"], correctAnswer: "Fact", explanation: "Це факт, бо за загальноприйнятим календарем тиждень складається рівно із 7 днів, і це можна перевірити."),
                ExerciseItem(id: UUID(), prompt: "Ванільне — найсмачніше морозиво.", options: ["Fact", "Opinion"], correctAnswer: "Opinion", explanation: "Це думка, бо смак «найкращого» залежить від особистих уподобань кожного."),
                ExerciseItem(id: UUID(), prompt: "Вода замерзає при 32 градусах за Фаренгейтом.", options: ["Fact", "Opinion"], correctAnswer: "Fact", explanation: "Це факт, бо це можна виміряти: за звичайного атмосферного тиску вода замерзає за цієї температури."),
                ExerciseItem(id: UUID(), prompt: "Собаки — найкращі домашні улюбленці.", options: ["Fact", "Opinion"], correctAnswer: "Opinion", explanation: "Це думка, бо для різних людей найкращим улюбленцем може бути різна тварина залежно від способу життя."),
                ExerciseItem(id: UUID(), prompt: "У трикутника три сторони.", options: ["Fact", "Opinion"], correctAnswer: "Fact", explanation: "Це факт, бо за визначенням трикутник — це многокутник із трьома сторонами і трьома вершинами."),
                ExerciseItem(id: UUID(), prompt: "Цей телесеріал смішний.", options: ["Fact", "Opinion"], correctAnswer: "Opinion", explanation: "Це думка, бо почуття гумору в кожного своє: що смішно одному, іншому може таким не здаватися."),
                ExerciseItem(id: UUID(), prompt: "Авраам Лінкольн був президентом Сполучених Штатів.", options: ["Fact", "Opinion"], correctAnswer: "Fact", explanation: "Це факт, бо історичні документи підтверджують, що Лінкольн був 16-м президентом США."),
                ExerciseItem(id: UUID(), prompt: "Земля — найкраща планета.", options: ["Fact", "Opinion"], correctAnswer: "Opinion", explanation: "Це думка, бо слово «найкраща» суб'єктивне, а об'єктивного способу оцінювати планети за красою чи вартістю не існує."),
                ExerciseItem(id: UUID(), prompt: "В одній годині 60 хвилин.", options: ["Fact", "Opinion"], correctAnswer: "Fact", explanation: "Це факт, бо за прийнятою системою вимірювання часу година дорівнює рівно 60 хвилинам."),
                ExerciseItem(id: UUID(), prompt: "Тюльпани гарніші за троянди.", options: ["Fact", "Opinion"], correctAnswer: "Opinion", explanation: "Це думка, бо краса суб'єктивна: одним більше подобаються тюльпани, іншим — троянди."),
                ExerciseItem(id: UUID(), prompt: "Вашингтон (округ Колумбія) — столиця Сполучених Штатів.", options: ["Fact", "Opinion"], correctAnswer: "Fact", explanation: "Це факт, бо Вашингтон офіційно є столицею США."),
                ExerciseItem(id: UUID(), prompt: "Неввічливо розмовляти з повним ротом.", options: ["Fact", "Opinion"], correctAnswer: "Opinion", explanation: "Це переважно думка, бо правила етикету залежать від культури й традицій, а не є універсальним фактом."),
                ExerciseItem(id: UUID(), prompt: "У році 12 місяців.", options: ["Fact", "Opinion"], correctAnswer: "Fact", explanation: "Це факт, бо за загальноприйнятим календарем рік поділяється рівно на 12 місяців."),
                ExerciseItem(id: UUID(), prompt: "Вставати рано — корисно.", options: ["Fact", "Opinion"], correctAnswer: "Opinion", explanation: "Це думка, бо користь раннього підйому залежить від біологічного ритму й способу життя людини."),
                ExerciseItem(id: UUID(), prompt: "2 + 2 = 4.", options: ["Fact", "Opinion"], correctAnswer: "Fact", explanation: "Це факт, бо це загальновизнана математична істина, яку можна перевірити."),
                ExerciseItem(id: UUID(), prompt: "Океан складається з солоної води.", options: ["Fact", "Opinion"], correctAnswer: "Fact", explanation: "Це факт, бо вимірювання підтверджують, що у воді океанів розчинені солі."),
                ExerciseItem(id: UUID(), prompt: "Садівництво — чудове захоплення.", options: ["Fact", "Opinion"], correctAnswer: "Opinion", explanation: "Це думка, бо чи є захоплення «чудовим», залежить від особистих інтересів."),
                ExerciseItem(id: UUID(), prompt: "Камінь важчий за пір'їну такого самого розміру.", options: ["Fact", "Opinion"], correctAnswer: "Fact", explanation: "Це факт, бо камінь щільніший за пір'їну, тобто має більшу масу в тому самому об'ємі."),
                ExerciseItem(id: UUID(), prompt: "У Сполучених Штатах 50 штатів.", options: ["Fact", "Opinion"], correctAnswer: "Fact", explanation: "Це факт, бо США офіційно складаються рівно з 50 штатів."),
                ExerciseItem(id: UUID(), prompt: "Піца — найкраща їжа.", options: ["Fact", "Opinion"], correctAnswer: "Opinion", explanation: "Це думка, бо смаки в їжі різні, а слово «найкраща» залежить від особистих уподобань."),
                ExerciseItem(id: UUID(), prompt: "Фізичні вправи корисні для здоров'я.", options: ["Fact", "Opinion"], correctAnswer: "Fact", explanation: "Це факт, бо численні медичні дослідження підтвердили, що фізична активність зміцнює здоров'я."),
                ExerciseItem(id: UUID(), prompt: "Класична музика нудна.", options: ["Fact", "Opinion"], correctAnswer: "Opinion", explanation: "Це думка, бо музичні смаки різні: що одному нудно, іншому може бути цікаво."),
                ExerciseItem(id: UUID(), prompt: "Яблука й апельсини — це фрукти.", options: ["Fact", "Opinion"], correctAnswer: "Fact", explanation: "Це факт, бо і яблуко, і апельсин відповідають визначенню плоду."),
                ExerciseItem(id: UUID(), prompt: "Котів доглядати легше, ніж собак.", options: ["Fact", "Opinion"], correctAnswer: "Opinion", explanation: "Це думка, бо поняття «легше» залежить від способу життя людини та потреб конкретної тварини."),
                ExerciseItem(id: UUID(), prompt: "У добі 24 години.", options: ["Fact", "Opinion"], correctAnswer: "Fact", explanation: "Це факт, бо доба триває приблизно 24 години, тобто стільки, скільки Земля робить оберт навколо своєї осі."),
            ]
        ),
        Exercise(
            id: UUID(),
            title: "Послідовність дій",
            instructions: "Кроки показано в НЕПРАВИЛЬНОМУ порядку. Пронумеруйте їх 1, 2, 3 ..., щоб розташувати в правильній послідовності.",
            section: .language,
            type: .sequencing,
            trackedType: .sequencing,
            difficulty: .medium,
            items: [
                ExerciseItem(id: UUID(), prompt: "Приготування тосту", options: ["Намазати тост маслом", "Покласти хліб у тостер", "Вийняти з тостера", "З'їсти"], correctAnswer: "Покласти хліб у тостер | Вийняти з тостера | Намазати тост маслом | З'їсти", explanation: "Спочатку хліб підсмажують, потім виймають, мастять маслом і лише тоді їдять."),
                ExerciseItem(id: UUID(), prompt: "Миття рук", options: ["Витерти руки рушником", "Намилити руки", "Відкрити воду", "Тертися 20 секунд", "Змити мило", "Намочити руки"], correctAnswer: "Відкрити воду | Намочити руки | Намилити руки | Тертися 20 секунд | Змити мило | Витерти руки рушником", explanation: "Гігієнічні правила: намочити руки, намилити, ретельно потерти, змити мило й витерти насухо."),
                ExerciseItem(id: UUID(), prompt: "Приготування кави", options: ["Налити каву в чашку", "Насипати мелену каву у фільтр", "Натиснути кнопку заварювання", "Налити воду в резервуар"], correctAnswer: "Налити воду в резервуар | Насипати мелену каву у фільтр | Натиснути кнопку заварювання | Налити каву в чашку", explanation: "У кавоварці спершу готують воду й каву, потім заварюють і лише тоді наливають напій."),
                ExerciseItem(id: UUID(), prompt: "Телефонна розмова", options: ["Сказати «алло»", "Покласти слухавку", "Взяти телефон", "Набрати номер", "Поговорити"], correctAnswer: "Взяти телефон | Набрати номер | Сказати «алло» | Поговорити | Покласти слухавку", explanation: "Спершу починають дзвінок, потім вітаються, спілкуються і наприкінці закінчують розмову."),
                ExerciseItem(id: UUID(), prompt: "Одягання", options: ["Взути черевики", "Одягнути сорочку", "Одягнути білизну", "Одягнути шкарпетки", "Одягнути штани"], correctAnswer: "Одягнути білизну | Одягнути сорочку | Одягнути штани | Одягнути шкарпетки | Взути черевики", explanation: "Одягаються від білизни до верхнього одягу, а взуття — наприкінці, після шкарпеток."),
                ExerciseItem(id: UUID(), prompt: "Підмітання підлоги", options: ["Викинути в смітник", "Дістати віник", "Зібрати сміття на совок", "Змести сміття в купку"], correctAnswer: "Дістати віник | Змести сміття в купку | Зібрати сміття на совок | Викинути в смітник", explanation: "Логічно: взяти віник, змести сміття, зібрати його і викинути."),
                ExerciseItem(id: UUID(), prompt: "Замовлення в ресторані", options: ["З'їсти страву", "Сказати офіціанту, що замовляєте", "Сісти за стіл", "Чекати на їжу", "Переглянути меню"], correctAnswer: "Сісти за стіл | Переглянути меню | Сказати офіціанту, що замовляєте | Чекати на їжу | З'їсти страву", explanation: "Спочатку сідають, обирають страву, замовляють, чекають і наприкінці їдять."),
                ExerciseItem(id: UUID(), prompt: "Випікання печива", options: ["Дати печиву охолонути", "Випікати в духовці", "Розігріти духовку", "Змішати інгредієнти", "Викласти тісто на деко"], correctAnswer: "Розігріти духовку | Змішати інгредієнти | Викласти тісто на деко | Випікати в духовці | Дати печиву охолонути", explanation: "За рецептом спершу готуються, змішують, формують, випікають і дають охолонути."),
            ]
        )
    ]
}
