// Generated by video-tools/scripts/extract-farsi.py from the app's own Farsi catalog.
// Every string below is copied verbatim from the app; none was written for this video.
export const FARSI = {
  "source": "CogniLink/FarsiLanguageExerciseData.swift",
  "exercise": "categoryCrossOutEasy",
  "itemIndex": 5,
  "title": "دسته‌بندی — ساده",
  "instructions": "کلمه‌ای را انتخاب کنید که در گروه جای نمی‌گیرد.",
  "options": [
    "دست (dast)",
    "پا (pā)",
    "چشم (cheshm)",
    "کتاب (ketāb)"
  ],
  "correct": "کتاب (ketāb)",
  "questionLabel": "سوال",
  "ofLabel": "از"
};
