#!/usr/bin/env python3
"""Copy one existing Farsi exercise item out of the app catalog for the RTL demo.

Reads the Swift sources read-only and writes a small generated ES module into the
deploy folder. No Farsi text is authored here: every string comes from the app.
"""
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
CATALOG = REPO / "CogniLink" / "FarsiLanguageExerciseData.swift"
CONTAINER = REPO / "CogniLink" / "ExerciseContainerView.swift"
OUT = REPO / "website-update" / "video" / "js" / "farsi-item.js"

EXERCISE = "categoryCrossOutEasy"
ITEM_INDEX = 5  # zero-based position inside the exercise's items array


def swift_string(src, label):
    m = re.search(label + r':\s*"([^"\\]*)"', src)
    if not m:
        sys.exit(f"could not find {label}")
    return m.group(1)


def label_for(src, var):
    block = src[src.index(f"private var {var}: String"):]
    m = re.search(r'case \.farsi:\s*return "([^"\\]*)"', block)
    if not m:
        sys.exit(f"could not find Farsi {var}")
    return m.group(1)


catalog = CATALOG.read_text(encoding="utf-8")
start = catalog.index(f"private static let {EXERCISE} = Exercise(")
end = catalog.index("private static let", start + 10)
block = catalog[start:end]

items = [line for line in block.splitlines() if line.strip().startswith("ExerciseItem(")]
line = items[ITEM_INDEX]
options = re.findall(r'"([^"\\]*)"', re.search(r"options:\s*\[(.*?)\]", line).group(1))

container = CONTAINER.read_text(encoding="utf-8")
data = {
    "source": f"CogniLink/{CATALOG.name}",
    "exercise": EXERCISE,
    "itemIndex": ITEM_INDEX,
    "title": swift_string(block, "title"),
    "instructions": swift_string(block, "instructions"),
    "options": options,
    "correct": swift_string(line, "correctAnswer"),
    "questionLabel": label_for(container, "questionLabel"),
    "ofLabel": label_for(container, "ofLabel"),
}
if data["correct"] not in options or len(options) != 4:
    sys.exit("unexpected item shape")

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(
    "// Generated by video-tools/scripts/extract-farsi.py from the app's own Farsi catalog.\n"
    "// Every string below is copied verbatim from the app; none was written for this video.\n"
    "export const FARSI = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n",
    encoding="utf-8",
)
print(json.dumps(data, ensure_ascii=False, indent=2))
